### ISSUE TITLE
Nested :export keys are being lowercased

### ISSUE THREAD

**Issue by timosaikkonen** [prettier/prettier#10057]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAZhCSAEBiAQwICNiwwBuAHShqTgA8AHCAJxh2Bpx0wgCECrXBizUoPKHADO8ACa4uEnryyDhOURHE8AvjV0gANCAhMYAS2jTkoIawgB3AApCENlAQA2jggE8bE2JWAjAAazgYAGUmUIsoAHNkGFYAVzgTOABbYjg5OTyAGQJE1IIEuAAxNiyCGEtE5BACVJgIYxAACxgsrwB1Tot4aViwOCj3IYsANyG-JrBpQJB46Th2ZxCE2uR0bzWTACtpBn4Q8Miogiy4Qvi4Xf2MkGOGKPiErzgARVSIeEeXgOIFirDWrAWSw6TFY8RgfQschgnWQAA4AAwmGEQNZ9EJMJowmTraYPEwARz+8E2Zg8zWkAFopHk8h1WHBKRZ2ZtyjskHsgc81lkLMk0kKPl9fv8HvyniYYCQEUiUUgAEwKkIWLwfADCECyfJAMgArB1UmsACokDwC4HTdIASSgBVgUTAsPMAEEXVEYH4voC1rpdEA)

**Input:**

```css
$foo: #aabbcc;

:export {
  fooBar: $foo;
  nested: {
    fooBar: $foo;
  }
}
```

**Output:**

```css
$foo: #aabbcc;

:export {
  fooBar: $foo;
  nested: {
    foobar: $foo;
  }
}

```

**Expected behavior:**
Nested :export keys should not be lowercased.
