### ISSUE TITLE
map-get() with trailing comma in calc()

### ISSUE THREAD

**Issue by jk-nilo** [prettier/prettier#10096]
**Prettier 2.2.1**
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASGBnAtAM2jLDASwC84kACACgB0oKGKaQAbAQwCcBzOZygRgBsABwAeAGjqMmIKBA4BbNiz4V+AFjF0AlAG46dVCwhhlWKGwVwsS0VgAWcIl3sxKplmCoBWCgCoKAGJgJWEsHhgqVFDKdGw8WEJSOHEKVABrOABPSmZ2bl4QCm0AXz0QcRAIYRgiaAxkUE4OCAB3AAVOBAaUZVa2LIbKgCMONjBMmABlYXGiKC5kGA4AVxSQOAVhuAATHd2AGTYFlbYeADF5JRhaheQQNhWYCAqQVwUWAHV7IngMWbAcCm3V+RAAbr8svcwBghiB5hg4BwYO0xlwlMgcMpEZUAFYYUQAITGEzg00scAO8zgmOx63xoim8y4LDgAEUVhB4LSWDiQLMOIiOPcMDC4cIOPMYJ8iDsYPZkAAOAAMlQlEERnzGwnuErgQrBNMqAEdOfBUdUeg9sFA4Ltdq8OHBTUQnaizhikFjeetEQoiEtVr7mayOVyaV66ZUYGxhjK5QqkAAmaNjIgsZkAYQgCk9Gww3leK0RABVYz1vXywWsAJJQfawKZgSU1ACC9amMCyrJ5iJKJSAA

```sh
# Options (if any):
--parser scss
```

**Input:**

```scss
$ts-font-size: (
    "large": 16px,
    "normal": 14px
);

$local-name-max-height: calc(5 * #{map-get($map: $ts-font-size, $key: "large" )});
```

**Output:**

```scss
$ts-font-size: (
  "large": 16px,
  "normal": 14px,
);

$local-name-max-height: calc(
  5 * #{map-get(
      $map: $ts-font-size,
      $key: "large",
    )}
);
```

**Expected behavior:**

```scss
$ts-font-size: (
  "large": 16px,
  "normal": 14px,
);

$local-name-max-height: calc(5 * #{map-get($map: $ts-font-size, $key: "large")});
```

It causes syntax error when compiling, because there is a trailing comma on the `$key` line + it's heavily expanded with `calc()` comparing a situation when there is just `map-get` on the line, eg. `line-height: map-get($map: $ts-font-size, $key: "large");`
