### ISSUE TITLE
Different output on second iterration in some strange SCSS

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#10153]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgPICcCWA5vlAIaYkAOArjJuqgDpTMB0AZhBJsM5pgAESYADbUAJnEwAjXHFIBrShBIwAFABIAtgEcAtJBEBmAJQ8+-TIQLi98LZRGl4e0nNIBnJJgDkH-JKWmKwyEG7iloSk1IRSMFwiHj6+-oGWIR5wHv7QwUGYkLC4EInJfgFS6Xn51ek+ANwW-NYBdnAOTi6G1FpQXpgahkZ61FD40mG4tqlSGtIiEGAKelGUA0MjYxPhegDuATAAFpgAbm5qeivRsVeUZoMlw6Pjk7YwpPNwjVD8AL7M-xYQIwmAAYvhcB46BBaDQYAAaTCeChQOH0JhAjhccw-QTCMSBWTyJQqWCaXQGR5mXi45o2NodZxwVzufqMEAzIIhbZTSLXOIJDzszDszlVTLZfC5EJBQowYqJYWiipc2qqrns75BFpvdqOJmUsS9foPYybF47TlzBZLW7rR7mnm2fbiI6nc5NfKXKIxZmrT38e4bZ5OuwfERfCyAwEgeEgCCUGBSvrIUBuYq7AAKbgQHmQIFIIl2pAAnnm47JSEs4DAAMqUKskQjIeXUOBx9rSODiSTiAAypCghGopFioIguC0ziTQ-z0XisZAhxgWhEAHVDvh4B4G2A4LXc1v8CctyX82BsouSJlcDBM7hR1PkOxC5k4wArDwADwAQg-q3WpBaHAfYkHAz6vu2ICfl+tZNhGACK1AQPAEGJFBDaQnAuD5h4F7liAlAELAa4HIcyAABwAAxxkRECZGuD6UPmRFZNhJzgXGOjIfA94JnmKCeHoUBwN23aLnI3EQnA96PqQaFvhy7T4C2uBtnG-hDohPHgUgL7oXG7zSKRrrkUgABMhkPvgIhNgAwhAWhPigWQAKyLtQmQACofAJ+mKScbYAJJQJIsC1mABCJgAgqFtYwCWEYKXAvy-EAA)
```sh
--parser scss
```

**Input:**
```scss
/* Origina input */

.foo {
  @include breakpoint($mq-col3) {
    grid-template-areas: 'side    . board   gauge tools' 'side    . session .     controls' 'side    . .       .     .';
    grid-template-columns: $col3-uniboard-side $block-gap $col3-uniboard-width var(--gauge-gap) $col3-uniboard-table;
  }
}


/* First output, as input */

.foo {
  @include breakpoint($mq-col3) {
    grid-template-areas: "side    . board   gauge tools" "side    . session .     controls" "side    . .       .     .";
    grid-template-columns: $col3-uniboard-side $block-gap $col3-uniboard-width var(
        --gauge-gap
      ) $col3-uniboard-table;
  }
}

```

**Output:**
```scss
/* Origina input */

.foo {
  @include breakpoint($mq-col3) {
    grid-template-areas: "side    . board   gauge tools" "side    . session .     controls" "side    . .       .     .";
    grid-template-columns: $col3-uniboard-side $block-gap $col3-uniboard-width var(
        --gauge-gap
      ) $col3-uniboard-table;
  }
}

/* First output, as input */

.foo {
  @include breakpoint($mq-col3) {
    grid-template-areas: "side    . board   gauge tools" "side    . session .     controls" "side    . .       .     .";
    grid-template-columns:
      $col3-uniboard-side $block-gap $col3-uniboard-width var(--gauge-gap)
      $col3-uniboard-table;
  }
}

```

**Expected behavior:**
