### ISSUE TITLE
The CSS indentationl level is miscalculated in calc()-like functions

### ISSUE THREAD

**Issue by hail2u** [prettier/prettier#10166]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAdwEsATGACyWzAEMAbMAChYEYAHAD2wGpsXXgKH9BPMaJETpw8XKnzJMpbICU2APTYATGoDcBAL4EQAGhAROMUtADOyUPQBOziMQAKLhA5RNi9ACeDhYARs70YADWcDAAypyRpFAA5sgwzgCucBZwALahcOTkRQAy9KmZ9ClwAGIQznn0MDapyCD0mTAQ5iBUMHmMAOpUpPB2iWBwcT5jpABuY4HtYHYhIMl2cM4wHhEpTcjoTFsWAFZ23ABCEdGxcfR5cKXJcEcnOSAX3HHJKYxwACKmQg8HejFOIESzi2zhWa16nGcyRgQwo1GQAA4AAwWJEQLZDCKcdpIuCw+ZvCwARxB8D2Vl8HTsAFooHAikVes44LTSDy9tVDkhjhDPls8qR0llxX8AcDQW8RR8LDB6KE0ZQqMgdKqIqRGH8AMIQPLCkDkgCsvUyWwAKurfKLIfNsgBJKAlWBxMDI6wAQU9cRggQB4K2RiMQA)
```sh
--parser css
```

**Input:**
```css
.foo {
  width: calc((1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px) / 2);
}

```

**Output:**
```css
.foo {
  width: calc(
    (
        1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px +
          1px
      ) / 2
  );
}

```

**Expected behavior:**
```css
.foo {
  width: calc(
    (
      1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px + 1px +
        1px
    ) / 2
  );
}

```
