### ISSUE TITLE
[Less] New-line after minus sign adjacent to parenthetical group breaks margin/padding shorthand notation

### ISSUE THREAD

**Issue by C-Hess** [prettier/prettier#10399]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABANtA5gWgG4CGATgJYEBG6cOUBAttQIxIAEjADAA4AeA3ADpQM2fMTKVqtBjgBMrDjwFDMUXIVIUqNetQDM8rn0GCAdHQCeOAM5wqYGBCItgglizrEsJKK2GrRGhLa0owsfmpimpI6siw4ABThAeJaUnosANRsAJRKAL4gADQgEJwwJNBWyKDERBAA7gAKxAhVKATo9QTmVcXkRARgANZwMADKnIPeWMgwRACucMVwdORwACbrGwAyBKrzBFhwAGKOHjDlqsggBPMORSAAFjB06ADqjyTwVpNgcGOtL4kPBfczXMBWXogbw2IgwRoDLAeZAAMw6NmKACsrNwAEIDYajMY6bbeOCo9FLEDY7hjaZUACK8wg8Ap6AxIEmRFh1yokIenFIsDeJHWMEeyAAHOxioKIDY3gNONdBXBYXhycUAI7M+AI0ptG5WGhwDYbB5EOA6kiWhGHZFINHsqk2OgkWYLF30uBMlnkx2U4owCgisUSpAyIMDEjoaYAYQgdAdIDVAFYHvMbAAVChtJ0cvCLACSUC2sDGYFIZQAgqWxjBzFQ2TY8nkgA)
```sh
--parser less
```

**Input:**
```less
@long-variable-name-1: 10px;
@long-variable-name-2: 10px;
@long-variable-name-3: 10px;

.my-selector {
  margin: @long-variable-name-1 @long-variable-name-2 -(@long-variable-name-3 + 1);
}
```

**Output:**
```less
@long-variable-name-1: 10px;
@long-variable-name-2: 10px;
@long-variable-name-3: 10px;

.my-selector {
  margin: @long-variable-name-1 @long-variable-name-2 -
    (@long-variable-name-3 + 1);
}

```

**Expected behavior:**
The "-" sign should be moved onto a new line along with the parenthesis group. Otherwise, Prettier breaks styling for these situations as the computed margin following margin's shorthand rules would end up having two values instead of three.

**Comment by thorn0** [comment]
As a workaround, you can add extra parentheses around the expression:
```less
.my-selector {
  margin: @long-variable-name-1 @long-variable-name-2
    (-(@long-variable-name-3 + 1));
}
```
