### ISSUE TITLE
YAML: alliases (node anchors) as keys error

### ISSUE THREAD

**Issue by v-goncharenko** [prettier/prettier#10414]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbCBnDB9ARmOJAHSgAJSAHAJzgDMBLADyVIDJ0s8DsBDVenhlIcc+OCRIjsAE3oFiZSjQbM2U2dz4Ch6ueKiTMOehACuC8tTpMW7I9hOne-QcPuOJUKTwDmPmj48MBBUFqQAthDShKQA7nD0PgAW8NLYGKbhJOThcDBUchhh5ABUUmLO2iwADAB0ABzZ5KRl9hpwlYIsAIy11U2lUo6dRaS9-VAgADQgEBQwJlAYyKA8VFQQsQAKawjLKDwAbhD00tMguFQ8YADWeQDKFNf0UD7I+aZwM3DhuHDS0WkABkeK9TL44AAxELhIILV7IEA8UzBc4pcKoADqSXo8AwTwI9z2uPoh1xAE9EWAsOcXhg4FQYFsrj5YchaHx6TMAFYYRgAISutwePFyQJecHZnK+IF5jHuLx8qDgAEVTBB4FLUFyQE8qPSqIjyaLUOdqC8YJjTjAksh6tUZtRMHBMVcKIirAbDpKZgBHdXwZlzfZIjAAWigcH+-3ONH99BozN8bKQHO1Mvp4Xo7yonxmGEVyrVGslqelMxgPFwVukNuQACYK1d6PxXgBhCDhFMgKDQH0gUz0gAqVf2aZ1h0+AEkoNFYPcwAV5gBBWf3GDk5Va+kAXx3QA)

```sh
--arrow-parens avoid
--parser yaml
--trailing-comma none
```

**Input:**

```yaml
loss_bce:
  prefix: &loss_bce_alias loss_bce

loss_dice:
  prefix: &loss_dice_alias loss_dice

loss_iou:
  prefix: &loss_iou_alias loss_iou

loss_aggregator:
  mode: weighted_sum
  metrics:
    *loss_bce_alias: 0.8
    *loss_dice_alias: 1.0
    *loss_iou_alias: 1.0

```

**Output:**

```yaml
SyntaxError: All collection items must start at the same column (11:3)
   9 | 
  10 | loss_aggregator:
> 11 |   mode: weighted_sum
     |   ^^^^^^^^^^^^^^^^^^
> 12 |   metrics:
     | ^^^^^^^^^^
> 13 |     *loss_bce_alias: 0.8
     | ^^^^^^^^^^
> 14 |     *loss_dice_alias: 1.0
     | ^^^^^^^^^^
> 15 |     *loss_iou_alias: 1.0
     | ^^^^^^^^^^
> 16 | 
     | ^
```

**Expected behavior:**

To parse valid YAML

I'm not a big expert in YAML, but this snippet looks understandable (subjectively valid) to me.

It's not an obvious case because only 2 out of 6 top searched online validators accepted this as a valid YAML.

[First (code already inserted)](https://codebeautify.org/yaml-validator/cba19606), [second (should be inserted manually)](http://www.yamllint.com/).
Noteworthy that second parser outputs plane YAML (aliases resolved) and it looks like I intended.

**Comment by thorn0** [comment]
Anchor names [can include commas](https://yaml.org/spec/1.2/spec.html#id2785586), that's why this is not valid YAML.

**Comment by thorn0** [comment]
Add spaces to make it valid:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbCBnDB9ARmOJAHSgAJSAHAJzgDMBLADyVIDJ0s8DsBDVenhlIcc+OCRIjsAE3oFiZSjQbM2U2dz4Ch6ueKiTMOehACuC8tTpMW7I9hOne-QcPuOJUKTwDmPmj48MBBUFqQAthDShKQA7nD0PgAW8NLYGKbhJOThcDBUchhh5ABUUmLO2qQsAAwAdAAc2eSkZfYacJWuLACMdTXNpVKOXUK9-SQgADQgEBQwJlAYyKA8VFQQsQAKawjLKDwAbhD00tMguFQ8YADWeQDKFNf0UD7I+aZwM3DhuHDS0WkABkeK9TL44AAxELhIILV7IEA8UzBc4pcKoADqSXo8AwTwI9z2uPoh1xAE9EWAsOcXhg4FQYFsrj5YchaHx6TMAFYYRgAISutwePFyQJecHZnK+IF5jHuLx8qDgAEVTBB4FLUFyQE8qPSqIjyaLUOdqC8YJjTjAksgGjUZtRMHBMVcKIirAbDpKZgBHdXwZlzfZIjAAWigcH+-3ONH99BozN8bKQHO1Mvp4Xo7yonxmGEVyrVGslqelMxgPFwVukNuQACYK1d6PxXgBhCDhFMgKDQH0gUz0gAqVf2aZ1h0+AEkoNFYPcwAV5gBBWf3GDk5Va+kAXx3QA)

```sh
--arrow-parens avoid
--parser yaml
--trailing-comma none
```

**Input:**

```yaml
loss_bce:
  prefix: &loss_bce_alias loss_bce

loss_dice:
  prefix: &loss_dice_alias loss_dice

loss_iou:
  prefix: &loss_iou_alias loss_iou

loss_aggregator:
  mode: weighted_sum
  metrics:
    *loss_bce_alias : 0.8
    *loss_dice_alias : 1.0
    *loss_iou_alias : 1.0

```

**Output:**

```yaml
loss_bce:
  prefix: &loss_bce_alias loss_bce

loss_dice:
  prefix: &loss_dice_alias loss_dice

loss_iou:
  prefix: &loss_iou_alias loss_iou

loss_aggregator:
  mode: weighted_sum
  metrics:
    *loss_bce_alias : 0.8
    *loss_dice_alias : 1.0
    *loss_iou_alias : 1.0

```
