### ISSUE TITLE
Respect overrides when formatting embedded languages

### ISSUE THREAD

**Issue by timecode** [prettier/prettier#10458]
**Prettier 2.2.1**

Weirdly, this has been working fine for me in the past (lots of markdown documents beautifully formatted using Prettier in VSCode to prove it), but recently things have changed and this is the only way I can think of describing the issue. I'm not aware of updating anything particular, so, not sure if it's anything I've done. More importantly, I'm not sure if this is expected behaviour in the first place. If it's not, then I guess this becomes a feature request, although, as I say, it's actually worked in the past :-/

Wondering if this exists for others?

Given `.prettierrc.yaml`:

```yaml
---
overrides:
  - files:
      - "*.md"
    options:
      tabWidth: 4
      # ^ this is to respect markdownlint requirements
      # allowing clear spacing of list elements (for example)
  - files:
      - "*.yaml"
    options:
      tabWidth: 2
  - files:
      - "*.json"
      - "*.js"
    options:
      tabWidth: 2
```

... which specifies tab widths for yaml and json, for example

**Input:**

```md
# Markdown Example

- List item 1
- List item 2

-  Some js

    ```js
    reallyUgly(
        javascript
        );
    ```

- Some json

    ```json
    {"this":"that", "more":"here", "list1":["a", "b", "c"], "list2":["d", "e", "f"] }
    ```

-   Some css

    ```css
    .h1 {color: red;
    }
    ```

-   Some yaml

    ```yaml
    ---
    this:
    - that 1
    - that 2
    ```
```

**Output:**

```md
# Markdown Example

-   List item 1
-   List item 2

-   Some js

    ```js
    reallyUgly(javascript);
    ```

-   Some json

    ```json
    {
        "this": "that",
        "more": "here",
        "list1": ["a", "b", "c"],
        "list2": ["d", "e", "f"]
    }
    ```

-   Some css

    ```css
    .h1 {
        color: red;
    }
    ```

-   Some yaml

    ```yaml
    ---
    this:
        - that 1
        - that 2
    ```
```

**Expected behavior:**

```md
# Markdown Example

-   List item 1
-   List item 2

-   Some js

    ```js
    reallyUgly(javascript);
    ```

-   Some json

    ```json
    {
      "this": "that",
      "more": "here",
      "list1": ["a", "b", "c"],
      "list2": ["d", "e", "f"]
    }
    ```

-   Some css

    ```css
    .h1 {
        color: red;
    }
    ```

-   Some yaml

    ```yaml
    ---
    this:
      - that 1
      - that 2
    ```
```
