### ISSUE TITLE
Feature request: fix indentation in invalid YAML

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#10468]
**Prettier 2.2.1**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEUCGBbOSAEAhAVwEsAbAExzSgoBU4BnGAHShelwG0AHA+gCwC6LFgCsIAI3pIWOWTnHFy0qHNU4ATgSj0AtOxwASYMBwY0MdUQAeAOghc4680SgBzHfQCejOBhwBff2EVNVlGJ3hXT2VQ0LMLaxjY5KgIMjgdADdHeiJ9DgBGABYbKyEQ5ND7R2c3D294DE5hZlamVoIFWAIdEnMGGAAaFvbR1rNIXT74RmHWNoWAYhwaAHkAEVWcVzgYHBmYehwAdwh1AGsXVxwXHAB1FzIIY-oRhfbl48fnqf7GN7G5RksR8XCkwMqOB0OF4DFwaDAMDy2gA9GA+HAwOcIAQYAABTIFCGVaHoLC4ACq9DgOAAcmk4DYREcjCZ4pZbKl0lkcsiAkEKpCYdSpJREcj6CjqTACFwdFy4ASiYLIV8YHwkkK1AqeepcvpWaZzBybDrsnq+YFiclSZhsDgoFw-C5GGgSCRBvJFGRPVQKAdrZVNFBcAAfQNax3OiNCqP7AYx0IITKarVyADCAElcBYCHBgiBBiB7EjoPRkKA0Op1M8AApVhDllBu45obyFkDiJxY3YAZS4CKuyFzcCLvnEcDI6TIABkqK4CGgdgAxM7xJFuZAgNC4iAdvgwDAkO58IgzAdgOC9xtnoiZM+eLdgejlosuxwwWtOVxmZAAMzdaki2ZKw8G7c4+ztGcXDgf9ANHEAQN7K4SDgABFAgIHgOCSCAkABz1Rwt08TASA7LhLFgB4yHVZAAA4AAYiwoiBqTuJwuC3CiGEcbIOwAR0w+Av3sJtt10KA4EnScO3UOBBKIOSvyXX8kAA3CEOpDAiGHTRNJQ9ChNgtT4KLGA0HEajaKQAAmMynFIK50wgDBVJABgAFYO1hGgLKbdS8MyPNM2oBAYF7MBLC4GAAEFqF7GBPFQnDqUCIA)

```sh
# Options (I don't think it matters, see playground):
prettier --config ./node_modules/@lume/cli/.prettierrc.js --ignore-path ./node_modules/@lume/cli/.prettierignore --check ./
```

**Input:**

I believe the following input is valid, because the program that reads it (GitHub Actions) works fine. Either that, or the yaml implementation that GitHub Actions uses is more lax than the official language, or something.

It has mixed indentation, but from what I've read in other place, mixed indentation does no matter inside `{}` or `[]`. It doesn't matter for GitHub actions apparently.

```yml
name: Build and Test

on: [push]

jobs:
    build:
        runs-on: ${{ matrix.operating-system }}

        strategy:
            matrix:
                node-version: [14.x]
                operating-system: [
					ubuntu-latest,
					macos-latest,
					# TODO get tests working in Windows
					# windows-latest
				]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, build, and test
              run: |
                  npm i
                  npm test
              env:
                  CI: true
```

**Output:**

```
SyntaxError: Insufficient indentation in flow collection (12:35)
  10 |             matrix:
  11 |                 node-version: [14.x]
> 12 |                 operating-system: [
     |                                   ^
> 13 | 					ubuntu-latest,
     | ^^^^^^^^^^^^^^^^^^^
> 14 | 					macos-latest,
     | ^^^^^^^^^^^^^^^^^^^
> 15 | 					# TODO get tests working in Windows
     | ^^^^^^^^^^^^^^^^^^^
> 16 | 					# windows-latest
     | ^^^^^^^^^^^^^^^^^^^
> 17 | 				]
     | ^^^^^^
  18 | 
  19 |         steps:
  20 |             - uses: actions/checkout@v1
```

**Expected behavior:**

It should work. Maybe it should fix the mixed indentation? Not sure what is actually valid or not. I'm old but still new to yaml, I get by with it.
