### ISSUE TITLE
Q: How to specify an option inline?

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier#10479]
.prettierrc:
```json
{
  "printWidth": 80
}
```
Prettified code:
```css
html[data-color-mode='dark']
  :is(:not(a, a *, .btn-link, .btn-link *, .octicon-dot-fill, .octicon-dot-fill
      path, [class^='pl-']), .pl-c) {
  color: var(--color-text-primary);
}
```
I want to specify `printWidth` inline, like:
```css
/* prettier printWidth: 1000 */
html[data-color-mode='dark'] :is(:not(a, a *, .btn-link, .btn-link *, .octicon-dot-fill, .octicon-dot-fill path, [class^='pl-']), .pl-c) {
  color: var(--color-text-primary);
}
```
So the selector won't wrap, is that achievable?
