### ISSUE TITLE
Stripping meaningful whitespace from YAML files

### ISSUE THREAD

**Issue by colinmeinke** [prettier/prettier#10506]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc16wMIQDYFcC2UAKgJ4AOcSABPAB4wA6UAZgJZzYAmA4gE4S4y1OJwBsAJgCGAdgCMAVgC00sQA5FAFlmr1ATmkAjJeLjSNzUQbAzTTABaSonbJSp2I+OAEEDAmAEl4fABnJlYoYJheXDAYVmhg6gByJKYoSU9knz8qViDg1Ii4SV4wBwMXamZJbGC4JjqYOKgAc0SmKipJTk4AJQgAdwAZSQMOLJ6uqn4Bws7IPEJSCmo6Rih5nAIIpA7OqgB9A8lg4IgwI92N-c7FPZvbqgWABnuHu+uH-aOTs4uDq5fL4fIFAxRuYqccItN6gx5EPIuWFg5Gg8EOJxIz5wx5xGBYnG3VFgqgDVicGB2YnAqgpan7EGE3HkerYnHg4LQlzYcKs4HE8ELWQC+k-U7nS70olsuHoyHQqUMqgAIRIPKgfMJjKZ6Mczk1OqoBjVvMV2q1pPJlMVjzpMv59pJMBZNqoHK5HFN13wklo-QGiVpcyo+HC-sDdqijmC2EkcWgAGk4CQAGIQXg+mDUKC4bDYJhRiKx+NQACycEpEE42egrOdKyevEkzEYDDYHE4oQYRFGWJAABoQBAyCXgshQCUZgAFEoIMcoGoDSQkMeDgxNsAAawrAGUyJIwNDkFFcHBB3B8GMeiIRq1cJIWnA0xm480WsgQJJcDAIAOQHYYHwbAAHU7DyOBgn3MA4B3Oc8lYAA3PISA-MBTj-cI6l4GApybFofWQapajPEAACtgloZUN23GAdwyOAhl5QiajqQdyNoHcPQARVwCB4GY4jB33XgsI-EgMmwP8yF4cIYGAq07GQVRniE-g6mApsyA-aSILgXgELgP8AEdePgXDh3nT9gkUDURBEP9eDgEzWEc3CHwIpAiNYkA6lDY9ohIzlWhcHi+MMzyWJImBRnkilFKQcRByjVh1RaLB8A8kAIPkP9cDqHsDHnLySIQ09-CcBBaLAGSRy8Jwd2dFwBLqABfFqgA)

```sh
--parser yaml
```

**Input:**

```yaml
contentColumnType: text
fieldGroup: ed62a715-7d68-4188-97b5-2e74f6bca7e7
handle: homeAboutItems
instructions: ''
name: 'About items'
searchable: false
settings:
  addRowLabel: 'Add a row'
  columnType: text
  columns:
    __assoc__:
      -
        - col0
        -
          __assoc__:
            -
              - heading
              - Title
            -
              - handle
              - title
            -
              - width
              - ''
            -
              - type
              - singleline
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - Byline
            -
              - handle
              - byline
            -
              - width
              - ''
            -
              - type
              - singleline
  maxRows: ''
  minRows: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table

```

**Output:**

```yaml
contentColumnType: text
fieldGroup: ed62a715-7d68-4188-97b5-2e74f6bca7e7
handle: homeAboutItems
instructions: ""
name: "About items"
searchable: false
settings:
  addRowLabel: "Add a row"
  columnType: text
  columns:
    __assoc__:
      - - col0
        - __assoc__:
            - - heading
              - Title
            - - handle
              - title
            - - width
              - ""
            - - type
              - singleline
      - - col1
        - __assoc__:
            - - heading
              - Byline
            - - handle
              - byline
            - - width
              - ""
            - - type
              - singleline
  maxRows: ""
  minRows: ""
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table

```

**Expected behavior:**

This input yaml file is a project config automatically generated by CraftCMS that represents a table field in Craft. After formatting with Prettier the table field loses its column data. This is because Prettier is not allowing `-` on their own line and therefore removing the newline. This results in:

```
-
  - heading
```

Being formatted to:

`- - heading`
