### ISSUE TITLE
YAML: a comment after an anchor doesn't stay on a separate line

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#10518]
After fixing #10510, we have this issue.

**Prettier pr-10516**
[Playground link](https://deploy-preview-10516--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBrOBPAjEgBAMgBM4AzAQwFcAbGAHSnt1wGJcAVACwEsBnXdDLgB0Ixrh4UARgJy4AbmSoU4WevQEAmJGIA8OvACpi5ajBAAaEBAAOMLtB7JQZAE4uIAdwAKrhI5SKHmQYjpaSLmRg6DAAytaRXFAA5sgwLsqWcAC2knCExIQAMmTJFGRJcABiEC5ZZDB2ycgglDAQFiAcMFlUAOrc8DzxYHAxflx2chMYzWA8oSCJPHAuMF4RSXXI5FTLlgBWPAAeAEIRUXCxZFlwhYlw24p7IIdHMYlJVHAAihQQ8I9dnBLPEXMsXM0MNcqB1rC5EjBelxCDAOMgABwABhB7mWvQi1macLg4LkD0sAEc-vB1jZ-C0eABaKBwPJ5DouOBUric9blLZIHbPZZZLipdLAkA8D5fX7-B6Cp6SmBkSRIlFopAaSxpMhcKgfADCECyApAJIArB0KMs2Kr-ELJXJlABJKDEWAxMDw2wAQXdMRgGC+gOWAF8w0A)

```sh
--parser yaml
```

**Input:**

```yaml
key1: &default

  # This key ...
  subkey1: value1

key2:
  <<: *default
```

**Output:**

```yaml
key1: &default # This key ...
  subkey1: value1

key2:
  <<: *default

```

**Expected behavior:**

```yaml
key1: &default
  # This key ...
  subkey1: value1

key2:
  <<: *default

```
