### ISSUE TITLE
Improve formatting for :is() selector

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#10639]
The `:is`/`:matches`/`:-webkit-any` selector doesn’t look very good when passed a bunch of comma-separated selectors:

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEZKpgFAOgEMAHYgWgDMIwBXAZzgBMBKAAiQEs7cAdKV1vjph0AG1FxUZAIwAhAG7EA1jQA0fAfkixCHKJLIBmAO4B2AFJkAHuv6DhYiVOnmARgGkAsnFuaAtnB+rpJ0MgCcYQAcxLK+ggFBIeFRMawAfKyMHPJ8bMAarK6EYEoA5ug0UIxIrPKEqLhkZEUl5RCVjGQM2oz1AJ5khKIwbACEHH7EEKgwhLAA3HwAvnwgqiAQxDAc0HTIoPXoxgAK9Qh7KEPGhH17666oxUpwMADKxMV6pcgwqDQ+IECwUYjCYABk5qUaIRSnAAGLTPyEGDbKDfS40GAQNYgAAWMD8ogA6riOPA6B8wHBXucydkyX1kOA6HcQHoGDNjo9SkjkBQhgx1gArOhWWSPEovV6EAJgvRwPkCgEiqyvL4SACKNEwCqQ-NEgpAH1QHKZYBZOOIqD0MCJHEYMFxyEiAAZ1laIAwiY9iEyrXAOfIFesAI7a+BczYXECEUL6JhMHGoOBhjjJrkw3l6pXrBh+Dg-P4AujquBanWKg0A2auO0Op1IABM61+ulEXwAwhA-FnAXQAKw4+hwAAqhFcF31hvk-wAklUEG8RBwtgBBKqvGB9CSVhhLJZAA)

```sh
--parser css
```

**Input:**

```css
:root:not(.app-focused) :is(
  .scroller-1Bvpku,
  .container-3w7J-x,
  .scroller-1JbKMe,
  .members-1998pB,
  .members-1998pB > div
) {
  background: var(--background-secondary-alt) !important;
}

```

**Output:**

```css
:root:not(.app-focused)
  :is(.scroller-1Bvpku, .container-3w7J-x, .scroller-1JbKMe, .members-1998pB, .members-1998pB
    > div) {
  background: var(--background-secondary-alt) !important;
}

```

**Expected behavior:**

Same as input maybe? Alternatively, 

```css
:root:not(.app-focused)
  :is(
    .scroller-1Bvpku,
    .container-3w7J-x,
    .scroller-1JbKMe,
    .members-1998pB,
    .members-1998pB > div
  ) {
  background: var(--background-secondary-alt) !important;
}

```
