### ISSUE TITLE
`yaml` not idempotent when using `proseWrap: never`

### ISSUE THREAD

**Issue by SimenB** [prettier/prettier#10776]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEArCAjAzkgOlAAgIBsIwBrPQogreABx3xpoFoCB3ASxgAsqWgglyxYArnFakKrSAFs5CGEgIA+ZkMEAVXiOGiJBXgEMsBDHAQFjYmBDnGYXMMeLEAniTLk4AE1pcUGBwBHxwAE4hJmZQEDDmloTGUJ6RwbDWYE4AbjyexgBm8OHC8RymBGCkWH4AdAQACsRwpiEQ9FbGBFBwHPriIQUQJZHEjn7mYgDmWLX4Gpo0TS013XEhfHoiA6HhxhQR+mvxXbxwxPQEQ+FicvUA6iFp9opQ-mJYgVMEANoAyjB9uQAPLZCIFUgcAC6AApeDAYIwkAB6ZF0IEQMHhCEQDi1eTIgCOEjoXGgWGRgKmUz8yNQcDoqCwAEoCMM2WISj9fCJIOF-GATFAesRYfDEThUTysHzfLVqXSAGwAMQA0qqAIoa8L3ACcrOuBGJDKc5Lm1EW9HCUm8rEC+xykl8xncOAIAHIAMwABndC00VptMnkr2Uan9ix0enoYjcBEixroRgqFk6tnsjmcrg8XgO-k+QQ2Z0iyZicQSnRS8bg6ROWS4uRg+SKhx4nAqVQgNTljWarTZHSS3V6-UMhtG438GGms3mFsWvZWIVi8FCujM20MMD2BxKehX1iM50u11uDyeNZeCHeBe+-0BFFB4MhYoRSNR6IomOfuPx9iJJKmlAFJUjSvh0iaTKsuyECcr80qypUQoiq+EoosiCHDHKCqoCq6pajq+pXOyiZAbMIAADQgO0ZHIKAxjhOEuINAxCBYMgICuOUrqUSAGA7j4MB-PQ+xfMg24SFRcByBYvi+H4AAyyRTGIxg0sqwwOAiYkoDYdi8fCcjEPcujwFgInBH8bE8A2eQcWAoi8YENThDADR7FMDjIAUrg1FRTIAB4AEICXAQnGIoCmBHA3m+XA-lYAFfxfM0GpiOssXEH5IAieELkce4EXELxVqBDA9xcL4fDIAAHN6VFWl2cD3Hs9AcT0WK8cS6zue07G6VgrA9H4fi8QmYhcJE7lqV5SA+Vl8UgDUchcOJNyLbeqXpfAmXZYCGAVVVvDIAATFR27GFwxBfAAwi8xgcQyACsvEfHAWjGNgu2LdkEgAJJvEofxgOEXD0DAACCbwAu4zTfQAvvDQA)

```sh
--parser yaml
--prose-wrap never
```

**Input:**

```yaml
jobs:
  lock:
    steps:
      - with:
          issue-lock-comment: >
            This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

            Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.
          pr-lock-inactive-days: '30'
          pr-lock-comment: >
            This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.

            Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.
```

**Output:**

```yaml
jobs:
  lock:
    steps:
      - with:
          issue-lock-comment: >
            This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
            
            Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.

          pr-lock-inactive-days: "30"
          pr-lock-comment: >
            This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
            
            Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.

```

**Second Output:**

```yaml
jobs:
  lock:
    steps:
      - with:
          issue-lock-comment: >
            This issue has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
            
            Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.


          pr-lock-inactive-days: "30"
          pr-lock-comment: >
            This pull request has been automatically locked since there has not been any recent activity after it was closed. Please open a new issue for related bugs.
            
            Please note this issue tracker is not a help forum. We recommend using [StackOverflow](https://stackoverflow.com/questions/tagged/jestjs) or our [discord channel](https://discord.gg/j6FKKQQrW9) for questions.


```

**Expected behavior:**
Ideally non of the formats should happen as the newlines added are not needed
