### ISSUE TITLE
Using selector as a mixin name with an optional argument causes formatting to remove characters

### ISSUE THREAD

**Issue by robert-j-webb** [prettier/prettier#10787]
Definitely a weird one!

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgGc4AbOMGCAJwAoASAQyoHMl8BGAJgEp9gAdAvkglqSAEYkArnADcgwQF8FUDDjxFS5SlXx789Jqw48+gvSLGSZ8qMqiC1uAgAcqcAGY4AylorVDFjYuXgEhSyoJaTklQRAAGhAIFxhMaEJkUCYqCAB3AAUmBAyUBhJchgBPDMTxKgYwAGs4GG8XBrxmZBgqGUS4dHE4ABNhkYAZBihmKQZmOAAxanQGGFTp5BAGKUoEkAALGHQSAHV9zHhCdrA4XyhCC8wANwvKzbBCGpA8YioYfPqzBWyA8ZWIiQAVoRsAAhepNFreBjoODjPBwEFguCQ6HeTpkACKUgg8ExJHBIHaVF+m0IHy+bjwMBOmGGMH2yAAHAAGRJuCDEE71FybNxwX5PDGJACOxPgAOSJS2hAAtFA4CMRnt3LLMO4AXNgUhQeTsSBiFhur0zQ9poS5RjjVjEjAGOIWWyOUhOC76pgSJ0AMIQdBGkDigCseykxAAKm6SiaKU8ZABJKBjWDeMBUTApACCGe8MEqZDJxEUiiAA)

```sh
--parser scss
```

**Input:**

```scss
@mixin selector($arg: 12) {
  color:blue;
}

@mixin selector    ($arg: 12) {
  color:blue;
}

@mixin prefixSelector($arg: 12) {
  color:blue;
}

```

**Output:**

```scss
@mixin selector($arg: 1) {
  color: blue;
}

@mixin selector(($ar) {
  color: blue;
}

@mixin prefixSelector($arg: 12) {
  color: blue;
}

```

**Expected behavior:**

Don't delete the characters (even if you use the mixin named selector)!

```
@mixin selector($arg: 12) {
  color:blue;
}

@mixin selector($arg: 12) {
  color:blue;
}

@mixin prefixSelector($arg: 12) {
  color:blue;
}
```
