### ISSUE TITLE
Inconsistent yaml formatting

### ISSUE THREAD

**Issue by quasarea** [prettier/prettier#10822]
**VS Code Version**: 1.55.2
**Prettier Extension Version**: 6.3.2.
**OS and version**: W10 1903

When formatting the first ?: gets reformatted while the second is left as is. It seems to depend on line length (happens only for shorter than 84 characters) but I have not found any place to configure/control this behavior. Due to that I'm ending up with inconsistent code like:

**Output:**
```yaml
  - stage: Process
    jobs:
      - template: Process.yml
        parameters:
          ${{ if in(parameters.BuildType, 'a') }}:
            BuildArtifacts:
              - input: Build.Release.x86
                output: Processed.Release.x86
          ? ${{ if in(parameters.BuildType, 'b                               ') }}
          : BuildArtifacts:
              - input: Build.Release
                output: Processed.Release
```

**Expected behavior:**
Given yaml like:
```yaml
  - stage: Process
    jobs:
      - template: Process.yml
        parameters:
          ? ${{ if in(parameters.BuildType, 'a') }}
          : BuildArtifacts:
              - input: Build.Release.x86
                output: Processed.Release.x86                   
          ? ${{ if in(parameters.BuildType, 'b                               ') }}
          : BuildArtifacts:
              - input: Build.Release
                output: Processed.Release
```
**Prettier 2.2.1** - here it is 78 chars that makes difference
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVBaVBnGBDAcziVQAUAnCMObbAHSnXQCsIAjbJBppreAWwAOAGzzwSFKjWwA6AJ79h3Hk0F5yefnHjlOylUwAkwYKgCWAM3NQAFGo1adsgEIBXM8IAmAFTmC4ADSoAOR4wQCUqAC+UVyMBipuHp4AguQwlnhgMHrxCSpYZlCCrjAkSV4yAEpwwnB42HAyAB4AHABs+vkqEKUlZWSU1LRwntW19Y0tHV0GAPyoxqaW1nbqmtpwujIVPn6BIWzdxychkTGzKuXuXmkZFlk5cafohcWl18njdQ1wl8e9GD9CRDaSjb6TOAgAIgCCCDLQbDIUDqSgAd1I6gQSJQeGEaLwciRMLYGjAAGttABlNRgIoEZAwciuQIgOD8NijTyjAAyeCgBFchDgADEIOR+GIMgLkCA8KUINCQAALGCKADqyrM8GwtLgVOx2rMADdtXJZWBaEqio10hRCJLkA9hI0YcxsM1nGTKTAqRseUUoUhna6QO7mlT6XUAIquCDwJ140P2W2yuSaYRKwTkIowdVmTwwZXIADsrRh2YgjXVGkEsuzNC2xqhMIAjnH4JJBDi5dgMFA4KNRkryHB22ZR-aCI7g0nWY1+GZGcz51G4LH40GQ6z8Gx84Xi0gAEwwpl4Dz0gDCEH4M7Z2AArErXI1vHgOImXazjSyAJJQblYCpMAc3hFIAKpGA5DqT9GhiIA
