### ISSUE TITLE
Missing space before/after slash preceding hsl/rgb alpha value

### ISSUE THREAD

**Issue by glen-84** [prettier/prettier#10831]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOldf2QA2EATkgBYDOhAFAAwAmcA5unQKRvsD0ArBwEoA3DnwEIxMlVqMWXefm5j+7YaPTq8RUkhLMARvTZs+gkbnzayew3WN3FyszgC+IADQgIABxgBLaEpkUFQSEggAdwAFUIQglFRCCNQATyDPfRJUMABrOBgAZW9svyhmZBgSAFc4TzgAW304BiYGABlUMqrUZjgAMVJ61Bh-MuQ0KpgIDxByGHrCAHVyP3hKYrA4ArjVvwA3VZTxsEp0kFLKOBIYKKzmIeQAM0TLzwArSgAPACEs3PyCqh6nA2qU4E8XrUQB9PgVSsxCHAAIpVCDwCGEV4gYokS4kY6nGbeEilGCLPwMGDkZAARjodE8xIgl0WWW842JcDxe3BngAjqj4LcfPE0JQALRQODNZozEhwAV+eW3HoPJDPTFQy71PwVapa+GIlFo8HqyGeGCofTkynUpAAFgtWT8hHhAGEIPU1SAubwZlVLgAVK3xDVYvY1ACSUCYsAKYBJvgAgjGCjAUoiMZcXC4gA)

```sh
--parser css
--print-width 100
--tab-width 4
```

**Input:**

```css
a {
    color:hsl(0deg 0% 0%/50%);
    color:hsl(0deg 0% 0%    /    50%);
  
    color:rgb(0 0 0/50%);
    color:rgb(0 0 0    /    50%);
}
```

**Output:**

```css
a {
    color: hsl(0deg 0% 0%/50%);
    color: hsl(0deg 0% 0% / 50%);

    color: rgb(0 0 0/50%);
    color: rgb(0 0 0 / 50%);
}

```

**Expected behavior:**

I expected to see a space on either side of the forward slash, in all cases.
