### ISSUE TITLE
SCSS @use strings not quoted consistently

### ISSUE THREAD

**Issue by apexskier** [prettier/prettier#11053]
**Prettier 2.3.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArgZzgAgOTyYx4DcAOlBtjmSITLeVBagJYC2ADhAE4z4A6APT1SLDtz40Qw+owoUB9HMAo4ckWAhhJ89VlADmYqOs3xYu2vqPyoAXxAAaEBE4xW0TMlABDHjwQAO4ACv4I3ii+ADZBvgCe3i4ARjy+YADWcDAAypzpBobIMDzocC5w7MlwACY1tQAyvkbovoZwAGK87L4wHkbIIL7oMBDOIAAWMOzRAOoTrIT5YHA5EYusAG6L8YNgmEkgBth8IWmGPcgAZjHYLgBWmAAeAEJpmdk5vuxwDQZw11u5RAjyeOUK0TgAEV0BB4IDoncQPkeCdBph9odODwDDBZqwajAJsgABwABhc2Ig2FmaU4g2xcBOmwBLgAjrD4Gc3JEhpgALRQOC1WrjHhwDmscVnNqXJA3RHA7DsVjFUpKiHQzkA+VAlwwXzJfGE4lIABM+rSrGihQAwhB2HKQEyAKzjLBwAAqhsiCqRmzKAEkoPVYDkwDj3ABBEM5GDxSEI7D2exAA)

```sh
--parser scss
```

**Input:**

```scss
@use 'test';
@use "test";

@import './test';
@import "./test";

.test {
  content: 'testing';
  content: "testing";
}
```

**Output:**

```scss
@use 'test';
@use "test";

@import "./test";
@import "./test";

.test {
  content: "testing";
  content: "testing";
}

```

**Expected behavior:**

The `@use` strings should have consistent quote styling (both should be converted to `"test"`), like `@import` and other string literals.

keywords: sass, scss, quotes
