### ISSUE TITLE
Yaml: wrapping long continuous strings

### ISSUE THREAD

**Issue by bitozoid** [prettier/prettier#11140]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBLKA3CbMOAAjKTJIGYAWADhqqwBMBDeSiygJgAZeAjKkGpuTKACNsAG2moYELmQBk2ZvwFZKJAObY8CbRQDCACwBO2AM5bKAM1YBbGQE9yJACIBXR63NXWQKDgkNCw8IjIqOiY2PDbMlZmZnM4KyskBO0SaVw0igAfLOzKGgBWOhIAdVZpAGtfKE9zADpikpIAZS9sDgBibgBObnayMF63DooAJQgXWpIAeVY60ZIrGHZSbIoAWQBJNYAHCA2Fkgp6XhoANiwrU2wj+UUSACo1DSwj8whmLzAMEyTUoqBIWXaVjqXg67gAQgAZKiDGgedoAfhIAEcvKxYBNtO1Lu1mGkwJYjjBsNALiQ4awoXAYBJatIMSQfkRttkiSRyrwWvx2sKQWQwZDobD3GRETRGHQABLtHF4qkwSZGMiaUWUUlWclPKnQJSUbpHODmEgKiAQI7tTnEKVcMTDQW8EUlLCbAAe0u4ZQELRoI1gEE20lpcsYLTKIcgjkcCBgGRIAD4sgitiRWHZ4OYoDamtYSBI0jA2jr6WBoUcSJBYKxASRiwA5PFgFxZOEyaRWROWgAC1CodFQjBHFZAABoQLajVArMhQH5fgB3AAKfgQi5QtVXrBci5nEnMjbqTM6R0buB0yBg5i8cBncEcpeScGYmagOlxOjgADEIHMXwYCpb9kBAVgvAUacQFMGBHGkKpHngKwr2ITpt16fQJggsB0lg3ArAtGB11PHRfGQBxeyfEAACsrG9OFT2rC8nDgBE8io2piJnBjvU6G9pDgABFLwwzgbiaJnK9-AtCD5kQ2DOVgKo1BgUxkDoXgZN+YiqlPI4IJ+NILQMWCcQksjbR3SCrFQKA4A-D9YNSHFsFSMjWAo1gpN4kBiOcO8H1oqwhNE8T4D82jNgkNTmA05BuBne9WBkG9jAgBNfJQNIylgrxiIAFVYCQd2o-y8EffYoFJWBOgNSkAEFas6dVhOigBfTqgA)

```sh
--parser yaml
```

**Input:**

```yaml
---
invoice   :   34843
date   :    2001-01-23
bill-to:    &id001
    given    : Chris
    family  : Dumarsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    address:
        lines: |
            458 Walkman Dr.
            Suite #292
        city        : Royal Oak
        state      : MI
        postal  : 48046
ship-to: *id001
product:
    - 
    
      sku         : BL394D
      ? quantity    
      : 4
      description : Basketball
      ? price       
      : 450.00
      
      
    - 
      sku          :   BL4438H
      quantity      :  1
      description:      Super Hoop
      price         :  2392.00
      
      
tax  :  251.42
total : 4443.52
comments: >
    Late afternoon is best.
    Backup contact is Nancy
    Billsmer @ 338-4338.

```

**Output:**

```yaml
---
invoice: 34843
date: 2001-01-23
bill-to: &id001
  given: Chris
  family: Dumarsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  address:
    lines: |
      458 Walkman Dr.
      Suite #292
    city: Royal Oak
    state: MI
    postal: 48046
ship-to: *id001
product:
  - sku: BL394D
    quantity: 4
    description: Basketball
    price: 450.00

  - sku: BL4438H
    quantity: 1
    description: Super Hoop
    price: 2392.00

tax: 251.42
total: 4443.52
comments: >
  Late afternoon is best.
  Backup contact is Nancy
  Billsmer @ 338-4338.

```

**Expected behavior:**

I just wonder whether breaking very long continuous strings (with a backslash) would be possible, to preserve print width.

**Comment by sosukesuzuki** [comment]
Sorry I don't know how we should format. Can you share the expected formatted code?

**Comment by bitozoid** [comment]
How about this? I'd rather prefer to wrap and use quotes rather than a very long line.

```yaml
---
invoice: 34843
date: 2001-01-23
bill-to: &id001
  given: Chris
  family: "Dumarsaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
  address:
    lines: |
      458 Walkman Dr.
      Suite #292
    city: Royal Oak
    state: MI
    postal: 48046
ship-to: *id001
product:
  - sku: BL394D
    quantity: 4
    description: Basketball
    price: 450.00

  - sku: BL4438H
    quantity: 1
    description: Super Hoop
    price: 2392.00

tax: 251.42
total: 4443.52
comments: >
  Late afternoon is best.
  Backup contact is Nancy
  Billsmer @ 338-4338.
```
