### ISSUE TITLE
Less: not formatting detached rulesets

### ISSUE THREAD

**Issue by satoshionoda** [prettier/prettier#11276]
It seems prettier ignores formatting detached rulesets arguments.
https://lesscss.org/features/#detached-rulesets-feature

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AJnGBDMALOdAWgCcBXAGzgGcsAKAAXKuoEpgAdKAAm6cpp1WXAL5cuGLLgLFmNepx69lygGbQYRagEsAXnCQBGAEwAHAB4BubhW1Q4RAtoDmeGEdGtL4qKmo4odGwSYkwwCmDsGG1oRRU1DS09AxMLa1t7RzgXNyNvKBEQABoQCFNo6GpkUGCSCAB3AAVghCqUbAp67ABPKpKAIxJcAGssAGVTXDtnZBhyOBK4AFt+wkx0ABlsKGcybGc4ADEIEiWo6J3kEGwyGAhikDcligB1PG14akmwODHWj+0ADcPt0rmBqH0QHZaCQYI0hs4zshVB1aCUAFbUcwAISGYFGMDG2CWcA2djgyNRCxAmPMY2mVAAimQIPBKRQ0SBJiQYVcWJDTCQ7DAXtp0DA8MgABwABhKgogtBeQ1MV0F8hIgIpJQAjiz4PCym1rtQiPZCIQHiQ4HrtNb4fskUgURzqbQltpZvMSjodkz9RTnVSSjh+qLxZKkMYQ0NtBlnABhCBLJ0gGgAVgeZFoABVsP02i7OYCyHAAJKBBCEsBC8oAQUCYxg3So7NoIhEQA)

```sh
--parser less
```

**Input:**
added dirty codes.

```less
.detached-ruleset(@rules){
  @rules()
}

.detached-ruleset({
         font-size:12px; line-height:1
});
```

**Output:**
returns exactly the same as the input

```less
.detached-ruleset(@rules) {
  @rules();
}

.detached-ruleset({
         font-size:12px; line-height:1
});
```

**Expected behavior:**
should return pretty.

```less
.detached-ruleset(@rules) {
  @rules();
}

.detached-ruleset({
  font-size: 12px;
  line-height: 1;
});

```
