### ISSUE TITLE
Prettier couldn't recognize the 'each' function in less.

### ISSUE THREAD

**Issue by yzqdev** [prettier/prettier#11281]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAznANnMMIBO6SABAQIZQDmcAFAIwAMjAlANwA6Uc5YAFrQzZc+IgBoSAOkEA3EixLAuJEj36DMOPIXSLlKqQFsAtKmAyAvqfPksAVzgXFBw+QJUAllFL0ADgA8AKlQ5PyCQ2wdOKAMSJ0lfa0skyMdnEl9yABMsryofAODQwoj7OGjYp30LFi4atgB6BpIcdF01PhIAMzsoPA9oZRAxEAhfGAGodGRQNwIIAHcABTcEaZRbBfIAT2mRgCMKMABrOBgAZUywPOQYAgcRuEN9uBzXgBlKKjtyGgAxQiuGATajIEDkOz4YYgPgwQxYADqfA88HQVzg5zWKI8MhR2zBYDa0K8mAIMCWFCormQXVsmBGACt0P4AEJHU4XciGODvLxwGl0uCM5nnPI4ACKdgg8AFWHpIEyRDgBDBrT2CoIXhgCI8WRgfGQAA5GCNfPNMAiKL4wWa4KSZPyRgBHKXwCljdbg9DGbivV7QghwF0eQMU37UpC0uVCkCYQweW73GPoMVwSXS-mRwUjGDkfY6vUGpAAJhzFA8WDyAGEIIYIyA7QBWaF2TAAFTz6yj8pkDgAklAsggLmBNeMAIKD84wbY4WWYCwWIA)

```sh
--parser less
```

**Input:**

```less
@selectors: range(100);
each(@selectors, .(@v ) {
  each(@selectors {
    .m-@{v}-@{value} {   margin: 1px*@v 1px*@value;
    } .p-@{v}-@{value} {  padding: 1px*@v 1px*@value;
    } 
  })
});// less each function
 
```

**Output:**

```less
@selectors: range(100);
each(@selectors, .(@v ) {
  each(@selectors {
    .m-@{v}-@{value} {   margin: 1px*@v 1px*@value;
    } .p-@{v}-@{value} {  padding: 1px*@v 1px*@value;
    } 
  })
}); // less each function

```

**Expected behavior:**
```less
@selectors: range(100);

each(@selectors, .(@v ) {
  each(@selectors {
    .m-@{v}-@{value} {
      margin: 1px*@v 1px*@value;
    }
    .p-@{v}-@{value} {
      padding: 1px*@v 1px*@value;
    }
  })
});
```
