### ISSUE TITLE
Hex format

### ISSUE THREAD

**Issue by 5alidshammout** [prettier/prettier#11305]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAnsAOlAAgNQEMwBrAcwCcIBXKDJAgYgGYARVAIQDEAzfAF8QAGhAQADjACW0AM7JQJarQDuABRUJFKEgBs1JLIvGpqZcnBgBlSWRlRKyGNTpxxcALao4GDH4AMiROdCSUcLwQ1F4kMLJOyCAkdDAQYiAAFjBe+gDqmTLw8vZgcDY6RTIAbkVYSWDypiCO8nDUMBoWlLHI-AZt4gBW8gAe3BYU1jYkXnCBjnB9Ax4gI6M2jpT6cACKdBDwy-qDIPbUbdQNTRmS1I4weTIYMJnIABwADOJ3EG15FkkSTucEu1SW4gAjgd4F0pLpkvIALRQOB+PwZahwaEyLFdcK9JD9E6rNpeGQuNykrY7faHJZElbiGAkVBPF5vJAAJmZFhk+i2AGEIF5CSBQQBWDJ0NoAFVZulc7nE1XcAElGAhbGB7tIAIKMGwwLA7Y5tIRCIA)

**Input:**

```css
body{
  background: #3DbBFf
}
```

**Output:**

```css
body {
	background: #3dbbff;
}
```

**Expected behaviour:**

```css
body {
	background: #3DBBFF;
}
```
The result can be `#3dbbff` or `#3DBBFF`, this is a choice by the user
