### ISSUE TITLE
[Bug] Incorrect formatting of attribute selector when containing `//`

### ISSUE THREAD

**Issue by wenfangdu** [prettier/prettier#11604]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA2gCwE5wGYB6AvAOSYwwAOAzkgPR1wAeqAtpQDZwB0krJAXQAEwADpQhQgCYBLap1QBPJEKjQ4AbnEBfcSAA0ICJRgzo1ZKFTZsEAO4AFawgspUHO0ouGARtlRgANZwMADKbHAAMjJQcMh47tRwvv5BIaGUATEA5sgw2ACuySBwrD5wUlIVkahQ2QWo2XAAYhDYrKgUOchoBTAQBiDkrBwA6pgy8PIBcKEukzIAbpOKPWDU3iAxSdgwDv7ZHfGJxQBW1EyhOVwAigUQ8MccSYaZ2DtrG4OU2DEwozIpDBMMgABwABletiSo38lB6PzgO0WcUMAEd7vB9sZXGhqABaWIVCqDXAYmS4faNI5IBLPYpJVgyPKFBnXOB3B5xWknQwwVA+AFAkFIABMfP8Mg4OQAwhBWDSStQAKyDApJAAqAtcdJeIEWRQAklAqrBQmBfiYAIIm0IwRRcJ5JbTaIA)

```sh
--parser css
```

**Input:**

```css
a[href^='https://example.com'] {
  display: none;
}
```

**Output:**

```css
a[href^='https://example.com']
{
  display: none;
}
```

**Expected behavior:**

```css
a[href^='https://example.com'] {
  display: none;
}
```
