### ISSUE TITLE
Format css is wrong

### ISSUE THREAD

**Issue by zhangdaren** [prettier/prettier#11811]
**Prettier 2.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKB6AVAAgA4CGA5nBgJZQAmcAHhgDZkDOMAdAO41NM5Ybb5ipCtTqVmbTt14Z0rAEYQATtSXBI9ZUgAMAX3TocAAQBm0GAFoTBMHBzBDZ2FYIBbMvQCeSJXHc0ySCgAbiYlMCQAVyV6AAp+MEooVgArJmpGADclVig4GAwoPFcMX39A6CMAJlYAVlZtDCcYJlK-MgCg1jgIGAB+GABeAEZagE5tKu0AdgAOADYx2dGAYjI4Ew6AShwzJVcCGFjUED95OEpqSgsIPAQYTzuTrYAaaLiEpNT0uCycvIKRRKZQ6FSg1TqDSa5laIM60A4EBMJiqAxG40mMwWS1GOz2ByOJ3YSJRzzeMXiGESyTSGTI2Vy+UKxTa5SCEPqjWasPa8OSxORaNGEymc0Wy1qeOUBOOIAFJjJ70p1O+dIZAOZwN5YI5UO5rNBXRgMBMQoxouxEql+0OspgSki+UecEVFM+NJ+f0ZgJZcJ1NU50NgPLZCKYmSIZpFWPFqz9QWtMpO4aIz2CzQs4iYeHoBG8BEiMAgwUMuhALxAtxgZGgTGQoAISiUEHYAAVGwg6ygCPR2Hm6xX5EobABrfIAZTccAAMhQ4MhrPQmHBB8OwGOYOPCGAKERkPbHRWzhcrtOCFAiJEhAAxaWHasX5AgAtF8sgAAWMFc9AA6u+yPA2Y2HA46dgB9IAZ4T5gNwb4UMuSgwK2w5EAcC49suFZpDQ467vQcAAIqRL085IIumEgIQSgIdBsEVngSgUDAP5kJQMDvsgszaPRzbLj+w54E+DFwAhmTzhWACOxHwMhtxds+TAWHkFwXG+vhSWQvjIcQaFkRhK4gMu7j7g6BlMHhhHSaR5EGTABDyCxbEcUgVQVvaBAeLuADCECuLppxMLUb6RMuAAq9ldjZFaZI6ACSVD3OOYCMXgMAAIJUOODz4ehS5wLouhAA)

```sh
--parser css
```

**Input:**

```css

/* page/index/list.wxss *//* page/index/dist.wxss */
.border{color:0}

 @font-face {
 font-family:remixicon;src:url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.eot?t=1590207869815#iefix) format("embedded-opentype"),url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.woff2?t=1590207869815) format("woff2"),url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.woff?t=1590207869815) format("woff"),url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.ttf?t=1590207869815) format("truetype"),url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.svg?t=1590207869815#remixicon) format("svg");font-display:auto;
 }
```

**Output:**

```css
/* page/index/list.wxss */
/page/index/dist.wxss / .border {
  color: 0;
}

@font-face {
  font-family: remixicon;
  src: url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.eot?t=1590207869815#iefix)
      format("embedded-opentype"),
    url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.woff2?t=1590207869815)
      format("woff2"),
    url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.woff?t=1590207869815)
      format("woff"),
    url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.ttf?t=1590207869815)
      format("truetype"),
    url(//cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.svg?t=1590207869815#remixicon)
      format("svg");
  font-display: auto;
}

```

**Expected behavior:**

**Comment by kachkaev** [comment]
Hey @zhangdaren 👋. Are you referring to the comment on line one or the line breaks in `@font-face` → `src`? Could you p please fill in the _Expected behavior_ section?

**Comment by sosukesuzuki** [comment]
A comment moving into next selector is a definitely bug...

**Comment by zhangdaren** [comment]
> 嘿@zhangdaren 海浪. 您是指第一行的注释还是`@font-face`→ 中的换行符`src`？请填写“_预期行为”_部分好吗？


Error in comment:
`/* page/index/list.wxss */ 
/ page / index / dist. wxss  / . 边框{
  颜色： 0 ;
}`

The correct thing is:
`
/* 页/索引/列表.wxss */ /* 页/索引/dist.wxss */ 
. 边框{颜色：0 }
`

**Comment by zhangdaren** [comment]
> Hey @zhangdaren wave. Are you referring to the comment on line one or the line breaks in `@font-face` → `src`? Could you p please fill in the _Expected behavior_ section?

Error in comment:

```css
/* page/index/list.wxss */
/page/index/dist.wxss / .border {
  color: 0;
}
```

The correct thing is:
```css
/* page/index/list.wxss *//* page/index/dist.wxss */
.border{
   color:0
}
```
