### ISSUE TITLE
Prettier breaks SCSS code when using negative values with functions

### ISSUE THREAD

**Issue by Mikilll94** [prettier/prettier#11944]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArgZzgAgOSYCGmmSAtoQA54DcAOlAwCSYRlwD6AboQE5I4AFAxz5CeAQEZKADwA0I-ACMJOAEyyFUAJT1GUAHSt2AWjAAbYphzBFlQgBMHASygBzE0ogwYbASZwKSgM3OBhBFjY4Ex5eOTE8XQYAXwYQORAIShhnaExkUD5eCAB3AAU+BHyUQnMSwgBPfIylXkIwAGswgGVCdgAZVzhkADNa7Ba2zp77MFc3ZBhedDgMuDIlOCct-sJ3dEJQgDEIXgofeeQQQnRfdJAACxgycwB1B+d4TFm4bqrP5xcT4NK5gEj3VzYXgwMptNwUUbjVYgABWmBk3Xm5jgAEV0N5hkgxuYJiB7LwoVdMGDmmTeK4YK9nA4YA9kAAOAAMGUoxWwrzalCuvLgUK4wwyAEd8fBYVlqtdMCYoHAtlt7rw4NLnJrYYcEUSkRlsGRnItlsjMFjcTLCcTSTBCEomSy2Ug1BkloRnOZ5gBhNgGkCigCs9ywcAAKk7qvbkVwVgBJKAOBAwbpgenZACCKe6MAa2MRJLgyWSQA)

```sh
# Options (if any):
no options
```

**Input:**

```scss
@use 'sass:map';

$some_var: (
  'a': 1px,
  'b': 2px,
);

.some-class {
  padding-bottom: - map.get($some-var, 'a');
}
```

**Output:**

```scss
@use "sass:map";

$some_var: (
  "a": 1px,
  "b": 2px,
);

.some-class {
  padding-bottom: -map.get($some-var, "a");
}
```

**Expected behavior:**
After Prettier formatting there is a compilation error:
```
Error: There is no module with the namespace "-map".
```

Prettier should not remove the space before `map`.

**Comment by sosukesuzuki** [comment]
This is a bug, but there is a workaround:+1:

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArgZzgAgOSYCGmmSAtoQA54DcAOlAwCSYRlwD6AboQE5I4AFAxz5CeAQEZKADwA0I-ACMJOAEyyFUAJT1GUAHSt2AWjAAbYphzBFlQgBMHASygBzE0ogwYbAScEKSgM3OBhBFjY4Ex5eOTE8bV0GAF8GEDkQCEoYZ2hMZFA+XggAdwAFPgQClEJzUsIATwLMpV5CMABrMIBlQnYAGVc4ZAAzOuxW9q7e+zBXN2QYXnQ4TLgyJTgnbYHCd3RCUIAxCF4KHwXkEEJ0XwyQAAsYMnMAdUfneEw5uB7qr7OLhfRrXMAkB6ubC8GDldpuChjCZrEAAK0wMh6C3McAAiuhvCMkONzJMQPZeNDrphwS1ybxXDA3s4HDBHsgABwABkylBK2De7Uo1z5cGhXBGmQAjgT4HDsjUbpgTFA4Nttg9eHAZc4tXCjojicjMtgyM4lisUZhsXjZUSSWSYIQlMzWeykGpMstCM5zAsAMJsQ0gMUAVgeWDgABVnTUHSiuKsAJJQBwIGA9MAMnIAQVTPRgjRxSNJcBSKSAA)

```sh
--parser scss
```

**Input:**

```scss
@use 'sass:map';

$some_var: (
  'a': 1px,
  'b': 2px,
);

.some-class {
  padding-bottom: -(map.get($some-var, 'a'));
}

```

**Output:**

```scss
@use "sass:map";

$some_var: (
  "a": 1px,
  "b": 2px,
);

.some-class {
  padding-bottom: -(map.get($some-var, "a"));
}

```

**Comment by stuprog** [comment]
Hello,

I tested the bug with the postcss-scss version 2.1.1 to see if the problem is coming from there or not. 

This is the result 

### Input 

```
const scssParser = require("postcss-scss");

const result = scssParser.parse(`
@use 'sass:map';

$some_var: (
  'a': 1px,
  'b': 2px,
);

.some-class {
  padding-bottom: -(map.get($some-var, 'a'));
}

`);
console.log(result);

```

### Output

```
<ref *1> Root {
  raws: { semicolon: false, after: '\n\n' },
  type: 'root',
  nodes: [
    AtRule {
      raws: [Object],
      type: 'atrule',
      name: 'use',
      parent: [Circular *1],
      source: [Object],
      params: "'sass:map'"
    },
    Declaration {
      raws: [Object],
      type: 'decl',
      parent: [Circular *1],
      source: [Object],
      prop: '$some_var',
      value: "(\n  'a': 1px,\n  'b': 2px,\n)"
    },
    Rule {
      raws: [Object],
      type: 'rule',
      nodes: [Array],
      parent: [Circular *1],
      source: [Object],
      selector: '.some-class'
    }
  ],
  source: {
    input: Input {
      css: '\n' +
        "@use 'sass:map';\n" +
        '\n' +
        '$some_var: (\n' +
        "  'a': 1px,\n" +
        "  'b': 2px,\n" +
        ');\n' +
        '\n' +
        '.some-class {\n' +
        "  padding-bottom: -(map.get($some-var, 'a'));\n" +
        '}\n' +
        '\n',
      hasBOM: false,
      id: '<input css 1>'
    },
    start: { line: 1, column: 1 }
  }
}

```

**Comment by literat** [comment]
I think I have a similar problem with a function name in SCSS after upgrading to Prettier v3:

**Input:**
```scss
@function -get-child-translate-map($prefix) {}
  
translate: map.get(-get-arrow-translate-map($prefix), $placement);
```

**Output:**
```scss
@function -get-child-translate-map($prefix) {
}

translate: map.get(- get-arrow-translate-map($prefix), $placement);
```

[Tested in Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKABAZgVymGAS2gAIBaAczhjLAAtCAbAEzJgCcBDKAZ0c-hkAtpwAOACgAko9nCyEAHgEoSwAL7oSJdB258BcJCRGiAdFRjjK1Mp3bsIAdzZde-QSaky5ipQBoSaX4wOCEEGCUAbhIAehiSAEZTAGYQPxAIUSJoHmRQOwdHAAU7BFyUTkZHTgBPXPSAIy4wAGtqAGVOMIAZQig4ZCxKnjhG5raYdtFOMD6KZA4cUZARoUIF9iX0njnGOABFHAh4QeHlgCseBXbdg6OTpCHGEfSAR3u4IodRcpBOHjI-TgzGBaRAuiYcwAwhAhCJkH9GIwwTsoBQ9gBBGAcQgNHDwIpwdi9fqnZ7LOgwISMADqDHgPGmIXaZUIRAAbmyagiwDx6iB2UsAJJQEGwdpgdiELIY0XtGA1PZkl4gGQQEY0riiBHeEbsdkDdJ9PUwL6cCjwx5ndLTdh6hE8Xn8mR9GA0wjMGB0ZAADgADOlZO9CLIzRbOMrljBOA13Z7vUgAEzpHAjAAqMfKTxVoQawJBzG63AoOHNcAAYhB2CJsXMEZx8RAQGo1EA).
