### ISSUE TITLE
Prettier add a white-space after escaped character inside CSS var() functions.

### ISSUE THREAD

**Issue by enjidev** [prettier/prettier#11982]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZtGAdbBqARgAJhsoiiBaSzWXQpIsAQwBswAKAN2YCcPqtGAEoieIgQAOAD2EBuMhUVEhlAM4BLAF5xGPfoKz0C8sgF8yZDEewAqAEwllhunfuMW7bnwE0so2yJ7U3IiZVVNHT0fFxw3ELMQABoQCEkYDWg1ZFA+XggAdwAFPgRslDYC5gBPbJSAI15mMABrOBgAZWYAWzgAGQ0oOGR0NjU4BqbW9o7JZsGAc2QYXgBXCZA4bvq4ABNdvb7mKAXV5gW4ADEIXm7mGAyT5BBmVZgIZJAACxhu1gB1L4aeBqOZgOAdMrAjRcYHVZ5gNR1ECDca8GBFJoLO4jMYbABWamkHUWrDgAEVVhB4LjWOMUnNeGjnmpEcjJLxBjB-hpdjAvsgABwABgZ+XG-yakmeHLgaK4wxSAEcqfBMWlyi81JQhns9p9eHAVRpDZjzjikKM6Rtxt0NMs1jbSRTVcNLXiUjBmPUeXyBUh7J6mhpWIsAMIQboWzZqACsn1W4wAKt7ylb6SAuOsAJJQA6wDpgTnpACCeY6MGqZNp4zMZiAA)

```sh
--parser scss
```

**Input:**

```scss
.font\+1 {
  --font\+1: calc(var(--font) + 1px);
  
  font-size: var(--font\+1);
}

.font\*2 {
  --font\*2: calc(var(--font) * 2);
  
  font-size: var(--font\*2);
}
```

**Output:**

```scss
.font\+1 {
  --font\+1: calc(var(--font) + 1px);

  font-size: var(--font\+ 1);
}

.font\*2 {
  --font\*2: calc(var(--font) * 2);

  font-size: var(--font\* 2);
}

```

**Expected behavior:**

Prettier should not add the space after an escaped character inside the CSS `var()` function. (e.g. after `\+` and `\*` ).

The current behavior causes the browser to treat it as an invalid property value.
