### ISSUE TITLE
Prettier fails to ignore liquid tags in css files

### ISSUE THREAD

**Issue by datapolitical** [prettier/prettier#12008]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdK7VYPQBUABAGICSAMgCoCiASmQHIDiRdAqhTQMpaDIBAMFDhI0WPHCiBPFmABSIgDMIAJyJgAhvADmqgJ5EAllCIBnQ-AB0AEy0bLKuGEMAHOAH1NO1YbimicgC+WADaAG4aADYArnAAvBggwMBecLoqepZQGgC2cIHBIAC6SGAAFk4A1nDWRAB+RJaKhpHwKv4hyioJSSlaafpZufmFRfJE0VCRfv5dkRAQLpaRGqYwAYEANLIKCNaT06b+QeN7XRtEwFhERABGGmCV2ioQk9ZIRDAqGlCmLhqOWAAbmu6gg8xUHwiKgAFOgAO5lCxwACUIJMd1U1jgKlQtwgMBgEByHwADJYAEwAVkcOTM4MMtQAxAARADCNFJNAAbOibv9rNZjNoyZSaXAcnyiDkAdpjHiCUSSURUGLaejglAdkpVOp+ukDMYzMibHYHE5XB5UulfMdNeEorEeslrYNsnkCokSlACTDShVHjUUfUiOCiJFDOGNLc4JFOqpnX1vBkhh7RuMDjMdSp5otlqt1kFtlBTlB9lMsyddmXzkFLqDIBCPkyAIIkNsAIRZGqw2vOroyRhM5isthg9kczjcnn1Pj8G1CERi8USLtnKfdIy9SB9MD95SqQZDYYjUZjkSQZQgYRx8e6q6TAw3w09xQzFaO2dzSxWaw2xdLctDjtQDa0CesMUbVRm3bdsAGY4J7LUoAdZcehbSJIm3A9A1qBpLEMGVtDgVBnkZIgQjHDRUAHPQiggm4hT+FY9A+W55keJDxn7ddDWHE0qPNKcrXXW1Q0URRTDgGAkAARgXFClydB9aNTLdin9Q88MaQiNGI0iVHIgiiJIyBYA0YwcR3X1KLsGjeLqRNVM3V8ihRd9gK-BYfwLf9tT2TNPyrIgzl1OsrgxJiXBYj4fSgOAkJATYQEWGBDGgUxkFAAEXnhAAFAEEEylAonhDQ9Ey5Lbm+QMYG4YYKEs5BFCiKSqpq6o6v+ZwoG0ZAvliZKJRjQUagoH5tGiPS4BIVQZUJYVkBADRoiJJKQDKGAckiAB1JF4D+B44G4IqLEMMILD0JawCOdbjCklQYDy75tBlZrWrgZKACtTAAD24YVpgARWiAk4HeyI2pAf52hxa7buSlxDNgHbGRgMpkAADlJRGXiknbvhcJakb8HEb3WgBHUH4GexZiuW0xUHimoanWxwqcMRxnr0t6kBayHPpAKSckMfqVEGoXAbgEGwYhqHx1uVHrHR5AKWSr4LIjXq2WJXmQD8Kl1uiKSqGjYr+ahsJYjIMsEDqsBDJcGAWzLbgYD0aY5ZGIA)

```sh
--parser css
```

**Input:**

```css
---
---
/* FILTERING RULES
–––––––––––––––––––––––––––––––––––––––––––––––––– */
{% for category in site.data.recipe_categories %}
[value="{{category.name}}"]:checked ~ .filters [for="{{category.name}}"]{% unless forloop.last %},
{% endunless %}{% endfor %} {
  background: transparent;
  color: var(--white);
  border-bottom: 0.25rem solid #DCE0E6;
  padding: 0.25rem;
  margin-bottom: -.25rem;
}

{% for category in site.data.recipe_categories %}
[value="{{category.name}}"]:not(:checked) ~ ol li label[for="{{category.name}}"]{% unless forloop.last %},
{% endunless %}{% endfor %} {
  color: #AFAFBD;
}

{% for category in site.data.recipe_categories %}
[value="{{category.name}}"]:not(:checked) ~ ol li label:hover[for="{{category.name}}"]{% unless forloop.last %},
{% endunless %}{% endfor %} {
  color: #FAFA33;
}

[value="All"]:checked ~ .image-grid [data-category] {
  display: block;
}
{% for category in site.data.recipe_categories offset:1 %}
[value="{{category.name}}"]:checked ~ .image-grid .image-container:not([data-category~="{{category.name}}"]){% unless forloop.last %},
{% endunless %}{% endfor %} {
  display: none;
}

```

**Output:**

```css
SyntaxError: CssSyntaxError: Unknown word (5:2)
  3 | /* FILTERING RULES
  4 | –––––––––––––––––––––––––––––––––––––––––––––––––– */
> 5 | {% for category in site.data.recipe_categories %}
    |  ^
  6 | [value="{{category.name}}"]:checked ~ .filters [for="{{category.name}}"]{% unless forloop.last %},
  7 | {% endunless %}{% endfor %} {
  8 |   background: transparent;
```

**Expected behavior:**
Should report no errors. This parses fine when the parser thinks it's html
