### ISSUE TITLE
missing space after class name will parse error when the class name has less variables

### ISSUE THREAD

**Issue by csu-feizao** [prettier/prettier#12051]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAhrAtABwE5wBmAlgB5IAEmMAJgNwA6UTAdHHnhHsExRQPT8KMABbEAzhRzo84uBXac8vCi1TBquAiVIBfLDTzoA7uyyRYCGFmNGcOdjyh8+AIwiks4kehoRjlAAMOKQUACwhFAAckcGhqCIQALZwWFDoAG5YrjLZHl4+fsbmEAA2XHQUKrpMNcxQLOIArmBgcOLiTnyCwmKS0rLyzW0dKmoa2PhEZPqGJmYW8Ni26PbsFF0u7p7evv5BkRGhMaFxFAnJqelZOXh5O4X+JeV4ldW1TEw9ohJSMnIUYYjSQwCAQVhA9riLCgiBIADm5RypQAFONNFMdLMjKY7osrDY7A48ABKTbbAp7AIUM5HaKxSIXFJpTLZXIU3ZFZ4VKpQXQgAA0IAgOBgxGg4mQoBknGMAAUZAhJSh0KVjOgAJ6SoWuIxgADWcBgAGV0CkADLEKBwZCEVVyHV6w0m6RgK3w5AwPBNOBCuBJVxwGg0IPmzDwproeFwABiXCS6BgYqgHpVTVBgpAIhgSVKAHUxPBxK64MalcQxRkKxrkOAOpmrXI8DA5UZ4QnbfbfSAAFbiUjG92lOAARSaEHgndKDpAAybteH9aF+CtMDzxBoomQUUCy84cjzdlrUybGRtQoAjuP4K2RcqQOhodag0HMwQr8QCK2ox2kHbp92chJMQnreoBQ6jteNp-l2QowOgrjrpuIjIAATHBRjEKU7oAMLJL+IDtAArJmTRyAAKghyr-jOGQ+gAklAIawMaYB4MQooAIJMcaMAasOU4zn2pAAEJOkapoWla0E0XAui6EAA)

```sh
--parser less
```

**Input:**

```less
@ant-prefix: antd;

.error{
  // this parse error
  .@{ant-prefix}-drawer-content-wrapper{
    box-shadow: 0px 4px 8px 0px @home-nav-bar-box-shadow-color; 
  }
}

.success{
  // this parse sucess
  .@{ant-prefix}-drawer-content-wrapper {
    box-shadow: 0px 4px 8px 0px @home-nav-bar-box-shadow-color; 
  }
}

// this parse success too
.success-too:global(.@{ant-prefix}-drawer-content-wrapper){
  box-shadow: 0px 4px 8px 0px @home-nav-bar-box-shadow-color; 
}
```

**Output:**

```less
SyntaxError: CssSyntaxError: Unknown word (6:5)
  4 |   // this parse error
  5 |   .@{ant-prefix}-drawer-content-wrapper{
> 6 |     box-shadow: 0px 4px 8px 0px @home-nav-bar-box-shadow-color; 
    |     ^
  7 |   }
  8 | }
  9 |
```

**Expected behavior:**
parse success
