### ISSUE TITLE
Broken output with postcss-simple-vars used with animation-delay

### ISSUE THREAD

**Issue by bschlenk** [prettier/prettier#12140]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAJnANgQwJ5IAEArANwA6UlAdDlAJYC2OM90hwlhhdTLbUALSZcBQqgAUI-AEoAzhSgBfEABoQEAA6toc5KBwAnQxADuABSMI9KHFlP496gEaGcYANZwYAZRyM4ABl6KDhkADM7OTgXN09vH013EIBzZBhDAFcYkDhGZzh0THRAuhTMnBS4ADEIQ2YYVig020yYCDUQAAsYRiwAdS76eDkksDgfa2H6ADdhvGRwOScQEOjDGHM3FOYIqJyAKzkADx9UrDgARUyIeD2saPUkw3XFsGXOzUMQmH76dBgXWQAA4AAxPEzRfpuTSLL5wdYzMLqACON3gWy0NhAODkglChUKnUMcDR9BJW0quyQkQeOWijHo6Sy9POV3RYRp+3UMBwzj+AKBSAATDy3PQsKkAMIQRjU3JyYidTLRAAqfJstMeIBm2QAklBMLAfGBvtoAIKGnwwPAXe7RJRKIA)

```sh
--parser css
```

**Input:**

```css
$delay: 5;

.animation {
  animation-delay: $(delay)s;
}
```

**Output:**

```css
$delay: 5;

.animation {
  animation-delay: $(delay) s;
}

```

**Expected behavior:**

The extra space between `$(delay)` and `s` makes the property invalid. It should be:

```css
$delay: 5;

.animation {
  animation-delay: $(delay)s; /* <-- no space */
}
```
