### ISSUE TITLE
Empty in-line values are not parsed correctly

### ISSUE THREAD

**Issue by jovandeginste** [prettier/prettier#12212]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKATAhjXARiQAJtCs8CAmU7ay-XAZiUYIBZSA-Ld3AKykA2gDNiJbgBoSo2iQC6WEFJAQADjACW0AM7JQuAE5GIAdwAKxhPpS4ANmdwBPfaoBGR3GADWcGADKuAC2cAAyWlBwyKIOunAeXr7+AerekQDmyDBGAK4JIHDB7nDY2KVhuFAZubgZcABiEEbB+NrVyCC4uTAQKiAAFjDB9gDqA1rwumlgcAE2k1oAbpPOnWC6biCR8UYwFl4ZrTFxBQBWugAeAZn2cACKuRDwJ-bxqmlGu53OIfb96iMkRgoy02BgA2QAA4AAwfUzxUZedSdQFwXZLaKqACOT3gBw0ti6ulQUVKpX6RjguK0VIOdWOSFibwK8WCWmyeVZtweeOiTNOqgI7lB4MhSGoQq8WnsmQAwhBgozCroBP1cvEACq4dy2ZnvEBLfIASRwCECYCBmgAgjgAjBnHdXvEAL4uoA)

```sh
--parser yaml
```

**Input:**

```yaml
---
data1: d1
data2: d2
data3:
data4: ~

data5: [f1: ~, f2: ]

```

**Output:**

```yaml
---
data1: d1
data2: d2
data3:
data4: ~

data5: [f1: ~, ? f2]

```

**Expected behavior:**

`f2` should be considered a key with a `null` value too.

Probably related to: https://github.com/prettier/prettier/issues/4843
