### ISSUE TITLE
Space between nth operations in nth-child

### ISSUE THREAD

**Issue by masoniis** [prettier/prettier#12326]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#.....)

**Input:**

```css
	.cell:nth-child(-n+3) {
		border-top: none;
	}

	.cell:nth-child(3n+1) {
		border-left: none;
	}

	.cell:nth-child(3n-3) {
		border-right: none;
	}

	.cell:nth-child(n+7) {
		border-bottom: none;
	}
```

**Output:**

```css
	.cell:nth-child(-n + 3) {
		border-top: none;
	}

	.cell:nth-child(3n + 1) {
		border-left: none;
	}

	.cell:nth-child(3n-3) {
		border-right: none;
	}

	.cell:nth-child(n + 7) {
		border-bottom: none;
	}
```

**Expected behavior:**

The output shouldn't be adding a space between the formulas within nth-child. I am using svelte/sveltekit, and I run into an error where the nth-child **only** works when there are no spaces. Additionally, even if the spaces are the intended effect, there should be a space added in the "3n-3" equation since it is added within the addition equations.

Note that this is within a svelte <style global> tag.
