### ISSUE TITLE
CSS values are transformed into lower case

### ISSUE THREAD

**Issue by alexander-rymasheusky** [prettier/prettier#12324]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAbgQwDYFc4AEALABoAymATgOaEBMAHAPQDMAbAA4AeA3ADpQBAOngBnGAWACCBAGbQYSYuSq0CACTjZ0cGAEswmflAC+AkABoQEDvuijkoKpQgB3AApUEDlDleYATwcrACNKTDAAa10AZUwAWzgyPSg4ZFkcUThQ8KjYjgiU6mQYSnwrOHiQuAATGtqKKGpcTFoAMQhKeMwYfSbkEExcGAhLEAALGHjsAHVxvTECsDgY7wW9dAWAgbBRYJAUrMoYd3DqbvTM7JAAK1EuGKLsOABFXAh4S+wsqwLKI52ezGHEoKRgMz0NRg42QDAADL8XFkZuEOAMQXAjjoxgBHd7wU42HyDUQAWlStVqY0ocDxehpp1aFyQGW+1yy8T0JTK7Ker3xaRZVysMEwIQhUJhSDoIvCemwRQAwhB4syQJiAKxjXBZAAqYp8rJ+IHQ+AAklB6rAYmBQbYAIKWmIwALPL5ZEwmIA)

```sh
# Options (if any):
(no options)
```

**Input:**

```css
@value 4XLarge 28/36px;

.test {
  font: 4XLarge Helvetica;
}
```

**Output:**

```css
@value 4XLarge 28/36px;

.test {
  font: 4xlarge Helvetica;
}
```

**Expected behavior:**
```css
@value 4XLarge 28/36px;

.test {
  font: 4XLarge Helvetica;
}
```

The project uses PostCSS with its @value and `@value...from` syntax extensions.  Typography rules are defined using constants like shown above; renaming the values is not an option.  Changing the case of the values is an error (violates the "Correctness" principle).
