### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'endOffset')

### ISSUE THREAD

**Issue by lg-kialo** [prettier/prettier#12504]
**Prettier 2.6.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ARgQzAawOYBOEArlACYC0hmZAlgjABQACYxMAlAATAA6UXQVyy5CJcki4AbWlDiYCVAjXqxG-IZq4wIXArTwALGABoNWwcwDuh2vC4AGAKRmBFrtdv2WbGFwqOqA4AjE4cru4eAA4QBDCYUhQi+ESkZB6+Ee7MMXEJSdgp4unBDs7mghwA3PwAvvwgJiAQUTC00ADOyKAKRFYACgoIXSgJVpgAnl1N6Mq4cDAAypgAtnAAMrJwyABmCR1wM3M4C4tR2LJ4yDAExIcgcCvocGRkL+uYUHjEmHhwAGKxFaYGBtL7IECYdgQRogYwrKQAdS8cA65zAcEWwzstAAbnYJhCwB1piBZAc4v1lHhgbt9vcAFYdAAei0uUjgAEViBB4HSpAcmucCBSIRySbCovpYIjaGQYIZkAAOBxCogHRHKKIQqWouAEXHbJoARx58CpLRGkI6FDkLxesIIcFNtCdVN+tKQewF9wOK1o11uvvZXLN2y99Ka8XQsvliqQACYo8paDIvgBhCArT0PDoAVlhxAOABVMOgRt7BSBcXcAJLkBiLMD6VoAQXIixgEw5-IOtVqQA)

```sh
--parser less
```

**Input:**

```less
.background-gradient(@cut) {
    background: linear-gradient(
        to right,
        @white 0%,
        @white (@cut - 0.01%),
        @portal-background @cut,
        @portal-background 100%
    );
}

```

**Output:**

```less
TypeError: Cannot read properties of undefined (reading 'endOffset')
    at v (https://prettier.io/lib/standalone.js:75:220)
    at w (https://prettier.io/lib/standalone.js:36:316)
    at https://prettier.io/lib/standalone.js:75:11235
    at https://prettier.io/lib/standalone.js:41:9097
    at u.each (https://prettier.io/lib/standalone.js:41:8932)
    at u.map (https://prettier.io/lib/standalone.js:41:9077)
    at Object.Ue [as print] (https://prettier.io/lib/standalone.js:75:10845)
    at F (https://prettier.io/lib/standalone.js:41:11582)
    at T (https://prettier.io/lib/standalone.js:41:11105)
    at https://prettier.io/lib/standalone.js:41:10991
```

**Expected behavior:**
Prettier doesn't break. Version 2.5.1 works fine.
