### ISSUE TITLE
Media query with multiple lines and inline comments gets corrupted

### ISSUE THREAD

**Issue by apepper** [prettier/prettier#12600]
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAk3QHMBaAJzhjwEMAKAEgDNMAbOUgRmwBp9m2HAEy9+Ad0wATGAAsuohjLiZiMmPICU+YAB0C+AEY0wAa2LkIAVyiTSRGsThJ8l8q0Yt2mgNx69+fAB6QPwAQUsYCAAHShZsOHJ8GBoTOABnfDAaSnwIJnwaSUk8YnxSMTgDE0x1LChSSTgAN0wwDiicOFYKGmoIApsyiFI6hubW9s7u8l7MCB5-IJCDCPxJCHSoAHIYTOgmhN3JKKjsAF4APmPMADpF4PwAFSVKLYyofrTLMBkkmRKChlrDE4HE4JJ8KNGi02qQOvFprNPng2oQYG98B8oGlkjZspI7voHgBhCDoKKzAxsGoAT0IUCYEGcahgUTSSGCWSgmEsaTgN0g6ECYDSaRG4MwNAo6QgrAicygiwwEpouSgrDpaTAlAQAwhdFGlDSsvl0GcnAAnEJrho+A8AJIAUQtXE4a2gO3wXxOEHIRxO2EWAWgGq92rgupogwNeGlxrlfSgzmtAa0wCW+AAyrjJPjMAAvcFBwzGMwWay2eyOZyudwCLwiDS+fQBIymcxWGykNIFpziKSyeT8JQqNTyZsBAC+SpRcsaazgIKy8DoOhAAAMiGRKNQoPQNOu13w100ACw3ADMNwADEf8CeAKxrpt6ScgHggaKJtLIUDZCxiAACtkCA-igNCsGINA0j+H4GDMphUJmNDoHAAAyeBwMgTAQXycEIakMCZhSYAlMgMDkJYcAfnA6AGOCjSSGhUbEJYDhwAAYr66C9LuxDICANARBA74gGo6CsAA6v88BpCRcCZqBNSYC0MA0gJIqwSAeB8n6gEzMQPHYbh1EgAAVmk2CZiU7AAIqWBA8DGaweEgBS5C6QJWqiqJMR4DAkkDjIyAABzXh+MQQHykkzFEAkgrpByiQAjg58D6dEYGCWKUARoxomUKlmCUPpDhGUgOEuaZfJYORlHVTZcD2Y5WEVSZH7JAYgXSMFSBCB1MzUlAxCkug5UgOkD6ibycCPDQBhgZVrlNFR9o2AgRHapgUQwKENjZjS7DOXyk6TkAA)

```sh
--parser scss
```

This snipped is taken directly from Bootstrap 4:

https://github.com/twbs/bootstrap/blob/349a373ff62bf530135ad95d7d1d3f1be6abbf22/scss/mixins/_image.scss#L23-L36

**Input:**

```scss
@mixin img-retina($file-1x, $file-2x, $width-1x, $height-1x) {
  background-image: url($file-1x);

  // Autoprefixer takes care of adding -webkit-min-device-pixel-ratio and -o-min-device-pixel-ratio,
  // but doesn't convert dppx=>dpi.
  // There's no such thing as unprefixed min-device-pixel-ratio since it's nonstandard.
  // Compatibility info: https://caniuse.com/css-media-resolution
  @media only screen and (min-resolution: 192dpi), // IE9-11 don't support dppx
    only screen and (min-resolution: 2dppx) { // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
  @include deprecate("`img-retina()`", "v4.3.0", "v5");
}
```

**Output:**

```scss
@mixin img-retina($file-1x, $file-2x, $width-1x, $height-1x) {
  background-image: url($file-1x);

  // Autoprefixer takes care of adding -webkit-min-device-pixel-ratio and -o-min-device-pixel-ratio,
  // but doesn't convert dppx=>dpi.
  // There's no such thing as unprefixed min-device-pixel-ratio since it's nonstandard.
  // Compatibility info: https://caniuse.com/css-media-resolution
  @media only screen and (min-resolution: 192dpi),
    // IE9-11 don't support dppx only screen and (min-resolution: 2dppx) {
    // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
  @include deprecate("`img-retina()`", "v4.3.0", "v5");
}

```

**Expected behavior:**

```scss
@mixin img-retina($file-1x, $file-2x, $width-1x, $height-1x) {
  background-image: url($file-1x);

  // Autoprefixer takes care of adding -webkit-min-device-pixel-ratio and -o-min-device-pixel-ratio,
  // but doesn't convert dppx=>dpi.
  // There's no such thing as unprefixed min-device-pixel-ratio since it's nonstandard.
  // Compatibility info: https://caniuse.com/css-media-resolution
  @media only screen and (min-resolution: 192dpi), // IE9-11 don't support dppx
    only screen and (min-resolution: 2dppx) { // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
  @include deprecate("`img-retina()`", "v4.3.0", "v5");
}

```
