### ISSUE TITLE
Prettier only indents half the comment for multiline CSS comments

### ISSUE THREAD

**Issue by gijsk** [prettier/prettier#12647]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKABAzgVwA54QBOMWABALQC2EAXhQEYQQA2FeRcAZgBSogAPHCwB0eAIZQ4bSQEsq4mLOhYRCcQxZwAJvwCUZYOgxUds8WR4ducIlgqdtOMDuoQl0JGSgR2nLrYILgZGmKba5pZu9HgsilzEVF4KkFgh6GRkAPQAVGQA8lBkALLiYAA0ZDhYcGQwABa1HBB4tkpw5PzRFADuslDaED0UMESSWAlEVPxkktpkXTT0fQNDFC1lsjAAnvwZmZn9WPDi8xBcCyCj45PTILMDlxtgW7v3k3WNNQ-yispQqn2BwAKo1KEtev1Bj08s1WiRZB1ZgQWNs6hBPrUevVWFioUMyP0wCwcBEoABzTFkFbQgDkWCBmSw9VOQ0qc0xaMGUFpMFmXACYD5DTxqx69MuzPErX4lSwGJFZCw22OcCoZEGHR5MEZZBZADdajAMZxIFQ8Dh4FSpdClSzWhqcER+pTFXIFB4oCIyKDZOQFABrJEi9XiXUsdxkLjiVVEb0ASSK0aFlQA4nAwAGMT4yBGKbY6s7yeTbOQbQSpQ7TRBzZa-ipdR9OBJ+qQRLrQR0mkQWm1EeRxJxvJH5LE1Qh4Gciu5GkQyLF4olVGQcll9gBiABCxU3AH0mBAAwoiAGsAAFFr4JA+GA8ADa7sUcAAvPxoywavwALrpIoHa4Als-x+L2JDbF43Q0msAETIklSQfiwzPK8ADcjIwUB0AUE4Yyel4AAMIgAIwABxYJUhGkVgaF-pkGGeiM8guhQXA4FAQr-EgupkPqg48BQFCPgxcAxsxrHsZ6eiVCJNTrJaNGZAAvug+y5AUUCohqCpgtG2hwBQ-Q-B6-xkNA86cBQm6yJSADKTrorM+oQLI8xUH6WAunarI9OQ0BAnkVm2U6cpwLUDA4JSREAGwAOwAEz4QAnER3qrvsJhmBY-EQikjDWRQuBECMjSmARv4HGQW47vuzBHoOp4XhaeDXu495CS+b7iB+cDfuVFXgnQkJiusEgvDsBEKf1CHDTBtxeDBcTwAAmvxMX4XgAh6JNSkqbRlXbnuB51Se56Xngd4eXpr4gEwMDGncX4tbeD5QL88DXe+n4gD+hjcdN0IjGMAJzYW4yLXAK1rRtW2Mspf5wwj6CKSA5QgC0npYMgoCDj2PRnoOCCYygXU9OIKoozdYyZnAMA2eIpgADL9HAyCfXAqMMFTQa06NLrIKMODsyAaoMDoenaAzkjkjg4glgAYokihKBSyAgOIloQBT9QwFQLAAOr1FsHSjXANmE0B+qvKrYBYJjqNHG0Z5jOSCis11NSowAVlgAg2S6WgAIo4O4LNIGzqMSHYtjW7bFMcK2esuQ0yAkfhEc9jUetjHgqvWDURCGhTACOwfwE7LRE2r9hSDoOgU5wJeyJwTuy67Yfu0LNRufzRCC6jHkUoHpeh+HVwaIn2jJ0gcWo9csgsC6ADCNZt8LWAAKwU9UcDAhoROj-qguJnpsA2WAzp4DAACCAw2TsWhu91imKUAA)

```sh
--parser css
```

**Input:**

```css

@supports -moz-bool-pref("xul.panel-animations.enabled") {
@media (prefers-reduced-motion: no-preference) {
@media (-moz-platform: macos) {
  /* On Mac, use the properties "-moz-window-transform" and "-moz-window-opacity"
     instead of "transform" and "opacity" for these animations.
     The -moz-window* properties apply to the whole window including the window's
     shadow, and they don't affect the window's "shape", so the system doesn't
     have to recompute the shadow shape during the animation. This makes them a
     lot faster. In fact, Gecko no longer triggers shadow shape recomputations
     for repaints.
     These properties are not implemented on other platforms. */
  #BMB_bookmarksPopup:not([animate="false"]) {
    transition-property: -moz-window-transform, -moz-window-opacity;
    transition-duration: 0.18s, 0.18s;
    transition-timing-function:
      var(--animation-easing-function), ease-out;
  }

  /* Only do the fade-in animation on pre-Big Sur to avoid missing shadows on
   * Big Sur, see bug 1672091. */
  @media (-moz-mac-big-sur-theme: 0) {
    #BMB_bookmarksPopup:not([animate="false"]) {
      -moz-window-opacity: 0;
      -moz-window-transform: translateY(-70px);
    }

    #BMB_bookmarksPopup[side="bottom"]:not([animate="false"]) {
      -moz-window-transform: translateY(70px);
    }
  }
}
}
}
```

**Output:**

```css
@supports -moz-bool-pref("xul.panel-animations.enabled") {
  @media (prefers-reduced-motion: no-preference) {
    @media (-moz-platform: macos) {
      /* On Mac, use the properties "-moz-window-transform" and "-moz-window-opacity"
     instead of "transform" and "opacity" for these animations.
     The -moz-window* properties apply to the whole window including the window's
     shadow, and they don't affect the window's "shape", so the system doesn't
     have to recompute the shadow shape during the animation. This makes them a
     lot faster. In fact, Gecko no longer triggers shadow shape recomputations
     for repaints.
     These properties are not implemented on other platforms. */
      #BMB_bookmarksPopup:not([animate="false"]) {
        transition-property: -moz-window-transform, -moz-window-opacity;
        transition-duration: 0.18s, 0.18s;
        transition-timing-function: var(--animation-easing-function), ease-out;
      }

      /* Only do the fade-in animation on pre-Big Sur to avoid missing shadows on
   * Big Sur, see bug 1672091. */
      @media (-moz-mac-big-sur-theme: 0) {
        #BMB_bookmarksPopup:not([animate="false"]) {
          -moz-window-opacity: 0;
          -moz-window-transform: translateY(-70px);
        }

        #BMB_bookmarksPopup[side="bottom"]:not([animate="false"]) {
          -moz-window-transform: translateY(70px);
        }
      }
    }
  }
}

```

(this is a slightly abbreviated snippet from https://searchfox.org/mozilla-central/source/browser/base/content/browser.css , one of the main files that determines how a Firefox browser window is styled. The `@supports` rule is non-standard, but the same problem occurs without it or with a different media query)

**Expected behavior:**

The media queries get indented (makes sense). The rules inside them get indented (makes sense). The *first line* of each comment gets indented (makes sense) - but the subsequent lines are not indented. If I manually indent them and re-run prettier, it doesn't "correct" to unindenting the other commented lines, so this seems like a bug. I assume that all lines in the comment should be indented by the same amount.

As you can see in the example, this happens both for multiline comments with and without the repeated `*` pattern.
