### ISSUE TITLE
Azure Pipeline YAML ${{ else }}: flagged as `SyntaxError: Map keys must be unique; "${{ else }}" is repeated`

### ISSUE THREAD

**Issue by jason-ha** [prettier/prettier#12651]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKAHAhgJ1wFs558BnJLAAmtWqmLiWomxgEtobbqYBPbM2oAjCBAA2cXFCxZy8bJR60AJMGDUOAM2p58cEmXIA6Np2jUAvlapReD6gHMOANwQsAwgAt8HcirU6ppwEuRw1raBDi7uUCwAIrjugcFauvqGpHAUZuxc9jZ2jrzaxBwS-IkArkQEAfa8aaHhkcUl1GVEFVXUAEKEUAAmDSAANCDmBeTIoAT4EADuAAoECDMouBKLuPwzEyKEYADWpADKTAAyHFBwyGVhcAdHpzBneGA3Tsgw+NVPIEMIjgQyGIMuMic1VwTjgADEIPg6jBOFBvptqjAIOMQN4YEQJAB1bwceDkD5wM7rUluUn8ZDgcj7EA3cL4GDLQhOOr3LbhCYAK3IAA8zl8pABFaoQeC8x4TfRshn8YgSHHYPywQkcIYwbzIAAcAAYFQtwoTCNgGRq4Gz3DiAI7S+CctgbEC4cioW4gkE4gxOjgGTkwnlIB78kDhbo-P4A8jiuBSmV3cN8gEwXAibW6-VIABME1+uAqX08ECIYcB5AArDjquEACpZjYRgGuf4ASWGCDeYD87AAgsMzgIpHLwjYgA)

```sh
--parser yaml
```

**Input:**

```yaml
---
parameters:
  - name: option
    type: boolean

steps:
    ${{ if paremeters.option }}:
        given: Chris
    ${{ else }}:
        given: Dave
    ${{ if paremeters.option }}:
        family: Dumars
    ${{ else }}:
        family: Brands

```

**Output:**

```yaml
SyntaxError: Map keys must be unique; "${{ if paremeters.option }}" is repeated (7:5)
   5 |
   6 | steps:
>  7 |     ${{ if paremeters.option }}:
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  8 |         given: Chris
     | ^^^^^^^^^^^^^^^^^^^^
>  9 |     ${{ else }}:
     | ^^^^^^^^^^^^^^^^^^^^
> 10 |         given: Dave
     | ^^^^^^^^^^^^^^^^^^^^
> 11 |     ${{ if paremeters.option }}:
     | ^^^^^^^^^^^^^^^^^^^^
> 12 |         family: Dumars
     | ^^^^^^^^^^^^^^^^^^^^
> 13 |     ${{ else }}:
     | ^^^^^^^^^^^^^^^^^^^^
> 14 |         family: Brands
     | ^^^^^^^^^^^^^^^^^^^^
> 15 |
     | ^
```

**Expected behavior:**
Repeated conditions for `${{ if paremeters.option }}` and `${{ else }}` are allowed. (In example, alter `if` just a bit for `else` to become a problem.)
Reference Azure Pipelines documentation:
 https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditional-insertion
and
  https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops#conditional-insertion

**Comment by kachkaev** [comment]
I believe that the above YAML is invalid. We end up with an object that has duplicate keys.

Which specific example do you refer to?

Here’s what I’ve [seen](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops#conditionally-run-a-step) for multiple conditions:

```yaml
variables:
  - name: foo
    value: contoso # triggers elseif condition

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "start"
- ${{ if eq(variables.foo, 'adaptum') }}:
  - script: echo "this is adaptum"
- ${{ elseif eq(variables.foo, 'contoso') }}: # true
  - script: echo "this is contoso" 
- ${{ else }}:
  - script: echo "the value is not adaptum or contoso"
```

[Prettier is happy with this input](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwJboEYA2cAzkgDpQAElAtJVOgLZxKUBmEEF11GBAri0qRYEYhEoBiSjBwBzOXEzFKcAsTjY2w6ABNsMbNAoUADpwLkqlVIwCSjdItYByfnn6x+NAunjEYFxMoALhTUgo6YjAcUxhWODAACwkyEACsGDTIygASYGBKLVUARwAKDBx8ImIAOg4IABpKF3RddDj+RhcASkoAX36raiiY7DiE5NSQGCTsFXnKNo6YLuyoOnzCtQ1iuHLK3EISes5mlxEYMQhegaGpGUxBblpKaNj41SnKNNnFxcu1zSPw2eQKqnUcDuw1e73Gn0SKR+MySUL4giKKigEBgS3anUYlAgmB0onEaRAjRAEDiRhCyFAWEwEAA7gAFLAIYjIEDoAgs9AAT25VLwmHQYAA1nAYABlJhwAAy2CgcGQbD5GlF4qlMtlpglKrkyFkgipcEYeDgul01sV6Cgcn4TjgADFiY4YIZHTz0PwrpSQEkYIwCAB1Ob+A1gOCyrkGbCoAyCnlgYgikAqjSYGBs8VyRzqzVwKkAK2IAA9ZUaiABFfg4tVIDWQqkG5RKHmCpgEQOmHCwMPYXSzZAADgADG3mRow+LTDz+yQlKg1VSSg34HmadyUOhiDRVdbrYHMPt+Ngz3mnIXm8WqRpGNgTU8S+ka3B642i62ZvghyOSTIAATFSsjoNgBBGgAwhAjC3iAJAAKyBvwGgACr4LuLZamggh2FAtqwLKYxxAAgoRsowIKRA-hogxAA).

**Comment by jason-ha** [comment]
Unfortunately, the possible fix does not produce the same result. I think this is a special case dealing with Azure Pipeline compilation. See Azure Pipeline [Expressions](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/expressions?view=azure-devops) and [Process the pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/runs?view=azure-devops#process-the-pipeline).

Everything in ${{ }} is processed and alters the final YAML result. In my particular case I have keys `given` and `family` that should be properties of `steps` once processed. The processed result should be:

```yaml
steps:
    given: Dave
    family: Brands
```
or
```yaml
steps:
    given: Chris
    family: Dumars
```
based on the value of `paremeters.option` fed into compilation.

It seems that prettier has some support for Azure Pipelines processing as I have seen it do things with very long ${{ }} expressions. I think we are looking at a new special case.

**Comment by fisker** [comment]
Maybe fixable from here https://github.com/ikatyang/yaml-unist-parser/blob/92ea25423fc23bc160477d21cc51d7beeace2a14/src/parse.ts#L45?

**Comment by fisker** [comment]
Workaround for now

**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKAHAhgJ1wFs558BnJLAAmtWqmLiWomxgEtobbqYBPbM2oAjCBAA2cXFCxZy8bJR60AJMGDUOAM2p58cEmXIA6Np2i0AvlapReD6gHMOANwQsAwgAt8HcirU6ppwEuRwjpFRNnZRzm4e1AAiuO6BwVq6+oakcBRm7Fz2MYEO2sQcEvwsSQCuRAQB9rwZoeFxHSXNkeVEldXUAEKEUAAmTSAANCDmReTIoAT4EADuAAoECPMouBIruPzz0yKEYADWpADKTAAyHFBwyOVhcMenFzCXeGD3Tsgw+FqrxAhhEcFGo3BNxkTlquCccAAYhB8A0YJwoH8drUYBApiBvDAiBIAOreDjwcjfOCXLYUtwU-jIcDkI4ge7hfAwNaEJwNJ67cLTABW5AAHpdflIAIq1CDwAUvab6TnM-jECT47B+WAkjijGDeZAADgADMrluESYRsMztXBOe58QBHOXwHlsbYgXDkVAPcHg-EGV0cAw8+H8pDPIUgcJ9f6A4HkKVwWXyx5RwXAmC4ER6g1GpAAJmmANwlV+nggREjIPIAFZ8bVwgAVXPbaPA1xAgCSYwQnzAfnYAEExpcBFJFeEbEA)

```sh
--parser yaml
```

**Input:**

```yaml
---
parameters:
  - name: option
    type: boolean

steps:
    ${{ if paremeters.option  }}:
        given: Chris
    ${{ else                  }}:
        given: Dave
    ${{ if paremeters.option }}:
        family: Dumars
    ${{ else                 }}:
        family: Brands

```

**Output:**

```yaml
---
parameters:
  - name: option
    type: boolean

steps:
  ${{ if paremeters.option  }}:
    given: Chris
  ${{ else                  }}:
    given: Dave
  ${{ if paremeters.option }}:
    family: Dumars
  ${{ else                 }}:
    family: Brands

```
