### ISSUE TITLE
negative sign before function

### ISSUE THREAD

**Issue by yukulele** [prettier/prettier#12893]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArgZzgAgDoiYCGmmSAtkTABYEDceUjAxAGYQQ7CM44DuASwAmNJDgC0OSjQB0QgQDcAFAEYADGoCkAGhwAmAJQMoAX0YhtICAAcYA6JmSgiAJxcQ+ABVcJHKIgA2fEQAno6WAEYuRGAA1nAwAMpE5HAAMgJQcMisgdiR0XEJidYxmQDmyDAu6HCWcOQRcEJCzWlEUOXoROVwAGIQLtJ2ncggROgwEBYg1DDkAQDq1ALwmKVgcIm+q4qrIWNgpDOZ2C4wntHllDl5dSAAVpgAHokVAXAAiugQ8LcB+RApRcZzGmCO4SBLkyMEWwhoyAAHGpLNZ3NhFtFrGM0XAzgpspYAI4-eCXGx+caYcRZZrNGYuOAkgSMy49G5IXIA+7YcgCKo1HnvL6k7Kcu6WGBECJwkTUZB6SXRAQBCoAYQg5A5IDxAFYZlg4AAVaV+LmAhS1ACSUFasESYGhtgAgrbEjAQh9-tgTCYgA)

```sh
--parser scss
```

**Input:**

```scss
@use "sass:math";

#foo {
  width: - math.div(100%, 2);
}

```

**Output:**

```scss
@use "sass:math";

#foo {
  width: -math.div(100%, 2);
}

```
a space is required after the minus sign, this causes a sass error:
```
Error: There is no module with the namespace "-math".
  ╷
4 │   width: -math.div(100%, 2);
  │          ^^^^^^^^^^^^^^^^^^
  ╵
```

**Expected behavior:**

```scss
@use "sass:math";

#foo {
  width: - math.div(100%, 2);
}

```
