### ISSUE TITLE
CSS: Using `@supports (not ...)` results in invalid CSS code

### ISSUE THREAD

**Issue by Mathias-S** [prettier/prettier#12958]
**Prettier 2.6.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAzgVwA7YgJxnQAIAKKCGMgWgDc58BPagG2gHNrMotcD4AJtWz4I2BjGZQAhgFs41ABYM4SYtMwwIASm3qoAsgICW6bC2mM17fMYF7gAHSjFiAOnjoqTl6+KQ2fGt8OAQAbmdXAF9nGKhnDBw8QhJyShp6JjoGZkzcnOystihObl5kwWFRcUIpOQVlELUNLV19Q1ITMwsrYhs7B0j3T28h1wCCNRCBCN84qJAAGhAxGGNodGRQaXxRAHcABR2ETZRpFj3LTeWAI3xpMABrOBgAZXqAGWMoOGQAM3O6Dgt3uTxer2wD2+7GQMHwmGBIDgshucAEAjRH2kJUw0nYcAAYgRZNIYGsSsgQC0IEsQIoYLIWAB1RTGTyQsBwV4nNnGWhsxiUsDoa4gb5AwgHe7sEn-QGIgBW6AAHq9oSw4ABFTCUX5IAEsIHLSH4CVCkW0kTfGBMuwwRTIAAcAAZjaIgUz7thKSI4BL6LSAI46+BSsSnKnoag-NFo2khYPGEJSvGy-Xy5ZA2TGWHwxHodVakN6g1GkAwaQ3W0Ce3IABMyzh0mMLGhAGEILI00j0ABWWmYIEAFUrp1LiNoCIAkgYEG8wLZsDAAIIGV6SDVyw1wKJRIA)

```sh
--parser css
```

**Input:**

```css
@supports (not (-very-long-unsupported-property-name-here: auto)) and (display: grid) {
  .test {
    color: green;
  }
}

@supports (not (-very-very-very-very-very-long-unsupported-property-name-here: auto)) and (display: grid) {
  .test {
    color: red;
  }
}
```

**Output:**

```css
@supports (not (-very-long-unsupported-property-name-here: auto)) and
  (display: grid) {
  .test {
    color: green;
  }
}

@supports (
    not (-very-very-very-very-very-long-unsupported-property-name-here: auto)
  )
  and (display: grid) {
  .test {
    color: red;
  }
}

```

**Expected behavior:**
The newline between `(` and `not` causes the CSS to not render correctly in Chrome. The code will still work in other browsers such as Safari or Firefox: https://jsfiddle.net/Lndutm0y/ 

In any case it's also invalid SCSS, and the SCSS compiler will fail with Prettier's output: https://www.sassmeister.com/gist/934259a609b9da7a1c9a211e506d4053

Both `(not` and `( not` would be valid, i.e. no wrapping inside the parentheses:
```css
@supports (not (-very-long-unsupported-property-name-here: auto)) and
  (display: grid) {
  .test {
    color: green;
  }
}

@supports
    (not (-very-very-very-very-very-long-unsupported-property-name-here: auto))
  and (display: grid) {
  .test {
    color: red;
  }
}
```

This may possibly be an upstream bug in both Chromium and SCSS, I wasn't able to find the exact CSS spec documenting this.
