### ISSUE TITLE
Ugly format of `less`'s `[@result]`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#13014]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhgE3QBxgWgFcoBLGACgAEA3dAG0LgEoACYAHShZcoCc4AzoTowkLEgDNynbtxICohALYAjOLyq0GzADQzZk8vOJlN9RjpYByAKRWmlmubiWTFJ9ss4AHkwf7uD0Z9JgBuTgBfTk5UARIALzgqAHcSTBgAC0cMuBIAcwzRHlT0jNYOLhYSzLEMbDwiUndqsoBtPkFhGABdcMqc-MLarFwCNyoBgpgmdv4hEV7IzhAdEAg8EmgBZFB0Xl4IZIAFPYRtlHpk9ABPbdWVXnQwAGs4GABldCU4ABkSKDgyAk9AELhADyerw+OCe-zyyBgvAsIDgqjgmEw6J+6CgeUI6DycAAYhBeEp0DAYHDkCB0IQYBAViBCko6AB1DJkQQwsBwd5nMgkahka40sACO4gf6g3gwI6PPLkoEgsEAKwE3necLocAAioQIPBlXRQasYbwZTSdRKmTheP8YGy0plkAAOAAMZoOoLZjxwNLtgnU1EBqwAjgb4PL1udaQJ8AD0eimfwIyR+PKCUqkMCTWDQUoSAikfntXrI4CcyrVjB0ConaVkAAmGuPEh0OEAYQgSmzKIEAFYmYRQQAVOvnXOmkDURgASSgmNg7zA9rwAEFF+8YNcdcbQREIkA)

```sh
# Options (if any):
```

**Input:**

```less
.adapt-unit(@value) {
  @result: if(
    isnumber(@value),
    if(isunit(@value, '%'), @value, unit(@value, px)),
    @value
  );
}

.size(@width, @height: @width) {
  width: .adapt-unit(@width)[@result]; // here
  height: .adapt-unit(@height)[@result];
}
```

**Output:**

```less
.adapt-unit(@value) {
  @result: if(
    isnumber(@value),
    if(isunit(@value, "%"), @value, unit(@value, px)),
    @value
  );
}

.size(@width, @height: @width) {
  width: .adapt-unit(@width) [ @result]; // here
  height: .adapt-unit(@height) [ @result];
}
```

**Expected behavior:**

No change
