### ISSUE TITLE
prettier-ignore does not work for YAML

### ISSUE THREAD

**Issue by themightyoarfish** [prettier/prettier#13223]
**prettier version:**  2.7.1

**os:** macos 12.4

**description:** I have a yam l file with content like this

```
# prettier-ignore
foo:
  include: bar.yml
  include: baz.yml
```
which gets handled appropriately by our application code. I wish to prevent prettier from complaining that the `include:` key is repeated. 

The ignore directive has no effect. It does not help to move `# prettier-ignore` above the offending `include` keys.
