### ISSUE TITLE
Line breaks in multiline strings in CSS aren't replaced with literalline and confuse fits

### ISSUE THREAD

**Issue by GlebDolzhikov** [prettier/prettier#13299]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ANtA5gWjOgQwGcioCBbOPQksy640iuAAgBMBLANwG0AzCBAC8AHRAAjAgCcRsqJJkgAui2AtImKUhZS4bFgF8RUY8YzYGtZpab18jOq068BwsQtnGFOb7+k--PylFFTUNCC0dPUMQABoQCAAHGA5oImRQaSkIAHcABWkEdJQCdByCAE90+PEpAjAAazgYAGVmABkOKDhkPlKiOBq6xuaWxPqurGQYKQBXQZA4cnE9Nj12gigsWYIsOAAxCPICGBSt5BACWZgIOJAACxhydAB1e454InGwOBaij+4HwqFzAJDuXQGUhgeTqWGOvX6CwAVkQAB4tSboOAARVmEHgCPQA3i4ykkJBYJJUi6MBeHDYMHuyAAHAAGKkQAYvOqJC6JXSQrg9eIARzx8BhSWKlyIOG6ej0d10Yo4uhhu3hSD6RIWA3IHGmc11mJx4p6WsR8RgBHEdIZTKQACYrXUOOhJgBhCDkTWLIgAVjuswGABUbcVtcSQFx5gBJKBrWAtMDU5IAQQTLRgFSxhIGBgMQA)

```sh
--parser css
```

**Input:**

```css
.long-classname-classname-classname div[foo="bar\
bar"] { color: red }


.long-classname-classname-classname div[foo="bar\
bar-bar-bar-bar-bar-bar-barr"] { color: red }
```

**Output:**

```css
.long-classname-classname-classname div[foo="bar\
bar"] {
  color: red;
}

.long-classname-classname-classname
  div[foo="bar\
bar-bar-bar-bar-bar-bar-barr"] {
  color: red;
}

```

**Expected behavior:**
```css
.long-classname-classname-classname div[foo="bar\
bar"] {
  color: red;
}

.long-classname-classname-classname div[foo="bar\
bar-bar-bar-bar-bar-bar-barr"] {
  color: red;
}

```

related to https://github.com/prettier/prettier/issues/13157
