### ISSUE TITLE
Commas separating arguments in interpolated function call are being removed

### ISSUE THREAD

**Issue by guilhermehn** [prettier/prettier#13580]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZgVymGBLaAAgCsI8oAKAEgEMAaQqgIwEpDgAdKQw1AJzgxMfbgGJgtAL4B6cc0kBuLpK5cAdOggR2XHkxpgA1gHM+EbABMAtHgC2NY3CSFhAGwqlyFDiBo+GPkxqAA5Qxj4sLEpQKlDq+nw63IT6RqbmUNZ2Dk4ufO7BAuh4AB6ywJ6UAOQ0VQxVQaHGVSySUcpcIHQgEMH40ADOyKA0fGYA7gAKowhDKDSu4zQAnkPdTHwGhoIAyjS2cAAy5HDI6AsDcOubRrvBBuTGyDB8mFcgcLZMcBYWP4c0MKYHIAMQgfHsMHwYWQvkwMAgXRAAAsYLZXAB1ZF4eADe5gOA7WY4vAANxxy1hYAGaxA5EufBgk02xnsZwu72IAxKO0erjgAEVMBB4OzXJduvc+AzYQNqbTCuQYBi8BYYMjkAAOAAMkrMlwxm2CsMKcAZpNO3QAjsL4MzenNfAMrFA4D8fkiBDa8AJmQ42UhzuL3pdbHhnq8Q3zBbbToGOd0YDQmCq1RqkAAmRObPCuR4AYQgtgDHwGAFYkZhLgAVZNzIMSkCkt4ASUyCBgOzAfDwfQAgpkdjBlvyxZdJJIgA)

```sh
# Options (if any):
```

**Input:**

```scss
@function join($a, $b) {
  @return #{$a}/#{$b};
}

.foo {
  background-image: url(join("a", "b.png"));
}

.bar {
  background-image: url(prefix/#{join('a', 'b.png')});
}
```

**Output:**

```scss
@function join($a, $b) {
  @return #{$a}/#{$b};
}

.foo {
  background-image: url(join("a", "b.png"));
}

.bar {
  background-image: url(prefix/#{join('a' 'b.png')});
}
```

**Expected behavior:**

The comma separating values `'a'` and `'b.png'` should not be removed.

```diff
-  background-image: url(#{ext('a' 'b.png')});
+  background-image: url(#{ext('a', 'b.png')});
```
This breaks sass compilation with the following error:

```
Error: Missing argument $b.
    ╷
1   │ @function join($a, $b) {
    │           ━━━━━━━━━━━━ declaration
... │
10  │   background-image: url(prefix/#{join('a' 'b.png')});
    │                                  ^^^^^^^^^^^^^^^^^ invocation
    ╵
```
