### ISSUE TITLE
Incorrect formatting for arguments in `:is()`, `:where()`, `:has()` CSS pseudo-class functions

### ISSUE THREAD

**Issue by ryami333** [prettier/prettier#13612]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AznANnMMIBOSAlugBRIAmpAhgEY6UA0ABFbQ3JUgGYRgBXdK3bp6jJGAAWuANZcR1MZ27S5XJFIgA3OAUUcJasPO59B6AJQtgAHSgsWAWid8ISFnRoF7AX3v2GNi4+ERSNOSi4gpsStFm-EIGykYyJjFRKpJpppo6esnx2eoJFtZ2Ds6uEO6e3n4BUEE4eIRIAO4yBHAUcSqFWeZJsYYaxqYDqSV5uvojKWM5GkNWNvaOLm4eXj5QviBMIBAADjDE0OjIoN4EEO0ACt4Ilyg0WO00AJ6Xh3QENOkYABlGgAWzgABliFA4MgeG9ML9-oCgccAdCAObIGAEARwQ5wUF0LiULgQmhQDECGgYuAAMUIoJoMDOlOQIBoAnwBxAUhgoKwAHUpMR4Og0WA4EDnqLiNpRZ92WB0D8QNDMAQYPd-himXCEfiQAArdAADyBmJwAEUBBB4PqsIiQGiCBqlSqeccCNCYILiJQYFJkAAOAAMhy9EEwgv+x3ZXrgGt0PIAjrb4NqTi8OegnDCuFwed008RutqaXreAbDphQcRsbjDehLXAbXbYVXHYaYPQ-QGg0gAEyHHE0YhYTEAYQgoMrIETAFYeUI4AAVegveFdw7aPEASSgpNgQLA3tOAEFD0CYJ8cA7ML5fEA)

```sh
--parser css
```

**Input:**

```css
.selector:is(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {
  --foo: bar
}

.selector:has(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {
  --foo: bar
}

.selector:where(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {
  --foo: bar
}
```

**Output:**

```css
.selector:is(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {
  --foo: bar;
}

.selector:has(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {
  --foo: bar;
}

.selector:where(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {
  --foo: bar;
}

```

**Expected behavior:**

Some variation of the following (where arguments are collapsed to observe the `--print-width` config):

```css
.selector:is(
  :disabled,
  :disabled:focus,
  :disabled:checked,
  :disabled:checked:hover,
  :disabled:checked:focus) {
  --foo: bar;
}

.selector:has(
  :disabled,
  :disabled:focus,
  :disabled:checked,
  :disabled:checked:hover,
  :disabled:checked:focus) {
  --foo: bar;
}

.selector:where(
  :disabled,
  :disabled:focus,
  :disabled:checked,
  :disabled:checked:hover,
  :disabled:checked:focus) {
  --foo: bar;
}
```

### Useful links:

https://developer.mozilla.org/en-US/docs/Web/CSS/:where
https://developer.mozilla.org/en-US/docs/Web/CSS/:has
https://developer.mozilla.org/en-US/docs/Web/CSS/:is

**Comment by fisker** [comment]
#13577 should already fixed this.

**Prettier pr-13577**
[Playground link](https://deploy-preview-13577--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEA6AznANnMMIBOSAlugBRIAmpAhgEY6UA0ABFbQ3JUgGYRgBXdK3bp6jJGAAWuANZcR1MZ27S5XJFIgA3OAUUcJasPO59B6AJQtgAHSj2WLALTO+EJCzo0C9+wF8-KAxsXHwiKRpyUXEFNiVYs34hA2UjGRM4mJVJDNNNHT1UxNz1JItrOwcoJ1d3T29fasDqkJw8QiQAdxkCOAoElWKc8xT4ww1jU2H0soLdfXG0ybyNUasbINq3CA8vHyD-ECYQCAAHGGJodGRQHwIILoAFHwQblBosLpoATxuTugEGiZGAAZRoAFs4AAZYhQODIHifTAAoEg0FnYFwgDmyBgBAEcBOcAhdC4lC40JoUGxAho2LgADFCBCaDBLjTkCAaAJ8McQFIYBCsAB1KTEeDoTFgOCgt4S4jaCU-LlgdD-EBwzAEGBPIHY1mI5FEkAAK3QAA9QTicABFAQQeBGrAokCYgja1Xq-lnAhwmAi4iUGBSZAADgADCdfRBMCKgWcub64NrdPyAI4O+B687vbnoZzwrhcfl9TPEPp6+mG3jGk6YCHEPEEk3oG1we2OhG1l0mmD0QPB0NIABMJ3xNGIWBxAGEIBCayAUwBWflCOAAFXo7yRvZO2kJAEkoBTYKCwH6LgBBE+gmA-HDOzD+fxAA)

```sh
--parser css
```

**Input:**

```css
.selector:is(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {

  --foo: bar

}

.selector:has(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {

  --foo: bar

}

.selector:where(:disabled, :disabled:focus, :disabled:checked, :disabled:checked:hover, :disabled:checked:focus) {

  --foo: bar

}
```

**Output:**

```css
.selector:is(
    :disabled,
    :disabled:focus,
    :disabled:checked,
    :disabled:checked:hover,
    :disabled:checked:focus
  ) {
  --foo: bar;
}

.selector:has(
    :disabled,
    :disabled:focus,
    :disabled:checked,
    :disabled:checked:hover,
    :disabled:checked:focus
  ) {
  --foo: bar;
}

.selector:where(
    :disabled,
    :disabled:focus,
    :disabled:checked,
    :disabled:checked:hover,
    :disabled:checked:focus
  ) {
  --foo: bar;
}

```
