### ISSUE TITLE
[BUG] Adds space after a colon for paged media (print css) on `@page` rule

### ISSUE THREAD

**Issue by deadcoder0904** [prettier/prettier#13623]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABADgQwOZyQMwEsAnAZxgAJgAdKCi0wgLzwoFYA6NwugDi54BuWvQC2mYth5IKABmFQAviAA0ICOhiFopZKAnEIAdwAKEhLpSYANkcwBPXWoBGxTGADWcGAGVMouAAZHjhkfBtSOBc3T28fLDAebGQYYgBXKJA4UWc4ABM8-MDMKGw0nDgAMQhicRgtUuQQTDSYCFUQAAsYUWsAdU7CeFIEuB8LIcIANyH7JrBSJxAeSOIYEzdscTCIzIArUgAPHyTrOABFNIh4HetItSwyOGJ5xY70Yh4YPsI8mE7kLxZA9DJE+m50E0PnBVlNQmoAI5XeAbDSWZqkAC0UDg+XyHWIcCRJDgGxw2wIuzUkVEhBS6UyjFKZ0u11ClLumRgmGcPz+AKQACY1KlMIRrEkAMIQUQUrKkNgdNKRAAqPMs4U5aimGQAklBCrAfGBPpoAIIGnwwexnW6RRSKIA)

```sh
--parser css
```

**Input:**

```css
@page:first {
  size: 5.5in 8.5in;
  margin: 0;
}
```

**Output:**

```css
@page: first{
  size: 5.5in 8.5in;
  margin: 0;
};

```

**Expected behavior:**

```css
@page:first {
  size: 5.5in 8.5in;
  margin: 0;
}
```

I thought it was a [tailwind bug](https://github.com/tailwindlabs/tailwindcss/issues/9528) but looks like prettier is the culprit.

happens in vscode when i try `save file` as i have `format.onSave` enabled.

it gives an error when generating a pdf with princexml that says:

> prince: output/styles/pdf.css:26: warning: parse error in page selector after ':'
