### ISSUE TITLE
[feature] config the behaviour about how many spaces can exist before a comment

### ISSUE THREAD

**Issue by Freed-Wu** [prettier/prettier#13702]
<https://github.com/prettier/prettier/issues/6780> discusses conflict with
yamllint and prettier on

```yaml
key1:  # two spaces
key2: # one space
```

and provide a solution:

```
%YAML
---
extends: default

rules:
  comments:
    # https://github.com/prettier/prettier/issues/6780
    min-spaces-from-content: 1
```

I want to let prettier keep two spaces before every comment and I search the
document but found nothing. So can we support this feature?
