### ISSUE TITLE
Regression in 2.8.1: Commas are removed from fn args in Sass maps.

### ISSUE THREAD

**Issue by jgerigmeyer** [prettier/prettier#13984]
Probably caused by https://github.com/prettier/prettier/pull/9184?
Possible related to https://github.com/prettier/prettier/issues/13580?

**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABOBDMALABAEigwFs4AaA7AVzlwEspKaBnXYAHUYOIwAclcPXgDpSAJwDmcABSdc87nzJyFsrgtwByAMTB8vMXABmdAB4BfALS7CJOOc0CARgBsEAE2HM4MaficY3hT41HACITQAlMrquJEqkQDcnOacIGQgELwwdNDMyKAYYmIQAO4ACkUI+SgYLqUYAJ75GU5iWADWPgDKdgAyDHDIRnVBIG2dPbxYDBLIMGI0GXDETnDu7ut9GFASVBhSAGIQYjwwObvIIBhUMBDpINgwxC4A6th08MzTYHDd1Z86AA3T6NK5gZgtEAMbxiGDldoSHjDUbkEAAK2Ypm6szcAEUqBB4CiXGNpmJYVdmBCoQYGDBXnR3DBsMgABwABgyBgg3le7V4VwMcFhQKGGQAjoT4AisjVrsxLFA4Ot1g9DFK6IYEQdkUgRqS0d5iHR5osjbi4ABBc5iOhOW5wcpwMQDZUksbMS0EolDfWojIwDBORnM1lIABMgfadBcswAwhBiHqQCKAKwPKjeAAqwZqBrGQJoAEkoJtYN0wHbslay90YI03B77OYgA)

```sh
--parser scss
```

**Input:**

```scss
@each $name, $hue in $hues {
  $map: map.merge(
    $map,
    (
      '#{$prefix}-#{$name}': blend.set($base, $hue: $hue),
    )
  );
}

```

**Output:**

```scss
@each $name, $hue in $hues {
  $map: map.merge($map, ('#{$prefix}-#{$name}': blend.set($base $hue: $hue)));
}

```

**Expected behavior:**

Comma should not be removed from `blend.set($base, $hue: $hue)` call.
