### ISSUE TITLE
Idempotent issue for SCSS map

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#14088]
**Prettier 2.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAJgSwM4AcA2AhgJ4C0ARgE5yEDWuEms2SABALaG6npxzfs4lAOZwAFAB0orVpOkzWEkAA9spaPmJK2SjcVbYw1BK0JR0szstIB3TOhgALNgGJgnbqJhjUwyvYpqOgYmGGwAGkUQbHYlAEpSAEYAXzilcKkZOIz5DBwCEkCaekZmKTiAbhBwkAhcGExobGRQQkpKCBsABTaEZpRCfBsSZpqqQjBaOBgAZUJBABkmOGQAM0HsODHKCanZ3AmmYWQYSgBXLZA4dnI4dF50BbNhM8JRADEISk4YBqhjgZnGAQaogRwwdj4ADqjkw8DwEzgMz6cMwADc4cRkOBsKMQExNpQYF0dsJOGsNpcAFbYZQzI74OAARTOEHgFPwmxqB0ohOxhlxoNw-lgUPsTmQAA4AAzcjqbKE7XDY4VwQlolY1ACOrPgJLq-RAhDUUD4D1B1B1mGoJLe5KQ605l027EwJ3OzoZcAAgr9-OQgXAukIlqaOVzol6WWyVg7KTUYIRyGKHI5kAAmBM7TD4I4AYQg7HtV2wAFZQWdNgAVJP9R0RtEXACS5gQsyMmHq3vMMxgxEZ4bgyWSQA)

```sh
--parser scss
```

**Input:**

```scss
$display-breakpoints: map-deep-merge(
  (
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, "sm")-1})",
  ),
  $display-breakpoints
);
```

**Output:**

```scss
$display-breakpoints: map-deep-merge(
  (
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, "sm")-1})"
  ),
  $display-breakpoints
);

```

**Second Output:**

```scss
$display-breakpoints: map-deep-merge(
  (
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, " sm
      ")-1})",
  ),
  $display-breakpoints
);

```

**Expected behavior:**

same as input

**Related:**

- https://github.com/prettier/prettier/issues/9128
- https://github.com/prettier/prettier/issues/13984
