### ISSUE TITLE
don't remove escape slash from css files

### ISSUE THREAD

**Issue by GorvGoyl** [prettier/prettier#14187]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAdFCMBOBDKAZwBs94BtAB1LDgAsJiATOHAKgF4AdEAFQE9KcVFy4ByAPSixqAGYQcqSAFtlBJoR4BdJEjyz4i4FyiozS6PFhIRIHqgCEAS2WUFMAjADcJswF8QABoQCEoYJ2hCZFA8HBwIAHcABViEKJQ8YgS8fijggCN8MABrOBgAZTxlOAAZJyg4ZFlMwjgCotKKyjwweoBzZFwAVzaQOGV8uCYWJhqCPqG8PrgAMQU1GHCoAYyhmAggkDoYZWIAdToneEJu2nK0q6cANyv+ZHBCPJB61pwYJPwfTUTRaowAVoQAB7lfrEOAARSG2EaSGaxFawW6OF+7zAn0OlBw9RgZycTBgdGQAA4AAyY+KtM74SjvQlwX5PRrBACOSPgANC6RAeEIAFoGlMpoccHBeU4ZQClsDUaDgq1lE5BjgRmrYQi+Si0RiQB58qTyZSkAAmYK4PBOYj9ADCEFUeHe7IArIchq1eHh8ukjaMniMAJJQFiwcpgIlhACCkfKMH4cJB6Lgfj8QA)

**Input:**

```css
 .notranslate[placeholder*="Type \'/\' for commands"]::after {
    content: "" !important;
  }

```

**Output:**
this would fail to select the element on browser as `\` escape slash is required

```css
 .notranslate[placeholder*="Type '/' for commands"]::after {
    content: "" !important;
  }
```

**Expected behavior:**

```css
 .notranslate[placeholder*="Type \'/\' for commands"]::after {
    content: "" !important;
  }
```

I'm actually using .scss file but I believe the resolution should be same.
