### ISSUE TITLE
@font-face urls are incorrectly stripped of commas

### ISSUE THREAD

**Issue by drott** [prettier/prettier#14237]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgPgB0oACEgAQDNoYBaSgQzDhOGLI4+tnoYFsAljixISAJwgAjANyc58hYqXKVqxewXoxYUQFcxOABQAlKRBgQAYngAetAGoMxAhpLyWaAfQDixgIIAIgA0ABoAKv5BAJoA8gAKAIrRYX4AyskBAKLJlgCSyQAyAMLJAKolEAAO6ABeQeg4sEEA7gAmMAAWLQDmHTAAdDAwlACU0hokAL5yxKgA9Ji4BBMkIEEgVTAC0OjIoE4SzXFOCLsoDDjNDFi765JiTADWcDCp-HAFAlBwyIw46HA7g8wM9XpUmF9usgYGJdICQHA+JI4K1WiiCgwoN1dAxunAPGI+AwhpDkCAGLoLGsQH0+DgAOodATwdDg5ipU7MgQAN2ZWDJYHQtxAXwBYhgcQe3SJvwuAPWACt0DZUpC8AldOYfkg-vKQOCxGKybScNTKs5YPSBO0OsgABwABnW5ogAPpD0qZPNcDF3J+6wAjpr4JKqmdyehaN8USjqWI4EGBPHJbiZTq5fCAYJobDM2q4H4hs5JJS4HE4GJPt9Zf881j1cHtbr4TBXFabcgAEzrGEMISQooQPhphHoACs1N0ALCrjOzfW3LhuSgaNgqTAzkqMD8K9S2DwNYBk0mQA)

```sh
--parser html
```

**Input:**

```html
<style>
  @font-face {
        font-family: rob;                                                                                
        src: url(RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf);
   }     
</style>
    
```

**Output:**

```html
<style>
  @font-face {
    font-family: rob;
    src: url(RobotoFlex-VariableFont_GRADXTRAYOPQYTASYTDEYTFIYTLCYTUCopszslntwdthwght.ttf);
  }
</style>

```

**Expected behavior:**

Commas in filename should be kept - I don't see why they would be invalid inside a url() CSS function.

**Comment by sosukesuzuki** [comment]
Thank you for reporting this! This is a CSS formatting problem, not for HTML!

**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVABAZtGBaLAQzDlWAB0p1rqdYDCBbASwBsBPJVAJwgCMA3DWEjRY8RMlSxlMQGduYLgFdurABQAlfhBgQAYqzgAPPADVC3ZoT5H9uAPoBxTQEEAIgBoAGgBU3ngCaAPIACgCKQb6uAMpR7gCiUfoAklEAMgDCUQCq2RAADnIAXp5yrLCeAO4AJjAAFtUA5vUwAHQwMFgAlAKy6AC+wv3oIJ4ghTDM0HLIoJa8VaGWCLMohKxVhOyz43zcxADWcDAxTHDpzFBwyESscnB7B2DHpwXEV03IMNzKjyBwRh8OA1Gog9KEKBNZSEJpwezcRiETqfZAgQjKPRjECtRisADq9WY8Dk7xIMVWxOYADdiew0WA5LsQFcHtwYKEDk0kbcNg9xgArOTGGKfIzhZS6G5IO78kDvbhshlM7EFKywfHMOr1ZAADgADOM1RAHviDgU0Wq4GzqTdxgBHSXwTmFNbouR4a4gkHY7hwR3MP2c2E8mV8-4PFjfX4RsVwVydKx8TFwUJwbiXa68+6xqHip3S2X-GA2TXa5AAJnGP0IbE+mQgjFDALkAFZscoHr4bGsi+NqX8UlAwbAYmArAUYK5hzEYOwjNmHgMBkA)

```sh
--parser css
```

**Input:**

```css
  @font-face {
        font-family: rob;                                                                                
        src: url(RobotoFlex-VariableFont_GRAD,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf);
   }     
    
```

**Output:**

```css
@font-face {
  font-family: rob;
  src: url(RobotoFlex-VariableFont_GRADXTRAYOPQYTASYTDEYTFIYTLCYTUCopszslntwdthwght.ttf);
}

```
