### ISSUE TITLE
less format error

### ISSUE THREAD

**Issue by chaxus** [prettier/prettier#14623]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
prettier --write --cache . 
prettier --check --cache .
```

**Input:**

```less
@number: 49;
@keyframes loading {
    .circle(@index) when (@index < @number){
        @i: @index+1;
        @x: round((@i / @number) * 100,2);
        @selector: e('@{x}%');
        @{selector}{
            background-image: url('../../assets/image/loading/1_@{i}.png');
        } 
        .circle(@i)
    }
    .circle(0);
}

.loading {
    width: 100px;
    height: 100px;
    background-position: center;
    background-repeat: no-repeat;
    background-size: contain;
    animation: loading 1s infinite;
}
```

**Output:**

 ELIFECYCLE  Command failed with exit code 2.

**Expected behavior:**

This less file will work fine, but formatting or checking will give an error, I expect no error, or I want to know what to do

**Comment by fisker** [comment]
It seems we can't parse  the following code  in v2.

**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABYBnOAbOYYQBOAvsADpQAElZMk2RSlAxAGasDcFxNUIANCAgAHGAEtoGZKACGhQhADuABTkIpKGdkUyAnlMEAjQjLABrODADKMgLZwAMmKhxkrLViMnzlq8NPOAObIMIQArnCCcLaGcAAmcfEOMlCBYTKBcABiRLYyMOKpyCAyYQQCIAAWMLbYAOqVYvAY-mBwVupNYgBuTbrFYBgGIM5YhDDKJoF5bh6RIABWGAAeVkG4AIphEPCz2J4g-oRjxbhDFcKEzjB1YnEwlcgAHAAMgpcQWHUmwsWXcGNuq5BABHbbwSYiDQlDAAWhc8XiFUIcDBYhRkwyMyQ7n28ywtjEIXC+PWcAAggUroYynBlHBCE4XHsDhgyVsdq4cXNBDAZIZbvdHkgAEy8kxibBBADCEFs2JAAIArBUwlgACr8jS4g7dCIASSgiVgVjAV1E5KNVhgulwLLgxGIQA)

```sh
--parser less
```

**Input:**

```less
@{selector}{
  	color: #ff;
} 

```

**Output:**

```less
SyntaxError: CssSyntaxError: Unknown word (2:4)
  1 | @{selector}{
> 2 |   	color: #ff;
    |   	^
  3 | } 
  4 |
```

But it's already fixed in v3.

**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABKBXAtgIzgJyQAIAWATgG4AdKVAazgE8AzfAQyzgGciAbCNgBMAllADmRYDSJEAdGGH4wvOAApUowXAAeASiIB3ABYIi6zTqIAeIumx58+qVBkyNxDVC3aA1AEZqF1dUbWJ8CAwvVXMiAHpbTFwCfQAqIj8ABgyAGiIAJl1A11suOBUwGAhCIjUqNGBtAF8AUjrC6WDgUvLK-EbJDuKcNjA6MXDIwQBaYSw2MThiDHxeVTrZWViN2LYuUpguWNn5uFj+IVExWL8AfVRgYUbZAAdxNqLXRsG5BSUVc3aQS+QXkimUagygOBNFk5xE4gGQQMwkEMCMxEyGWe2g+JmEYiMMAxWWxH2Go3GES8U2eEC4whgwmgxDACHg+DJIzGE2p+DgzzgbCJRCgECmfIFQs5FJ503pAC9FkRILA2KIPmwoMdGcy+AJ4RI-DxRMxRAy4IFGiBsiAIM8dVAuMhQGx8OEDAAFV0IJ0oNi8AxsRhOm04dijOAwADKHDgABlRHBkMx-aVQ+GGNHniNLsgYPgMHAbXAkoItII45qxBgTgAxKpzGCM8TIEBsDCVa0gQlYXgAdSM5q42dZUZ9DOEADcGYxW2A9l3RKV8DAPewxHNk6miyAAFZcbRRy4qACKGAg8C3vDTIGz+GXrZUC5tz3wohgfZRaOQAA4crfwlKPt2GeVtX24AhJyTG0AEdz3gNc7V9NsuCmKA4Dgcsuz5ODFDgNd5k3JAU2vHdSiwYQ8wLMjjzgABBJs3xwDt8IIBN0KvG96XEU94KTYjtxtGA2BwT9USMZA8iE9hhF4S4AGEICwIiQG4ABWLsMFKAAVETfRIm9J0LABJLw2SjMA33tOivCjGBGBUTi4EaRogA)

```sh
--parser less
```

**Input:**

```less
@number: 49;
@keyframes loading {
  .circle(@index) when (@index < @number) {
    @i: @index+1;
    @x: round((@i / @number) * 100, 2);
    @selector: e("@{x}%");
    @{selector} {
      background-image: url("../../assets/image/loading/1_@{i}.png");
    }
    .circle(@i);
  }
  .circle(0);
}

.loading {
  width: 100px;
  height: 100px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: contain;
  animation: loading 1s infinite;
}
```

**Output:**

```less
@number: 49;
@keyframes loading {
  .circle(@index) when (@index < @number) {
    @i: @index+1;
    @x: round((@i / @number) * 100, 2);
    @selector: e("@{x}%");
    @{selector} {
      background-image: url("../../assets/image/loading/1_@{i}.png");
    }
    .circle(@i);
  }
  .circle(0);
}

.loading {
  width: 100px;
  height: 100px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: contain;
  animation: loading 1s infinite;
}

```

We need add it to tests.
