### ISSUE TITLE
Unwanted space after `$` in less file

### ISSUE THREAD

**Issue by AkatQuas** [prettier/prettier#14694]
**Prettier 2.8.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABGALOBbOBnJAAgBsBLAcwxgBpCATAQwCcBrAbgB0ouA6THOAFpIxCEzwAKVCLFEA5HICUhYF0KE4DMBin9ceWqqjr1PVMABuDYgFc4AX0IAyFWpOm8cGIL1CZTCX9aaQhRJmCrWzhFTmMTezd7GK4E7igeT29fYVCxKQAHJgh8uCYYAE8I6ztg32UAdyxjKAgYQilIu0IAXkIFZSN1c0Li0or7IlROuABtABJ0LFwAXVjUrlQAIQBxIkH6ZhYiJnIAIwYJACYAFgBmWhv7whvr2gBGHgAGT+S4skoYMczhdHg87mDXoQPt9fut0gxXHE+Es-LlxFJ-JMdooUiBqCBijBSNA8MhQMwivUAArMBCklDWeoMcqk-GnJhaFheADKDFwABlSFA4MgAGbWTxsjlgLkwbn5LRC8jIGBMGogHCnOB0Oja-kMKDkGwMchwABiYmwDBgRMNyBADBsMAgeJAVGwxAA6hhSPA8AqwHBuXTfaQLL7yvawHhWSAhZ4ylSOeQrWKJXB8QArPAAD25SuIcAAijZWiKkOLiJKQArxKV7YWY67CkKYJ7SHRMMgAByffEjTyejn5e2FfClCwi-EAR1L8CTxXpDrwgmF2u1rqYcFnpC3SZNqYr6fxnmwpBVaozIDwBbgAEEbUxSKcnXAqaVBcK01WrzfDYWSzLb9qxgBhTnbTsMGQS58VVBhSDIQ0AGEIGwQ8NTwABWV0bE8AAVMD6UrasLDsABJKBdVgbkwCffIYDvSjuQqQtgIcewgA)

**Input:**

```less
@themes: light, dark;

.theme-colors(@color: '') {
  each(@themes, {
    .@{value} & {
      .set-theme-color(color, @color, @value);
    }
  });
}

.set-theme-color(@property, @value, @theme) when not (@value = '') {
  @{property}: @value[$@theme];
}

@BG: {
  dark: rgba(243, 243, 244, 1.00);
  light: rgba(243, 243, 244, 1.00);
}

.a {
  .theme-colors(@color: @BG)
}
```

**Output:**

```less
@themes: light, dark;

.theme-colors(@color: "") {
  each(@themes, {
    .@{value} & {
      .set-theme-color(color, @color, @value);
    }
  });
}

.set-theme-color(@property, @value, @theme) when not (@value = "") {
  @{property}: @value[$ @theme];
                    // ^ unwanted space
}

@BG: {
  dark: rgba(243, 243, 244, 1);
  light: rgba(243, 243, 244, 1);
};

.a {
  .theme-colors(@color: @BG);
}
```

**Expected behavior:**

Don not insert space between `$` and `@` .
