### ISSUE TITLE
Unexpected behavior with --loglevel flag in GitHub Actions

### ISSUE THREAD

**Issue by veekhere** [prettier/prettier#14739]
**Environments:**

- Prettier Version: 2.8.7
- Running Prettier via: npm run
- Runtime: Node.js v18
- Operating System: Linux

**Steps to reproduce:**

- Setup ```npm``` script with command ```prettier --loglevel error --check .``` (add quotes if you want)
- Setup Workflow job with ```run: npm run SCRIPT_NAME```
- Run Workflow

**Expected behavior:** shows linting errors

**Actual behavior:** exited with code 1

> **Warning**       
> The ```npm``` script ```prettier --check .``` is working correctly with ci/cd

**Comment by sosukesuzuki** [comment]
It is expected that `--check` will exit with exit code 1 when Prettier finds unformatted code. Also, the --loglevel CLI option has nothing to do with exit code. It simply determines how error messages are output.

**Comment by veekhere** [comment]
Yes, but I actually mean that code passes linting on local machine but fails on remote server

**Comment by kachkaev** [comment]
This probably means that your remote server creates temp files that are not mentioned in `.prettierignore`. Please share a repository with reproduction steps, it is hard to help without it.

**Comment by veekhere** [comment]
> This probably means that your remote server creates temp files that are not mentioned in `.prettierignore`. Please share a repository with reproduction steps, it is hard to help without it.

Unfortunately, this repo is no longer available. I had a basic Angular `ng new app` with Prettier inside. I ran `prettier --loglevel error --check .` in root of the project and then fixed 1-2 warnings. After this I created simple workflow to test Prettier for CI/CD like this:
```
name: Deploy application
on:
  push:
    branches:
      - master

jobs:

  # testing job

  lint:
    name: Linting
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npx prettier --loglevel error --check .

  # building & deploying jobs

```

I tried to wrap flags & arguments in quotes but it not worked (crashed with code 1). Then I removed `--loglevel error` from `run` and linting successfully passed (no errors, no warnings). I placed `--loglevel error` back and it crashed again.
