### ISSUE TITLE
LESS mixins are not formatted, except when used as functions

### ISSUE THREAD

**Issue by lg-kialo** [prettier/prettier#14789]
**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AtgSwB6agCgAFIAbCAJwBoACQgBwEMATJvAcxsPQfLbyWoAmAJTVgAHSjVqpCgFoAzAOIQy5ANyTpjFu0XKdrKG01Tq3Xv1oW+Urj1vWHeJ5aimAvpMkB6AFR+1AByEDDUAGYU3DDwTNRI+PjUAT6SqADOEOhw1BlwJHBgMBTUrABuYlq5WLgE4jD1jTAAxAAMrQAc7a00VX0NA-WClP31AIxVwp7eUBg4eIJEsuQCAEYkDGAA1uqutgJjrXTYu-TMRmwCgkfYohJmy8rLptI2VvZuL9SG7Abn7NMoP5AiEwpFyNFYvFEsk-KlZmANul0mNKmY5rVFn0zB99kIbrsqio1AJmgoFJtwnAmk0ppIvECAsFQhEogwYnA4gkkik0oiGMjBGjpBiFvhsdJmnBwmAGAAWOWnH7GAQ0mBym50qAM3xMgBibI5XOEol5swYZTg5AYbDgRGwnAAnncieQ4OkAK4kGACcVmaRVAP+6j26gAalozuoPmogaEavqWp1jMCBoh7KhSBNsPh5WF0ZjspIJGoDHM8ykDCgcTIEC21A9dGomBg6VjIEIbs93vEIGoZQYJA91LMysuuQtVptdskYwAbMcaABWG6jBpmBMwYQAbU77q9MAAup4QJQQBA6DBMNB0shQDxyBAAO4ABR4CFvKEHT4YjtvZ9Wa1tjgGAAGUGGyAAZPA4GQGByGHACgK2EDQMYMB2DghC4DPOB0FWTkmE5SCqzYD1pzTSFMK-D1ilPEAAAsYHQEgAHUGJbd10LgUCPxbTAyhbR1kHAZF6LwdIrRgF9rTYbhkHCQdJLPAArdJsFA9gCgARQ9UJYKQRSSGUkBGHISTyBEgoxLPOhyDwGBWMwJgYAY5AxmuWzH0k1jrToES7PdK1LXogBHPT4Bki9PxAAU5CgOBOU5ei3XCzA3Rkm15MMpScJASSsCwxD8q0uAAEEYns1ZaLgF8rWghKFNys90lK3T9KKvKYAYVYnJctykDlM94IYTASHYABhLJspAd0l3oj1JIAFR6z8jJMsphwASWrBAwLAezLzK6tQJgR0Cia4y4A8DwgA)

```sh
--parser less
--print-width 120
--tab-width 4
--single-quote
--bracket-same-line
```

**Input:**

```less
.mixin(@color, @padding, @margin: 2) {
  color-3: @color;
  padding-3: @padding;
  margin: @margin @margin @margin @margin;
}

/** Not formatted :(( **/
.some .selector div {
  .mixin(				#008000, 
  
  				2,
  		1
  );
}

.mixin2(@color: black; @margin: 10px; @padding: 20px) {
  color: @color;
  margin: @margin;
  padding: @padding;
}
/** Not formatted :(( **/
.class1 {
  .mixin2(
  
  @margin: 20px; 
  @color: #33acfe				);
}
/** Not formatted :(( **/
.class2 {
  .mixin2(
  
  #efca44; @padding: 			40px);
}

/** Formatted :)) **/
.average(@x, @y) {
  @result: (
    
    
    (@x + @y) / 
    2				);
}

/** Formatted :)) **/
div {
  // call a mixin and look up its "@result" value
  padding: .average(
16px, 50px
  		
  				)[@result];
}
```

**Output:**

```less
.mixin(@color, @padding, @margin: 2) {
    color-3: @color;
    padding-3: @padding;
    margin: @margin @margin @margin @margin;
}

/** Not formatted :(( **/
.some .selector div {
    .mixin(				#008000, 
  
  				2,
  		1
  );
}

.mixin2(@color: black; @margin: 10px; @padding: 20px) {
    color: @color;
    margin: @margin;
    padding: @padding;
}
/** Not formatted :(( **/
.class1 {
    .mixin2(
  
  @margin: 20px; 
  @color: #33acfe				);
}
/** Not formatted :(( **/
.class2 {
    .mixin2(
  
  #efca44; @padding: 			40px);
}

/** Formatted :)) **/
.average(@x, @y) {
    @result: ((@x + @y) / 2);
}

/** Formatted :)) **/
div {
    // call a mixin and look up its "@result" value
    padding: .average(16px, 50px) [ @result];
}

```

**Expected behavior:**
I would expect all the mixin usages to be formatted, but only when the mixins are used as functions that works.
