### ISSUE TITLE
Support custom languages within YAML inline strings

### ISSUE THREAD

**Issue by felipecrs** [prettier/prettier#14957]
PS: I did not find an existing suggestion for this from the issues.

I have a bunch of YAML files that embeds other languages like:

```yaml
javascript: |
  console.log('hi')
json: |
  {
    "hello": "world"
  }
```

Which is very similar to what happens to markdown (and it is supported by Prettier):

    ```js
    console.log('hi')
    ```
    ```json
    {
      "hello": "world"
    }
    ```

Which means Prettier will format the blocks using the formatter that matches the language of the block.

It would be really nice if the same could be supported to YAML files like the one above. It would save me a lot of time, as I have really huge YAML files with inline blocks.

What I currently do is to extract them to a different vscode tab, set the language, format, and copy back to the YAML.

However we need a way to tell Prettier which language should be used. Maybe:

```yaml
javascript: | # prettier-language=javascript
  console.log('hi')
json: | # prettier-language=json
  {
    "hello": "world"
  }
```
