### ISSUE TITLE
Support Handlebar templating in CSS files

### ISSUE THREAD

**Issue by mangelozzi** [prettier/prettier#15283]
The templating support in HTML files is great. In a project I am working on have `{{ foo }}` or `{% foo 'bar' %}` in a CSS file. It would be great if Prettier could support templating in CSS too, e.g.:

```css
:host {
    --fg: black;
    --gray: {% color 'gray-4white' %};
}
:host([dark]) {
    --fg: white;
    --gray: {% color 'gray-4black' %};
}
```
