### ISSUE TITLE
Regnize `<ratio>` CSS value

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#15339]
**Prettier 3.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATAlgNwATADpTbYCGAzgA5xgwC0ATsTOhEtgIwBs2A9NgJwBubASJlK1eo2atOvQcMIkKVWgyYt2XbvIIBfEABoQEcuqilkoYnToQA7gAVrCCymIAbO8QCeFowCMGMABrOBgAZWIAWzgAGXQoOGQAMw9SOACg0IjyYjAEgHNkGDoAVwyQdKj0YrKK0kL3OABFUoh4FLSKgCtSAA9wxpa2jqRU93SjAEcRuAdbclcQMhpEuFR1wxAS4nR3QoBhCCio4mRl93cthqgCpoBBGBL0f1L4Bzg6eMTOiYqACxgUXcAHV-uh4BQ8nBwi4IVgId5zmBSH4QJhygBJKAbWDhMB0dCme448IwbxNX6TEDkWzpEEMcjnWlwdJ0TBJIwJNkwebEAqnKkVXJ0NnI1FbWkJGAg9CoGD-ZAADgADEY6HAZugNXyBWcxl0jDBiP5ZfLFUgAExGUrpAAqJtc42pcCi-nWG1QsWIt1K-LgADEIHRTk9CudiG8ICBdLogA)

```sh
--parser css
```

**Input:**

```css
div {
  aspect-ratio: 16 / 9; 
  aspect-ratio: 16/ 9; 
  aspect-ratio: 16 /9; 
}
```

**Output:**

```css
div {
  aspect-ratio: 16 / 9;
  aspect-ratio: 16/ 9;
  aspect-ratio: 16 /9;
}

```

**Expected behavior:**

They should format the same.

[The `<ratio>` CSS data type](https://developer.mozilla.org/en-US/docs/Web/CSS/ratio)
