### ISSUE TITLE
CSS selectors are completely ignored

### ISSUE THREAD

**Issue by fregante** [prettier/prettier#15356]
It seems to me that CSS selectors are not formatted at all. Is this a bug or a feature request?

**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhgHSgAj-gwnTGVAEwEsAzKgWngA8Zaw4AbN7I7-Enc6nUYxsXQgHoAVDwIBRSjBwAHdAHM4AGmUAnCACN0etgE8cAVyWQAthSiqcAEQDyAWRxwAbnG3GA7gAtvOGIoSXExAiQkPTgqCG1g4FFFbg8KAGcKPQo2ChhjJBCZQn8KMjIEAG5sAF9sEA0QCCUYCmh05FB0bV1fAAVuhA6UdDZfdGMOxr1tdDAAazgYAGV0KzgAGVs4ZCpR9M0QGbnFlZUwW1VkGG0zQ4Oba9v7y7Y4AEUzCHhd-cOAK3SDGWrw+Xx+SD2bAOjQAjuC4H1dEphiB0OlaFA4HAKmQGiAbugcpcAMIQKxWdDINEcfGZOxvACCMBuWTM8D63i2WN+0MO-hgVjYAHVSvB0uc4MshnkKGl8tSwOkpiAPHcAJJQCqwZZgbQUFqMrXLfJvXkwkBKXQHYWzJTUq1wA7aLz42zOmBItSU82HFTaZ2K5X4q22GDCsowfzIAAcAAZGgl4RQEl7VD7IX9GjBDBGyFHkAAmRpmA4AFUMwyhFrgVhi5RxG3QdjMajgADF4pSWZdqeh2RAQDUakA)

```sh
--parser css
```

**Input:**

```css
.a
                	.diff-text-cell
                	 .diff-text

      /*            Edit page, probably upcoming DOM everywhere 
*/
      ::before {
	        visibility: 
              hidden;
}

```

**Output:**

```css
.a
                	.diff-text-cell
                	 .diff-text

      /*            Edit page, probably upcoming DOM everywhere 
*/
      ::before {
  visibility: hidden;
}

```

**Expected behavior:**

Something like this:

```css
.a .diff-text-cell .diff-text
/* Edit page, probably upcoming DOM everywhere */
  ::before {
  visibility: hidden;
}
```

**Comment by fregante** [comment]
_Some_ optimizations are applied:

```css
hello:is(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {}
/* Becomes */
hello:is(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  ) {
}
```

But even that is broken because the closing parens has a wrong indentation. It can be fixed by adding one more part to the selector:

```css
.BUGFIX hello:is(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {}
/* Becomes */
.BUGFIX
  hello:is(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  ) {
}
```
