### ISSUE TITLE
Indentation of multiline :is() selector is wrong

### ISSUE THREAD

**Issue by fregante** [prettier/prettier#15359]
I think the default breaking for JavaScript parens looks like:

```js
if (
  longCondition
) {
}
```

But with `:is()` in CSS I'm seeing consistently:

```css
:is (
    selector
  ) { /* see extra indentation*/
}
```

Here's the [live example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALOAbDEkEsDOAFAIalnkWVWUA0ABAEZPMutvsfMCUdwAviBogIABxi5o+ZKGIAnWRADuABTkIpKYhkXEAnlKENZxMAGs4MAMrEAtnAAyuKHGQAzLfjiHjZi5ZEmTgDmyDCyAK5eIJ42uKERUfjBGHAAiuEQ8G4eUQBW+AAelslpGVlI7hieQgCOZXDKCiIaIMT4ALTOcAAmPYIgYcS4GMEAwhA2NsTIrVj9SVBBKQCCMGG4DOHwynCyjs7ZVVGoMDYYAOqouPD4AWBwlurXuABu17ozYPgGIC+RAJJQXqwSxgWS4MTLIGWGC6FKHaogEQKTznYwiGbIuCeWQvFxCJw4mCNYhBKYIqIBWQ4z7ffrIpwwc64bowVDIAAcAAYhLI4HVcHySWTphUckIYMQGMzWeykAAmIThTwAFSlGkqiLgNgYPV63XsxEW4VJcAAYhBZFM1sEZsQthAQHw+EA) for the playground:

```css
hello:is(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {}
/* Becomes */
hello:is(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  ) {
}
```

This bug is no longer visible/present when the selector is extended slightly:

```css
.BUGFIX hello:is(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {}
/* Becomes */
.BUGFIX
  hello:is(
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  ) {
}
```

_Originally posted by @fregante in https://github.com/prettier/prettier/issues/15356#issuecomment-1705934941_

**Comment by fregante** [comment]
This bug is no longer visible/present when the selector is extended slightly.

**Input:**

```css
.BUGFIX hello:is(aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb) {}
```

**Output:**

```css
.BUGFIX
  hello:is( /* This is now aligned*/
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
  ) {
}
```

**Expected behavior:**

The break should probably still not happen before `hello`

```css
.BUGFIX hello:is(
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,
  bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
) {
}
```

**Comment by fregante** [comment]
I think this is "technically correct" because it's just wrapping the line _and_ indenting the function at the same time. This is why the "longer selector" below _works_.

```css
hello world {}
hello
  world {} /* indentation added after wrap */
```

```css
hello:is(world){}
hello:is(
    world /* indentation added after wrap AND indentation added due to parens */
  ) {}
```

I still prefer how it looks in JS though, so the behavior should be altered IMHO
