### ISSUE TITLE
Nested SCSS function calls with leading dash are interpreted as unary minus

### ISSUE THREAD

**Issue by threema-danilo** [prettier/prettier#15369]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZgVymGBLaAAgFoATCTAIwBs4AKAEgDcBDazOASkOAB0pChVACc4MTMIHM2HQgCpCAJgDc-AL79+AOgDOcWrgjCe-QemgxiOvAC84SEuSq06ZCjXoBGOAFtOnVSg1EAAaEAgAB3xoHWRQFmFhCAB3AAUEhFiUNmSWAE9YsMphFjAAazEAZRYfOAAZPCg4ZHQ2PSKS8qqI0saAc2QYYQ4wvR88QeG4Uf7aAEVMCHgWtumQACsdAA9K2bgFpeakVup2kABHRfhUpIiskBYdYia4UlfQkCGWPGp+gGEID4fCxkA9qNQPtYoH1aABBGBDPCUTDXODCBpNFanNYACxgPmoAHUcXh4DoemA4JVMqS8ExSXlQWAdIUQEwOABJKBvWCVMDCPBRWHcyowPK0LFnCJJPSEkoRUHSuB6YRMZphRoqmA3Fh9YGStY9YQq0E6Zms6WNGCEvCkGA45AADgADGFRJc8KIdXqQcdVmEYCxKDa7Q6kIowpg9AAVINZE5nXyUV5vUh1FjQzC6uAAMSMwIR-VBLBREBAajUQA)

```sh
--parser scss
```

**Input:**

```scss
@function -double($value) {
  @return $value * 2;
}

.selector {
  font-size: -double(-double(1em));
}
```

**Output:**

```scss
@function -double($value) {
  @return $value * 2;
}

.selector {
  font-size: -double(- double(1em));
}

```

**Expected behavior:**

Dashes are valid parts of SCSS function names. You can test this by pasting the following snippet at https://www.sassmeister.com/:

```scss
@function -double($value) {
  @return $value * 2;
}

.selector {
  font-size: -double(-double(1em));
}
```

However, if a function call is nested, the inner leading dash is interpreted as unary minus, and a space is inserted. This breaks the SCSS function call.
