### ISSUE TITLE
Prettier doesn't understand `s` in attribute selector

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#15397]
**Prettier 3.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEEA2BtGBPADnAXgEMACAZwF0TgAdKEktASzJgFpXs042d8lGEAO5wATmyJpcACyIBuOgF86ddFjyEaIIlvJVa9Ri3aduvDQLTCxEqbIVRFIADSpcMJtDLJQRUaOEABT8EbxRJISJsb1cAI1EiMABrOBgAZSIAWzgAGSYoOGQAM0kyODiE5NS03ET8gHNkGFEAV3KQMsymJtb2sgbuAEUWiHhi0vaAKzIADzSBuGHRwqQStDLXAEcR+ECA3DDtMjYCuAATc5cQZqImZih6gGEITMyiZG00NCv+h+4AQRgzSYsRauzEeQK43W7WkMEyaAA6tImPAyLUwHA0qFUUwAG6o7AfMBkGIgPFtACSUAusDSYFETHc-xpaRw3GhGxAuACZURCVwHx5cDKojxhVc+VFMD2RHqb057VqolFxNJVx5+RgiKYZxg0mQAA4AAyuURwbZMc2y+XvVYTVwwIixHV6g1IABMrhaZQAKs6wmsuXBMrFzhczjkiA8WnK4AAxCCiN5AhofIhgiAgRSKIA)

```sh
--parser css
```

**Input:**

```css
ol[type=a s] {
  list-style-type: lower-alpha;
}

ol[type="a" s] {
  list-style-type: lower-alpha;
}
```

**Output:**

```css
ol[type="a s"] {
  list-style-type: lower-alpha;
}

ol[type="a" s] {
  list-style-type: lower-alpha;
}

```

**Expected behavior:**
```css
ol[type="a" s] {
  list-style-type: lower-alpha;
}

ol[type="a" s] {
  list-style-type: lower-alpha;
}

```
