### ISSUE TITLE
Prettier 3.0.3 can't use plugin-xml in the context of pre-commit

### ISSUE THREAD

**Issue by kamitchell** [prettier/prettier#15696]
See https://github.com/prettier/prettier/issues/15517 for previous discussion. Since this problem only happens with plugin-xml, they suggested I report it here.

**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: pre-commit
- Runtime: Node.js v20
- Operating System: macOS
- Prettier plugins (if any): @prettier/plugin-xml

**Steps to reproduce:**

Add the following to `.pre-commit-config.yaml`:

```yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3 # Use the sha / tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
          - "@prettier/plugin-xml@v3.2.1"
```

Add a misformatted XML file, and run `pre-commit run --all`

**Expected behavior:**

Formats the XML file

**Actual behavior:**

```
[error] Cannot find package '@prettier/plugin-xml' imported from /Users/kevin/src/.../noop.js
```

I tried a whole bunch of options including adding the plugin option to `.prettierrc.yaml` or adding a `--plugin @prettier/plugin-xml` to the args in `.pre-commit-config.yaml`.

Going back to a pre-v3 version works, which is what I'm going to go back to for now.

I've created an example repo: https://github.com/kamitchell/pre-commit-xml-plugin-example which has an example and more discussion of things I tried.

**Comment by kachkaev** [comment]
@kddnewton, why do you think that it’s an issue with Prettier core rather than the plugin?

> Since this problem only happens with plugin-xml, they suggested I report it here [in prettier/plugin-xml]

This made sense to me. Now this issue is kind of a duplicate of https://github.com/prettier/prettier/issues/15517 😄

**Comment by kddnewton** [comment]
I'm assuming this has something to do with how plugins are loaded because the XML plugin is using all the standard stuff (unlike the Ruby plugin, which has a whole server setup). If I'm using the standard options/configuration for a plugin and it can't be used properly, that sounds like a bug with prettier not the plugin.

**Comment by Goldziher** [comment]
I have a similar issue.

This is my pre-commit config:

```yaml
default_stages: [commit]
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: "v9.10.0"
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@commitlint/cli"
          - "@commitlint/config-conventional"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ".idea/modules"
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        exclude: ".idea/modules"
        additional_dependencies:
          - prettier
          - "@prettier/plugin-xml"
          - prettier-plugin-sort-json
```

And this is my prettier config:

```json
{
	"jsonRecursiveSort": true,
	"plugins": ["@prettier/plugin-xml", "prettier-plugin-sort-json"],
	"quoteProps": "consistent",
	"semi": true,
	"singleQuote": true,
	"tabWidth": 4,
	"trailingComma": "all",
	"useTabs": true
}
```

When executing, I get:

```shell
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...........................................(no files to check)Skipped
check for added large files..............................................Passed
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

[error] Cannot find package '@prettier/plugin-xml' imported from /Users/naamanhirschfeld/workspace/basemind/sdk-android/noop.js
```

I am using pre-commit `3.5.0`, which is the latest.

Also-- this is not '@prettier/plugin-xml'  specific, when I remove it I get:

```shell
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

[error] Cannot find package 'prettier-plugin-sort-json' imported from /Users/naamanhirschfeld/workspace/basemind/sdk-android/noop.js
```

So this is definitely something else.

**Comment by paddyroddy** [comment]
Could this be related to the archiving of the [mirrors-prettier repo](https://github.com/prettier/prettier/discussions/16227)? I'm certainly keen to keep using `prettier` via `pre-commit`

**Comment by jonasengelmann** [comment]
There is a workaround that currently works for me (it has been posted elsewhere but I don't seem to find the original comment anymore):

.pre-commit-config.yaml:
```
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@3.1.0"
          - "@prettier/plugin-xml@3.3.1"
```


.prettierrc.cjs (note the cjs suffix):
```
module.exports = {
    plugins: [require.resolve("@prettier/plugin-xml")]
}

```

**Comment by JoC0de** [comment]
I created a fork of https://github.com/pre-commit/mirrors-prettier with a script that allows using plugins as normally.
```
  - repo: https://github.com/JoC0de/pre-commit-prettier
    rev: "v3.3.3"
    hooks:
      - id: prettier
        additional_dependencies:
          - "prettier@3.3.3"
          - "@prettier/plugin-xml@3.4.1"
```
