### ISSUE TITLE
Bug: Single space before comments at end of YAML files are removed

### ISSUE THREAD

**Issue by TimHaboldt** [prettier/prettier#15720]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAJzgcwJbToBKArgDZwDOAOlLQHQAO2MMecmA+pFAGZ45OmcnCS106ABYBDAG54ogsDMVVOCzo2lgA1tJyjxE9MumrKYqMeMBadFt36qAemZxW7TDZ78czgFT+AbS0GAgAJtj4hKQUNHRQGFEEVgAqcAC2jGTS8PEMbh4cnPBZOfCWEnAAHvBQ4RZGEnb0UBDhcCWZ2blwTegtZBAA7kJUECSYYGrCUFDFpT3wRpQwTkjoJFB4MEbzcA0bANoAuitgmHiMMJW29lCMGfYsbBwhiegRyYTpZb3xIAANCAINcUpRkKBpJhMCMAArQhAQlDSMjDaQATwhwIARphtDp3ABlaQZOAAGQUcGQvFRlDguPxumJDgUOGQMGEDJA9IyeA5XOBNUYHDwZNgqPSmCg0PYyNpZHpwMobIoAEUSBB4DS6dyAFaUapE1VwDVa6lIBVKkAAR018DhsMYyJA0koNn2HXCQJAnOkeDIbIAwhAMhlpMhXWQyD6VYoKABBViXHEkB0cSnzHWK7mSGAZMgAdUkOyoDjgRKROzw8hgGMjYEo2JAshIcAAkvUEDAiRcrjAE-UiXWKNnrcwIPTC-jGJG3PTMLJqcCFAuYI79OGx9ytJgF5GMaSY8DmAoYIW8OEYJJkAAOAAMwOwdrw2A3OC3lt1wLWOIvV5vJAACZgRIelUmkHF5W-EBMhxA4vXJMwcBIJwADEIEwcMPEUSNpDTCAQAAXyIoA)

```sh
--parser yaml
```

**Input:**

```yaml
# region Rules

.prettier_config_rule:
  having_changes_in_package:
    changes:
      - packages/prettier-config/**/*

# endregion Rules

# region Templates

.prettier_template:
  extends:
    - .node_template
    - .low_resources_runner_template
  stage: unit
  needs: []
  script:
    - pnpm prettier

# endregion Templates

```

**Output:**

```yaml
# region Rules

.prettier_config_rule:
  having_changes_in_package:
    changes:
      - packages/prettier-config/**/*

# endregion Rules

# region Templates

.prettier_template:
  extends:
    - .node_template
    - .low_resources_runner_template
  stage: unit
  needs: []
  script:
    - pnpm prettier
# endregion Templates

```

**Expected behavior:**

The new line before "# endregion Templates" should be preserved like it is done for "# endregion Rules" but it isn't.
