### ISSUE TITLE
Bug: YAML comment on array items, only first item gets dedented

### ISSUE THREAD

**Issue by thernstig** [prettier/prettier#15733]
**Prettier 2.8.3**

**Input:**

```yaml
properties:
    # Test 1
  - test1: test1
    # Test 2
  - test2: test2
    # Test 3
  - test3: test3
```

**Output:**

```yaml
properties:
  # Test 1
  - test1: test1
    # Test 2
  - test2: test2
    # Test 3
  - test3: test3
```

**Expected behavior:**

```yaml
properties:
    # Test 1
  - test1: test1
    # Test 2
  - test2: test2
    # Test 3
  - test3: test3
```
