### ISSUE TITLE
[css]: custom property with comment breaks

### ISSUE THREAD

**Issue by emilbader** [prettier/prettier#15948]
**Prettier 3.2.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALAjAAmAHSpzAWkICMBDMAawHMAnCAVygBMlMSAbBuAbjwOIB5AHJsAllDEwxZDpgD0AKkwjMi+X3xFCggGK62SlfrUb+2sAwDOMCAFtCAB3qO2ANzK0AFEP0BKPABfEAAaEAhHaWgrZFBPegB3AAVPBBiUWQSyAE8YsJJaCko4GABlMjs4ABkJOGQAM1krOHzCqhLSxwoJamQYWm4w5rsxPoGWkDgAD0c4WjFK2FkAFTmoTzE4dMaOZqGejjgARQYIeAamiYArKynSg+PT86QdvZAARye4JJd0kDIrIQoHA4MxQaEQP0yGIOD0AML2OxkZD-DgcCFWB4AQRg-TEJAY8CScxqwIuuwmqBgdg4AHVUFItl0wHBSmkpGI3FJsiiwFY8iA3NwAJIsBBlMDzSJYlilGDZQ7kt7OCDNWmFRwo5xbOZuOphCTNWgwH5kahIpUTLq0I28-kQ5wSGC0sTMGCoZAADgADGFaHBPmJ-abzciXpcwjAyCQXW6PUgAExhaxwZbR7YRyZ2EigsHMKpkKDUBhmuC6CC0JG4noosiEiAgQKBIA)

```sh
--parser css
```

**Input:**

```css
h1 {
  --background: blue;
  --ON: initial /* ON */;
  --OFF: /* OFF */;
  --custom-prop: var(--OFF)
}
```

**Output:**

```css
h1 {
  --background: blue;
  --ON: initial /* ON */;
  --OFF:  /* OFF *;
  --custom-prop: var(--OFF);
}

```

**Expected output:**

```css
h1 {
  --background: blue;
  --ON: initial /* ON */;
  --OFF: /* OFF */;
  --custom-prop: var(--OFF);
}
```

**Why?**
In this case, the custom property without a value is indented to a point where the ending slash (of the --OFF property comment) gets removed and opens up the comment, essentially commenting out the following code.

**Comment by FilipRazek** [comment]
This seems to be an issue with the underlying css parser, which should probably warn when an empty property is passed.
This code is sufficient to break formatting:
```css
h1 {
  property: /* */;
}
```
