### ISSUE TITLE
Invalid CSS from comments in empty values

### ISSUE THREAD

**Issue by jacobrask** [prettier/prettier#15950]
**Prettier 3.2.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHShxwFoT4BnGJHAegCocAVOKne2gbkONQEMwAawDmAJwgBXKBhoB3ABYBLeNygBfEABoQEAA4xF0CslB9R42QAUzCYyj4AbWXyzHtqUQMFwYAZT4AtnAAMopQcMgAZo4UcO6eQj6+ugJhwsgwohJxILEBihlZOXAAHrpwoopBsI4solBmiqxRMTkUaQ5wAIoSEPAtDrHaAFYUJb4d3b39SNGDOQCO03CW4rp2IHwUJOFwGHtaIJl8ig5pAMIQAQF8yJsODoftUMKdAIIwmYqoEvCWFaFwgMhiB5DAAg4AOpKSgpMBwXy2ZSKABuyiwdzAFDcIBR2QAktIEH4wJV9G9pL4YFhOsCcrpxLFIZ5dHcGawKiiItowrFRDBVnxhDc6doUqI+ZjsYcGWEYJDFBgYPJkAAOAAM2lEcCWim1guFt1mrW0MD4qAVSpVSAATNoJLEmOa7HMQXAAqg9vsMME+C8JEK4AAxCCiG6fNJ3Pi-CAgNRqIA)

```sh
--parser css
```

**Input:**

```css
body {
  --test: /* Test */;
  background: white;
}
```

**Output:**

```css
body {
  --test:  /* Test *;
  background: white;
}

```

**Expected output:**

```css
body {
  --test: /* Test */;
  background: white;
}
```

**Why?**

Prettier produces invalid CSS if there's a comment in an empty property value.
