### ISSUE TITLE
New lines inserted before empty list/dict when followed by a comment

### ISSUE THREAD

**Issue by BapRx** [prettier/prettier#16074]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBbAngEQEswYkACYAXyzLIGIy4APAQ2wAcAbOAaTlwCM5AG4tOAVzg16jVh259cAJhFjJWLHgAyhAM6kyAbQC60hqjJQ2ccszZcpUWg1qiJN2fe5YQAGhAQ7DCE0LrIoCwATpEQAO4AClEIYShisSy4Yf4ARpEsYADWcDAAytY6UHDIAGZiunA5eYXFJez5hFAA5sgwkZL+9diEPX0NIMzscJGE2AgwYgAqU1bTcCm1nPUDHZ3cAIriEPA1dWMAVrpMJTv7h8dIG1sgAI53cPEx7CkgLLqolXAACZAvwgXosQicHYAYQg2GwLGQP04nFBuhucAAgjBeoRsuJ4PEphUqg9Tv4ABYwbCcADqFMI8F0bTAcBKyUZhGEjNwSLAuiyIGEkgAklBgbASmBpkFMeKSjBcNwTpsxuwYvVaXl2Ej1WspsIqv4OvVIjAPixOgiVU82pFTUjcGxUf51R0YLTCICYBTkAAOAAM-kicFehBDFqtiLJqv882ynu9vqQSn84nqCxY2XW5PG2GyQOBgK0LC64ktcAAYhBIgicTskSwCRAQJRKEA)

**Input:**

```yaml
---
myDict: {}
  # exampleKey1: value
  # exampleKey2: value

myList: []
  # - name: example
  #   value: example
```

**Output:**

```yaml
---
myDict:
  {}
  # exampleKey1: value
  # exampleKey2: value

myList:
  []
  # - name: example
  #   value: example
```

**Expected output:**

```yaml
---
myDict: {}
  # exampleKey1: value
  # exampleKey2: value

myList: []
  # - name: example
  #   value: example
```

**Why?**

When providing a commented example of what's expected under a given key, the formatting gets messed up with a new line inserted before the empty list/dict. The new line is removed if we delete the comment.

I wasn't able to find what's causing this and didn't find any other open issue regarding this behavior.

This code structure is widely used by the Helm community (eg: [prometheus-community](https://github.com/prometheus-community/helm-charts/blob/e4588e35952ebccedd028bcdcdc7dacf4720ba91/charts/kube-prometheus-stack/values.yaml#L27-L29), [traefik](https://github.com/traefik/traefik-helm-chart/blob/1f042ea9a0d354ebc00707bfd4e4f534a2a41859/traefik/values.yaml#L79-L102), [grafana](https://github.com/grafana/helm-charts/blob/06500b7ed7ff1c281f083139e55d595f985c17a2/charts/grafana/values.yaml#L268-L294), etc.)
