### ISSUE TITLE
[CSS] Remove extra indent for multiline `:where`, `:is` and `:not` selectors

### ISSUE THREAD

**Issue by GrimLink** [prettier/prettier#16165]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZB3AFnATnAFASygAcBXGJKCGXAbRgE8i4BeAHRACMyZp2BdADQACOoxbscAZzgx+w0UzYhJJDgFt8skHwCUw+AA8YAQxzHh0gDZwwMHUOCsorGAHoAVEIDCAZR9DMHCF3VycAXxABEAgiGHxoSWRQUywIVAAFUwRElGNLVGN6RKiOLGMwAGsZH2M1OAAZQjhkADM86RKyyuqicsIAc2QYLBI4KOkNIZGxkDgDJix8Otg8gBVsKFN8OBy2yw7lAesARRIqZqQ9g4ArSQMfI7hT89b2mYBHM-h01KIckGMkgAtFA4HAACYQyIgYbGfCWAZeCBqNTGZAAyyWaGSR4AQRgw3wXG+2EaoNe+xm6BgaksAHV0Jodr0wHAfNlNPgAG6aejosCSYogLmjACSUEhsB8YEWsVxEp8DGsFIORFS0jpZSI6LVO2wXOaUUI0iwMB+xn6qJVM16WBN-MF0LVhBgdPw4Jg6GQAA4AAxRHCffA4c2WtGXN5REwcN0er1IAAsURI0lWxg4u0jszUHAhkPB9WMUH6JAtcAAYhAsKiCQN0cYyBAQGEwkA)

```sh
--parser css
--tab-width 4
```

**Input:**

```css
:where(input:not([type="button"], [type="reset"], [type="submit"]), textarea, select) {
    /* CSS here */
}
```

**Output:**

```css
:where(
        input:not([type="button"], [type="reset"], [type="submit"]),
        textarea,
        select
    ) {
    /* CSS here */
}

```

**Expected output:**

```css
:where(
    input:not([type="button"], [type="reset"], [type="submit"]),
    textarea,
    select
) {
    /* CSS here */
}
```

**Why?**

The extra indent added when wrapping, the extra indent should not be needed, it makes more sense to format the `:where`, `:is` and `:not` selectors with a single indentation based on the tab-width as shown in the Expected output
