### ISSUE TITLE
[bug] [yaml] list indent fix can result in invalid yaml or change the meaning of existing yaml

### ISSUE THREAD

**Issue by michaele-blend** [prettier/prettier#16183]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbAlgZxkgOlAWgAIB3dGACzyiNqMigDN0BzAgTwFtUkiAfAEz46dCnFSoIvEhABOqACYgANCAgAHGOmiZkoAIazZEEgAVDCXSn2oS+9rtUAjWfrABrODADK+znAAZdCg4ZEYbTDhnVw8vb3U3YJZkGFkAVyiQSM50FPTMuAAPdThZdH9YGwAVUqhDdDgrcNRI1Uwk1DgARTSIeDCIzIArTELvDu7e-qRm1pAARym4U2N1KxB9TAIQuAVdlRBU-XQMKBYAYQhOTn1kDYkD9rPOgEEYVPQnNPhTUqCQgYtTIUGDcADqFHIjQSYDg3ks5HQADdyOw7mBMI4QEiMgBJKB7WDeMBlTQvAneGDsTqAubqYyRMGudR3emNUpI0KqYKRWQwFb6Fg3WmZBKyXl3dh+VAHenBGBg9AKSjIAAcAAZVLI4It0NqBULbjNBqoYPonIrlRRkAJVGlIlVzU0TSA4JwnLs9goAvozmlBXAAGJyG7vJJ3fTfCAgAC+MaAA)

```sh
--parser yaml
```

**Input:**

```yaml
list:
- with:
    config-yml: |2
      hello: world
```

**Output:**

```yaml
list:
  - with:
      config-yml: |2
      hello: world

```

**Expected output:**

```yaml
list:
  - with:
      config-yml: |2
        hello: world

```

**Why?**

my expectation is that prettier does not change the meaning of a yaml document.
the list indent fix here changes the meaning of the document, the `config-yml` values are promoted, and `with` gains new keys.
this can also result in invalid yaml documents, if the multi-line string is not also valid yaml. for instance,
```yaml
list:
- with:
    config-yml: |2
      hello
```
will be transformed into
```yaml
list:
  - with:
      config-yml: |2
      hello
```
which is not a valid yaml document.
