### ISSUE TITLE
[SCSS] Put unary boolean operator in front of expression when wrapping

### ISSUE THREAD

**Issue by apfelbox** [prettier/prettier#16232]
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgMwAQAoAkAbnAE4CeANtAOZVS010P1OuPssfPeECGJ6XgCMKcGBEwQSYOMJKyA1tl5QAJtny9la7FAgwNQgJTZgAHSjYr2SFRJJs81QG4LAXwsgANCAgAHGHRoAGdkUH4SCAB3AAV+BFCUXgoo3jJQnyESXjAFMQBlXgBbOAAZdCg4ZExk4LhM7NyCvxyK6mQYEgBXepA6ovQO7t64AA8-UnQS2GSAFVIofnQ4RJqKOp9gttEARS79KqQ1jZAAK2DR-O24PYPq2t6AR334GMi-RJBeYIBaSrhVADvCBOrx0BQ2gBhCBFIq8ZBfCgUYFbFhwACCME66CEXVepHKlXu616AAsYEUKAB1UnoeDBFoyfIJOnoQh0sgIsDBDIgQg9ACSagQMHyYAEAXRanyMEoh2OvT8kTqVOyfgRSpWpGIwIqdRIMDevGocOJJxaJH1COC3N5SoqMCp6FUMFJyAAHAAGHzyZ7oeRGk3wo4PHwwYROl1upAAJh8XTqs2Eq1DIDgRSEAMBqlKKmoXWNcAAYlI4Vi2gjeHiICA3G4gA)

```sh
--parser scss
```

**Input:**

```scss
@if ($verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak and $a and not $b) {
    color: red;
}

```

**Output:**

```scss
@if (
  $verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak and
    $a and not
    $b
) {
  color: red;
}

```

**Expected behavior:**

```scss
@if (
  $verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak and
    $a and
    not $b
) {
  color: red;
}
```

Hi,

It is pretty confusing, that the unary `not` is placed in the line above instead of in front of the expression it is affecting.
That makes it really hard to read long `if` statements with multiple terms correctly.

**Comment by apfelbox** [comment]
Actually, looking deeper into it, the whole segmentation of the CNF seems pretty chopped up:


**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgDMAbAV0wBMBaABwCcIaAKAEnsbjpgE8AafFlihUAbgHd+ggIbZREgUNFSycSehlKVASnzAAOlD0xUmQgPY1OPfAEIAvPiilixXQaNGTZnpaoRCrIoiyqRwOnYOAORO6ABGnJH4UlAUjhAw+KRQmDDEcADO+YF4mqE6+oYwHjAAxMBsDJZc3AC+SAolwSoA3PgA9H34AGLKxLFSYADWRBB0+BDEFJz4sQxi+Zz57lUwLduepvg+cH4Bgp1i4VEx8XSJyalQ6ZnZuQVF58JdZUkpR9y+fyBDTiK74aKkOIJX6PZ5ZHJ5QrFL4hMIw-6As5BVFgiFQu7op4ZeFvJGfUpoh4Yk5A6Syb5oiLgm7QqlEl4I97Iik6Kkk7mg-BM-l0uS8v4ioKXIUOSWdHHouVfaXC17A+kKirVIwsQgTGCzdrqGAACwAdBRMCImABGNQgsT4KgdZU6ABU+HVFKdLp53X2OxYYGUYAp7SyAEdSOk4Ew9CA6r6GT6BY6Pbr9bMdC18ABqfCJm0ABiL4nw6b1YANcz2IC0-sMlWqdQaHGabXwYGIUnQzETpgFqPwAD4FCDUfaNSo1PLtPgWvxE0GQ96FwXgPgB+Tk6PRQyZyjp2Opz8WvWA3tKpeWiBeCBGDBMNB8shQFI6GsAArvhAvlDKMQpG4F871WCZJjgGAAGUezgAAZPA4GQPViA2UC6HAyCoJoCY8AAc2QGA6FCO8NiwQjiNUEA4GwJpMHQBAYGUAAVTgoHfTACmQ5Q0JAfJ8LyABFaN4G41CqIAK3ybAoIEuBhJjMTeKjGNP0aP8QCkfIqCgOA4CWChbxAIipEwYh8IAYQgdB1GQTSXCM-ioDwvIAEEYCIzBYlIeBP04BDdKUqiTRgdBiAAdRNHIChwsA4Cg38citHJuDssBCiMkRQgASRSRioLAOhMBoGBXJSKCeDyIK73YDZwowmg7PoApOBEJC7zwDYuDUqQ8NspAUN4nC6C6uz8nSkCQHoPAYHCyhTWQAAOIs7zoOAo0wNaer6qRquMqRYjmigFqQAAmO9SA2ZiDr-QaqLgKEKAMuDkjw0hergIZZmNR9nLsqQfIgEAWhaIA)

```sh
--parser scss
```

**Input:**

```scss
@mixin fluid-prop($property, $min-vw, $max-vw, $min-value, $max-value) {
	@if $property != null {
		@if type-of($min-value) == 'number' and not unitless($min-value) {
			#{$property}: $min-value; // Fallback for older browsers
		}
		@if type-of($min-vw) == 'number' and not unitless($min-value) and type-of($max-vw) == 'number' and not unitless($min-value) and type-of($min-value) == 'number' and not unitless($min-value) and type-of($max-value) == 'number' and not unitless($min-value) and unit($min-vw) == unit($max-vw) and unit($min-vw) == unit($min-value) and unit($min-vw) == unit($max-value) {
			$factor: math.div(1, $max-vw - $min-vw) * ($max-value - $min-value);
			$calc-value: unquote("#{ $min-value - ($min-vw * $factor) } + #{ 100vw * $factor }");

			#{$property}: clamp(#{ if($min-value > $max-value, $max-value, $min-value) }, #{ $calc-value }, #{ if($min-value > $max-value, $min-value, $max-value) });
		}
	}
}
```

**Output:**

```scss
@mixin fluid-prop($property, $min-vw, $max-vw, $min-value, $max-value) {
  @if $property != null {
    @if type-of($min-value) == "number" and not unitless($min-value) {
      #{$property}: $min-value; // Fallback for older browsers
    }
    @if type-of($min-vw) ==
      "number" and not
      unitless($min-value) and
      type-of($max-vw) ==
      "number" and not
      unitless($min-value) and
      type-of($min-value) ==
      "number" and not
      unitless($min-value) and
      type-of($max-value) ==
      "number" and not
      unitless($min-value) and
      unit($min-vw) ==
      unit($max-vw) and
      unit($min-vw) ==
      unit($min-value) and
      unit($min-vw) ==
      unit($max-value)
    {
      $factor: math.div(1, $max-vw - $min-vw) * ($max-value - $min-value);
      $calc-value: unquote(
        "#{ $min-value - ($min-vw * $factor) } + #{ 100vw * $factor }"
      );

      #{$property}: clamp(
        #{if($min-value > $max-value, $max-value, $min-value)},
        #{$calc-value},
        #{if($min-value > $max-value, $min-value, $max-value)}
      );
    }
  }
}

```

**Expected output:**

```scss
/* ... */
@if type-of($min-vw) == "number" and 
      not unitless($min-value) and
      type-of($max-vw) == "number" and 
      not unitless($min-value) and
      type-of($min-value) == "number" and 
      not unitless($min-value) and
      type-of($max-value) == "number" and 
      not unitless($min-value) and
      unit($min-vw) == unit($max-vw) and
      unit($min-vw) == unit($min-value) and
      unit($min-vw) == unit($max-value)
    {
/* ... */
```

**Why?**


This seems like a canonical way to write  a conjunctive normal form, as every boolean segment is in one line, including their identity check or unary operators.

**Comment by guilhermetod** [comment]
Given #3806 is also highly requested, i suggest going for another strategy:

```scss
@if (
  $verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak
    and $a
    and not $b
) {
  color: red;
}
```

**Comment by apfelbox** [comment]
@guilhermetod I would like your proposal even more. 👍

**Comment by g-plane** [comment]
Would you like to give a try to [Malva](https://github.com/g-plane/malva) (another CSS formatter)? It supports both @apfelbox 's and @guilhermetod 's suggestions with configuration.

### Input

```css
@if ($verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak and $a and not $b) {
    color: red;
}
```

### When `operatorLinebreak` is `"after"`

It formats as @apfelbox suggests.

```css
@if (
  $verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak and
    $a and
    not $b
) {
  color: red;
}
```

[playground](https://malva-play.vercel.app/?code=H4sIAAAAAAAAA3PITFPQUClLLarMyc9LJweXJRZlJiblpJbkp%2BUXJacmJhWlJmYrJOalKKgkgqm8%2FBIFlSRNhWouBSBIzs%2FJL7JSKEpNseaq5QIAr0TroH8AAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyi9ILUosyS%2FyycxLTSpKTcxWslJQSkwrSS1S4qoFAKcZSFsiAAAA&syntax=scss)

### When `operatorLinebreak` is `"before"`

It formats as @guilhermetod suggests.

```css
@if (
  $verylonglonglonglonglonglonglonglonglonglonglonglonglonglongvariabletoforceabreak
    and $a
    and not $b
) {
  color: red;
}
```

[playground](https://malva-play.vercel.app/?code=H4sIAAAAAAAAA3PITFPQUClLLarMyc9LJweXJRZlJiblpJbkp%2BUXJacmJhWlJmYrJOalKKgkgqm8%2FBIFlSRNhWouBSBIzs%2FJL7JSKEpNseaq5QIAr0TroH8AAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyi9ILUosyS%2FyycxLTSpKTcxWslJQSkpNyy9KVeKqBQAUkWQCIwAAAA%3D%3D&syntax=scss)

### Complex input

It also works with https://github.com/prettier/prettier/issues/16232#issuecomment-2076573224 . Result:

```css
@mixin fluid-prop($property, $min-vw, $max-vw, $min-value, $max-value) {
  @if $property != null {
    @if type-of($min-value) == "number" and not unitless($min-value) {
      #{$property}: $min-value; // Fallback for older browsers
    }
    @if type-of($min-vw) == "number" and not unitless($min-value) and
      type-of($max-vw) == "number" and
      not unitless($min-value) and
      type-of($min-value) == "number" and
      not unitless($min-value) and
      type-of($max-value) == "number" and
      not unitless($min-value) and
      unit($min-vw) == unit($max-vw) and
      unit($min-vw) == unit($min-value) and
      unit($min-vw) == unit($max-value) {
      $factor: math.div(1, $max-vw - $min-vw) * ($max-value - $min-value);
      $calc-value: unquote(
        "#{$min-value - ($min-vw * $factor)} + #{100vw * $factor}"
      );

      #{$property}: clamp(
        #{if($min-value > $max-value, $max-value, $min-value)},
        #{$calc-value},
        #{if($min-value > $max-value, $min-value, $max-value)}
      );
    }
  }
}
```

[playground](https://malva-play.vercel.app/?code=H4sIAAAAAAAAA51TXW%2BCMBR91l9xpiTCJlNfNSw%2B7X9UKFmz0rJSREP639cyxDqN2XwhN%2Bfcc%2B5HL9uCHZhAzmuWxaWSZRi4L1X6OEdQMBHvGxeQQx84hPCankAXR2jHoy3LMWjxlEDUnDuiY%2FSxpLHMw7NBhCTBTNTFjqoZiMggpEYtmOa0qi4Snclo2g7uZu01ssFigXfC%2BY6kn8ilguQZVdgp2VRUVVZrbjbR%2FKMDR57V3TIeVj%2BwgOvyDxg44mL0HuinuZfydyPvwYKcpFqqNQqiP14ztg9XwyUhxmDwDE87EJ3RpvNJCU9%2FgLUt9VVLTcPJtPUSrerUkLXrC0cweIHNWy2XPg4zscbXJ5VyUpShzWf%2BK%2BHNO%2FT5r%2Fi8FzN3lbxWe%2BS%2B1%2B2fyXRz26M1Y%2FMN0RmCWKADAAA%3D&config=H4sIAAAAAAAAA6vmUlBQyi9ILUosyS%2FyycxLTSpKTcxWslJQSkwrSS1S4qoFAKcZSFsiAAAA&syntax=scss)
