### ISSUE TITLE
Less variable name been lowercased incorrectly

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#16409]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZhCAhAhmAawHMAnCAVygBMkAbASyjgFpTcr6EYAKAYnQAMAgJQBuADpRJuAATBJMmQCN8xMpRoyMWPIVIVqEqAF8QAGhAQADjHrQAzslC4SZAO4AFFwkcpctN1wAT0cLJRJVOBgAZVwAWzgAGUY4ZHR-ezgwiMIo6Kt8RiJkGBJyLJBMuPoSsoq4AA8rOBJ6BNh-ABUWqBdOX3TaTIt7Ito4AEVyCHg0jIqAK3sG6LHJ6dmkQeGQAEcNuA8yK18QXHtmJjgqa-MQUtx6BigiAGEIOLjcZDPaWjvRi9xgBBGClehKcjwDwtZJMOZDCoACxgcVoAHUkfR4PYCmA4NEfNj6AA3bFBH5geyhEAk8oASWoXGiYFaNmB1GiMCC4wROysZEy6IiVh+ArgmRIJNSFkYkpgR1wRC+fIqBRIkp+42pdwFjBg6PoVBgSOQAA4BBYSHB9vRrYrld8tvMLDBcEpDcbTUgAEwWciZTrugYukBwOJKa43KiJXAvchKuAAMQgJC+YKKP1wUIgIGMxiAA)

```sh
--parser less
```

**Input:**

```less
@fooBackground:line-gradient(#f00);

a {
  background: @fooBackground;
}
```

**Output:**

```less
@foobackground:line-gradient (#f00);

a {
  background: @fooBackground;
}

```

**Expected output:**

```less
@fooBackground: line-gradient(#f00);

a {
  background: @fooBackground;
}
```

**Why?**

The code is not correctly parsed, it I add space after `:`, it work as expected, but it's valid Less code without space. [Less playground](https://lesscss.org/less-preview/#eyJjb2RlIjoiQGZvb0JhY2tncm91bmQ6bGluZS1ncmFkaWVudCgjZjAwKTtcblxuYSB7XG4gIGJhY2tncm91bmQ6IEBmb29CYWNrZ3JvdW5kO1xufSIsImFjdGl2ZVZlcnNpb24iOiI0LjIuMCIsIm1hdGgiOiJwYXJlbnMtZGl2aXNpb24iLCJzdHJpY3RVbml0cyI6ZmFsc2V9)
