### ISSUE TITLE
wrong indent in less function "each"

### ISSUE THREAD

**Issue by zzxming** [prettier/prettier#16433]
**Prettier 3.3.2**
**Less 4.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcCGYAWAKATmqAczmwCYBKAGgAJgAdKa6gOkgBsBaAAWADc02AVzgBfWgyaSp1THACWhTDCTVsXfkLjUAVNQCsABgAOAD3IBuCdKYiGIiyEogIRmHOgBnZKDS5cEAHcABV8ELxQBALQATy8nACN8MABrOBgAZTQAWzgAGTkoOGQAMwEPOASk1IyjDALCZBhcYSdyrLlG5orUEyM4XDkc2AEAFX6oXzk4cNK2ctb6tjgARUEIeBKy7oArDxN0xZW1jaRZ+ZAAR2O4IP8jcJA0Dw5CuAATd8cQJrQ5NnqAMIQLJZNDIR5sNhfDyHACCMCacnigngQX6+UKmzm3SUWTYAHVMHJ4B5amA4OkwsS5LxidFwWAPHEQLxhABJKAfWDpMADVywznpGDRJZY85GfzlfH4IzgiXTfq8IpOArlXAwW5oQigsXdWq4NXgpZMr4SgowfFyN4wTDIAAcBicuDgVzkzs12rBpy2ThgaHiluttqQpCcgnKI39Mx9qCy8XeHzeuQIhEEWrgADEILhQQj6uC0CiICARCIgA)

```sh
# Options (if any):
--single-quote
```

**Input:**
```less
each(range(2), {
  .col-@{value} {
          height: (@value * 50px);
        }
});
```

**Output:**

```less
each(range(2), {
  .col-@{value} {
          height: (@value * 50px);
        }
});
```

**Expected output:**

```less
each(range(2), {
  .col-@{value} {
    height: (@value * 50px);
  }
});
```

**Why?**

Incorrect code formatting. It cannot format indentation correctly. but it works for normal code.
