### ISSUE TITLE
CSS: Inconsistant break for comma seperated value

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#16485]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhgAmAHSpzAI3TAGsBzAJwgFcoATAWgEsBbdcuJTGygGwAUACxgwADgGckAemlwAHulZi+cVJFbS+0clp16ou7YYNH9bDmrGGAlABo8BAn2ZQ46Soyrp6zBDAEATgAGejhyO0wAYlDg9AAOOExggFJIqIAmAGYARgAzOBzMHODUmwBuPEciCHlGCSEfCAB3JGqCVwk4GGTekrF5aIBWEYd8J2DejOCBoj4SUkqoAF88EDsQCDEYZmgJZFAPamaABQ8EfZR0Pmb0AE99jcJKBe6AZSU4ABlXOGQ865dJ4vMjvMQkVzkZAwSg0OAbLqsZjQ2HwkAKMRwShsfzXAAqWKgHj8lwBfCBIAkkNUAEUaBB4P9AWiAFYSeRvalwOkMv5IMkUgCO9PgJ2okmQIHQEkYbjgYXo6xAMPQzBchgAwhBWOxJdc+EqqYZVABBUTYwg0UVYn5uJnktEiVh8ADqQmY8Ak4LAcDeFw9zAAbh67pKwBJHiBA3CAJIMfxvMDY7YmhhvGB3VT2iliahdF0vMSS3NwLqUQN-DadLEwMUcXX85kbcGUMthiNK3OuGAu5j0GBCZDxYIbShwYXMMd18gNgVomDoQi9-uDpAZDY0Lp4xekpvo1iEeUKr7oQw0SwAMQglHYokheqtEBAy2WQA)

```sh
--parser css
```

**Input:**

```css
.a {
  background-image: url(https://example.com/long/long/long/long/long/long/image.png),
    linear-gradient(90deg, #0d0a8e 0%, #231fe1 100%);

  box-shadow:
    inset 0 0 10px #555,
    0 0 20px black;
}

```

**Output:**

```css
.a {
  background-image: url(https://example.com/long/long/long/long/long/long/image.png),
    linear-gradient(90deg, #0d0a8e 0%, #231fe1 100%);

  box-shadow:
    inset 0 0 10px #555,
    0 0 20px black;
}

```

**Expected output:**

```css
.a {
  background-image:
    url(https://example.com/long/long/long/long/long/long/image.png),
    linear-gradient(90deg, #0d0a8e 0%, #231fe1 100%);

  box-shadow:
    inset 0 0 10px #555,
    0 0 20px black;
}
```

**Why?**

Prettier
