### ISSUE TITLE
Applying flow style to the elements of the YAML sequence when there is enough width

### ISSUE THREAD

**Issue by mineco13** [prettier/prettier#16773]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDADgSwGpwE4DOm0SABAG4CMAOlANaZQAmZAyvuZmHLQLZwxUTVIKS1SpKKn5leATwC0BDlx5QC6OGDFQJ6CHhgEdEhaXR4IMCJAA2ZACoBhAAriJ5gzDKUADP993CUE8AHMBFy8yACYAwN1SMwsrGwh7Umc3BL0o0j9-GmzSEPCYSMMYgMLTc0trO0dXIM8KvIDo5pKI3Nj-DoSkutT0zOb9VvzfAGZO1DDu1t7p90GUhoymovHvNv8AFln5sp6Ag4HatbTGrI8WncmAVkPS8p2lp-Pk+quNm49tnwBABszwWb2BtBAABoQBB0DBiOpkKA5pYAO4uOYIAjINC2NGoOQ4mEAIzwqDAdAErGkcAAMow4MgAGaoWzKUnkynU9AUxihZAwPAAVzgMOUvEwgpFYpAcAAHpo8Jh+LA2Q58FJlXAcUhWezZUQoKFbHAAIrCqxMvVsjkgABWBHlrH5potVpZttlAEdLfAXJZ0Lq0AQFFA4HAmJHoSAhahMLZ+U4ILxeKhcWzbDGjSa4ABBGBCzAk4X+-AM8Oeg0wgAWMF4tgA6jXMPANBS4Ox1K3MJwYHJcWACMSQORRQBJZgIGCsMDK+F55isfumqt25LKRvk9C4iw6jhMmGMZSGAOoUJptey3mEfC4uTSLMwiyMGCNzBMGA15AADl8MLwOBfUwQCzwvdMbWrWNUBJd9P2-JBohhYVlAcGDdX1O04F4ElIyjJg6VQY1hXPOAADEDDTQt+QzUsIBAABfBigA)

```sh
--parser yaml
```

**Input:**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - protocol: TCP
    port: 10000
    targetPort: 20000
  - protocol: TCP
    port: 10001
    targetPort: 20001
  - protocol: TCP
    port: 10002
    targetPort: 20002
  - protocol: TCP
    port: 10003
    targetPort: 20003
  - protocol: TCP
    port: 10004
    targetPort: 20004
  - protocol: TCP
    port: 10005
    targetPort: 20005
  - protocol: TCP
    port: 10006
    targetPort: 20006

```

**Output:**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
    - protocol: TCP
      port: 10000
      targetPort: 20000
    - protocol: TCP
      port: 10001
      targetPort: 20001
    - protocol: TCP
      port: 10002
      targetPort: 20002
    - protocol: TCP
      port: 10003
      targetPort: 20003
    - protocol: TCP
      port: 10004
      targetPort: 20004
    - protocol: TCP
      port: 10005
      targetPort: 20005
    - protocol: TCP
      port: 10006
      targetPort: 20006

```

**Expected output:**

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  ports:
  - {protocol: TCP, port: 10000, targetPort: 20000}
  - {protocol: TCP, port: 10001, targetPort: 20001}
  - {protocol: TCP, port: 10002, targetPort: 20002}
  - {protocol: TCP, port: 10003, targetPort: 20003}
  - {protocol: TCP, port: 10004, targetPort: 20004}
  - {protocol: TCP, port: 10005, targetPort: 20005}
  - {protocol: TCP, port: 10006, targetPort: 20006}

```

**Why?**
In sequences, similar structures are often repeated.
When there are sufficiently few keys for the elements, a compact flow-style format on a single line can reduce the amount of scrolling, making it easier to compare elements and potentially improving visibility.
