### ISSUE TITLE
Prettier does not preserve CSS property casing

### ISSUE THREAD

**Issue by lts20050703** [prettier/prettier#16772]
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABADgGwK4HMCWUABADogAmAhvgM4Ce2+A9DABZwC2cZRwJUJGFEpckpCpQBOAazIBufoPSS4AMziSaAESnSxMSdjgKoAXxAAaEBHQx80GslBTJEAO4AFKQkcpKmN0o6RysAI0lKMGk4GABlETgAGUI4ZFV-GjgwiKiY2PRIwlxkAyMrTI58EsMskDgAD3QNfC5YfwAVDWFJfDhfdMxM8qLMOABFbAh4NIzagCsaetiR8cnppAGhkABHNbgPV3RfEEoaAFooODhya8sQA2pMIoBhCA4OSmQTzEw7mhWAIIwAz4ULYeAeDTJS4zQa1VgwDiYADqrHw8BoBTAcFiPnR+AAbui6F8wDQQiACUYAJJQG6wWJgHq2AF02IwOijWFbZQQTLIiLoL7KPoaAmpKyETKSGAHSi4D7c2oFTQaUnku7KQgwZH4chsZAADgADFYVLt8Co5QrPhtZlYYJRQrr9axkAAmKzYTLtJ39e11Diha43ciJShQXDYeVwABiEEkH2BRS+lHBEBAplMQA)

```sh
--parser css
```

**Input:**

```css
@plugin "daisyui/theme" {
	name: "dark";
	prefersDark: true;
}
```

**Output:**

```css
@plugin "daisyui/theme" {
  name: "dark";
  prefersdark: true;
}

```

**Expected output:**

```css
@plugin "daisyui/theme" {
	name: "dark";
	prefersDark: true;
}

```

**Why?**

The upcoming version of DaisyUI (v5) now involve writing configurations in the CSS file. Some property is in camelCase and the casing needs to be preserved, otherwise it wouldn't work.
