### ISSUE TITLE
[CSS] Remove extra indent for multiline :has selectors

### ISSUE THREAD

**Issue by ulrichstark** [prettier/prettier#16895]
**Prettier 3.4.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbAlkgFgQwM4AUAOlAASkAOOMWA2gCYC8RIAsgKwAsnANAEwB2PgAlOADgAMANQCM7CQDoAbIIAy7PgGYFmmbxkSBOvQEEZSnuZ4Trt+YqViLYzsrEDVndkc0DNlvjFRORwZQQUJCU0xGQCjSOjYmySAWj4ua2EZGTFlNQF2Y14XNwEzCytkuz43CsMi1QBOCvk8gSlBEU0+UIqLGwHbbuFmgDc+TlCBV0axMXYK6YVZ+f7bG01FcV5ZhTnG1UdSnm3a0MLGy6FLC6u+WyT+GpUBJ7bUdkKlcxTP5XMzAUFF5zOxLECQUowYMbJ0ePJOFhulNCpCwTIIexQesHukIgJfjVNpoPl8rH9vkpzss7jcaY1rjC3i80s9BKhfkYBAzOQpuWUMTM5gtwULVjibOINoEpJtEUpJlZKhKUt0AFqsQJiHjdCJhJSaEyNW4LbXGmmmnGxaL+MJBGSNQ3my6W53GxxW-hzHU1CT6zQa7ja7piMA2bnAv0pBUKdizSzcFJ6fTcDqaKlhCKRDQBLMSHMwpN8ItYFJiUK+7P3TORfP3QthAJSThCMApCOcCT1pOJmNxxo9ziD2RKCSicRqlgAXRIAEpSMASOR6Og8BRUDgAJ5IUhQaBwADcJAAviAeCAIBQYOhoHhkKAcAAnR8QADuAAUnwg7ygcKhX1ud7ngARo+OBgAA1nAMAAMo4AAtnAqjoFAcDIAAZn+eBwCBYGQdBMFUGAKEAObIDAj4AK44SA2Hweg5FUTRcAAB4UHAj7oIhsB-gAKhxUBPugcA-phqDYeeeCkagcAAIqURA8AYVhNEAFZ4CxMHSXJClKUgYkSSAACOulwO+L4UD+ID4CkqFwPQ9lniAFE4OgGBQCRADCEDwfBODINZqCoE5UkeTJJgwBR6DAZR8DvhxyGocp4k0VgMDwagADqWDoPAa7gXAMHfrl6CjLlm4BWAeBASAozUQAklADmwDBYCcVeJhNTBMCbjJyWGRQL7YZlYEUAFg0iRxoxoeeKHYY+MDmTgJF+f1NFUI+82VdVTmDShMCZeg9A0Mgcg2CAj5wCZ6CXUtK3+fpKnnjAODAYdx1YMg9wgJR2G8a9olPSAcDwcB9kOfQqg4B5lHLXAABiECPn5kWkQFOCxRAIDHseQA)

```sh
--parser css
--print-width 150
```

**Input:**

```css
li:has(
  path[d="M544,272H480V150.627L523.314,107.314A16,16,0,0,0,500.686,84.687L457.373,128H415a127.00381,127.00381,0,1,0-254,0H118.627L75.314,84.687A16,16,0,1,0,52.686,107.314L96,150.627V272H32a16,16,0,0,0,0,32H96v24a174.98856,174.98856,0,0,0,30.484,98.889L68.687,484.686a15.99972,15.99972,0,1,0,22.627,22.627l55.616-55.616A175.45165,175.45165,0,0,0,272,504h32a175.45165,175.45165,0,0,0,125.07-52.303l55.616,55.616a15.99972,15.99972,0,0,0,22.627-22.627l-57.797-57.797A174.98856,174.98856,0,0,0,480,328V304h64a16,16,0,0,0,0-32ZM288,32.01263A95.99568,95.99568,0,0,1,383,128H193A95.99568,95.99568,0,0,1,288,32.01263ZM448,328c0,79.401-64.598,144-144,144V236a12.00052,12.00052,0,0,0-12-12h-8a12.00052,12.00052,0,0,0-12,12V472c-79.402,0-144-64.599-144-144V160H448Z"]
) {
  display: none;
}
```

**Output:**

```css
li:has(
    path[d="M544,272H480V150.627L523.314,107.314A16,16,0,0,0,500.686,84.687L457.373,128H415a127.00381,127.00381,0,1,0-254,0H118.627L75.314,84.687A16,16,0,1,0,52.686,107.314L96,150.627V272H32a16,16,0,0,0,0,32H96v24a174.98856,174.98856,0,0,0,30.484,98.889L68.687,484.686a15.99972,15.99972,0,1,0,22.627,22.627l55.616-55.616A175.45165,175.45165,0,0,0,272,504h32a175.45165,175.45165,0,0,0,125.07-52.303l55.616,55.616a15.99972,15.99972,0,0,0,22.627-22.627l-57.797-57.797A174.98856,174.98856,0,0,0,480,328V304h64a16,16,0,0,0,0-32ZM288,32.01263A95.99568,95.99568,0,0,1,383,128H193A95.99568,95.99568,0,0,1,288,32.01263ZM448,328c0,79.401-64.598,144-144,144V236a12.00052,12.00052,0,0,0-12-12h-8a12.00052,12.00052,0,0,0-12,12V472c-79.402,0-144-64.599-144-144V160H448Z"]
  ) {
  display: none;
}

```

**Expected output:**

```css
li:has(
  path[d="M544,272H480V150.627L523.314,107.314A16,16,0,0,0,500.686,84.687L457.373,128H415a127.00381,127.00381,0,1,0-254,0H118.627L75.314,84.687A16,16,0,1,0,52.686,107.314L96,150.627V272H32a16,16,0,0,0,0,32H96v24a174.98856,174.98856,0,0,0,30.484,98.889L68.687,484.686a15.99972,15.99972,0,1,0,22.627,22.627l55.616-55.616A175.45165,175.45165,0,0,0,272,504h32a175.45165,175.45165,0,0,0,125.07-52.303l55.616,55.616a15.99972,15.99972,0,0,0,22.627-22.627l-57.797-57.797A174.98856,174.98856,0,0,0,480,328V304h64a16,16,0,0,0,0-32ZM288,32.01263A95.99568,95.99568,0,0,1,383,128H193A95.99568,95.99568,0,0,1,288,32.01263ZM448,328c0,79.401-64.598,144-144,144V236a12.00052,12.00052,0,0,0-12-12h-8a12.00052,12.00052,0,0,0-12,12V472c-79.402,0-144-64.599-144-144V160H448Z"]
) {
  display: none;
}
```

**Why?**

Similar issue of already fixed issue https://github.com/prettier/prettier/issues/16165, but seems like the `:has` selector was missed.
