### ISSUE TITLE
Extending default printers [postcss]

### ISSUE THREAD

**Issue by sAs59** [prettier/prettier#17035]
**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAQAcAnOGGASzlJ31RxwDoBbCAIyoBs4B5KNwCeuYPVzEIAZyrVoSXAEMOUiNwCu8ANziqUKRQUBGAAzEAHjrxE9YDQBM4uVnHtVFACnG4Ji+26gAcwBaDghKCFZcACYLXG5FYhgIYlwAH1wTXBhlXhhggBpvXDcpYgSRDm4IMABrZ04eJwyoaCccqooAaiLrH1ZFUkC9YOTUowA2OPYuXnEASisAXxACkBS5fWRQQdIIAHcABUGEKWQQRW59xSEztY5SRTqKAGVFFwAZPThkADNLgz3R7PGAvYhPPSBZAwUjqOBrAysKjQ2HwkBwczEWhUFywS4AFVoUEGNDOSH+3EBIBkQV4AEV1OEfuSAWiAFZScwvSH0xnwP6stYARz5cEOe2IZIuUmCUDgrlcqxAMMUPEhAGFIgNzpduEqaYFeABBSikKgcTRi2hfOUCylogAWMFY3AA6g7ZHAyk84C9TrIqAA3WRCc5gKR3ECBuEASSgjlgLzAZqSRvjLxgQl4dqpZGkcFdj2I5zIXtogZ+az0BlIMHFikC2pZ9rW4NINbDEaVZD0MFdVHsMAdyAAHCY1uQRVRyPXG4oc2iOv3B8OkNE1uoDPjlGSKVS4KwOK5HPYPooguoG3AAGIQUgDSiQnWaCAgJZLIA)

```sh
--parser css
```

**Input:**

```css
.mobileOnly {
  position: absolute;
  inset: 10px;
  @include media(
    padding-bottom 2px laptop | 0 tablet-,
    display block mobile | none tablet+,
    margin-top 16px mobile
  );
}
```

**Output:**

```css
.mobileOnly {
  position: absolute;
  inset: 10px;
  @include media(
    padding-bottom 2px laptop | 0 tablet-,
    display block mobile | none tablet +, // <---- w/ blank space
    margin-top 16px mobile
  );
}

```

**Expected output:**

```css
.mobileOnly {
  position: absolute;
  inset: 10px;
  @include media(
    padding-bottom 2px laptop | 0 tablet-,
    display block mobile | none tablet+, // <---- w/o blank space
    margin-top 16px mobile
  );
}
```

**Why?**

The task is to support custom postcss syntax above. My current approach is to write custom plugin which extends the current postcss printer. Following the issue #8195 I came across the code below which outputs error "InvalidDocError: Unexpected doc.type 'undefined'"

```js
const postcss = require('postcss');

const plugin = {
  languages: [
    {
      name: 'CSS',
      parsers: ['css'],
      extensions: ['.css']
    }
  ],
  parsers: {
    css: {
      parse: text => postcss.parse(text),
      astFormat: 'format-media'
    }
  },
  printers: {
    'format-media': {
      print: (path, options, print) => {
        const jsPlugin = options.plugins.find(p => {
          return p.printers && p.printers.postcss;
        });
        const defaultCSSPrint = jsPlugin.printers.postcss; // ! async function
        const node = path.getValue();
        if (
          node.type === 'rule' &&
          node.name === 'include' &&
          node.params.startsWith('media')
        ) {
          // logic to remove extra space
          return; 
        }
        return defaultCSSPrint(path, options, print);
      }
    }
  }
};

module.exports = plugin;
```

What is the correct way of extending default printers with some extra logic?
