### ISSUE TITLE
Tailwind V4 functional utilities formatting error

### ISSUE THREAD

**Issue by andershagbard** [prettier/prettier#17049]
**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABArjAlgGyzATwAIYBDAIwFoAqI4AHSiJIsoGcsAvOJIyygG6kc6OAAp+ZKh240AlAG5GAXxAAaEBAAO2aG2ShSAJyMQA7gAVjCfSmFnSBfRvJHSYANZwYAZVIBbOAAZLCg4ZAAzYTY4FzdPbx8td1CAc2QYI1ENGP8sDKzYkDgADy04IyxA2GEAFQqoYyw4WyicGJy0nDgARXQIeEjoooArNhKfLt7+waQ2jpAARxm4C1MtWxBSNkowuAATA-UQTNJcNIBhCH9-UmQtnBxjjihU7oBBGEysckxVipCYSG7SKAAsYP4cAB1UH4FrJMBwHw2fBYAT4Aj3MBsZwgASiACSUEOsB8YEqOnexJ8hG6wIWWlMMShbi090ZLQqAnCGlCMSMMDWpFSt3pRWSRn5WJxx0ZoRgUKw+xgoOQAA4AAwaIxwZZYHVCkV3ObDDRSRXK1VIABMGnQMVqFFapuK-nIB0O+yCpFe6GFcAAYhAjLcvml7qRMBAQMplEA)

**Input:**

```css
@utility tab-* {
  tab-size: --value(--tab-size-*);
}
```

**Output:**

```css
@utility tab-* {
  tab-size: --value(--tab-size- *);
}
```

**Expected output:**

```css
@utility tab-* {
  tab-size: --value(--tab-size-*);
}
```

**Why?**

Adding a space before the asterisk probably breaks most syntax highlighting.

I am unsure if should be solved in [tailwindlabs/prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss).

Ref: https://tailwindcss.com/docs/adding-custom-styles#functional-utilities
