### ISSUE TITLE
Prettier breaks CSS variables ending in a comma

### ISSUE THREAD

**Issue by adamwathan** [prettier/prettier#17058]
Reproduction:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAWmIFsBPYgNwEMAnJbAS0IgGsAbWgIwBoA3AQC+IPiAgAHGM2gBnZKAb0IAdwAKDBApS1Oq2hQXie9WmHZwYAZVpk4AGVZxk6PXLgmzFq9cnnWAHNkGHoAV08QDzJmEPDIuAAPSTh6ZntYPQAVVKgGZjgdN04PcTkgzjgARTCIeFd3SIArOUTrCura+qRi0pAARy64dRVJHRBaOWIoODgAE3mxEFDaZk4ggGEIMjJaZAnOTiXyqEDKgEEYUOYeMPh1VKcZhpLIgAsYMk4AdTfmeDk-jAcGs2n+zGo-wo+zAcmMIGoEQAklAFrBrGA0tJzqjrDAKJUXn1JCoPN8zJJ9iTCqlqC5xKwPPQYCNaIFdkTIv56EyYXCliTWDBvsw5jA3sgABwABnE9Dgg2Y8tZ7L2PUa4hgvBFYolSAATOIwh4srwihqQHAyDx5gs5g5aKcwmy4AAxCD0XZXIL7Wh3CAgYTCIA

Prettier strips trailing commas from CSS variables which changes the actual value of the CSS variable:

```css
/* Input */
.foo {
  --my-var: in oklab,;
}

/* Output */

.foo {
  --my-var: in oklab;
}
```

This breaks situations like this, where the comma needs to be included when resolving the variable at run-time:

```css
.in-oklab {
  --interpolation-method: in oklab,;
}

.radial-gradient {
  background-image: radial-gradient(var(--interpolation-method,) black, white));
}
```

In that example the comma is necessary if `--interpolation-method` is defined, but if it's not defined you need to make sure the comma is not there.

**Comment by kachkaev** [comment]
Prettier tries to fix comma-separated values like font sizes or background images:

**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbTWAWnQEMBbASwBsBPJbPEAQQCcaK7WAaFiAAScOgDc4MGmAr8i8ogGcKURaUVwu6AQG4CRAEYUwAawDmHCAFcoAE1I0qFM3GZWOdABQByR87gAjKgADlBm3gCUAu5evk4uAEwhYZG6BAC+IHwgEMFS0IrIoBQclgDuAAolCIUoPGUUDIXZBhzGJpIAytRwADI0UHDIlHQaLW2mXcHGA2bIMBxWcNkatPOLyyBwAB7Bmo4IMDwAKppQJTRwtSNjIIqzdHAAilYQ8MM8twBWitudD89Xu8kDdNgBHIFwCqWYK1EAUNSDOC2ZFZEALCj0WYAYQgVCcyHhdDoaPuYUebBgCxoBis8Aqmn6gw+o02AAsYFQ6AB1Nk0eCKaZgOCdGr8mhifkMQlgRTNEBiJYASTsh06YC4eTYdk6MAYjxZt2Clg03LawUJxqumgkaIGGg4MGhzgJIM+m2mHAdMrlaONAxg3JothgbOQAA4AAzZDhwCE0WPOsyu0HZI4GIMhsNIBLZKwaY4UAzXd3ZOBUAzIlG2XoqMxWfwAMQgHCcVNmhIodIgIHS6SAA)

```sh
--parser css
```

**Input:**

```css
.foo {
  font-family: "Arial", "Helvetica",       sans-serif, ;
  background-image: url('image1.png'), url('image2.png'), ;
}
```

**Output:**

```css
.foo {
  font-family: "Arial", "Helvetica", sans-serif;
  background-image: url("image1.png"), url("image2.png");
}

```

We probably need to disable this fix if CSS Property key starts with `--`. This will mean that all CSS vars are preserved as is. Any drawbacks of doing this?
