### ISSUE TITLE
Formatting can break CSS variables intended for the animation property

### ISSUE THREAD

**Issue by stropitek** [prettier/prettier#17064]
Reproduction:

https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEYAJgB0pZYC0RAtgJ5GpwCGANnZdfY0XdAOZE1QCWpNGL2hEAbjVS8aAIzpwkWZg3IB9JYxXsoHFT36DhUFVBqk4WAIwAGG6QDOWMAFdpvMEWlwAXrzioAFFYANFjBoQB0AEwhFgCUWABmEKgA7hIAJnYA3PgAvvj44UkQOPiEegJC0AriASQUVLTKjSyUWlwVBiK1UrJwsTlQ+VD4AAIA1nDkCaimcA7qqouanLp8lYbGc6UEoQCkO4SEEAAONGC8MOQKVoOEw4TWVgd4u8dnF1cKFndYw7kgIIgU5VKB2ZCgCToFIABQkCHBKHoaXI4KB0lmYEmMAAynMADK8KBwZAJeh2ODozHYnEfIkcZAwVBOSkgCmkXiM5msuAADxOfn4CBg9AAKn4TJJ5qTyay7PS5ABFJyYElIMl0ClAgBWdl5OIVcGVqplmtZAEcVfAYegToiQDQ7ERiXB0q7ASAmTReHR6QBhCCkATIB0MD3y7RyACCMCZvGkTmtfkJxNNWpAAAsYKQ6AB1DOXeYfOA4hGXXiiS7kENgOxokCiFkASSgbtgOLAkhOMCjrZxVzkadZJ3QFNzsxOIZH8z8ohJQKJFNQMBtNA4wfVsqBZ1QS5rdY9I6JMFzvHSMAzyAAHMEQNRLbxqKv1zQh0CRdJT+fL0hoiAnBSooyIiGrpnApCeOkbrpPiPAcE4a5wAAYsklRCNoIY0ImEAgLkuRAA

Prettier adds a line break right after the animation name. This breaks the animation in all major browsers (tested on Chrome, Firefox and Safari).

```css
:root {
  --my-really-really-long-animation-variable: really_really_long_animation_name
    1000ms cubic-bezier(0, 0, 0.2, 1) forwards;
}
```

If the animation name is followed by a space before the line break, it works.
