### ISSUE TITLE
`v3.5.0` is a BREAKING CHANGE

### ISSUE THREAD

**Issue by lumirlumir** [prettier/prettier#17094]
**Prettier 3.5.0**
[Playground link](https://prettier.io/playground#N4Igxg9gdgLgprEAuEA6AagBQHIEMBuABKjAJYwA2chAzgA65SHAA6ThAZtDALQe4BbUhQCeSQgHIAUgFdcEgDSSAkrDgAnRYRmkeNRjT0bSHJTRE14AnjrMGj6k0okBBOnSqEAwhAoR1hACiAhAAVqSKbITRkgDKcADmENQAqspBIeFaEvFJqemxIgIARr7Z2BAwEN6+-hlhEQDcbAC+IAogEHRk0DTIoLjq6hAA7piDCH0ouBQjuBbtIMXquGAA1nAwsYJwADKkUHDI-BQ0cB0QxaFwYDAA6it0yCB06nBn6vhHHcurG1sMMAHBLIGDqGTnEBnISg8GQuAADzoxgECBgMwA8siVlV1JgIDRyKRoM8EAATRaI7GkVGwGYAFQ0UEGpHexxmZw6hKgCSoAEUZJUjkgwRCOqEaAjYsD+YL4OzTpCAI5yuCYYZ0KYgXCGQ5wMn6xZg3DCYE+AQCXDPGYURbc3lwFwwMGkYoyeCYDT7Q4KzkgAAWMAEFDu-vI70BcHiUEJZHw5BEzzAND6HXwENUBtgsTAjm6LigZNiMBEVF9kNeBLgD1wTxQr3eGi+iwOHxg6twCUt5Y6DHUHyTKcWrwO91IZJg-uQAE4AAwdN4q0hvDtdq1IE5+9HFO7jyfIABMHRkZ3puGKU038JK+oNZN2jAScgScAAYv5Lc7gdb3RAQC0WiAA)

```js
// Options (if any):
module.exports = {
  printWidth: 90,
  tabWidth: 2, // Default.
  useTabs: false, // Default.
  semi: true, // Default.
  singleQuote: true,
  quoteProps: 'as-needed', // Default.
  jsxSingleQuote: false, // Default.
  trailingComma: 'all', // Default.
  bracketSpacing: true, // Default.
  bracketSameLine: false, // Default.
  arrowParens: 'avoid',
  proseWrap: 'never',
  htmlWhitespaceSensitivity: 'css', // Default.
  endOfLine: 'lf', // Default.
  singleAttributePerLine: false, // Default.
};
```

**Input:**

```css
.VPNav .title span {
  font-family: 'Jua', 'Inter', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}
```

**Output:**

```css
.VPNav .title span {
  font-family:
    'Jua', 'Inter', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}
```

**Expected output:**

```css
.VPNav .title span {
  font-family: 'Jua', 'Inter', ui-sans-serif, system-ui, sans-serif, 'Apple Color Emoji',
    'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
}
```

**Why?**

Hello,

I've discovered that `v3.5.0` is breaking builds. The [release note](https://prettier.io/blog/2025/02/09/3.5.0#css) mentions that the feature "Break before breaking comma separated values [#16907](https://github.com/prettier/prettier/pull/16907)" was added.

The "Input" was the original version, which worked fine in `v3.4.2`. However, the result in `v3.5.0` now matches the one shown in the "Output". I believe this is not a minor change, as it currently breaks builds.
