### ISSUE TITLE
Content-based cache still checks modified times

### ISSUE THREAD

**Issue by reteps** [prettier/prettier#17278]
https://prettier.io/docs/cli#--cache

> (if --cache-strategy is metadata) file metadata, such as timestamps
> (if --cache-strategy is content) content of the file

This suggests that if the cache strategy is content, only the hash will be checked not timestamps.

Looking at the implementation,

https://github.com/prettier/prettier/blob/26f99aef8bb8e822602af91c17d89ae167ac5357/src/cli/format-results-cache.js#L72-L76

Calls out to

https://github.com/jaredwray/cacheable/blob/a95f7f7f8c2dafcd78fee6a310874a6b03ed974b/packages/file-entry-cache/src/index.ts#L299-L305

Which appears to check both the timestamps AND the hashes. I am noticing this in a CI pipeline that does clones, where the cache hit is ignored. Can we update the documentation to be more clear about this if this is indeed what is happening?

Additionally, I have opened https://github.com/jaredwray/cacheable/issues/1047 to discuss a hash-only solution.

**Comment by fisker** [comment]
We noticed this change when [upgrading `file-entry-cache` to v10](https://github.com/prettier/prettier/pull/16725#discussion_r1907304267), but we thought it's acceptable.

May I ask how did you notice this change? Does your file `mtime` keep changing?

**Comment by reteps** [comment]
@fisker I am trying to cache prettier outputs in a CI pipeline. When CI checks out the repo, the `mtime` of all files is changed, invalidating the cache. I have to use a tool like https://github.com/MestreLion/git-tools/blob/main/git-restore-mtime to avoid this.

**Comment by fisker** [comment]
I see, let's wait for https://github.com/jaredwray/cacheable/issues/1047 then.

Also, there is a proposal switch to use `@file-cache` https://github.com/prettier/prettier/pull/16725#pullrequestreview-2557931890

AFAIK, stylelint also upgraded to v10, did you noticed same issue?

**Comment by fisker** [comment]
> This project seems much smaller than @file-cache, I would be curious what the immediate advantage of switching is. 

Don't know, I didn't look into it. Another maintainer mentioned about it.

**Comment by phillipuniverse** [comment]
Confirmed broken in 3.5.0+, thanks @fisker to the link to the regression! Fix is to downgrade to the latest 3.4 version, 3.4.2.

Here's an example GitHub Actions workflow which does the following:

1. Establishes a cache to `.prettiercache` using `actions/cache@v4`
2. Output md5 and ownership of `.prettiercache`
3. Runs prettier with `--cache-location=.prettiercache`
4. Output md5 and ownership of `.prettiercache`
5. Runs prettier againIn-between each step 
6. Output md5 and ownership of `.prettiercache`

```yaml
name: ci
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Prettier Cache
        uses: actions/cache@v4
        with:
          path: .prettiercache
          key: ${{ runner.os }}-prettier-cache-${{ hashFiles('.prettierrc.yaml') }}

      - name: cache file hash
        run: |
          echo "hash of cache $(md5sum .prettiercache), size $(ls -lisah .prettiercache)"

      - name: Prettier
        run: npx prettier@3.5.3 --write "**/*.{html,yaml}" --cache --cache-location=.prettiercache

      - name: cache file hash
        run: |
          echo "hash of cache $(md5sum .prettiercache), size $(ls -lisah .prettiercache)"

      - name: run it back
        run: npx prettier@3.5.3 --write "**/*.{html,yaml}" --cache --cache-location=.prettiercache

      - name: cache file hash
        run: |
          echo "hash of cache $(md5sum .prettiercache), size $(ls -lisah .prettiercache)"
```

Here's the output on the first run when there's no cache:

<img width="1350" alt="Image" src="https://github.com/user-attachments/assets/414e6c68-b3f0-41e9-9401-cab0243392e0" />

- No cache to find, so `actions/cache@v4` is a miss
- no `.prettiercache` file
- Running `prettier` creates a `.prettiercache` file on first run with a hash of `0d6f6ede21bf7a384096983b25f69fd2`
- 2nd run of prettier has the same cache
- GH actions cache is persisted

And here's the output when I get a hit:

![Image](https://github.com/user-attachments/assets/ac9f7576-5d36-4255-80ed-5e64f0dc0ef6)

- `actions/cache@v4` finds the cache, restores `.prettiercache` file
- md5 hash of `.prettiercache` is exactly what it was in the first run - `0d6f6ede21bf7a384096983b25f69fd2`
- ------> BUG ------> Running `prettier` **modifies the .prettiercache file** on first run to change it to have a hash of `8d4e5d8af3ad5f51199847dc933f05af `
- 2nd run of prettier has the same cache as before
- GH actions cache got a hit so nothing changed

---

When I rerun with 3.4.2:

```
npx prettier@3.4.2 --write "**/*.{html,yaml}" --cache --cache-location=.prettiercache
```

everything works great! prettier uses the cache and my build times go from ~2 minutes to ~4 seconds.
