### ISSUE TITLE
YAML - Indented comments after empty braces trigger newline and same indentation in front of braces

### ISSUE THREAD

**Issue by Gufderald** [prettier/prettier#17296]
**Prettier 3.5.3**
[Playground link](https://prettier.io/playground#N4Igxg9gdgLgprEAuEBadAdKAHAThAWzhgAs4BXAZwGFoAzASwHMAlOAGwgEMATOXJFgAEQhgS5M4gqCJG44TBpRi4AnkiEBHcl1UA6BhGGz52CJQYwIajXkLEyVVBGz8uV3AHo7RUhUqokFCMTKjynLz8xiIAxKJ0QlAQMEKUxEJc2NgAavwW0EKMHDyF+ARC1CRcuDB6qlwE7KKUQlRwPNFCMBIaGCB9nZRVvf39UMZxvCU+Dv5CQSFC4dx8uELsDABuCHCULVxQJfK8DFC7LXYARnB6QgAicHRc5OwwGk-sacYIXJfscAAFfDXd5cT5wLATOIASQSlFcYAYRR4ABoumQhGYeAByFpWf64dyGKCUPRQpaPDQkGAwbCUJCeTwAa3I11wZ3gpMMnh4EDAlE8QTAcGwMAFC2Y5EJMGJnm6pxgqAOPFQ+LcMugnlksRixjV0uJ9KEAG0ALqdIRxVBCJlwdRCPpJPhhCD-PQstkc3YGCCecTKKJjbWW2QudXWEYAUW0YIGMm1cREmzB5CkDtGkPjcXklAgUuF83ozEK1kxZVmVFowWYbAiq2MObzuGFRuAAF9Otm4NpdmLpAnZGBsOQNAAmAAM44IndkRAI1ntAFZxwBZBgzjYESz0mciIcjoQTqe7oRzhcaZdr4wN3ZNlsAfU5byE7b1rvVhsfvY0ZszIBRIAuBqJLIKA1T4AA7gC1QIJQyAgGCEG6HBAGXISYC2jAADKDRwAAMqccDIB8aQARAlwAFZwGAMAAOqEtg8F4Ls-DbP+IBoVwGHEFh2BcacTDICoqYAWkW5CbgIkgHAAAeri4GICDdOwADy8nuNYALmJYxLwQgPDsbJ8mKbAYIACr8FA1QMLsxFgqRIAWFATD-AAiuQyREUgJFwABFGUDJWECW5HnwHZ4IAdonlAi4cEoFwARnO07TsSoXAMBszm0AQ4jwWC7DsU5LlwAAgjSCmXOQ8AAvwBFnOFDnUo0tEkJYux8cKWGwTpmyWKo8H8ihICbKm0KHEpWFgApoolYcWEwKo-wNb5IB2Gk9GZExOasURAGnGkNRAhIuXefZK18bgB3wfUjTsXgCq0QwPCkMgAAc44AfI2gMPIR1MCdPkAd0lyPc9JDIKOAFtGZvxxYD0kENcPB8DweEHEwOiSAAYtY4g0gJeVVRAIBtm2QA)

```sh
--parser yaml
```

**Input:**

```yaml
---
prometheusConfigReloader:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-config-reloader
    # if not set appVersion field from Chart.yaml is used
    tag: ""
    sha: ""

  # add prometheus config reloader liveness and readiness probe. Default: false
  enableProbe: false

  ## If specified, the pod's tolerations.
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/     ##
  tolerations: []
     # - key: "node-role.kubernetes.io/master"
     #   operator: "Equal"
     #   value: ""

  # resource config for prometheusConfigReloader
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 50Mi
    # limits:
    #   cpu: 200m
    #   memory: 50Mi
  
  resources_test: {}
  tolerations_test: []


```

**Output:**

```yaml
---
prometheusConfigReloader:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-config-reloader
    # if not set appVersion field from Chart.yaml is used
    tag: ""
    sha: ""

  # add prometheus config reloader liveness and readiness probe. Default: false
  enableProbe: false

  ## If specified, the pod's tolerations.
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/     ##
  tolerations:
    []
    # - key: "node-role.kubernetes.io/master"
    #   operator: "Equal"
    #   value: ""

  # resource config for prometheusConfigReloader
  resources:
    {}
    # requests:
    #   cpu: 200m
    #   memory: 50Mi
    # limits:
    #   cpu: 200m
    #   memory: 50Mi

  resources_test: {}
  tolerations_test: []

```

**Expected output:**

```yaml
---
prometheusConfigReloader:
  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-config-reloader
    # if not set appVersion field from Chart.yaml is used
    tag: ""
    sha: ""

  # add prometheus config reloader liveness and readiness probe. Default: false
  enableProbe: false

  ## If specified, the pod's tolerations.
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/     ##
  tolerations: []
    # - key: "node-role.kubernetes.io/master"
    #   operator: "Equal"
    #   value: ""

  # resource config for prometheusConfigReloader
  resources: {}
    # requests:
    #   cpu: 200m
    #   memory: 50Mi
    # limits:
    #   cpu: 200m
    #   memory: 50Mi

  resources_test: {}
  tolerations_test: []

```

**Why?**
According to [YAML spec](https://yaml.org/spec/1.2.2/#66-comments), I see no explicit definition to add indentation before empty according to following comment. What was the source for this rule?
