### ISSUE TITLE
dessant/lock-threads is broken

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#17454]
https://github.com/prettier/prettier/actions/runs/14918457059/job/41909109542

https://github.com/dessant/lock-threads/issues/53

**Comment by tenthirtyam** [comment]
The following change should resolve the failing workflow:

```yaml
name: Lock

on:
  schedule:
    # “At 00:00.” https://crontab.guru/#0_0_*_*_*
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  lock:
    if: github.event_name != 'schedule' || github.repository == 'prettier/prettier'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      discussions: write
    steps:
      - uses: dessant/lock-threads@1bf7ec25051fe7c00bdd17e6a7cf3d7bfb7dc771 # v5.0.1
        with:
          # https://github.com/dessant/lock-threads
          github-token: ${{ github.token }}
          issue-inactive-days: "90"
          exclude-issue-created-before: ""
          exclude-any-issue-labels: "keep-unlocked, status:awaiting response"
          add-issue-labels: "locked-due-to-inactivity"
          issue-comment: ""
          issue-lock-reason: "resolved"
```
