### ISSUE TITLE
CSS formatter adds extra indention parts of properties with multiple values following a comment

### ISSUE THREAD

**Issue by n3dst4** [prettier/prettier#17479]
**Prettier 3.5.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAIwEMwBrAcwCcIBXKAEwFoBLAW1KriQKKIAbNlDikaLWqSZsEMABT8BRGDlUAHADRLlxQfTjbCy7DThNsARgAM1gKQ7sASiPKA9ACps8AB4x6Ztgebo5EZupiMCJULMKi4pI00rKwisYm2ACc1kxwVK4Z2OoiFAUZAJ5wgoIQAO7YAEzW6j5lJrRwCI3NraECxVAU2AAsPX0ufeGR0bEiYhJSMnJphVk5eW3KA6V9RJXVdd0tmwIdXU3Hu0UlI2PpAhNQAL4EIJogEOpR0ADOyKDiOi1AAK4gQfxQpEEtVI5T+72ISUocBgAGVSBw4AAZObIdBQn6GD7EABWcDAMAA6kl1MgQOozISaAA3OBvECI8gUFGo9TkaLIGA0AzvQkcNiC4VEuA+CI0ThyKEAeTlpFUNGBEB+bG+UDpCCY7JlcoVsChABU4DQoOJZBD8YJCaLooI4ABFegQeB4glEkk-Hyol3uz3epAOp0gACOobgwLo6ghIFIPxYonM5nZQtIbDiVAAwhAOFw6VDBOztVAqK6AIIwIVsYj0eDAq040Q+x1EgAWMA4gkp3Z1cB+fLAcFR4J1bGZOvKdLAP3hIGZBgAksw5KiwPKvjXmKiYOVXZ3IwytXBqaRaSgGSOraz2SImTB49wS+Hfe8+TQmQul+yDIiFSbBMDA3bIAAHNY7xmDGbBmG+VAfhGRIwKQxCUqB4HIA07z0IS5oYfaX4gHAHDEOYuRMFipBVvQ3BwAAYhANBcPWAqQs2EAgE8TxAA)

```sh
--parser css
```

**Input:**

```css
.foo {
  background-image:
    linear-gradient(
      to top,
      blue,
      red 100%
    ),
    /* texture */
      repeating-linear-gradient(
        90deg,
        pink,
        yellow 20px,
        green 20px,
        pink 40px
      ),
      repeating-linear-gradient(
        90deg,
        pink,
        yellow 20px,
        green 20px,
        pink 40px
      ),
}

```

**Output:**

```css
.foo {
  background-image:
    linear-gradient(to top, blue, red 100%),
    /* texture */
      repeating-linear-gradient(90deg, pink, yellow 20px, green 20px, pink 40px),
    repeating-linear-gradient(90deg, pink, yellow 20px, green 20px, pink 40px);
}

```

**Expected output:**

```css
<!-- prettier-ignore -->
```css
.foo {
  background-image:
    linear-gradient(to top, blue, red 100%),
    /* texture */
    repeating-linear-gradient(90deg, pink, yellow 20px, green 20px, pink 40px),
    repeating-linear-gradient(90deg, pink, yellow 20px, green 20px, pink 40px);
}
```

**Why?**

The `repeating-linear-gradient` following the comment `/* texture */` should be aligned to match the other definitions in this value, but it's gained an extra two spaces.
