### ISSUE TITLE
CSS: Call that shouldn't have been

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1803]
```css
a {
  box-shadow: inset 0 $size $size (-$size) black;
}
```

outputs

```css
a {
  box-shadow: inset 0 $size $size(-$size) black;
}
```

**Comment by lydell** [comment]
In case it helps, it happens for numbers too:

```scss
a {
  flex: 0 1(100% * 2 / 3);
}
```

**Comment by vjeux** [comment]
Do you know if `$size(-$size)` can even be a call?

**Comment by lydell** [comment]
It does not seem so. I tried pasting this into https://www.sassmeister.com/:

```scss
a {
  $size: f;
  box-shadow: inset 0 $size $size (-$size) black;
  box-shadow: inset 0 $size $size(-$size) black;
  box-shadow: inset 0 $size 1(-$size) black;
  box-shadow: inset 0 $size g(-$size) black;
}
```

and only the last line is a call. In the other cases the space does not seem to matter.
