### ISSUE TITLE
Mixed SCSS feedback

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#1805]
I ran Prettier on some real word SCSS code and went through the diff. I found a few things that didn't print super nice, and a few things that broke the code.

### Missing space to the right of `/`

- [x] https://github.com/prettier/prettier/pull/1806

```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom:
      (
        100% *
        $image-height /
        ($image-width-responsive + $image-margin-responsive * 2)
      );
  }
}
```
```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom: (
      100% *
        $image-height /($image-width-responsive + $image-margin-responsive * 2)
    );
  }
}
```

Also, printing it more like we do for JS would be nicer:

```js
if (1) {
  if (1) {
    padding_bottom = (
      100 *
        $image_height /($image_width_responsive + $image_margin_responsive * 2)
    );
  }
}
```
```js
if (1) {
  if (1) {
    padding_bottom =
      100 *
      $image_height /
      ($image_width_responsive + $image_margin_responsive * 2);
  }
}
```

Another example:

- [x] https://github.com/prettier/prettier/pull/1806

```scss
a {
  padding-right: (100% * $info-width / (1 - $image-width));
}
```
```scss
a {
  padding-right: (100% * $info-width /(1 - $image-width));
}
```

### Extraneous space before `>` at BOL

- [x] https://github.com/prettier/prettier/pull/1807

```scss
a {
  > * {
  }
}
```
```scss
a {
   > * {
  }
}
```

Also happens for `+` and `~`.

Hmm, not only beginning of lines, but also beginning of sub selector:

```scss
a {
  &,
  > span[data-i18n] {
  }
}
```
```scss
a {
  &,  > span[data-i18n] {
  }
}
```

### This would be nicer if printed more like JS

```scss
a {
  b {
    img {
      max-height:
        calc(
          100vh -
          #{var(--margin)} * 2 - #{var(--padding)} * 2 -
          #{$extra-space-for-scrollbar}
        );
    }
  }
}
```
```scss
a {
  b {
    img {
      max-height: calc(
        100vh -
          #{var(--margin)} *
          2 -
          #{var(--padding)} *
          2 -
          #{$extra-space-for-scrollbar}
      );
    }
  }
}
```

```js
{
  {
      max_height = calc(
        100 -
          $(car(__margin)) *
          2 -
          $(car(__padding)) *
          2 -
          $($extra_space_for_scrollbar)
        );
  }
}
```
```js
{
  {
    max_height = calc(
      100 -
        $(car(__margin)) * 2 -
        $(car(__padding)) * 2 -
        $($extra_space_for_scrollbar)
    );
  }
}
```

### Should we try to break here?

- [x] https://github.com/prettier/prettier/pull/1809

Garbage in, garbage out, or do we want to break something like the input here?

```scss
a {
  ~ .Pagination-itemWrapper:not(.is-separator):not([data-priority^='#{$priority}'])
    ~ .Pagination-itemWrapper.is-separator[data-priority^='#{$priority}'] {
    display: flex;
  }
}
```
```scss
a {
  ~ .Pagination-itemWrapper:not(.is-separator):not([data-priority^='#{$priority}']) ~ .Pagination-itemWrapper.is-separator[data-priority^='#{$priority}'] {
    display: flex;
  }
}
```

### Removed space before `-`

- [x] https://github.com/prettier/prettier/pull/1806

```scss
a {
  width: calc(100% - (#{var(--g-spacing)} - #{$iframe-x-padding}) * 2);
}
```
```scss
a {
  width: calc(100% -(#{var(--g-spacing)} - #{$iframe-x-padding}) * 2);
}
```
