### ISSUE TITLE
CSS: Improve arithmetic operators

### ISSUE THREAD

**Issue by lydell** [prettier/prettier#1811]
Goal: Print them more like JS. Flatten indentation and group operators.

```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom:
      (
        100% *
        $image-height /
        ($image-width-responsive + $image-margin-responsive * 2)
      );
  }
}
```
```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom: (
      100% *
        $image-height / ($image-width-responsive + $image-margin-responsive * 2)
    );
  }
}
```

Compare to this JS:

```js
{
  {
    padding_bottom = (
      100 *
        $image_height /($image_width_responsive + $image_margin_responsive * 2)
    );
  }
}
```
```js
{
  {
    padding_bottom =
      100 *
      $image_height /
      ($image_width_responsive + $image_margin_responsive * 2);
  }
}
```

---

```scss
a {
  b {
    img {
      max-height:
        calc(
          100vh -
          #{var(--margin)} * 2 - #{var(--padding)} * 2 -
          #{$extra-space-for-scrollbar}
        );
    }
  }
}
```
```scss
a {
  b {
    img {
      max-height: calc(
        100vh -
          #{var(--margin)} *
          2 -
          #{var(--padding)} *
          2 -
          #{$extra-space-for-scrollbar}
      );
    }
  }
}
```

Compare to this JS:

```js
{
  {
      max_height = calc(
        100 -
          $(car(__margin)) *
          2 -
          $(car(__padding)) *
          2 -
          $($extra_space_for_scrollbar)
        );
  }
}
```
```js
{
  {
    max_height = calc(
      100 -
        $(car(__margin)) * 2 -
        $(car(__padding)) * 2 -
        $($extra_space_for_scrollbar)
    );
  }
}
```

Extracted from: #1805

Important comment by @vjeux:

> Right now we only get a stream of tokens. We'd need to parse it to be able to reprint it properly. For this, we need to implement a small arithmetic parser and print it correctly. It shouldn't be too hard

**Comment by j-f1** [comment]
Here’s the current status of this:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AkgWwIYHM4AEwAOlAQQAKZwAmAltgQBQ4AeAtAO500wAWSAgBI6OfFx792AJzgBnAA7Q5dAG5wAlEVLlyC7DXpRc7AEYQYMCJiQ7d5JnfvkAjAAY3AUgIAqJ85ExOHY+ODpcPhgCAHp-eyZAvGDuXj4ZeSUoFXUCAGphUST2HGlcOih0xWU1Qh8CACYNOIINAG47AF9SLqgQABoQCAUYOmVkUGxpaQhOAAVJhDlkEGxVCB5+lbkYZAAzbAAbOTgB02lsMABrOBgAZX0wctxkGGkAVxOQGggwPcPjgblY7SGCzc64HB-I6fABWclYACFzlcbrdsNQADLlOBQgGDN4wBQE+q4z76aTA5ZyMByJYDBTScowADqkj4yHqbnp02OzPOCmWDPkcGk6k2sgAjm86LIwXhIUh9tCBsdMHQXu9PipjAc4ABFN4WHGK-6fGDYUys1IcgavbB0A5PADC1gVICg0BxAzexwAKhaliboR0OkA)
```sh
--parser scss
--print-width 20
```

**Input:**
```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom:
      (
        100% *
        $image-height /
        ($image-width-responsive + $image-margin-responsive * 2)
      );
  }
}

```

**Output:**
```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom: (
      100% *
        $image-height /
        (
          $image-width-responsive +
            $image-margin-responsive *
            2
        )
    );
  }
}

```

Is this good enough to close the issue?

**Comment by lydell** [comment]
The other example does not look very good though:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOld6BGmOeeAlgLYDmRuJe5qAHgLQAWcplrMSxdJYVABswACj78SARgAMMgG6t0zCZPQBiYPNQAnUc2YMdlUlACUAX3QAqdACZlGrbv3MADqgAmn05Us37ZVVJTQASOEYYHVRmAGcPMDhmADMIHTiwHQghIXxdC2CSMwBuVQLacosQABoQCDcYUmhY5FBdLIB3AAVdBBaUVHkIUk8atFiYZGThWLha-GiwAGs4GABlBN9kKIBXOZBPCDApmf3TWZ0YLujKBhOhWdqAK1jGACFFlfXUcjgAGVMcHujzqOxgbjBdmB+w8OguyHAsRatTcOlMMAA6iMYKxkAAOGQorKzDHRNwI1FwC7yIG1HRwACOO1I9OuqFuqGhtVm5FI2x0e25viEcAAijsIPAuSAYKh8FjPDjkHZalFUKQhL4AMIQch3FBQaC0kA7WYAFTl-WmDzgFgsQA)
```sh
--parser css
```

**Input:**
```css
a {
  b {
    img {
      max-height:
        calc(
          100vh -
          #{var(--margin)} * 2 - #{var(--padding)} * 2 -
          #{$extra-space-for-scrollbar}
        );
    }
  }
}
```

**Output:**
```css
a {
  b {
    img {
      max-height: calc(
        100vh - #{var(--margin)} * 2 - #{var(--padding)} * 2 - #{$extra-space-for-scrollbar}
      );
    }
  }
}

```

**Comment by lydell** [comment]
And if you use a sane print width, the first example is not so pretty either:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AkgWwIYHM4AEwAOlAQQAKZwAmAltgQBQ4AeAtAO500wAWSAgBI6OfFx792AJzgBnAA7Q5dAG5wAlEVLlyC7DXpRc7AEYQYMCJiQ7d5JnfvkAjAAY3AUgIAqJ85ExOHY+ODpcPhgCAHp-eyZAvGDuXj4ZeSUoFXUCAGphUST2HGlcOih0xWU1Qh8CACYNOIINAG47AF9SDpAAGhAIBRg6ZWRQbGlpCE4ABQmEOWQQbFUIHj7luRhkADNsABs5OH7TaWwwAGs4GABlfTBy3GQYaQBXY5AaCDBdg6P+8pHaQwGZnXA4X6HD4AKzkrAAQmdLtcbthqAAZcpwSH-AavGAKfH1HEffTSIFLMByRb9BTScowADqkj4yAAHG5aVMjoyzgolnT5HBpOoNrIAI6vOiyUF4CFIPZQ-pHTB0Z5vD4qYz7OAARVeFmxCr+Hxg2FMzNSyHq-Re2Do+0eAGFrPKQFBoNj+q8jgAVc2LY1QjodIA)
```sh
--parser css
```

**Input:**
```css
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom:
      (
        100% *
        $image-height /
        ($image-width-responsive + $image-margin-responsive * 2)
      );
  }
}
```

**Output:**
```css
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom: (
      100% * $image-height / ($image-width-responsive + $image-margin-responsive *
            2)
    );
  }
}

```
