### ISSUE TITLE
[Prettier CSS] Multi-line comma separated selectors

### ISSUE THREAD

**Issue by TheSisb** [prettier/prettier#1962]
I think in terms of legibility, multi-lining comma separated selectors is much more readable.  Could this be the default?

## Example of desired effect:
```css
.ball, 
.rabbit,
.wrapper:hover .contents,
.wrapper:active .contents {
  color: red;
}
```

## What prettier currently emits:
```css
.ball, .rabbit, .wrapper:hover .contents, .wrapper:active .contents {
  color: red;
}
```

The single line approach usually ends up creating really long lines that require horizontal scrolling and break n characters per line conventions (usually 80 or 120).
