### ISSUE TITLE
[Prettier CSS] Sort declaration properties in consistent manner

### ISSUE THREAD

**Issue by TheSisb** [prettier/prettier#1963]
Some of the difficulty in reading someone else's CSS comes from having to deeply read each line in a declaration block to make sure you understand the full scope of the styles.

```css
.wrapper {
   top: 20px; /* is it absolute? fixed? You begin searching downwards */
   margin-left: 20px; /* Any other margins applied? */
   display: flex; /* How is this flexed?  searching for justify / align / flex rules */
   position: absolute; /* ah absolute */
   margin-bottom: 20px;
   border-radius: 5px;  /* Is there even a border? */
   color: red;
   justify-content: center;
   margin-left: 2px;
   border: 1px solid red;
}
```

There's a postcss plugin to sort these properties in a consistent way that makes reading CSS easier: https://github.com/hudochenkov/postcss-sorting

Have you considered enabling it by default in prettier?  I think it would be a good addition.
