### ISSUE TITLE
[CSS] single line property formatting

### ISSUE THREAD

**Issue by onigoetz** [prettier/prettier#2021]
Hi, 
thanks a lot for this project, it's really great and I look forward to use it on all projects at work :)

I noticed that prettier does absolutely no distinction between single-property statements and multi-property statements. Meaning they're all formatted on multiple lines.

It's very useful in CSS when you have many rules with only one property to format them on a single line. 
Here's an example from fontawesome:

```css
.#{$fa-css-prefix}-gear:before,
.#{$fa-css-prefix}-cog:before { content: $fa-var-cog; }
.#{$fa-css-prefix}-trash-o:before { content: $fa-var-trash-o; }
.#{$fa-css-prefix}-home:before { content: $fa-var-home; }
```
Prettier would format it like this : 
```css
.#{$fa-css-prefix}-gear:before, .#{$fa-css-prefix}-cog:before {
    content: $fa-var-cog;
}
.#{$fa-css-prefix}-trash-o:before {
    content: $fa-var-trash-o;
}
.#{$fa-css-prefix}-home:before {
    content: $fa-var-home;
}
```

Would it be possible to automatically format rules with a single property on a single line ?
Even better would it be possible to do it only if it was already placed on a single line ?

The second requirement might seem weird, but it's to address the following; a single-property rule can be one of two kinds : 
1. A rule that was just created and might receive more properties in the future
2. A rule that isn't meant to receive more than a single property (in the case of sprites, fonts and such)

If you agree on the principle, I can try to make a pull-request adressing this.
