### ISSUE TITLE
SCSS - Unusual formatting of lists of lists

### ISSUE THREAD

**Issue by karl** [prettier/prettier#2126]
In SASS/SCSS you can declare variables of a list data type. The list items can be separated by either by commas or spaces:

http://sass-lang.com/documentation/file.SASS_REFERENCE.html#lists

You can create lists of lists like so:

```scss
$var: (0 0) (0 0) (0 0);
```

or

```scss
$var: (0, 0), (0, 0), (0, 0);
```

When running a long list of lists through Prettier, if the outer list is separated by spaces you get unusual formatting.

This input:

```scss
$var: (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0);
```

Gives this output:

```scss
$var: (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0) (0 0)
  (
    0 0
  ) (0 0);
```

---

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%2F%20This%20formats%20strangely%5Cn%24var%3A%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%20(0%200)%3B%5Cn%5Cn%2F%2F%20This%20formats%20strangely%5Cn%24var%3A%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%20(0%2C%200)%3B%5Cn%5Cn%2F%2F%20This%20is%20OK%5Cn%24var%3A%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%20(0%2C%200)%2C%3B%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Do you have a real world use case where this is breaking?

**Comment by karl** [comment]
We use it to create classes for our most common margin, padding, and gutter sizes:

```scss
$space-scale: (0, "0") (0.25, "0-25") (0.5, "0-5") (0.75, "0-75") (1, "1") (1.25, "1-25") (1.5, "1-5") (1.75, "1-75") (2, "2") (2.25, "2-25") (2.5, "2-5") (2.75, "2-75") (3, "3") (3.25, "3-25") (3.5, "3-5") (3.75, "3-75") (4, "4");

// Margins and paddings
@each $spacing in margin, padding {
  @each $v, $suffix in $space-scale {
    :local(.#{$spacing}-#{$suffix}) {
      #{$spacing}: #{$v}rem;
    }
  }

  @each $v, $suffix in $space-scale {
    @each $pos in top right bottom left {
      :local(.#{$spacing}-#{$pos}-#{$suffix}) {
        #{$spacing}-#{$pos}: #{$v}rem;
      }
    }
  }
}

@each $v, $suffix in $space-scale {
  :local(.gutter-#{$suffix}) {
    margin-right: -#{$v / 2}rem;
    margin-left: -#{$v / 2}rem;
  }
}
```
