### ISSUE TITLE
CSS: Comment gets eaten

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#2127]
Input: 

```css
@font-face {
  font-family: "Prettier";
  src: local("Prettier"), /* Local */
    url("http://prettier.com/font.woff") /* Network*/
}
```

Expected:

```
@font-face {
  font-family: "Prettier";
  src: local("Prettier") /* Local */, url("http://prettier.com/font.woff"); /* Network*/
}
```

Output (the `/* Local */`) comment is dropped:

```
@font-face {
  font-family: "Prettier";
  src: local("Prettier"), url("http://prettier.com/font.woff"); /* Network*/
}
```

Repro: https://prettier.github.io/prettier/#%7B%22content%22%3A%22%40font-face%20%7B%5Cn%20%20font-family%3A%20%5C%22Prettier%5C%22%3B%5Cn%20%20src%3A%20local(%5C%22Prettier%5C%22)%2C%20%2F*%20Installed%20*%2F%5Cn%20%20%20%20url(%5C%22http%3A%2F%2Fprettier.com%2Ffont.woff%5C%22)%20%2F*%20Network*%2F%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
