### ISSUE TITLE
`@include` not respecting 80 columns

### ISSUE THREAD

**Issue by sdougbrown** [prettier/prettier#2158]
It'd be preferable to break up long `@include` lines, I think...

```css
.selector {
  @include absolute($top: $long-variable-name, $right: $long-variable-name, $left: auto, $bottom: auto);
}
```

should reformat too...

```css
.selector {
  @include absolute(
    $top: $long-variable-name,
    $right: $long-variable-name,
    $left: auto,
    $bottom: auto
  );
}
```

I was planning on submitting a PR with a failing test, but I don't think I'll have time today so I just wanted to flag this.  Thanks for everyone's work with this project so far. 😄 

---

https://prettier.github.io/prettier/#%7B%22content%22%3A%22.selector%20%7B%5Cn%20%20%40include%20absolute(%24top%3A%20%24long-variable-name%2C%20%24right%3A%20%24long-variable-name%2C%20%24left%3A%20auto%2C%20%24bottom%3A%20auto)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D
