### ISSUE TITLE
Formatting CSS breaks when using css-module's `composes`

### ISSUE THREAD

**Issue by tdeekens** [prettier/prettier#2189]
# Background & Context

When using `css-modules` with `composes` formatting the source code using prettier's defaults seem to cause an error in the `css-loader`. 

## Example

```css
.button {
  composes: button-base from './base-button.css';
  background: red;
}
```

will be formatted to

```css
.button {
  composes: button-base 
      from './base-button.css';
  background: red;
}
```

This yields the following type of error 

<img width="367" alt="screen shot 2017-06-18 at 17 23 04" src="https://user-images.githubusercontent.com/1877073/27261817-e5d0ec66-544a-11e7-8ad4-697b1235da63.png">

stating that the "referenced class name 'x' in composes could not be found" using the `css-loader` in a webpack@2 context.

**Comment by vjeux** [comment]
Thanks for the report, we should be able to fix it by not breaking into new lines if the left hand side is `composes`.

**Comment by tdeekens** [comment]
That sounds great. I will try to jump on it later too and if I don't "make it" am super curious how it would be solved in the prettier code base.

**Comment by tdeekens** [comment]
This test input reproduces the issue

```css
.reference {
  composes: selector from "a/long/file/path/exceeding/the/maximum/length/forcing/a/line-wrap/file.css";
}
```

surpassing the default line width.

I just gave my first shot at fixing the issue by creating a test case and changing the `printer-postcss.js` and L62 onwards.

```js
case "css-decl": {
 // When the following less construct &:extend(.foo); is parsed with scss,
 // it will put a space after `:` and break it. Ideally we should parse
 // less files with less, but we can hardcode this to work with scss as
 // well.
 const isValueExtend =
   n.value.type === "value-root" &&
   n.value.group.type === "value-value" &&
   n.value.group.group.type === "value-func" &&
   n.value.group.group.value === "extend";
 const isComposed =
   n.value.type === "value-root" &&
   n.value.group.type === "value-value" &&
   n.prop === "composes";

 return concat([
   n.raws.before.replace(/[\s;]/g, ""),
   n.prop,
   ":",
   isValueExtend ? "" : " ",
   isComposed
     ? n.value.group.group.groups.join('')
     : path.call(print, "value"),
   n.important ? " !important" : "",
   n.nodes
     ? concat([
         " {",
         indent(
           concat([softline, printNodeSequence(path, options, print)])
         ),
         softline,
         "}"
       ])
     : ";"
 ]);
}
```

which produces "sane" output for the snapshot.
