### ISSUE TITLE
additional semicolon in *.less files for mixins and multiline arguments

### ISSUE THREAD

**Issue by Jumace** [prettier/prettier#2281]
Good day fans of pretty code,

I've found a little issue with less files and multiline arguments in mixins.

Here's some sample code:
**Before prettier**
```less
.global > .mixin-multiline(childName,{
    // comment
    
    height: 100%;
    widows: 50%;
});

.global > .mixin-multiline(childName,{

    height: 100%;
    widows: 50%;
});

.mixin-multiline (@name, @rules) {
  .@{name} {
    @rules ();
  }
}
```

**After prettier**

```less
.global > .mixin-multiline(childName,{
    // comment
    
    height: 100%;
    widows: 50%;
});;

.global > .mixin-multiline(childName,{

    height: 100%;
    widows: 50%;
});

.mixin-multiline (@name, @rules) {
  .@{name} {
    @rules ();
  }
}
```

After the usage of the mixin with a comment a second `;` is added.

Prettier doesn't care about the styling (e.g. indent) inside the second argument of the mixin, which is understandable as it's a argument.

But I don't understand why a comment inside the multiline argument is responsible for a second `;`.

I hope that helps to make prettier even more prettier. ;)
