### ISSUE TITLE
CSS nesting support (postcss-nesting)?

### ISSUE THREAD

**Issue by jackysee** [prettier/prettier#2318]
Writing a `.vue` file with `<style>` section processed by `postcss` with `postcss-nesting`:

```css
.calendar{
    & td, &th{
        width: 4rem;
        text-align: center;
        vertical-align: middle
    }
}
```

Prettier now complains unexpected token:
```
stdin: SyntaxError: Unexpected token (4:9)
  3 |     .calendar{
> 4 |         & td, & th{
    |         ^
  5 |             width: 4rem;
  6 |             text-align: center;
  7 |             vertical-align: middle;
```
I originally just intend to format the `<script>` section. It would be fine for me if the css part can be turned off.
