### ISSUE TITLE
CSS Modules: Respect print width when composing multiple classes

### ISSUE THREAD

**Issue by moretti** [prettier/prettier#2391]
This https://github.com/prettier/prettier/pull/2190 is great work, but `composes` can also accept multiple classes.

For example the following block:

```.css
.thumbnailText {
  composes:
    global(c-silver)
    global(lineHeight-s)
    global(breadkPointM-lineHeight-m)
    global(breakPointL-lineHeight-l)
    global(fontSize-xs)
    global(breakPointM-fontSize-s)
    global(breakPointL-fontSize-m);
}
```

is formatted to:

```.css
.thumbnailText {
  composes: global(c-silver) global(lineHeight-s) global(breadkPointM-lineHeight-m) global(breakPointL-lineHeight-l) global(fontSize-xs) global(breakPointM-fontSize-s) global(breakPointL-fontSize-m);
}
```
(prettier@1.5.2)

It would be nice have one class per line, or respect the print width.

What do you think? I'm happy to create a PR if you'd like 😄

**Comment by azz** [comment]
Sounds good to me!

**Comment by moretti** [comment]
@azz So should be have one selector per line:

```.css
.example {
  composes:
    global(selector)
    localSelector
    externalSelector from from "a/path/file.css";
}
```

or respect the print width (and only create a new line when necessary):


```.css
.example {
  composes: global(selector) localSelector0 localSelector1 localSelector2
    externalSelector0 from "a/long/file/path/exceeding/the/maximum/length/file.css"
    externalSelector1 from "a/short/path.css" localSelector6 localSelector7;
}
```

**Comment by azz** [comment]
Probably use the default prettier behaviour of breaking onto multiple lines if it doesn't fit on one?

```css
.example {
  composes: 
    global(selector)
    localSelector0
    localSelector1
    localSelector2
    externalSelector0 from "a/long/file/path/exceeding/the/maximum/length/file.css"
    externalSelector1 from "a/short/path.css" localSelector6 localSelector7;
}
```
