### ISSUE TITLE
CSS: No formatting between css selector and sub-selectors

### ISSUE THREAD

**Issue by mafredri** [prettier/prettier#2410]
Reproducible using prettier@1.5.2:

**Input:**

```css
.hello

            .how-you-doin
  {
  height: 42;
}
```

**Output:**

```css
.hello

            .how-you-doin {
  height: 42;
}
```

**Expected:**

```css
.hello .how-you-doin {
  height: 42;
}
```

Reproduction link can be found [here](https://prettier.io/playground/#%7B%22content%22%3A%22.hello%5Cn%5Cn%20%20%20%20%20%20%20%20%20%20%20%20.how-you-doin%5Cn%20%20%7B%5Cn%20%20height%3A%2042%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D).

Same effect is reproducible even without a newline, just multiple spaces between selectors.
