### ISSUE TITLE
Sort css properties alphabetically [feature request]

### ISSUE THREAD

**Issue by AvraamMavridis** [prettier/prettier#2502]
That is mostly a feature request. What about sorting the css properties alphabetically? I think that makes the file look prettier :)

e.g.

```
.something {
   position: relavive;
   background: black;
}
```

to 

```
.something {
  background: black;
  position: relavive;
}
```

**Comment by topaxi** [comment]
Potentially dangerous as they might overwrite each other, consider:

```css
.something {
  flex-flow: column wrap;
  flex-direction: row;
}
```

would be converted to

```css
.something {
  flex-direction: row;
  flex-flow: column wrap;
}
```

which is semantically different.
