### ISSUE TITLE
SCSS minor space issue

### ISSUE THREAD

**Issue by gabrielmaldi** [prettier/prettier#2554]
prettier adds a space when formatting this:

```diff
-$map: map-merge($map, ($key: $value));
+$map: map-merge($map,  ($key: $value));
```

Thanks

**Comment by lydell** [comment]
The cause of this issue are these lines: https://github.com/prettier/prettier/blob/854bb3ccc5b2e155930f600b4f2b6aa83b82ddc3/src/printer-postcss.js#L334-L336

They come from #1806, fixing this case from #1805: "Missing space to the right of `/`":

```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom:
      (
        100% *
        $image-height /
        ($image-width-responsive + $image-margin-responsive * 2)
      );
  }
}
```
```scss
.Image {
  @media (max-width: $image-width-responsive) {
    padding-bottom: (
      100% *
        $image-height /($image-width-responsive + $image-margin-responsive * 2)
    );
  }
}
```

I'm not sure what the solution is (yet).

**Comment by hudochenkov** [comment]
Probably related issue:

**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOld6wA2AlgA5LoBOcYMAFAAwA06tAJGKhQCYC0AzpCr8iALzjoA9OgBMASmZN09WQG4cAXxCMQEEjCLQ+yUJwoQA7gAVOCIylQA3CES5a0fGMgBmqAnzjaAEYUqGAA1nAwAMokoURQAObIMBQArgEgXBBg3r7+2vH+FDCWIQkAtqi5fhkAVnwAHgBCIeGRUajlcAAy8XDV+TqpMCTD0gMZsRRFyCACfEbaJBTxMADqLjAAFsgAHEwgyxD+ayEks8twRQ792lQAjqlEVKWoFVVIPjXa-uVEyWkMnx4gkCHAAIqpCDwCbaGCoQIbLjbZDSOEhIjERIAYQg5Uqsyg0FuIFS-gAKgi7F9-Op1EA)
```sh
--parser scss
```

**Input:**
```scss
a {
  clip: rect(0, ($card-score-size / 2), 0, 0);
}
```

**Output:**
```scss
a {
  clip: rect(0,  ($card-score-size / 2), 0, 0);
}

```
