### ISSUE TITLE
[SCSS] Comments inside mixin parameter lists get stripped

### ISSUE THREAD

**Issue by hamlim** [prettier/prettier#2578]
Comments within the mixin parameter list are getting completely removed yet comments within the mixin body are not. It also leaves white space/a new line when it removes a comment on its own line.

### What I did to test:

`prettier test.scss`
where `test.scss` contains the content below.

Sample code before going through prettier:
```scss
@mixin Thing(
  $Thing-param: null, // trailing comment
  // leading comment
  $thing-param2: null
) {
  // leading comment
  .class { // trailing comment on selector body
    // leading comment
    color: red; // trailing comment on declaration
  }
}
```

Sample code after running through prettier:
```scss
@mixin Thing(
  $Thing-param: null,

  $thing-param2: null
) {
  // leading comment
  .class {
    // trailing comment on selector body
    // leading comment
    color: red; // trailing comment on declaration
  }
}
```

Prettier version: `1.5.3`
