### ISSUE TITLE
CSS - font-face with multiple urls

### ISSUE THREAD

**Issue by alexilyaev** [prettier/prettier#2595]
Original:
```css
@font-face {
    font-family: "coolremote";
    src: url("/fonts/coolremote.eot");
    src: url("/fonts/coolremote.eot?#iefix") format("embedded-opentype"),
    url("/fonts/coolremote.woff") format("woff"),
    url("/fonts/coolremote.ttf") format("truetype"),
    url("/fonts/coolremote.svg#coolremote") format("svg");
    font-weight: normal;
    font-style: normal;
}
```
Formatted:
```css
@font-face {
  font-family: "coolremote";
  src: url("/fonts/coolremote.eot");
  src: url("/fonts/coolremote.eot?#iefix") format("embedded-opentype"),
    url("/fonts/coolremote.woff") format("woff"), url("/fonts/coolremote.ttf") format("truetype"),
    url("/fonts/coolremote.svg#coolremote") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

Expected (break after comma all the way till `;`):
```css
@font-face {
  font-family: "coolremote";
  src: url("/fonts/coolremote.eot");
  src: url("/fonts/coolremote.eot?#iefix") format("embedded-opentype"),
    url("/fonts/coolremote.woff") format("woff"),
    url("/fonts/coolremote.ttf") format("truetype"),
    url("/fonts/coolremote.svg#coolremote") format("svg");
  font-weight: normal;
  font-style: normal;
}
```

**Comment by azz** [comment]
This is a tricky one, to fix it we'd need to tell prettier about `url` and `format` specifically.

**Comment by zyy7259** [comment]
any progress on this one?

**Comment by BlindDespair** [comment]
This basically conficts with my stylelint... Can anything be done about it?

**Comment by kachkaev** [comment]
Seems like the current version of stable matches the _expected_ block in the issue. See [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0ojKjNZc8BbASwBsBPJI08CCZgJzj0I8LgG5yVIgGc+YDgFc+zABRcA9DRhS1kXgKHwAdHGFcAlOIpUZcoopXrN23f0HC4x4QH4AxIzjojAAe5tQQfPR4MKogggBGcAAmiUnYEAAOCDCsmeYANBJU9jEaWM48rgYeAO4Q6OihmBFRMbX1+YWUxY5lOhX67oYwMA0gZmHN0VwwfPJw2bljBVZdSiVOfXpuRlIAbgDmPi4DImMTkVMge-vmlpKa2NVwjPsAFjAcUOGRzHdUD1Jssw4J9vnhfuQAL4gPIgDIwRjQKTIUB4Ph8CDVAAKaIQyJQeF2EEYiRhIDifAIAGt5gBldIERhQfbIGZzWHvejMADqr0Y8CkDMItLx-MYu35rGQ4CkyNhTKkcD4MCxlP2kWQ+GYithACspEEAEKUsA0mC0hhwAAyTLgmvBOpA+qCtKZ+2BAEV5O57dq4LCGXxFXxpWBZWT0nwmTBuSSYK9kAAOAAMAYxiu5lPS0sjcGDuztsIAjt74KqMviQHgpNgoHAkkkyQIS4wBKq8Oq8L7HYqmKzZv6rm7PaW7UgtY6YHg4rHEvHkAAmWEzPAsN0AYQg9A1KC+dbJ8kVABVp-iJ4PdnMAJJQFKwWlgKPpGAAQVvtKBY-PkMhQA).

**Comment by thorn0** [comment]
@kachkaev Increase `--print-width` to see the issue:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0ojKjNZc8BbASwBsBPJI08CCZgJzj0I8LgG5yVIgGc+YDgFc+zABRcA9DRhS1kXgKHwAdHGFcAlOIpUZcoopXrN23f0HC4x4QH4AxIzjojAAe5tQQfPR4MKogggBGcAAmiUnYEAAOCDCsmeYANBJU9jEaWM48rgYeAO4Q6OihmBFRMbX1+YWUxY5lOhX67oYwMA0gZmHN0VwwfPJw2bljBVZdSiVOfXpuRlIAbgDmPi4DImMTkVMge-vmlpKa2NVwjPsAFjAcUOGRzHdUD1Jssw4J9vnhfuQAL4gPIgDIwRjQKTIUB4Ph8CDVAAKaIQyJQeF2EEYiRhIDifAIAGt5gBldIERhQfbIGZzWHvejMADqr0Y8CkDMItLx-MYu35rGQ4CkyNhTKkcD4MCxlP2kWQ+GYithACspEEAEKUsA0mC0hhwAAyTLgmvBOpA+qCtKZ+2BAEV5O57dq4LCGXxFXxpWBZWT0nwmTBuSSYK9kABGAAMyYDGMV3Mp6Wlkbgwd2dthAEdvfBVRl8SA8FJsFA4EkkmSBKXGAJVXh1XhfY7FUxWbN-Vc3Z6y3akFrHTA8HFY4l48gAEywmZ4FhugDCEHoGpQX3rZPkioAKjP8ZOh7s5gBJKApWC0sBR9IwACCd9pQPHF8hkKAA)
```sh
--parser css
--print-width 100
```

**Input:**
```css
@font-face {
    font-family: "coolremote";
    src: url("/fonts/coolremote.eot");
    src: url("/fonts/coolremote.eot?#iefix") format("embedded-opentype"),
    url("/fonts/coolremote.woff") format("woff"),
    url("/fonts/coolremote.ttf") format("truetype"),
    url("/fonts/coolremote.svg#coolremote") format("svg");
    font-weight: normal;
    font-style: normal;
}
```

**Output:**
```css
@font-face {
  font-family: "coolremote";
  src: url("/fonts/coolremote.eot");
  src: url("/fonts/coolremote.eot?#iefix") format("embedded-opentype"),
    url("/fonts/coolremote.woff") format("woff"), url("/fonts/coolremote.ttf") format("truetype"),
    url("/fonts/coolremote.svg#coolremote") format("svg");
  font-weight: normal;
  font-style: normal;
}

```

**Comment by evilebottnawi** [comment]
Other example:

**input**

```css
@font-face {
  font-family: 'common-iconfont';
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot');
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot?#iefix') format('embedded-opentype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff2') format('woff2'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff') format('woff'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.ttf') format('truetype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.svg#iconfont') format('svg');
}
```

**output**

```css
@font-face {
  font-family: "common-iconfont";
  src: url("//at.alicdn.com/t/font_940408_1r71t42ct7i.eot");
  src: url("//at.alicdn.com/t/font_940408_1r71t42ct7i.eot?#iefix")
      format("embedded-opentype"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.woff2") format("woff2"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.woff") format("woff"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.ttf") format("truetype"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.svg#iconfont") format("svg");
}
```

**expected**

```css
@font-face {
  font-family: 'common-iconfont';
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot');
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot?#iefix') format('embedded-opentype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff2') format('woff2'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff') format('woff'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.ttf') format('truetype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.svg#iconfont') format('svg');
}
```
