### ISSUE TITLE
Unwanted space when using variable interpolation in mixin name

### ISSUE THREAD

**Issue by asis** [prettier/prettier#2612]
We are using [postcss-mixins](https://github.com/postcss/postcss-mixins) to dynamically apply a mixin, like this:

```css
$theme: blue;

a {
  @mixin $(theme)-colors;
}

a:hover {
  @mixin $(theme)-hover-colors;
}
```

but prettier is adding a white space after the closing parenthesis:

```css
$theme: blue;

a {
  @mixin $(theme) -colors;
}

a:hover {
  @mixin $(theme) -hover-colors;
}
```

Is this syntax supported or going to be supported in the future?

Thank you so much for this project. It has been a game changer for our coding experience in JS and we would like to use it also for our CSS code base :D
