### ISSUE TITLE
[SCSS] stylelint-disable-line 

### ISSUE THREAD

**Issue by tirli** [prettier/prettier#2674]
Hi. I've tried to prettify my scss files that are already checked by stylelint. I also supressed several lines in my css with stylelint-disable-line. So my code was looking like that(let's suppose that the error in .root line):
``` scss
.root { // stylelint-disable-line
  padding-bottom: 32px;
}
```

but after using prettier it moves to the next line and suppression not working
``` scss
.root {
  // stylelint-disable-line
  padding-bottom: 32px;
}
```
[Demo](https://prettier.io/playground/#%7B%22content%22%3A%22.root%20%7B%20%2F%2F%20stylelint-stylelint-disable-line%5Cn%20%20padding-bottom%3A%2032px%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Yes, I know that I can use `stylelint-disable-next-line` though it would be cool if prettier will know about such option too.
