### ISSUE TITLE
SCSS Selector List with Comments loses code, causes syntax error

### ISSUE THREAD

**Issue by Kerrick** [prettier/prettier#2686]
[Playground Link](https://prettier.io/playground/#%7B%22content%22%3A%22.field%20%7B%5Cn%20%20%26%5Bdata-field-id%3D%5C%221%5C%22%5D%2C%20%2F%2F%20Name%5Cn%20%20%26%5Bdata-field-id%3D%5C%222%5C%22%5D%2C%20%2F%2F%20Email%5Cn%20%20%26%5Bdata-field-id%3D%5C%223%5C%22%5D%2C%20%2F%2F%20Postal%20Code%5Cn%20%20%7B%5Cn%20%20%20%20background%3A%20green%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

Input:

```sass
.field {
  &[data-field-id="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], // Postal Code
  {
    background: green;
  }
}
```

Output:
```sass
.field {
  &[data-field-id="1"],
  // Name &[data-field-id="2"],
  // Email &[data-field-id="3"] {
    background: green;
  }
}
```

This is a serious problem, as it is invalid CSS syntax and comments out many of the selectors.

**Comment by vjeux** [comment]
This is not a 1.6 issue, this has been an issue ever since we shipped support for CSS. We need to fix it at some point, thanks for the report!

**Comment by jackyho112** [comment]
Should it be printed as 

```
.field {
  // Name
  &[data-field-id="1"], 
  // Email
  &[data-field-id="2"], 
  // Postal Code
  &[data-field-id="3"],
  {
    background: green;
  }
}
```

**Comment by dcalhoun** [comment]
Below is a slightly different example I use often that suffers similar issues.

### Input
```scss
/**
 * 1. Footnote number one.
 * 2. Footnote number two
 */
.VideoPlayer .vjs-big-play-button::before, /* 2 */
.VideoPlayer .vjs-icon-placeholder::before {
  line-height: 1.88; /* 1 */
}
```

### Output
```scss
/**
 * 1. Footnote number one.
 * 2. Footnote number two
 */
.VideoPlayer .vjs-big-play-button::before,
/* 2 */ .VideoPlayer .vjs-icon-placeholder::before {
  line-height: 1.88; /* 1 */
}
```

**Comment by j-f1** [comment]
Current status:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZgSzgGwCYAEwAOlAQQGQDaeAhjLQLRa56OZ4C8xIAjDwF0ANAQD0oggDlaAWzily1Og2bZ87LjwBMgkeIIBRGbUw4FlGvSYt1HbiADMusRIAKEAM4McBAMIQ8eTIic3IAI1owAGsAcwAnCABXKDwkAni4BABucwBfUlyQIRAIAAcYTGgPZFBaOISAd1c6hGqUIpBaL2R0WhwPOGKwuMiouBgAZVLIzCgY5Bg4xMGQPAgwHr6B4tmBuJhXEZjjTf6VgCsPAA8AIRHo8YnZOAAZWbhT7ZLEmFKfrU+K2mcT2yBAHjAHmqxVKcVmMAA6hwYAALZAADgADDCEgMESNSmCOnE4ABHRKYEmHWjHWiA4oDGSYBZLFYeWYxHBwACKiQg8HpIAYYSReFRyC0xUWJhwHP8MhOKCg0A+xUSAwAKrQwm1emdcrkgA)
```sh
--arrow-parens 
--parser scss
--prose-wrap 
```

**Input:**
```scss
.field {
  &[data-field-id="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], // Postal Code
  {
    background: green;
  }
}
```

**Output:**
```scss
.field {
  &[data-field-id="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], {
    background: green;
  }
}

```

One of the comments is eaten, but the syntax is still valid.

**Comment by evilebottnawi** [comment]
@j-f1 already reported https://github.com/postcss/postcss-scss/issues/75

**Comment by evilebottnawi** [comment]
We fix this, but we have open issue about best place for comments, please see https://github.com/prettier/prettier/issues/3905

**Comment by j-f1** [comment]
Status after PR:

**Prettier pr-3909**
[Playground link](https://deploy-preview-3909--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEA6AZgSzgGwCYAEwAOlAQQGQDaeAhjLQLRa56OZ4C8xIAjDwF0ANAQD0oggDlaAWzily1Og2bZ87LjwBMgkeIIBRGbUw4FlGvSYt1HbiADMusRIAKEAM4McBAMIQ8eTIic3IAI1owAGsAcwAnCABXKDwkAni4BABucwBfUlyQIRAIAAcYTGgPZFBaOISAd1c6hGqUWgA3CA4ikFovZHRaHA84YrC4yKi4GABlUsjMKBjkGDjEsZA8CDBB4dHipdG4mFdJmOM9kc2AKw8ADwAhSeiZ2dk4ABkluCuDksSMFKgK0f02Czix2QIA8YA81WKpTiSxgAHUODAABbIAAcAAZEQlRqjJqVoUi4McOr9inE4ABHRKYOlnWgXWhg4qjGSYVbrTYeJYxHBwACKiQg8E5IAYYXReCxyC0xTWJhwQv8MkuKCg0BpIESowAKrQwm0htdcrkgA)
```sh
--parser scss
```

**Input:**
```scss
.field {
  &[data-field-id="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], // Postal Code
  {
    background: green;
  }
}
```

**Output:**
```scss
.field {
  &[data-field-id="1"], // Name
  &[data-field-id="2"], // Email
  &[data-field-id="3"], // Postal Code
 {
    background: green;
  }
}

```
