### ISSUE TITLE
messes up formatting of css grid layout

### ISSUE THREAD

**Issue by geddski** [prettier/prettier#2703]
CSS Grid layout encourages a somewhat special syntax where the lines of the rule represent the grid being described. For example this rule:

```css
.item {
    grid-template-areas: 
        "header header"
        "main sidebar"
        "footer footer";
}
```
describes the grid areas for a 2-column, 3-row grid. You'd want to keep the formatting just like this because it's easier to understand when it's laid out the same way as the grid being described. 

Same goes for the `grid-template-columns`, `grid-template-rows`, and `grid-template` properties. Another example:

```css
.item {
    grid-template: 
        "a a a" 200px
        "b b b" 200px
        / 200px 200px auto;
}
```

Having it on separate lines like this makes it easier to understand which part of the CSS correlates to specific rows/columns.

Prettier currently concats everything to a single line, when ideally it should only handle indents and semicolons for these cases.

**Comment by vjeux** [comment]
When just looking at grid-template, is there a way to know what is the layout?

**Comment by vjeux** [comment]
I would be inclined to just output the raw value for `grid-template*` and let the developer print it himself.

**Comment by geddski** [comment]
that would be better, yeah. Would it be possible for prettier to only handle the indenting for grid-template* rules?

**Comment by geddski** [comment]
the `grid` shorthand is also going to have the same issues.

```css
.thing {
  grid: [wide-start] "header header header" 200px [wide-end]
        "footer footer footer" 25px
        / auto 50px auto;
}
```

**Comment by vjeux** [comment]
Are you interested in working on "blacklisting" all those keys from being reformatted by prettier?

**Comment by geddski** [comment]
Sure I can take a look. Any pointer for where to start? Is there already some kind of blacklist for other properties?

**Comment by vjeux** [comment]
Instead of printing the value, you want to print `options.originalText.slice(util.locStart(node), util.locEnd(node));` instead.

**Comment by lydell** [comment]
But we probably want to normalize quotes, numbers and units in there...

**Comment by keithjgrant** [comment]
> I would be inclined to just output the raw value for grid-template* and let the developer print it himself.

I would recommend that prettier still format `grid-template-columns` and `grid-template-rows` normally. The bigger problems come from some of the shorthand properties that mix syntaxes of multiple long-form properties: `grid`, `grid-template`. `grid-template-areas` is also worth exempting because it’s effectively ascii-art in the form of multiple quoted strings each on its own line.

**Comment by keithjgrant** [comment]
Hmm... on further thought, maybe I’m wrong: maybe all `grid-template-*` should be left as authored by the dev.

I just wrote needed this, and Prettier smashed it into two lines, which is not what I want:

```
grid-template-columns:
  [full-start] minmax(1em, 1fr)
  [main-start] minmax(40ch, 75ch)
  [main-end] minmax(1em, 1fr)
  [full-end];
```

**Comment by wesbos** [comment]
Yeah it's tough for prettier to determine how it should be formatted. 

Currently getting this smashed onto a single line: 

![prettier-grid](https://user-images.githubusercontent.com/176013/32285243-1974b5be-bf00-11e7-9454-88d82cd3d215.gif)

And the only solution right now is:

<img width="720" alt="screen shot 2017-11-01 at 12 26 25 pm" src="https://user-images.githubusercontent.com/176013/32285257-28939b14-bf00-11e7-87c5-f89b916b19c2.png">

I hate to be the "can we get a setting" guy. But... can we get a setting to ignore grid-template-*?

**Comment by vjeux** [comment]
@duailibe are you interested in adding a workaround for this? We should preserve formatting for all the grid-template css values for now, to prevent the bleeding.

**Comment by vjeux** [comment]
@wesbos if you put the ignore comment before `grid-template-areas:` you should only have to add one.

**Comment by wesbos** [comment]
@vjeux I tried that too - doesn't seem to work. Is this right? 

![](http://wes.io/nR0e/content)

**Comment by vjeux** [comment]
Yeah, this should be. Thanks for raising this, we need to fix it. I also didn't know you could chain those string literals like this, TIL :)

**Comment by lydell** [comment]
@wesbos It’s strange that all strings end up in a single line for you, because in the playground they end up on several lines (still not the preferred way, but at least better than a single line).

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOld6DmATgJYAmAtPALYAOANqvOZHQK5VQDOSOeeWIABZxUpOIXTDR4ySLESp8gbz4DFM9QrkbthZblUhOZOACNUE42PMTIsBDHR34sJ9Bcx9fdAKtmL6H42bvauzg4hHl6GmrLSWvFxSiAA3DgAviAANCAQNDDE0JzIoKicMMgAZqh0nHA5poSoYADWcDAAyjTNxFD4yDCErPUgpBBgVTV1OQBWnAAeAEJNre0dqFRwADK9cJO1IxCsMDTHAEz70yDdhHWEyOCcxTk0JLAA6mQwgsgAHAAMOTqVGIAyGI2MfTocAAiqwIPBLiMYKhTJ9SN9kGccoNUMQ6L18ABhCBUKioB5QaB7HKsOoAFVRxSQ1QO6XSQA)
```sh
--parser css
```

**Input:**
```css
a {
  grid-template-columns:
    "header header header header"
    "header header header header"
    "sidebar sidebar content content content"
    "sidebar sidebar content content content"
    "header header header header";
}
```

**Output:**
```css
a {
  grid-template-columns: "header header header header"
    "header header header header" "sidebar sidebar content content content"
    "sidebar sidebar content content content" "header header header header";
}

```
