### ISSUE TITLE
CSS: Comments intertwined with selectors have inconsistent formatting

### ISSUE THREAD

**Issue by Kerrick** [prettier/prettier#2769]
**Prettier Version:** 1.6.1

**Code**

([playground](https://prettier.io/playground/#%7B%22content%22%3A%22%20%20%2F*%20Workaround%20for%20one%20thing%20*%2F%5Cn%20%20.foo%2C%5Cn%20%20%2F*%20Workaround%20for%20another%20thing%20*%2F%5Cn%20%20.bar%20%7B%5Cn%20%20%20%20display%3A%20block%3B%5Cn%20%20%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D))

```css
  /* Workaround for one thing */
  .foo,
  /* Workaround for another thing */
  .bar {
    display: block;
  }
```

**Expected behavior:**

One of two things:
```css
/* Workaround for one thing */ .foo,
/* Workaround for another thing */ .bar {
  display: block;
}

```
OR:
```css
/* Workaround for one thing */
.foo,
/* Workaround for another thing */
.bar {
  display: block;
}
```

**Actual behavior:**

```css
/* Workaround for one thing */
.foo,
/* Workaround for another thing */ .bar {
  display: block;
}
```
