### ISSUE TITLE
Consistent spacing around mathematical operators in CSS

### ISSUE THREAD

**Issue by fredrikekelund** [prettier/prettier#2793]
**Prettier Version:** 1.6.1 / master

**Code**

In CSS (and CSS-like languages), it would be nice if prettier could output the same consistent spacing around mathematical operators as we get in JS (a single space on each side of the operator).

Example input:

```css
body {
    margin-left: calc(2em/2);
}
```

**Expected behavior:**
Preferred output: 

```css
body {
    margin-left: calc(2em / 2);
}
```

**Actual behavior:**
No change between input and output
