### ISSUE TITLE
CSS quotes problem 

### ISSUE THREAD

**Issue by hugomrdias** [prettier/prettier#2817]
**Prettier 1.6.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%2F*%20doesnt%20work%20*%2F%5Cn%40charset%20%5C%22UTF-8%5C%22%3B%5Cn%5Cn%40import%20%5C%22x.css%5C%22%20screen%20and%20(orientation%3A%20landscape)%3B%5Cn%2F*%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20this%20comma%20is%20also%20wrong%20but%20theres%20an%20issue%20already*%2F%5Cn%40import%20url(%5C%22responsive%2Fgt768.css%5C%22)%20screen%20and%20(min-width%3A%20768px)%3B%5Cn%5Cn%5Cn%2F*%20works%20*%2F%5Cninput%3Anot(%5Btype%3D%5C%22submit%5C%22%5D)%20%7B%5Cn%20%20%20%20color%3A%20pink%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
--single-quote
--tab-width 4
```

**Input:**
```css
/* doesnt work */
@charset "UTF-8";

@import "x.css" screen and (orientation: landscape);
/*                                 | this comma is also wrong but theres an issue already*/
@import url("responsive/gt768.css") screen and (min-width: 768px);


/* works */
input:not([type="submit"]) {
    color: pink;
}
```

**Output:**
```css
/* doesnt work */
@charset "UTF-8";

@import "x.css" screen and (orientation: landscape);
/*                                 | this comma is also wrong but theres an issue already*/
@import url("responsive/gt768.css"), screen and (min-width: 768px);

/* works */
input:not([type='submit']) {
    color: pink;
}

```

**Expected behavior:**
```css
/* doesnt work */
@charset 'UTF-8';

@import 'x.css' screen and (orientation: landscape);
/*                                 | this comma is also wrong but theres an issue already*/
@import url('responsive/gt768.css'), screen and (min-width: 768px);

/* works */
input:not([type='submit']) {
    color: pink;
}

```
