### ISSUE TITLE
CSS: 1.7.0 - postcss media variables downcased

### ISSUE THREAD

**Issue by gpoitch** [prettier/prettier#2820]
Postcss custom-media variables are being downcased since 1.7.0, causing them to no longer match their definition.

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40custom-media%20--tabletPortraitAndUp%20screen%20and%20(width%20%3E%3D%20768px)%3B%5Cn%5Cn.section%20%7B%5Cn%20%20width%3A%20200px%3B%5Cn%7D%5Cn%5Cn%40media%20(--tabletPortraitAndUp)%20%7B%5Cn%20%20.section%20%7B%5Cn%20%20%5Ctwidth%3A%20400px%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```css
@custom-media --tabletPortraitAndUp screen and (width >= 768px);

.section {
  width: 200px;
}

@media (--tabletPortraitAndUp) {
  .section {
  	width: 400px;
  }
}

```

**Output:**
```css
@custom-media --tabletPortraitAndUp screen and (width >= 768px);

.section {
  width: 200px;
}

@media (--tabletportraitandup) {
  .section {
    width: 400px;
  }
}

```

**Expected behavior:**
The variable is not altered
