### ISSUE TITLE
Do not lowercase LESS variable names

### ISSUE THREAD

**Issue by nvie** [prettier/prettier#2829]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40borderSize%3A%202px%3B%5Cn%40outerSize%3A%2018px%3B%5Cn%40innerSize%3A%20%40outerSize%20-%20%40borderSize%3B%5Cn%5Cn.Foo%20%7B%5Cn%20%20width%3A%20%40innerSize%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%2C%22output2%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```scss
@borderSize: 2px;
@outerSize: 18px;
@innerSize: @outerSize - @borderSize;

.Foo {
  width: @innerSize;
}

```

**Output:**
```scss
@bordersize: 2px;
@outersize: 18px;
@innersize: @outerSize - @borderSize;

.Foo {
  width: @innerSize;
}

```

**Expected behavior:**

LESS variables casing would be unaffected.

**Comment by lydell** [comment]
Looks like I forgot to add tests for top-level Less variables -.-

What happens here is that those variables are parsed as media queries (!). I think we could fix this by not lowercasing if the "media query name" ends with a colon.

**Comment by lydell** [comment]
It turned out that the reason `@borderSize: 2;` is parsed as an atrule is because your code triggers the SCSS parser. A workaround is to insert a comment that busts the "SCSS detection":

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40borderSize%3A%202px%3B%5Cn%40outerSize%3A%2018px%3B%5Cn%40innerSize%3A%20%40outerSize%20-%20%40borderSize%3B%5Cn%5Cn%2F%2F%20%3A%5Cn%5Cn.Foo%20%7B%5Cn%20%20width%3A%20%40innerSize%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```scss
@borderSize: 2px;
@outerSize: 18px;
@innerSize: @outerSize - @borderSize;

// :

.Foo {
  width: @innerSize;
}

```

**Output:**
```scss
@borderSize: 2px;
@outerSize: 18px;
@innerSize: @outerSize - @borderSize;

// :

.Foo {
  width: @innerSize;
}

```
