### ISSUE TITLE
Don't lowercase class names built with LESS's "ampersand" operator

### ISSUE THREAD

**Issue by nvie** [prettier/prettier#2830]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.Foo%20%7B%5Cn%20%20%26__Bar%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20'red'%3B%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```scss
.Foo {
  &__Bar {
        color: 'red';
  }
}

```

**Output:**
```scss
.Foo {
  &__bar {
    color: "red";
  }
}

```

**Expected behavior:**

Class name should remain to be "Foo__Bar", not "Foo__bar".
