### ISSUE TITLE
CSS: `url(unquoted)` is broken: Can be lowercased, normalized and broken across lines

### ISSUE THREAD

**Issue by sampi** [prettier/prettier#2835]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40font-face%20%7B%5Cn%5Ctfont-family%3A%20'Some%20Font'%3B%5Cn%5Ctfont-style%3A%20normal%3B%5Cn%5Ctfont-weight%3A%20300%3B%5Cn%5Ctsrc%3A%20local('Some%20Font')%2C%20url(data%3Aapplication%2Ffont-woff%3Bcharset%3Dutf-8%3Bbase64%2CThisIsNormalBut%2F%2B0ThisIsLowerCased)%20format('woff')%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Atrue%7D%7D)
```sh
--parser postcss
--use-tabs
```

**Input:**
```css
@font-face {
	font-family: 'Some Font';
	font-style: normal;
	font-weight: 300;
	src: local('Some Font'), url(data:application/font-woff;charset=utf-8;base64,ThisIsNormalBut/+0ThisIsLowerCased) format('woff');
}
```
[Full example on Gist](https://gist.github.com/sampi/33248fa89ebbe01ff0bbc5063052424f)

**Output:**
```css
@font-face {
	font-family: "Some Font";
	font-style: normal;
	font-weight: 300;
	src: local("Some Font"),
		url(data:application/font-woff;charset=utf-8;base64,ThisIsNormalBut/+0thisislowercased)
			format("woff");
}

```
[Full example on Gist](https://gist.github.com/sampi/d2826fe92402f2c2b2dbf81ffa1d053e)

**Expected behavior:**
Some characters are lowercased inside the base64-encoded `@font-face` `url()` rendering them useless.
Anything inside `url()` should be left untouched.

**Comment by lydell** [comment]
Oh, this is a tough one. The parser doesn't treat the whole `url(...)` as one single thing, but parses everything inside the parens. So it thinks that `0ThisIsLowerCased` is the number 0 with the "ThisIsLowerCased" unit. There might be a workaround we can use, but the real fix is to add [url-unquoted](https://www.w3.org/TR/css-syntax-3/#url-token-diagram) support to [postcss-values-parser](https://github.com/shellscape/postcss-values-parser).

To get you unblocked, add quotes:

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%40font-face%20%7B%5Cn%5Ctfont-family%3A%20%27Some%20Font%27%3B%5Cn%5Ctfont-style%3A%20normal%3B%5Cn%5Ctfont-weight%3A%20300%3B%5Cn%5Ctsrc%3A%20local(%27Some%20Font%27)%2C%20url(%27data%3Aapplication%2Ffont-woff%3Bcharset%3Dutf-8%3Bbase64%2CThisIsNormalBut%2F%2B0ThisIsLowerCased%27)%20format(%27woff%27)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Atrue%7D%7D)
```sh
--parser postcss
--use-tabs
```

**Input:**
```scss
@font-face {
	font-family: 'Some Font';
	font-style: normal;
	font-weight: 300;
	src: local('Some Font'), url('data:application/font-woff;charset=utf-8;base64,ThisIsNormalBut/+0ThisIsLowerCased') format('woff');
}
```

**Output:**
```scss
@font-face {
	font-family: "Some Font";
	font-style: normal;
	font-weight: 300;
	src: local("Some Font"),
		url("data:application/font-woff;charset=utf-8;base64,ThisIsNormalBut/+0ThisIsLowerCased")
			format("woff");
}

```

**Comment by sampi** [comment]
The quickest unblock was to place the affected files in `.prettierignore`, but the `'` idea is better.

Thanks!

**Comment by evilebottnawi** [comment]
@lydell we can't use `url-unquoted` because we need parse `url` func inside to allow usage variables for css, less, scss - example `url(var(--somevar))`

**Comment by lydell** [comment]
As far as I know `url(var(--somevar))` is equivalent to `url("var(--somevar)")` due to legacy reasons (`url()` is the only function where `var()` cannot be used). https://youtu.be/UQRSaG1hQ20?t=8m14s

**Comment by evilebottnawi** [comment]
@lydell how about:
```less
a {
  background-image: url(@var);
}
```
It is valid as unquoted url, but it is less variable, seems we should fix it in prettier

**Comment by lydell** [comment]
Yeah, I guess SCSS and Less have different rules for the `url` function. Difficult problem. I think I’m going to leave it up to you to come up with the best solution given what we have, that works for most people’s use cases :)

**Comment by evilebottnawi** [comment]
@lydell i try to find solution, maybe we can fix this for `data:` (PR exists), looks it is have equals rules for all preprocessors

**Comment by evilebottnawi** [comment]
Only problem with:
```css
a {
  background-image: url(/data/data/+0ThisIsLowerCased);
}
```
