### ISSUE TITLE
SCSS output altered when using `&-` syntax

### ISSUE THREAD

**Issue by mdekrey** [prettier/prettier#2860]
Prettier lower-cases scss classes when using the `&-` suffix syntax. This appears to be a false-positive on the element lowercasing rule.

Note: the below was written by hand due to not finding a prettier css playground.

**Input:**
```scss
.someClass {
  &-someSuffix {
    display: initial;
  }
}
```

**Output:**
```scss
.someClass {
  &-somesuffix {
    display: initial;
  }
}
```

**Expected behavior:**
```scss
.someClass {
  &-someSuffix {
    display: initial;
  }
}
```

**Comment by lydell** [comment]
Hi! Thanks for the issue! This was fixed in master at the same time as #2830 was fixed.

About the playground, at the bottom you can click "Options" to expand the options panel and to the right you can choose "postcss" as the parser for CSS/SCSS/Less stuff.

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.Foo%20%7B%5Cn%20%20%26__Bar%20%7B%5Cn%20%20%20%20%20%20%20%20color%3A%20%27red%27%3B%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```scss
.Foo {
  &__Bar {
        color: 'red';
  }
}
```

**Output:**
```scss
.Foo {
  &__bar {
    color: "red";
  }
}

```
