### ISSUE TITLE
CSS parser bug with unicode chars

### ISSUE THREAD

**Issue by brikou** [prettier/prettier#2873]
Prettier should double backslash unicode chars.

**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.blockquote-footer%3A%3Abefore%20%7B%5Cn%20%20content%3A%20'%5C%5C2014%20%5C%5C00A0'%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```scss
.blockquote-footer::before {
  content: '\2014 \00A0';
}

```

**Output:**
```scss
.blockquote-footer::before {
  content: "\2014 \00A0";
}

```

**Expected behavior:**
```scss
.blockquote-footer::before {
  content: "\\2014 \\00A0";
}

```
