### ISSUE TITLE
!important appears twice if it follows a LESS mixin without whitespace

### ISSUE THREAD

**Issue by orottier** [prettier/prettier#2880]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.round-borders%20(%40radius)%20%7B%5Cn%20%20border-radius%3A%20%40radius%3B%5Cn%7D%5Cn%5Cndiv%20%7B%5Cn%20%20.round-borders(4px)!important%3B%5Cn%7D%5Cnsection%20%7B%5Cn%20%20.round-borders(4px)%20!important%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser postcss
```

**Input:**
```less
.round-borders (@radius) {
  border-radius: @radius;
}

div {
  .round-borders(4px)!important;
}
section {
  .round-borders(4px) !important;
}
```

**Output:**
```less
.round-borders (@radius) {
  border-radius: @radius;
}

div {
  .round-borders(4px)!important !important;
}
section {
  .round-borders(4px) !important;
}

```

**Expected behavior:**
Only one `!important`

(thanks for the amazing work btw)
