### ISSUE TITLE
Less: Spaces between variable name and `:` are not handled

### ISSUE THREAD

**Issue by KINFOO** [prettier/prettier#2925]
**Prettier 1.7.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.navbar%20%7B%5Cn%20%20%40borderTopPx%20%3A%204px%3B%5Cn%20%20.media%20%7B%5Cn%20%20%20%20i.user%20%7B%5Cn%20%20%20%20%20%20margin-top%3A%20%40borderTopPx%20%2B%2010px%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22less%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser less
```

**Input:**
```less
.navbar {
  @borderTopPx : 4px;
  .media {
    i.user {
      margin-top: @borderTopPx + 10px;
    }
  }
}

```

**Output:**
```less
.navbar {
  @bordertoppx : 4px;
  .media {
    i.user {
      margin-top: @borderTopPx + 10px;
    }
  }
}

```

**Expected behavior:**

Same as when there is _not_ a space before the colon:

**Prettier 1.7.1**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.navbar%20%7B%5Cn%20%20%40borderTopPx%3A%204px%3B%5Cn%20%20.media%20%7B%5Cn%20%20%20%20i.user%20%7B%5Cn%20%20%20%20%20%20margin-top%3A%20%40borderTopPx%20%2B%2010px%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22less%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser less
```

**Input:**
```less
.navbar {
  @borderTopPx: 4px;
  .media {
    i.user {
      margin-top: @borderTopPx + 10px;
    }
  }
}

```

**Output:**
```less
.navbar {
  @borderTopPx: 4px;
  .media {
    i.user {
      margin-top: @borderTopPx + 10px;
    }
  }
}

```
