### ISSUE TITLE
Error: Couldn't resolve parser "scss"

### ISSUE THREAD

**Issue by mrmartineau** [prettier/prettier#2998]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.reposition%20%7B%5Cn%5Ctdisplay%3A%20flex%3B%5Cn%5Ctalign-items%3A%20center%3B%5Cn%7D%5Cn%5Cn.reposition__button%5Bdisabled%5D%20%7B%5Cn%5Ctopacity%3A%200.25%3B%5Cn%7D%5Cn%5Cn.reposition__separator%20%7B%5Cn%5Ctbackground-color%3A%20%23fff%3B%5Cn%5Ctwidth%3A%202px%3B%5Cn%5Ctborder-radius%3A%202px%3B%5Cn%5Ctheight%3A%2015px%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22scss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser scss
--tab-width 4
```

**Input:**
```scss
.reposition {
	display: flex;
	align-items: center;
}

.reposition__button[disabled] {
	opacity: 0.25;
}

.reposition__separator {
	background-color: #fff;
	width: 2px;
	border-radius: 2px;
	height: 15px;
}

```

**Output:**
```scss
Error: Couldn't resolve parser "scss"
```

**Expected behavior:**
Prettier should work with `.scss` files..
