### ISSUE TITLE
CSS/SCSS indenting

### ISSUE THREAD

**Issue by holloway** [prettier/prettier#3012]
This is a suggestion for a ~~change~~ **option** in formatting SCSS/CSS.

When reading JavaScript we all know how beneficial indentation can be to express nesting blocks, but in CSS there are also defacto and popular ways of expressing nesting that I think Prettier could automate.

[BEM](http://getbem.com/) codifies some defacto standards in naming conventions for CSS, in which classes are named as,

```scss
.block { /*props*/ } 

  .block__child1 { /*props*/ } 

    .block__child1--modifier1 { /*props*/ } 

    .block__child1--modifier2 { /*props*/ } 

  .block__child2 { /*props*/ } 

    .block__child2--modifier { /*props*/ } 
```

Here nesting is expressed in a naming convention *but also whitespace*, and when I'm reading CSS I often find that classNames have hierarchy expressed in naming conventions (with SCSS of course programmers can also nest selectors and use `&` but that's a separate issue).

**Would you be open to accepting a patch to indent CSS/SCSS blocks based on the previous selector?**

I think the formatting rule could be that if the previous selector is a prefix of the current selector then we consider that to be nesting and the block is nested a level. Any name that doesn't match would be formatted as Prettier currently does it (pushed left-most). Selectors would need to be contiguous to be indented. Of course there might be some details to work out but I just want to know if there's interest in this type of formatting for CSS/SCSS?

Just to be more specific...

**Input:**
```scss
.reposition {
	display: flex;
	align-items: center;
}

.reposition button[disabled] {
	opacity: 0.25;
}

.maps {
	display: block;
	overflow: auto;
}

.maps--disabled {
	opacity: 0.5;
	pointer-events: none;
}
```

**Current Output:**
```scss
.reposition {
  display: flex;
  align-items: center;
}

.reposition button[disabled] {
  opacity: 0.25;
}

.maps {
  display: block;
  overflow: auto;
}

.maps--disabled {
  opacity: 0.5;
  pointer-events: none;
}
```

**Expected behavior:**

**Output:**
```scss
.reposition {
  display: flex;
  align-items: center;
}

  .reposition button[disabled] {
    opacity: 0.25;
  }


.maps {
  display: block;
  overflow: auto;
}

  .maps--disabled {
    opacity: 0.5;
    pointer-events: none;
  }
```
