### ISSUE TITLE
Support SCSS comments between two selector

### ISSUE THREAD

**Issue by tzi** [prettier/prettier#3020]
Hi everyone!

I noticed that having a SCSS comment between two selectors generate a broken output

**Input:**
```scss
// Comment selector 1
.selector-1,
// Comment selector 2
.selector-1 {
  display: none
}
```

**Output:**
```scss
// Comment selector 1
.selector-1,
// comment selector 2 .selector-1 {
  display: none;
}
```

Here is a [Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22%2F%2F%20Comment%20selector%201%5Cn.selector-1%2C%5Cn%2F%2F%20Comment%20selector%202%5Cn.selector-1%20%7B%5Cn%20%20display%3A%20none%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22scss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D).

Thanks for prettying all our code! 

Cheers,
Thomas.
