### ISSUE TITLE
Format SCSS maps like CSS rules

### ISSUE THREAD

**Issue by tzi** [prettier/prettier#3056]
Hi!

It seems weird to me that prettier doesn't format SCSS maps like CSS rules.
What do you think? 

**Input:**
```scss
$map: (
  color: #111111,
  text-shadow: 1px 1px 0 hotpink 
);

.selector {
  color: #111111;
  text-shadow: 1px 1px 0 hotpink 
}
```

**Output:**
```scss
$map: (color: #111111, text-shadow: 1px 1px 0 hotpink);

.selector {
  color: #111111;
  text-shadow: 1px 1px 0 hotpink;
}
```
Here is a [Playground demo](https://prettier.io/playground/#%7B%22content%22%3A%22%24map%3A%20(%5Cn%20%20color%3A%20%23111111%2C%5Cn%20%20text-shadow%3A%201px%201px%200%20hotpink%20%5Cn)%3B%5Cn%5Cn.selector%20%7B%5Cn%20%20color%3A%20%23111111%3B%5Cn%20%20text-shadow%3A%201px%201px%200%20hotpink%20%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22scss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D) (prettier 1.7.4).

Cheers,
Thomas.
