### ISSUE TITLE
Less incorrectly changes case of base64 image

### ISSUE THREAD

**Issue by aboyton** [prettier/prettier#3072]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22.test%20%7B%5Cn%20%20background-image%3A%20url(data%3Aimage%2Fpng%3Bbase64%2CiVBORw0KGgoAAAANSUhEUgAAAA4AAAAKCAYAAACE2W%2FHAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAFxJREFUeNpiYCAS%2FP%2F%2F3wCI7wPxfiAWIEXT%2B%2F8IcB4mEQDEBURqAgOQRAISfz4xmkB6GLAIzieoCargPBbJ9Xg1QTUK4NCMWxMJmhPwBTkuzQnExBe6ZpyaAAIMAFslPPTuxAjkAAAAAElFTkSuQmCC)%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22less%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser less
```

**Input:**
```less
.test {
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAKCAYAAACE2W/HAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAFxJREFUeNpiYCAS/P//3wCI7wPxfiAWIEXT+/8IcB4mEQDEBURqAgOQRAISfz4xmkB6GLAIzieoCargPBbJ9Xg1QTUK4NCMWxMJmhPwBTkuzQnExBe6ZpyaAAIMAFslPPTuxAjkAAAAAElFTkSuQmCC);
}
```

**Output:**
```less
.test {
  background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAKCAYAAACE2W/HAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAFxJREFUeNpiYCAS/P//3wCI7wPxfiAWIEXT+/8icb4meqdeburqagoqraisfz4xmkb6glaizieocargpbbj9xg1qtuk4ncmwxmjmhpwbtkuzqnexbe6zpyaaaimafslpptuxajkaaaaaelftksuqmcc);
}

```

**Expected behavior:**
The image has `+/8IcB4m` converted to `+/8icb4m` which should not happen for base64 images.
