### ISSUE TITLE
Less ruleset declaration: semicolon is removed

### ISSUE THREAD

**Issue by slorber** [prettier/prettier#3093]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAJnMAbAQwCc5s4YCwALOLDIgVzzgGdyAdKAARwutoC0jZmxhIMwDACNKAawDmRCAyhZxJLAG4MAX02dO6DAzZk+NOsNYcoAOhgQADhM4Y3GHuUoWhTazAAKAEptTh0QABoQJxgAS2gWZFACFhhkADMCPDYoqSI5cgBlR0pYqHlkGEY4KKwIMAysnJAAKxYADwAhfLBZIoIAWzgAGTK4Ruya6IYYRxmAJgnmkqI2ImQQEUSoxyIymAB1WKwYKmQARnmABii2AdjK6tuy+WYARQYIeCWpiikjk5nJDzKJVAixPAvADCEAGAwIGyg0HGURMcAAKgQpIkkJlJjodEA)
```sh
--parser less
--print-width 120
```

**Input:**
```less
// declare detached ruleset
@detached-ruleset: { background: red; };

// use detached ruleset
.top {
    @detached-ruleset(); 
}
```

**Output:**
```less
// declare detached ruleset
@detached-ruleset: {
  background: red;
}

// use detached ruleset
.top {
  @detached-ruleset();
}

```

**Expected behavior:**

```less
// declare detached ruleset
@detached-ruleset: {
  background: red;
};

// use detached ruleset
.top {
  @detached-ruleset();
}

```

The `;` at the end of the `@detached-ruleset` should still be there, as documented by http://lesscss.org/features/#detached-rulesets-feature
