### ISSUE TITLE
CSS Grid Template Areas are placed in one line.

### ISSUE THREAD

**Issue by amirmishani** [prettier/prettier#3136]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AtgTwOYCcCWAJgATAA6UxxeRAtPOgA4A2AhvLa7nKwM5IUqQ4mRAALHoTi5iE1lJlyFokZWEiQ6VvkpadxXkTgAjLqMHrRe3dsqGpp3ObXDRAMwgR4Mj1+nFfb1EAbgoAXxAAGhAIRhh8aF5kUD4YZDdWZl44aONcVjAAazgYAGVGAp1sZBhcAFcckEIIMHTM7OiAK14ADwAhfKKS0tZ0OAAZHTg2rMaIOphGBYAmGY6QCtxs3GRwXiToxgJYAHUiGDFkAA4ABmjs9Hwa+sbDKGxmOABFOr81xpgrGMZ0IF2Qy2itW0zCqAGEIOgtLsoNBptE6tkACpApJIDKzMJhIA)
```sh
--parser css
```

**Input:**
```css
.mygrid {
  grid-template-areas:
      "header header header" 
      "main main sidebar"
      "main main sidebar"
      "footer footer footer";
}
```

**Output:**
```css
.mygrid {
  grid-template-areas: "header header header" "main main sidebar"
    "main main sidebar" "footer footer footer";
}

```

**Expected behavior:**
The idea here is to mimic the grid layout, so the value for grid-template-areas should start on a new line and each value in the double quotes need to stay on their own line as seen in the input code.
