### ISSUE TITLE
Prettier throws error on *.scss files

### ISSUE THREAD

**Issue by natenorberg** [prettier/prettier#3190]
**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEA5AH4CGAzpXDJQPSVUOQA2+lxA3ADpR8A6AMpR02bLUqFgfQoQBG+ACZw8SQpQit0SwgBJFeFXgDCW-LygBfEABoQEbDHTRKyUNjzpYAdR0wAC2QARgAGUPsYcnk-JUDkACZ7Sm8Ac1Y4AEUAVwh4ZBg8bLhIvHJ0bShUs0xMcmQQclZWOxB5MrAAa1ohbHIwNOQAMyaaewArSgAPACEO7pghckw4ABlvOGHRkpA+vBo8BqH2AHdWmkx0AqKd7JoAFWi3JBHWMZAlCDAtt52qGB+7wg2Rg2BBCUBcCsViAA)
```sh
--no-bracket-spacing
--parser flow
--print-width 100
--single-quote
--trailing-comma all
```

**Input:**
```jsx
@import '~assets/sass/colors';

.Snippets {
  border: solid $borderColor;
}
```

**Output:**
```jsx
SyntaxError: Unexpected token @ (1:1)
> 1 | @import '~assets/sass/colors';
    | ^
  2 | 
  3 | .Snippets {
  4 |   border: solid $borderColor;
```

**Expected behavior:**
Prettier formats normally.

This didn't blow up in 1.7

**Comment by ikatyang** [comment]
**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEA5AH4CGAzpXDJQPSVUOQA2+lxA3ADpR8A6AMpR02bLUqFgfQoQBG+ACZw8SQpQit0SwgBJFeFXgDCW-LygBfEABoQEbDHTRKyUFRjIAZuVY17eTxyMABrWiFsEPQoAHMfPwCQJQgwBP84ewArSgAPACFgsIjyTDgAGRi4dKSIAFcYbAaAJhrMkCi8GjxkEEowajsOvBiYAHUdGAALZABGAAZ5+xpMdGQYPDr2yhjY1jgARTqIeHXN9phyeQmlaeRm+w3ydG04s0xMcl6-ViG6mgAKlc3EhfBkrFYgA)
```diff
 --no-bracket-spacing
- --parser flow
+ --parser scss
 --print-width 100
 --single-quote
 --trailing-comma all
```

**Input:**
```scss
@import '~assets/sass/colors';

.Snippets {
  border: solid $borderColor;
}
```

**Output:**
```scss
@import '~assets/sass/colors';

.Snippets {
  border: solid $borderColor;
}

```
