### ISSUE TITLE
SCSS configuration

### ISSUE THREAD

**Issue by iGitScor** [prettier/prettier#3202]
Hi folks,

**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASGAnAhlAzgBywwRiQAIA6ADgG4AdKCgMwgjOAbLIkLAEsYATyTpseQsVj0oAXwYNUAcwx8AJgFoARsSwBrfBD6xc6gK5QBAGzi5c5ABScuZAPQuyAUQAemLGVwAtliWlv5gxAiuZPgAFtBwTlxedmQADAA0ia7uAMpBIWERUFGx8QCUWYHkAKwALLWZxc5uZACycKp8pgGFcJHuMFia1jAVTVwBquQA7ABsAJyNztlkADJEinC9-WSqNrowPFmWiuTztRlZLXA+2OsYm9vF7nu4B0fjK16W5ACMvxcGGUyABCPZMLCmSwwGggdIgHgwPjQXDIUBYXAwZAQyy4ODw7RYMC6OAwHK8IyKZCYUz4kCqCBgbHBPHwgBWuC8ACFsMTSTksAE4KsjHBmbi6RBTDB8NKAEzi1kgCR4jDIEC4MC2OHKlSwADqahgMWQVAyGrgAT41IwtPhuEp1gAiqYIPAbXaQINNIbVMbkA0vdg+JZKQBhCABILqqDxHWmPEAFSGqKQOLxMhkQA)
```sh
# Options (if any):
--parser scss
--single-quote
--tab-width 4
```

**Input:**
```css
$transparent: .8;
.foo {
  opacity:$transparent;
}

$grid-breakpoints-unitless: (
    // Extra small screen / phone
    xs: 0,
    // Small screen / phone)
    sm: 544,
    // Medium screen / tablet)
    md: 769,
    // Large screen / desktop
    lg: 940,
    // extraLarge screen / desktop
    // xl: 1140
) !default;
```

**Output:**
```css
$transparent: 0.8;
.foo {
    opacity: $transparent;
}

$grid-breakpoints-unitless: (xs: 0, sm: 544, md: 769, lg: 940) !default;
```

**Expected behavior:**
- Keep comments
- Let the leading zero removed

We use `scss-lint` config file to have a code style standard but we want to use prettier
Does prettier can use `scss-lint` or at less keep comments ?

Thank you!
