### ISSUE TITLE
SASS language elements (@mixin, @function, @if...) are not formated correctly

### ISSUE THREAD

**Issue by yukulele** [prettier/prettier#3282]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgAcIBnTGTaACgBIYJD8mkn8AGVgGhoCdMBzABYwkUAK4AbCdwBGEGPXSjJ0mhLgAzEeKkBKfMAA6BfKkwbafITAC8NnRN3BeA4SzoMA3AF9jTMxY0cgoQ6HZMDk5B8oru9IQ+fqbmtOparHaRzmki+C7WiSbEZBTQLACGMiQQEmLwnknxcV5JOe45DSZWbnndMJ1MwbF5Q6GdvlDGAHTlZAAmcMD+eGC1C0Sk5JRQVGycAEycrPgAzJwALPreIJwgDKVQJMigszDIGuUSJHC3MjzlYAA1nAYABlQgAvD8ZAwHhiH4gOYQMDvT7fW54b48GAABX+-HQ5VRXwRACsSNgAEL-IEg0HldBwAAyeDgxPRdzqhDq+3ZCIhPCxyBAJDAJCet0IfFgAHVMHMYIJkAAOPYgKWkOAy-6EGFwhE8OAARzEmENePKBKJSA+JNu3ywevh9qh6gAimJ5GybWiETBKnKFUqkIcQLDypgJFCAMKhQnCqDQNm3MTfAAqlSePpJ3m8QA)
```sh
--parser scss
```

**Input:**
```scss
@mixin position($top   :   0   ,$right:null,$bottom:null,$left:null) {
  @if($right==null){$right: $top;}
  @if($bottom==  null){$bottom: $top;}
  @if($left   ==null){$left: $right;}
  position: absolute;
  top: $top;
  left: $left;
  right: $right;
  bottom: $bottom;
}

.aside{  @include position(0,2,    3,4) }
```

**Output:**
```scss
@mixin position($top   :   0   ,$right:null,$bottom:null,$left:null) {
  @if ($right==null) {
    $right: $top;
  }
  @if ($bottom== null) {
    $bottom: $top;
  }
  @if ($left ==null) {
    $left: $right;
  }
  position: absolute;
  top: $top;
  left: $left;
  right: $right;
  bottom: $bottom;
}

.aside {
  @include position(0,2,    3,4);
}

```

**Expected output:**
```scss
@mixin position ($top: 0, $right: null, $bottom: null, $left: null) {
  @if ($right == null) {
    $right: $top;
  }
  @if ($bottom == null) {
    $bottom: $top;
  }
  @if ($left == null) {
    $left: $right;
  }
  position: absolute;
  top: $top;
  left: $left;
  right: $right;
  bottom: $bottom;
}

.aside {
  @include position(0, 2, 3, 4);
}
```
