### ISSUE TITLE
Comments in less are parsed incorrectly after comma

### ISSUE THREAD

**Issue by alexkuz** [prettier/prettier#3438]
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDANAHSgehwAmjn0gFtSEZsAjfYbfEiAGwgCcl9rnUwBrANzYAvtmwZseQlGJkKsdPhgB3CE3KUAzjToMmrDlx78hUYSHQgIABxgBLaJuShUbNhGUAFVwicpUAG4QdgAmFmiaMMgAZqjMmnCW1Gy8fHAwAMrWvHZQAObIMGwArokgIRBgMXEJlrkJbDCeKXmkqNXxZQBWmgAeAEIp-OkZqBQAMrlwHbVWxTDW8wBMM2XZbA3IIMxwmk6W1my5MADqoTAAFsgAHAAMB+4JJynWW4e7cGwB05ZscACOxTsf2aqFa7SQsU6lgSpDshRKZU0uTyOwAisUIPBVpYYKhqGcQpdkEtcSk7MwUQBhCDkCEgKBEcLFBIAFXxfihCWEwiAA)
```sh
--parser less
```

**Input:**
```less
a,
// one comment
b {
  color: black;
}

a,
// one comment, two comments
b {
  color: black;
}
```

**Output:**
```less
a,
// one comment b {
  color: black;
}

a,
// one comment,
two comments b {
  color: black;
}

```

**Expected behavior:**

```less
a,
// one comment
b {
  color: black;
}

a,
// one comment, two comments
b {
  color: black;
}
```
