### ISSUE TITLE
SCSS always expands comma selectors and single-line rules to multiple lines

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#3464]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALAjAGgASoEw6oDMhALIQKyEBs2wAOlNtgGbQwC0A7nAJYDmqGEmwAjCABsAJgG5GAX0aMMdVuw4BnXgC84IonAC2M7Iqj5VbWJp17seAHQUjJs8UvqtukXhenlpB7WXnboTn5uFEGcISLoEcq0wGrBtiIADOHGpiCYIBAADjC80BrIoACGAE5VEFwACtUIZSgVAG4QvFK5IBUaMMgsFRIacHmiVRVgANZwMADKBVO8UPzIMFUArmMgUhBgg8OjeSujVTD1k-yGFYcjOwBWGgAeAEKTM3PzFYZwADIrOB3Y75TYwApgvDAnZLKpnZAgDRgDRlPIFKorGAAdS6MFQyAAHOk0bVRljJgUEei4Gc2kC8lU4ABHTa8RmXCrXW5IIb3PKjQy8dZbHZaVYSOAARU2EHg0LyMAqohxUjxyAIIA2FV4EhW-AAwhBDDcEVBoPSQJtRgAVJUtXmjeTyIA)
```sh
--parser scss
```

**Input:**
```scss
h1, h2, h3, h4, h5, h6 {
  font-weight: bold;
}

h1 { font-size: 3em; }
h2 { font-size: 2.5em; }
h3 { font-size: 2em; }
h4 { font-size: 1.5em; }
h5 { font-size: 1em; }
h6 { font-size: 0.5em; }
```

**Output:**
```scss
h1,
h2,
h3,
h4,
h5,
h6 {
  font-weight: bold;
}

h1 {
  font-size: 3em;
}
h2 {
  font-size: 2.5em;
}
h3 {
  font-size: 2em;
}
h4 {
  font-size: 1.5em;
}
h5 {
  font-size: 1em;
}
h6 {
  font-size: 0.5em;
}

```

**Expected behavior:**
No changes from input
