### ISSUE TITLE
css/scss comments

### ISSUE THREAD

**Issue by oligot** [prettier/prettier#3545]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEEA2AaAOlA9LgAgAsBGDYgJmygFc0DgcCCBbAQwCcBzASyiQIAGANw4AvjhwASAM48AXnBkCAFDgAeygiQB0AFnL4CMIjxkEA7jzT0ARnAIc4LCADc4AEwK2AngQAOTjAwPHAcODIsAroAHDgAlCAYqP4h0DLIoJwcEBYACpwIGShsrhA8HkkgbDIwyABmbGgycMm2HGxgANZwMADK-p18XMgwHDStIB4QYA1NLcl8LRwweR1c7HPNkwBWMuoAQh3dvX1sLHAAMnxwWwuoNDD+jxR3k4Mcy8ggMmAyGclAnwYAB1ComZAxQSAnItEEdfzfQJKMLuKpOACONB4TjWbA2bDeyRaLB4o3GkzkUC4aDgAEUaBB4ESQDA2LYwR4IUgqKyOtZhgBhCAsTYoKDQW7JGgtAAq7OKjW2YjEQA)
```sh
--parser scss
```

**Input:**
```scss
ol,
// h1, h2,
ul {
  margin: 0;
}

$sizes: (
xs: 1.4, // this will be removed by prettier
sm: 1.8
)
```

**Output:**
```scss
ol,
// h1,
h2,
ul {
  margin: 0;
}

$sizes: (
  xs: 1.4,
  sm: 1.8
);

```

**Expected behavior:**
```scss
ol,
// h1, h2,
ul {
  margin: 0;
}

$sizes: (
  xs: 1.4, // this will be removed by prettier
  sm: 1.8
);

```
