### ISSUE TITLE
CSS/SCSS unicode-range not lower case when codepoint has a leading letter

### ISSUE THREAD

**Issue by esturcke** [prettier/prettier#3646]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0oiiBXKAS0gBM5sAnPKAcziSIFUBqAAwAxQYIA0ffqLEBucgF8Q4kBAAOMWtADOyUHhYsIAdwAKBhLpR4AbhFoNlIPNpjJ8AG21wVAIzZgANZwMADKagS0nMgwLFQ+IAwQYO54XglR3iwwpmwcALZ4qekqAFbaAB4AQgHBYXj5cAAyUXDF3ioQVDBq3QBM7QkRLFnIINpg2roqaixRMADqDjAAFsgAHBIgsxDeC2xqY7NwWTZtKixwAI5UtJe5eAVFSJ4d43D5tDFxCdpRHB44ABFKgQeCDFQwPC+JYMVbIPqQti0Dz-ADCEHyhTGUGg5xAVG8ABVoVZXnAFAogA)
```sh
--parser scss
```

**Input:**
```scss
@font-face {
  unicode-range: U+0F00, U+F000;
}
```

**Output:**
```scss
@font-face {
  unicode-range: U+0f00, U+F000;
}

```

**Expected behavior:**

I expected the second codepoint to be lower case as well.

```scss
@font-face {
  unicode-range: U+0f00, U+f000;
}
```
