### ISSUE TITLE
`//` comments in SASS break formatting.

### ISSUE THREAD

**Issue by ryanpcmcquen** [prettier/prettier#3647]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAKgCwJYDOGhGAygMKmkB0GACgE5wwx5wMYC2EAbnEQANqAIwCGDARgCuABwwwcceYowFRnJQBs8UJaKIBychE4bY1A9QA6UagDMIEADQ30GY6YQxrtsR2A2GBgAJoQymqIAnkgYwpoQYADWANw2AL4gTiAQMqzQBMig4gwQAO504ggFKKI8EHjBmSD6MMh2opoEcFnCDKJJzKQy-ToA5sgwDFLdIMEJbR1dWTpdDDCMoqOcogudMwBWBAAeAEJ9AzCk6nAAMjpwu0vZUjAyLwBMjzPDDKvIIAQwAQClkZAwdDAAOoNBTIAAcAAZQSUupC+jJ-mD+Ow+E0mABHKR4JgbLY7JDtPZZLqcPATKYzAhjTRwACKUgg8C+WRgomE0OCsKQABYeX08NooKMPNt-lBoA8slIulg+dVKV00mkgA)
```sh
--parser scss
--tab-width 4
```

**Input:**
```scss
// This is SCSS. Prettier moves `.bar` up the the same line as 'Comment.'.
.foo,
// Comment.
.bar {
  display: block;
}
```

**Output:**
```scss
// This is SCSS. Prettier moves `.bar` up the the same line as 'Comment.'.
.foo,
// Comment. .bar {
    display: block;
}

```

**Expected behavior:**

When running `prettier` on this code inside of Atom, it bumps `.bar` up to the comment line. It should keep it on a separate line. This completely breaks the file.

<sub>*example updated by @j-f1 to use the correct parser*</sup>
