### ISSUE TITLE
Format SCSS deep map like CSS rules

### ISSUE THREAD

**Issue by tzi** [prettier/prettier#3654]
Hi everyone!

I reported that SCSS maps was not format like CSS rules, and it was fixed (#3056).
Now, I found that maps that contains map them-self have the same behaviour.

**Input:**
```scss
$theme: (
  color: #111111,
  text-shadow: 1px 1px 0 hotpink 
);

$themes: (
  light: (
    color: #111111,
    text-shadow: 1px 1px 0 hotpink 
  )
);

.selector {
  color: #111111;
  text-shadow: 1px 1px 0 hotpink 
}
```

**Output:**
```scss
$theme: (
  color: #111111,
  text-shadow: 1px 1px 0 hotpink
);

$themes: (light: (color: #111111, text-shadow: 1px 1px 0 hotpink));

.selector {
  color: #111111;
  text-shadow: 1px 1px 0 hotpink;
}

```

Here is a link to [the playground demo](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASGALOBbOSAEAFADpT76QA2EATgQMQCMzLANKefAB4wC0AzhgCGAEwgB3AowAOXfDLkAGfBggxpASygBrfKQCUAblKl0WXPwIky+ShoDmGGFY7kKEanXxMWzdjc44HgFhMUl5WQilFTVNHT0bfQNjKFIAOn44SjgwGFp8YFcqWgZfZhTA4MFRCSlIhXxlVXUtXVIAXxBWEAhpGA1ofmRQIRoaCQAFUYQhlC6QIX4YZAAzIUpM7oAjGiEwbTgYAGVpPa17ZBgaAFc4brEwVfXNkC1MmhgJ3ftsISeNu4gABW-C4ACFdvtDkchLgADJaOD-F4Qa7qNEAJmRgNONHeyBA-DA-CG3WkNC0MAA6hoRJhkAAORRk8aZKm7aQE+Y0OAAR2uGh5XyEPz+SDWAO6mWwGkuN0B-HO2QAitc1Ejxc9ATAhFsaXSMMgMd0rkINHYoPYAMIQbC-AlQaBI7rXTIAFV1swlmXa7SAA) (prettier 1.9.2)

Cheers,
Thomas.
