### ISSUE TITLE
[scss] bug with interpolation inside media

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#3719]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtnAJgSwIYAEAzmAE5wIF5RYEDEwAJEegLTQA2AngDQGMcA5q2pZWAVwAOAXwLAAOlALKCkDhFJJ6ABl0BuRdMUgeICJJg5oRZKDylSEAO4AFewhso8ANwg4sJiB4RDDIAGZ4HERwpgBGpHhgANZwMADKkok4UILIMKTiMSBYEGDhkdGm2dGkMC4Jguh45VFFAFZEAB4AQgnJqWl4mAAy2XAtlWbiMJLTAEwTRZmkNcggJEQ2ppKk2TAA6v4wABbIABza247R+wmSaztwNd7jpuQAjuI45PV4jc1ICKtUzRdA4PIFIpEbKCDhwACK4gg8EWphgeFihywJ2QczRCRwHBhAGEIOgmmsoNBXiBxNEACoYzz5QrSaRAA)
```sh
--parser scss
```

**Input:**
```scss
$sm-only: '(min-width: 768px) and (max-width: 991px)';
$lg-and-up: '(min-width: 1200px)';

@media screen and #{$sm-only, $lg-and-up} {
    color: #000;
}

```

**Output:**
```jsx
@media screen and,  {
	color: #000;
}

```

**Expected behavior:**

```scss
$sm-only: '(min-width: 768px) and (max-width: 991px)';
$lg-and-up: '(min-width: 1200px)';

@media screen and #{$sm-only, $lg-and-up} {
    color: #000;
}

```

Seems problem inside `postcss-media-query-parser`
