### ISSUE TITLE
[scss] bug with string inside media expression

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#3721]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgMwAQAoDOMATgLT4A26YcuAJOvALYA02ADKwKwCU2AvH2wAdZPjjlMI3sCFRs87LQDWSbADoAjJwBsAJk4BuWQF9sqcWOxY8hUhSo16TVh2wbeA4ci-TZCxSrqbAAcwWwAzEZQpubkljJyCsqqamzanBppUcYgzCAQAA4w6ND4yKAAhkREEADuAApVCGUoFQBuEOgAJrkgFYTImBVxcHkARkQVYEpwMADKBVPoUADmyMQArqMgXRBgg8NiectiRDD1kyuMFQcjeQBW+AAeAEKT07NzFYxwADLLcFuR3yGxgBVBuiB20WRFOyBA+DA+DKeQKRGWMAA6t0YAALZBhVE1MSYyYFeFouCnNqAvJEOAARw26HpFwqVxuSCGdwRcEY6HWRC2eXwyxW5DgAEUNhB4FC8jAKmNsV08chdArJuhKKsAMIQRjXeFQaC0kAbMQAFSVLU2cGMxiAA)
```sh
--parser scss
```

**Input:**
```scss
@if (str-slice($item, 0, 5) == ":self") {
    $k: .15625;
} @else if (str-slice($item, 0, 1) == ": ") {
    $k: .08803;
} @else {
    $k: .065106;
}

```

**Output:**
```scss
@if (str-slice($item, 0, 5) == ": self") {
    $k: .15625;
} @else if (str-slice($item, 0, 1) == ":  ") {
    $k: .08803;
} @else {
    $k: .065106;
}

```

**Expected behavior:**

```scss
@if (str-slice($item, 0, 5) == ":self") {
    $k: .15625;
} @else if (str-slice($item, 0, 1) == ": ") {
    $k: .08803;
} @else {
    $k: .065106;
}
```
