### ISSUE TITLE
SCSS function names are being inconsistently case-changed

### ISSUE THREAD

**Issue by thedamon** [prettier/prettier#3748]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKABAZgVymGAS2gAIBzOGAIQAcAKAEgGs4BPAShOHRJI0KwkAtgEMaAWgAWIgM7iWrRmQBOhACYB9AEbK4IpjQiFYMgDQlmbTtyi9eGXTBzLboiRRhLVmnXoNGTc0sOAG4eEgBfdHCMAHcRFxJUEABVKCYoCFjbAAMAYmBgiJySYwsVdW1dfUNjGBkAOmSw2z5HZ1soHAAbbpaoqHRsPAJiWw8temDrGPbEj1pGBXZ+6MGoBrAEtXFIbpwhKHEZQiEabrguNftjMH21S98agM9ySkXhNRJOGdbeGhEajUxjISAsMgBYBBGkgsAQMGOQnBkOhsPgsHEQjULV4Axit3uj2q-jqJDoC3oWPYvzsJAAZEhYJJdpJCN01HQAEy2ADUJAAzDTaSQ7nplGCtBAYJIcXYBrjrnwCTgHiQniTYGSKXQAB7dalXP70xnSllsjnckh8wWG4Uii4JMGZKBwWUKo0Mplm9l0fm8kgAFiFtNFjrVUpl4Xd7rx6xAphAEBoRGgMmQoASyiyAAUEgg0ygRAA3IxqeMgWQwZBYETdGRwBM6ERgFgwADKKKgZGQMGUOAbIDUEDA1dr9YTxnryhg2eUIjIolHdYHACsZDqqHOW5Q2yIhHAADLGOBL8eJnAwGgXzmngcA5RT5AgGRgGRphM0VSwADq6mlyAADgABg-LN62-OcaCfT84CnIsTwTXQAEccEIXRZ3nRckBrZcE3rIRCB7PsBxOLsLgARRwKUT2wscBxgEQtF-NR-yQTkE17EQ2RBABhCAhCwkBnQQkAcHrAAVRiCxw+sIgiIA)
```sh
--parser scss
```

**Input:**
```scss

@function getBp($key) {
  @if map-has-key($grid_breakpoints, $key) {
    @return map-get($grid_breakpoints, $key);
  }

  @warn "Unknown `#{$key}` in $grid_breakpoints.";
  @return null;
}

@function getbp($key) {
  @return getBp($key);
}


.card-column-simple {

  @include breakpoint( getBp( md ) ) {
    padding: $spacing_content-sm $spacing_content-md;
  }

  @include breakpoint (getBp(md)) {
    &:nth-child(2n + 3) {
      clear: both;
    }
  }

  @include breakpoint (getBp(xl)) {
    &:nth-child(2n + 3) {
      clear: none;
    }
    &:nth-child(3n + 4) {
      clear: both;
    }
  }
}



```

**Output:**
```scss
@function getBp($key) {
  @if map-has-key($grid_breakpoints, $key) {
    @return map-get($grid_breakpoints, $key);
  }

  @warn "Unknown `#{$key}` in $grid_breakpoints.";
  @return null;
}

@function getbp($key) {
  @return getBp($key);
}

.card-column-simple {
  @include breakpoint( getBp( md ) ) {
    padding: $spacing_content-sm $spacing_content-md;
  }

  @include breakpoint (getbp(md)) {
    &:nth-child(2n + 3) {
      clear: both;
    }
  }

  @include breakpoint (getbp(xl)) {
    &:nth-child(2n + 3) {
      clear: none;
    }
    &:nth-child(3n + 4) {
      clear: both;
    }
  }
}

```

**Diff:**

```diff
--- a/example.scss
+++ b/example.scss
@@ -11,20 +11,18 @@
   @return getBp($key);
 }
 
-
 .card-column-simple {
-
   @include breakpoint( getBp( md ) ) {
     padding: $spacing_content-sm $spacing_content-md;
   }
 
-  @include breakpoint (getBp(md)) {
+  @include breakpoint (getbp(md)) {
     &:nth-child(2n + 3) {
       clear: both;
     }
   }
 
-  @include breakpoint (getBp(xl)) {
+  @include breakpoint (getbp(xl)) {
     &:nth-child(2n + 3) {
       clear: none;
     }
```

**Expected behavior:**

The function calls being used as parameters get changed to lowercase... but not always. Based on everything I've read I would expect them to be left alone entirely.
