### ISSUE TITLE
[css] no space in property value

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#3842]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOld6AOAThPkliABTmowyEUAmNqAtDAJYwA2cAlOfxABuHAF8QAGhAkO0AM7JQqQsQDuABWUIFKVADcI7BpLRyYyAGaoucuFIBGhVGADWcGAGV8z9lADmyHQArnYgDBBglta2Ur62hDDqTn4AtqhRNqEAVnIAHgBCTq7uHqgpcAAyvnAZMdJBMPgNAEy1od6E8cggcmByClJEvjAA6kYwABbIABwADIPEtiNO+N1EcPF6NVKEcACOQey7Saip6UhWmVK2KeyBhCHXvn48AIpBEPBtUjCo9mMMSbIZo-JzsLjPADCEBSaW6UGg2xAQVsABU-jpgnBRKIgA)
```sh
```

**Input:**
```css
a {
  prop:"("attr(data-title)")";
}
```

**Output:**
```css
a {
  prop: "("attr(data-title)")";
}
```

**Expected behavior:**
```css
a {
  prop: "(" attr(data-title) ")";
}
```

Ref: https://github.com/prettier/prettier/pull/3825#discussion_r164231204
