### ISSUE TITLE
[css] comments around declaration

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#3905]
**Prettier 1.10.2**
[Playground link](https://deploy-preview-3897--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBDABMAOldf0D0AVOpALZkIzoCM6RBO+hJ5ls6ATPQegA6oAJoICWUAOYtSEClXQBmHuiRS2cgCxKaABj4APVTPbUArFt0Hi02RwBsPANyGb1AOw8m+K2o4AOD7j4MABOqFAAzgBmEMFkKiFh4QA2qPAAFN5GcgCc5vrOxrTaPACUDp54kEkxKpkutHQM6MFwggVyNNxNAIQiZHwxMGHUdYU0ik1Oox2aDBXtHDRmc1AAviAANCAQfDAi0OHIoKjBwRAA7gAKJwiHKKgAbhAigpto4TDIkahJ4XBbACNQmAANZwGAAZQEYDE4mQIQArv8QIIIGAvj8-lsxH9gjBLqFxGRUBjfsiAFbhPQAIWBYMhqEoABkxHBSVjtgiYHwuZx2ciBMFcchwOFDls+MExDAAOovGAAC2Qvm0ErOfxloT4IslcFxDzZWxaAEcESIWgTUESSUhvmStn8yCJ4cEkQ7YUk4ABFBEQeD8rZDAFywSK5CcQOhERJWEAYSMNpAUGghpACL+ABVUAC7na-qtVkA)

**Input:**
```css
a {
    /* comment 1 */
    /* comment 2 */ padding /* comment 3 */ : /* comment 4 */ 10px /* comment 5 */ 10px /* comment 6 */; /* comment 7 */
    /* comment 8 */
    transform: translate(/* comment 9 */ 10px /* comment 10 */);
    color: /* comment 11 */ red /* comment 12 */ !important /* comment 13 */ ; /* comment 14 */
    /* comment 15 */
}
```

**Output:**
```css
a {
  /* comment 1 */
  /* comment 2 */
  padding/* comment 3 */ : /* comment 4 */ 10px /* comment 5 */ 10px
    /* comment 6 */; /* comment 7 */
  /* comment 8 */
  transform: translate(/* comment 9 */ 10px /* comment 10 */);
  color: /* comment 11 */ red /* comment 12 */ !important /* comment 13 */ ; /* comment 14 */
  /* comment 15 */
}
```

**Expected behavior:** **Wait feedback from contributors and community.**

Don't work in main playground because this fix only in master and was not released.
