### ISSUE TITLE
colon after class name in .scss files not flagged

### ISSUE THREAD

**Issue by goleary** [prettier/prettier#3912]
sometimes I accidentally put a colon after a tag type or class name like below
![image](https://user-images.githubusercontent.com/16123225/35888376-47da39b8-0b4c-11e8-9b5d-ce04f7ff1fcf.png)

this results in my style not being applied and no warning or flag in the IDE (using vs code).

seems like the kind of thing that prettier could take care of, flagging or auto removing these unwanted colons on format.

**Comment by j-f1** [comment]
This is actually a feature of SCSS:

```scss

.cta {
  padding: {
    left: 10px;
    top: 7px;
  };
}

// is equivalent to:
.cta {
  padding-left: 10px;
  padding-top: 7px;
}

```
