### ISSUE TITLE
PostCSS @nest wrong output

### ISSUE THREAD

**Issue by igor-ribeiro** [prettier/prettier#3974]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6GBLGAbOACYAHSjzwAEo4BnGPJAc2wgCMBDbACgAsBGASgBkBYqVJswAa3oAnCAFcoAEyR5pcRQG4ReAL7EdIADQgIAB0zQqyUK2myA7gAVbCKylYA3CBkVGQrGmQAM3YqOGNmaVZJOBgAZVNojCh6ZBhpOXCQRQgwYNCs5LDpGEco+gBbVnzsMOMAKyoADwAhKJj41gq4ABlkuBq6kzkYUxGAJkGsxOli5BAqMCorY1NpZJgAdR8YLmQADgAGVdkwzajTebXqOGkPAeM1AEc5DDUy1krqpBDarLCKhg0hl-slGHAAIpyCDwKbGGCsZjbRS7ZDjeFRDDYMEAYQgFSq8yg0AeIDkYQAKoi3L8wjodEA)
```sh
--parser scss
```

**Input:**
```scss
.title {
  @nest :global(h1)& {
    background: red;
  }
}
```

**Output:**
```scss
.title {
  @nest :global(h1) & {
    background: red;
  }
}

```

**Expected behavior:**
```scss
div {
  @nest :global(h1)& {
    background: red;
  }
}
```

This is crucial because without the extra space the result is:
```css
h1.title {}
```
With the extra space the result is:
```css
h1 .title {}
```
http://cssnext.io/features/#nesting
