### ISSUE TITLE
Don't add spaces around + in unicode-range

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#4063]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0oiiBXKAS0gBM5sAnPKAcziSIFUBqAAyDsAMVEBucgF8QAGhAQADjFrQAzslB4WLCAHcACjoSaUeAG4RaDeSDzqYyfABt1cBQCM2YANZwYAGUlAlpOZBgWKg8QBggwZzw3GLD3FhhDNg4AWzxE5IUAK3UADwAhH38gvGy4ABkwuHz3BQgqGCV2gCZmmJCWNORwdU0FJRYwmAB1GxgAC2QADkExvXcptiUh8bg0iyaFFjgARypaI8y8HLykVxaQd2zaCKiY9TCOFzgARSoIeF6ChgeE8MwY82QXSBbFoLg+AGEINlckMoNADiAqO4ACogsx3ODSaRAA)
```sh
--parser css
```

**Input:**
```css
@font-face {
  unicode-range: U+00-FF;
}
```

**Output:**
```css
@font-face {
  unicode-range: U + 00-FF;
}

```

**Expected behavior:**

Unchanged
