### ISSUE TITLE
[SCSS] breaks unicode range

### ISSUE THREAD

**Issue by zieka** [prettier/prettier#4067]
**Prettier 1.11.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0pSZNZc8BbASwBsBPJIgcgCEGZ4AnDgG5ylAM78w7AK78mACg4B6JdRhiAdAHMxMPDAZgNkOkrFKARrwFKAbgHYlACQCiABwAKADhgApABpMAOp4AJpODHRiUP5a6ADCAPK2tgAiDFAAjG4A0l54OfAAMm5wAFoArGAADACCGgDuEOjoAEwcAJQiFDDSUIYQACZw2Px4UFpw7ACqANQALJnY86kANERzAGwu61sAYruz9gD83ZQAvqIw5Bp4-Ah4RG5EYm7jJGrsrRoVcHScPD4cEE6zEwIY6CE5xAqxAEDcBmgYmQoDu-AgDQ8dwQyJQeFsEAYgxhIDwumQ+CYYNhFjGYAA1nAYABlN5gDJaZAwfjSOCwwYQMAUvBUvkgDJg-gwDxjLR0PDC0WwgBWYgAHlw6YyWfQ4EUMnBFdS4dIYG5Ta0jWK3vxJcgQGIwGJkbC3PwMjAgkSYAALZCZebVV3osFBMZue1uuCS2yG2H3ACO0gY9xleDlCqQlONYMYXJ5YrEHKYcAAitIIPB87zYXoLF7Br7kPNa2NmBz4hA6PL7VBoHGQNIwQAVPAWXHZuDnc5AA)
```sh
--parser scss
--print-width 140
--single-quote
--tab-width 4
```

**Input:**
```scss
@font-face {
	font-family: 'Bitter';
	src: url('//fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2');
	unicode-range: U+41-4D, U+6E, U+6F, U+7?;
	}
	
.arena p span {font: 2.5em 'Bitter', serif;}
```

**Output:**
```scss
@font-face {
    font-family: 'Bitter';
    src: url('//fonts.gstatic.com/s/bitter/v7/HEpP8tJXlWaYHimsnXgfCOvvDin1pK8aKteLpeZ5c0A.woff2');
    unicode-range: U + 41-4d, U + 6e, U + 6f, U + 7?;
}

.arena p span {
    font: 2.5em 'Bitter', serif;
}

```

**Expected behavior:**
The spaces added to the unicode range break the functionality of the unicode range.  Expected there to be no spaces before or after `+` in unicode-range

If you want to see how the range is affected please see following codepen:
https://codepen.io/zieka/pen/Zrmgbr
