### ISSUE TITLE
Sass @include argument or variable being incorrectly escaped

### ISSUE THREAD

**Issue by samanthaksanders** [prettier/prettier#4149]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAKgCwJYDOGhGMOcGBMATgK5gy3UUQBmp5xsCAJnDxgi0YAB2EA6DAB0o6DAAFKATwC2AIwgAbDJGrMGmpRjgEwAQxH9KEDAHcK5qBloEKAHh54Abjs1mCBAC8UiC2eDxkALQAjKgATPIEKmaamiEAfG6onl7pMuJhETiRrLSpUlKJyakYwDIYduFkSBjRAAxtAKQA3DIAvjIycgCyeAAeeE4wNgDmCHDUZvCNRb7+rgQy8irjkytkBAAUACSFB5GQmrQqUAQANBinTTgEkWrMZgDWIhCTMC1QMqaACUtXqDQwBWeJSBAGJgE8iq93nAvj8-n0wU4ITizjgWu0uhgAIR4FQ-agwMywXrYhoDKDghpyAAyEAgIg41CEMxwHAogPUC0E7Eu11uGFYEGoxjMYD5fCgEB2UCW0pFgiYksWDDw0AI4iZClR8seeNeiuVkzVMr2iPOYpuRDqdJxGDkACE4DM9mAPjBJjMMGYMIK1AsbZL1UIZawdQHoM5ObRYHhtPYMPgYPyjTi5JaVTbDa6cfIpTL7S9IoKI9NY9yVK0uTy+ZWLQgraq61i3b33ZgPbQ0wIQ2A-AEuPyo9RktmAAZQoqRADMqAALAvc335Hh2G3q9da+riYEzc920rC92XX3b5C8ZF4fua4s6wMpKgn+bIgXrW+v+ebwfN8vywJiN53pBeItCc34vpGmD7r+XbSqCABUrQdJ0JJkhSVI0lukEMpB9KERgxEQgyDJDJgACqUC2NS8ACAQIhyhQ4aBlwriUlY4YwPYCBTmocqfAQ458tSAgAOTyNJyjqFoWwqPweAhtAhiUH6cBCVJGCHMkYyRNBGAAOwAGymSIYyghBDQ7lAY60Hw+wvIccQYMuGBrg8FRVCkIK0tRsiYAAgpoBA2CmjHcCxbFgBQtjkE4fBjmY1Bcf4wYYF46VqWomhwDI+4omioEwJErhsa+0otH5SQBd0IB3CAHIJrcyCgOl3K2AACulCAEMgIBmF4vw8M1I1UMgrApK4LXvKJcAwAAyvFgbIDQtBwC1PAQGAM1zTtICTDxMC9YsMzJIdEXHQAVgQYwejqnzLStZgqSykxwDd82tcIYgwHEv3HdVPHDaYASTSIGWwAA6s8yDRHEbQtTDECuHDiwiMNMMmAsXg-S1zAAI5DswF1mFdZggy1rg7JtdDHQQgaFQAirQEDwIz20tVSagI0UyA+SANBmGmgYAMLKtdKBKlARMgC4cBYGYahDUgs23X0fRAA)
```sh
--parser scss
--print-width 120
--single-quote
--tab-width 4
```

**Input:**
```scss
// This is the structure of the intended output. 
// @ symbol correctly escaped so we can use <div class="width-1/2@small"></div>
.width-full\@small {
  width: 100%;
}

// Mixin to generate width classes
@mixin widths($widths-columns, $widths-breakpoint: null) {
    .width-full#{$widths-breakpoint} {
        width: 100% !important;
    }

    // Loop through the number of columns for each denominator of our fractions.
    @each $widths-denominator in $widths-columns {
        // Begin creating a numberator for our fraction up until we hit the
        // denominator.
        @for $widths-numerator from 1 through $widths-denominator {
            // Build a class in the format `.width-3/4`.
            @if $widths-numerator != $widths-denominator {
                .width-#{$widths-numerator}\/#{$widths-denominator}#{$widths-breakpoint} {
                    width: ($widths-numerator / $widths-denominator) * 100% !important;
                }
            }
        }
    }
}

// Unwanted space being inserted between the backslash and '@' symbol
@media only screen and (max-width: 767px) {
    @include widths(2 3 4, \@small);
}

// Also unwanted space when declaring as a variable
$widths-breakpoint-separator: \@small;
```

**Output:**
```scss
// This is the structure of the intended output.
// @ symbol correctly escaped so we can use <div class="width-1/2@small"></div>
.width-full\@small {
    width: 100%;
}

// Mixin to generate width classes
@mixin widths($widths-columns, $widths-breakpoint: null) {
    .width-full#{$widths-breakpoint} {
        width: 100% !important;
    }

    // Loop through the number of columns for each denominator of our fractions.
    @each $widths-denominator in $widths-columns {
        // Begin creating a numberator for our fraction up until we hit the
        // denominator.
        @for $widths-numerator from 1 through $widths-denominator {
            // Build a class in the format `.width-3/4`.
            @if $widths-numerator != $widths-denominator {
                .width-#{$widths-numerator}\/#{$widths-denominator}#{$widths-breakpoint} {
                    width: ($widths-numerator / $widths-denominator) * 100% !important;
                }
            }
        }
    }
}

// Unwanted space being inserted between the backslash and '@' symbol
@media only screen and (max-width: 767px) {
    @include widths(2 3 4, \ @small);
}

// Also unwanted space when declaring as a variable
$widths-breakpoint-separator: \ @small;

```

**Expected behavior:**
Should not insert space after backslash.
We like to use the `@` symbol for responsive suffixes so we can use classes like so:
`<div class="width-1/2@small">`
Since the `@` symbol is a reserved symbol in CSS, it has to be escaped with a `\`
Prettier inserts an unwanted space between these two characters both as a variable and as an include argument.
Seems to be fine if you simply write the class out by hand without helper mixin to generate them all.
