### ISSUE TITLE
Prettier cli command erases important parts of "background" css rule.

### ISSUE THREAD

**Issue by denzenin** [prettier/prettier#4200]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AznAhgJzACwFoBLSKAAmAB0Lzz85iBzfGJcgRgBYAHADwDcNOuQDuxACYx87bvyG1yAIyxgA1kxwQArlAnttOADYAKCVhhYkxALZYmcAPToAbkwDUfG0YErMANi4AGgAFAAkAOQAmAC0ATwAhAGYsAHUAJQAGLAARTOIAWQAVAEViAEkAcXwjNIkICTzC0oqw1iVKgFYALxCAZQApBrD00QB5YgAOFwkk2YAZKDBu+ZsATjj4ybiCnIBBUXmk6Pjy9wBhYj2mcvO9ybBKgDFs84S1foGI4oLtCO6St1yjkAKJxeYAKwAqscQaJOpC1HxgUw-t10vgIn0uJkCtCmFicXioUwCndRMDrgVsaIsZkVhDyt0CmoQRxIVDmVd2dCuQdKaS7jySlEBYTcd0AJoE7ES6Vk-n7QV7YVRMaVNkcvk8zkFK4UpUKnUyrgcXZME24nIW8Xm5UGqlxLhxCI5cowalcWkQp7oSEHCLnTLaXZ7IE5X5jCOkp1cArdJ74SFMF3ELhxiHyu7Iw3YvgRCFgD15gtGfxFIpQv45NSimvaKNgLiS0rV8p1kptutU7PzVuBzKZSElWlXIcQgocYGd+MkhUGkEE85cboFpgwQMr-4lJdE-Gb3H4+fAxcH6fVvYdkPdEmb1d9RVUvqDyEFNV3ccFY5hCDES7XW4ALuJgYm8dAlCaJl8CeMYQShToCjicoQLApRzg4OIJFSPgjE+IwJBsAA1bQlCidI1HKK4XBCJgIEmI4Tm6LgAGkAEpyDABB4BwDiuLgHioAgQgcDgHhsBgBQRBUdRNB0PRCHQYhujgdgyEsYgoEkgBfGgQCCEAIB4GBiGgdBkFAXAtFEEJcAQMyUCwFxfwkPSQCwdAYGQAAzLAjEwfSlBwVQ1DgGA+h4VQNKYZAYBwbQ4H0+owG83z-JADTMBwGAQiCpg7BSvyEpACF0D4BIgvUUK+iwGw4HmDS4AKtKdBgHhtBgKImqKiKcEy5BwHQMz9J4HANJgVJJGkZBJkyYatEwVIgp4fqRrgTKXEa-SRIAR20YgRJy+x8qQHzCv0zAbGIGK4qKxSoCYIw4E7CB4C6-TLCUCapHwZAoneoLiCMKLzggGxjpAQSoE2kBtEwIosCUezTswLStKAA)
```sh
--parser css
```

**Input:**
```css
.search-icon {
   height: 14px;
   width: 14px;
   background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTQiIGhlaWdodD0iMTQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8cGF0aCBkPSJNMTMuNzQzIDEyLjU3NEw5LjkxIDguNzRhNS40MjUgNS40MjUgMCAwIDAgMS4wNS0zLjIzMkE1LjUzMiA1LjUzMiAwIDAgMCA1LjQ2IDAgNS40MzYgNS40MzYgMCAwIDAgMCA1LjQ2OGE1LjUzMiA1LjUzMiAwIDAgMCA1LjUgNS41MDggNS40MDggNS40MDggMCAwIDAgMy4yNDItMS4wNjFsLjAwNC0uMDAzIDMuODMgMy44MzFhLjgyNi44MjYgMCAxIDAgMS4xNjctMS4xNjl6TTUuNDk2IDkuODc4YTQuNDI2IDQuNDI2IDAgMCAxLTQuNC00LjQwNiA0LjM1IDQuMzUgMCAwIDEgNC4zNjgtNC4zNzQgNC40MjUgNC40MjUgMCAwIDEgNC40IDQuNDA2IDQuMzUgNC4zNSAwIDAgMS00LjM2OCA0LjM3NHoiCiAgICAgICAgZmlsbD0iIzhFOEU5MyIgZmlsbC1ydWxlPSJldmVub2RkIiAvPgo8L3N2Zz4K) center center no-repeat;
   background-size: contain;
 }

```

**Output:**
```css
.search-icon {
  height: 14px;
  width: 14px;
  background: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTQiIGhlaWdodD0iMTQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CiAgICA8cGF0aCBkPSJNMTMuNzQzIDEyLjU3NEw5LjkxIDguNzRhNS40MjUgNS40MjUgMCAwIDAgMS4wNS0zLjIzMkE1LjUzMiA1LjUzMiAwIDAgMCA1LjQ2IDAgNS40MzYgNS40MzYgMCAwIDAgMCA1LjQ2OGE1LjUzMiA1LjUzMiAwIDAgMCA1LjUgNS41MDggNS40MDggNS40MDggMCAwIDAgMy4yNDItMS4wNjFsLjAwNC0uMDAzIDMuODMgMy44MzFhLjgyNi44MjYgMCAxIDAgMS4xNjctMS4xNjl6TTUuNDk2IDkuODc4YTQuNDI2IDQuNDI2IDAgMCAxLTQuNC00LjQwNiA0LjM1IDQuMzUgMCAwIDEgNC4zNjgtNC4zNzQgNC40MjUgNC40MjUgMCAwIDEgNC40IDQuNDA2IDQuMzUgNC4zNSAwIDAgMS00LjM2OCA0LjM3NHoiCiAgICAgICAgZmlsbD0iIzhFOEU5MyIgZmlsbC1ydWxlPSJldmVub2RkIiAvPgo8L3N2Zz4K);
  background-size: contain;
}

```

**Expected behavior:**

In the example you can see (actually to see that you need to get to the end of that long url in the example first :)) that `center center no-repeat` part of `background` rule is missing in the output. As `center` and `no-repeat` are not default values for `position` and `repeat` rules prettier should not erase `center center no-repeat`.
