### ISSUE TITLE
CSS var() with unit unexpected space

### ISSUE THREAD

**Issue by mazfish** [prettier/prettier#4224]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEYAJgB0pZYC0RAtgJ5EBuAhqklgIwAsA3PoSRUeptXQ0YA2dlAC++fADoKYAM5ywAGxoKcHLAAs4ASwDmmmAzA0lYABS1U5rpSsBKOKSwB6LFZtlKvGP1T37UTEQABoQCAAHGB1oOWRQOnQAdwAFOgQ4lBoqCB0AE1CQVRhkADNTOTgwgCNUGjAAazgYAGUI+p0oPWQYVABXKpA8iDAyisHOytQYFLq9UhoxpUqwgCs5AA8AITrG5paaUjgAGU64JZXwvpgI64AmC8H21CnkcAVCiNROmAB1fJgmmQAA4AAxhL4QSq-OoRN5fOBTKjnMKoOAARz6OjRsxo80WSHKy0GlVIOh6-RJnT0SjgAEU+phzoTxmEYDRqv88oDkHc2XUdEpqQBhCCkBZvKDQFEgPqVAAqHMyRMqYjEQA)
```sh
--parser css
```

**Input:**
```css
:root {
  --my-var: 14;
  --my-root-var: 16;
}

.mycssclass {
  height: calc(var(--my-var)em / var(--my-root-var));
}
```

**Output:**
```css
:root {
  --my-var: 14;
  --my-root-var: 16;
}

.mycssclass {
  height: calc(var(--my-var) em / var(--my-root-var));
}

```

**Expected behavior:**
Keep 'em' near 'var()' otherwise css post-processing fails.

**Comment by evilebottnawi** [comment]
@mazfish it is valid CSS?

**Comment by evilebottnawi** [comment]
From spec
> Similarly, you can’t build up a single token where part of it is provided by a variable:

```css
.foo {
  --gap: 20;
  margin-top: var(--gap)px;
}
```

**Comment by evilebottnawi** [comment]
Closed due it is invalid CSS.

**Comment by lydell** [comment]
@mazfish I think you are looking for this:

```css
:root {
  --my-var: 14;
  --my-root-var: 16;
}

.mycssclass {
  height: calc(var(--my-var) * 1em / var(--my-root-var));
}
```

Notice `* 1em`.

**Comment by mazfish** [comment]
Yes, exactly.
My final css after post-process is valid because "var(--my-var)em" is replaced by "14em" but not when Prettier goes on. That's the point. You're right.

Looking at the spec pointed by @evilebottnawi, the next paragraph details this specific case:

> Again, this is not equivalent to setting margin-top: 20px; (a length). Instead, it’s equivalent to margin-top: 20 px; (a number followed by an ident), which is simply an invalid value for the margin-top property. Note, though, that calc() can be used to validly achieve the same thing, like so:

```css
.foo {
  --gap: 20;
  margin-top: calc(var(--gap) * 1px);
}
```

Here is how to fix my (not) "Prettier issue" and add css to hook formatting.
Thanks @evilebottnawi @lydell.
