### ISSUE TITLE
Prettier discarding styles for long shorthand properties.

### ISSUE THREAD

**Issue by nomcopter** [prettier/prettier#4249]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6eBnGACYAdKbbAIwEMwBrAcwCcIBXKAEyW3poBsAKJ0mUpAEsAtqSpwA9FUEAzANxkMcAGwAWADQAlAAwcA4gHkAIhwAWAYSoBBAKJWAsgEk7ABQCcAIT0vlABw4SEgDqAJ4SAOyBLoExsXESIQASAKwetgDSVlYAilYAMlmFVpk5hfaaBuYGpunaEFbaTgCq9sIAKlYAWqYYQR7mAJpWBgDuALxjAJTYNHC+cHwAtAAe2BhgdBwc2NrYAIza2gCkcgQAviDqIBC+MILQGMigvjSCsEGCTDCmyHsATNorvxiB8vj8kH8rhg3lQOHBsvQIPBkDAaPQ4ECaKRBBwYeYIMJRMgQKQtpcQMQsZQ4DAAMq+cgwlFojEgABWGGWHipFBptNIwjgeTecGQMlJSiuDJoShoxPWGEeULgwkEzPRV3oSjapGIjyQ4o4kpAb1lMBcWKoRINEtZswAjvRBLMLWJrYbjS8IEogljfMSXnBZQA3UVXUg0OgjFwRhD6kkcEakEJKkBMCBgMW28NYLNG1kMGC+egwP55pRnM5AA)
```sh
--arrow-parens always
--parser scss
--print-width 120
--single-quote
--trailing-comma all
```

**Input:**
```scss
.test {
  background: url(data:image/gif;base64,R0lGODlhCgAEAMIEAP9BGP6pl//Wy/7//P///////////////yH5BAEKAAQALAAAAAAKAAQAAAMROCOhK0oA0MIUMmTAZhsWBCYAOw==) repeat-x scroll 0 100%;
}
```

**Output:**
Note the missing styles after the `url`:
```scss
.test {
  background: url(data:image/gif;base64,R0lGODlhCgAEAMIEAP9BGP6pl//Wy/7//P///////////////yH5BAEKAAQALAAAAAAKAAQAAAMROCOhK0oA0MIUMmTAZhsWBCYAOw==);
}

```

**Expected behavior:**
```scss
.test {
  background: url(data:image/gif;base64,R0lGODlhCgAEAMIEAP9BGP6pl//Wy/7//P///////////////yH5BAEKAAQALAAAAAAKAAQAAAMROCOhK0oA0MIUMmTAZhsWBCYAOw==)
    repeat-x scroll 0 100%;
}

```
