### ISSUE TITLE
custom selectors case is changed to lowercase

### ISSUE THREAD

**Issue by Coobaha** [prettier/prettier#4254]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABMBXAzjCBbAWizgBs4xcAnAAiQILAEM9SBhR46gOjwE8GsWIqXJUA3AB0oUug2ZsOcasCnVIJCJSTVKcACaSoAXykgANCAgAHGAEtoWZKCuVbsAOq29MABbIAHAAMFjCMAEae3n5IAEwWWG4A5mQAihgQ8MgAZowkxCGUjLYkSaz4eIzIIFDQcOYgYYVgANZwMADKVoxgScgwlBhwFgBWWAAeAEJNrR3yADJudUg5eUMgXZTElFVggvXEeLZ9A2vYcAAq4Y7LufkgblswAAqFiRXZt2u6AI4YtrovRhvSo3VYWFwQYjuQpWKouOBbABudQsjEolAgAHcnmiENcQIxERAvPU9BAwB8wQScJS7hAMDArAyYrS4EYjEA)
```sh
--parser css
```

**Input:**
```css
@custom-selector :--camelCase .my-css-selector;

:--camelCase {
 color: red;
}

```

**Output:**
```css
@custom-selector :--camelCase .my-css-selector;

:--camelcase {
  color: red;
}

```

**Expected behavior:**
```css
@custom-selector :--camelCase .my-css-selector;

:--camelCase {
  color: red;
}

```
