### ISSUE TITLE
SCSS: string argument in interpolated function are changed

### ISSUE THREAD

**Issue by TimPetricola** [prettier/prettier#4294]
When interpolating a function, if we have an argument containing a string, spaces are added in it. 

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6eBnGACYAdKbbSWBGJbAWwE8BaAMygAo8QB9VgSgG5sB6PtgAKAQQDKYgkRLxYFVgGJgNBs1YcQnAL6teA7ADERASQAyU7BZlkKKxixC0uewaIlXos8pZBK7axy4dEBdhcUlCS0jrOSo6e1ZaAENnfldwj1JYxWV4gOSg3TTDE3Nozxs41Qckp01QtwjpCuzfXOrWWsKQ4qMzC0yvWzyHeggIVP1Gwcqc-1Hx7tC+sq0QABoQCAAHGABLaAxkUCSAJ1OIAHchM4QjlCSANwg9gBMNkCSsZHokgBsMHBNgAjU5JMAAazgMDE23BeygAHNkDBTgBXIEgV4QMA-f6AzYIwGnGBCMGIyhJPEAzEAKwwAA8AEJgyHQsRJShwUwIuDUglbNEwbZCgBM-MxcNOxOQIAwYAwR0221OCJgAHU3jAABbIAAcAAZlRdAeqwdtZSq4MTHnzNqc4ABHNF7B1kpIUqlIX40zaAyh7FHozEYBGIv5wACKaIg8AlmxgSWBmteOuQooTYL2fzDAGEIJRKbKoNA7SA0YCACpJ+4+wFaLRAA)
```sh
--parser scss
```

**Input:**
```scss
.test {
  content: my-fn("_"); // PASS
  content: "#{my-fn("_")}"; // FAIL
  
  content: my-fn("-"); // PASS
  content: "#{my-fn("-")}"; // PASS
  
  content: my-fn("-a"); // PASS
  content: "#{my-fn("-a")}"; // FAIL
  content: my-fn("a-"); // PASS
  content: "#{my-fn("a-")}"; // FAIL
  
  content: my-fn("foo"); // PASS
  content: "#{my-fn("foo")}"; // FAIL
}
```

**Output:**
```scss
.test {
  content: my-fn("_"); // PASS
  content: "#{my-fn(" _ ")}"; // FAIL

  content: my-fn("-"); // PASS
  content: "#{my-fn("-")}"; // PASS

  content: my-fn("-a"); // PASS
  content: "#{my-fn("-a ")}"; // FAIL
  content: my-fn("a-"); // PASS
  content: "#{my-fn(" a- ")}"; // FAIL

  content: my-fn("foo"); // PASS
  content: "#{my-fn(" foo ")}"; // FAIL
}

```

**Expected behavior:**

Argument should not get mutated and spaces not added. The diff in the output should be as follow:

```diff
- content: "#{my-fn(" foo ")}";
+ content: "#{my-fn("foo")}";
```

In the meantime, a workaround to avoid that is to write `content: "my_" + fn("foo");` instead of `content: "my_#{fn("foo")}"`
