### ISSUE TITLE
SCSS comments are formatted incorrectly

### ISSUE THREAD

**Issue by am0d** [prettier/prettier#4311]
**Prettier 1.12.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wA6UABCQPTkkBqAhnurQEYA2cAzsWQOSboAe6KO24AaLiW4A3eo1YcxEyiQBCtdnAnc8HODEWlJ7MLQBmpiCwAmQgOYGeMAJ7Y4DilQDCEHNAQxOQ24menduGGYRAG4QURAIbBh0aHZkUHo8CAB3AAV6BFSUWikIdCtYkHUYZFNaFg04pjxaMABrPQBlbBa7ZBg8AFc4OKsIMBq6hpAhDQIc5ttMWgn64ZAAK3Z+FWa2ztpMOAAZITgVqYgBmGwrgCZzte68WeQQY3ZUuOwGWAB1MpgAAtkAAOAAMX0yGl+zWwr2+ujwUjOcR0AEcBugdPNaItlkhaqs4ho+H1Bmt2HY2ABFAYQeAPOIRJj-KxA5C3JnNdAsOzeTBLV5QPwVAYaAAqkQeAF9pUA)
```sh
--parser scss
```

**Input:**
```scss
@import
  // Variables
  'mixins',
  'variables',
  // Base
  'reset',
  'scaffolding',
  'type',
  // Components
  'bar',
  'tabs';
```

**Output:**
```scss
@import // Variables "mixins",
  "variables",
  /* Base*/ "reset",
  "scaffolding",
  "type",
  /* Components*/ "bar",
  "tabs";

```

**Expected behavior:**
```scss
@import
  // Variables
  'mixins',
  'variables',
  // Base
  'reset',
  'scaffolding',
  'type',
  // Components
  'bar',
  'tabs';
```

**Notes:**
There are 2 problems with this reformatted code:

1. According to [the SCSS docs](https://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments) there is a difference in behaviour between `// single line` and `/* multi line */` comments - single line comments are not preserved in the outputted code.  The comments should not have been changed to multi-line comments because this has a different meaning and results in different output behaviour.
2. The first comment (`// Variables`) has now been placed on the same line as the import following it, which comments out that import.  This is most definitely a bug as the code no longer compiles with this change.

**Comment by evilebottnawi** [comment]
We should switch to value parser for at rules

**Comment by evilebottnawi** [comment]
@jgerigmeyer very strange :confused: Can you create new issue?

**Comment by evilebottnawi** [comment]
@jgerigmeyer can you test this locally not in `playground`? Looks something wrong with `playground`, because test contain right comments

**Comment by jgerigmeyer** [comment]
@evilebottnawi I've tested both locally and in the `playground`, with the same results. I'll create a new issue.

**Prettier 1.13.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCAaAOlAegIAIYALASwGdjIBbOhGfVAIwEMAnY4fY4oqTLsYtCAyZ8xAGwickxAOSc4AE0UBuASXZQI5ON3qNY+AL758AEjoBPALTTqMJFMWYIi7NuIAxLG4cnJo+AEJcllA2DnTsAA4KABRuHooKAIzegv4QgVxpxABMWSThnPgAlBqRANpkKugAukhkEABuhsQAZCVC1GISplB1Dc2YYACuND0+5CIDJszD9XBNSOxgMBQd3TxSqDBY0ltxe1D8-BBxGxQwthnV58QWUGYg2CBXW9BUyKBcnAgAHcAApcBC-FDsNoQCiqd4gVicDYAazgMAAytcwBQoABzZAwTgTOAfXFUQwwEHIvGxZDodjSCkfABWVAAHqFkWA0Zj2IwADK4uD0xnMkDXTgUzjIEBUMBUX4fOKcXEwADqcPIyAAHAAGZWAinq5FxWUquDSjoIlQARwmFBU1PYtPYoqZpLlcDoFEJxM9VFxeOkcAAihN9CKkAyPR8YOxWJrVNqkMUQET2BQnPiAMLiOkoPRQEUfKZwAAqCchMYpZjMQA)
```sh
--parser scss
```

**Input:**
```scss
.foo,
// this comment
.bar {
  // that comment
  color: 'red'; // another comment
}

$my-list:
  'foo', // Foo
  'bar'; // Bar

$my-map: (
  'foo': 1, // Foo
  'bar': 2, // Bar
);

[href]:hover &, // this comment
[href]:focus &, // that comment
[href]:active & {
  .tooltip {
    opacity: 1;
  }
}
```

**Output:**
```scss
.foo,
/* this comment*/
.bar {
  // that comment
  color: "red"; // another comment
}

$my-list: "foo", /* Foo*/ "bar"; // Bar

$my-map: (
  "foo": 1,
  /* Foo*/ "bar": 2,
  /* Bar*/
);

[href]:hover &, /* this comment*/
[href]:focus &, /* that comment*/
[href]:active & {
  .tooltip {
    opacity: 1;
  }
}

```
