### ISSUE TITLE
CSS: box-shadow comma-separated value should break on multiple lines when >print-width

### ISSUE THREAD

**Issue by kaelig** [prettier/prettier#4460]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AynAhgJzACwCEIAPAAmAB0oyyAjUgWgGd8sATCAdyTIAYyARhxwAtmQBsI8TgDmdLAAo+AGn5rV-VIIAcASg1aAzNKGm5C5RutbBAdj0BuagF9qIFSAgAHGAEtoZmRQXBxuAAVcBCCULAA3CD92DxA6HCwwAGs4GHRvDL8oWWQYHABXOE9C5jgcGHD02VEsZAAzLAAbGs8AK2YSQnSsnPQsUTgAGUK4Ns7ukHycGpxkcGYgz28cQpgAdSSYfGQdVQWwmt3071WtuGW4mc8RAEcyvxEGrCaWpHauypANVEfhK5QBzEKsg6cAAimUIPBZv9PDAsHR9uxDsgAEwo9J+DqQgDCEFEzVWUGgjxAZRqABU0TE-jUXC4gA)
```sh
# Options (if any):
--print-width 80
--tab-width 2
```

**Input (line 2 is 81 chars):**
```css
.SearchBox {
  box-shadow: 0 1rem 6rem rgba(0, 0, 0, 0.18), 0 0.3rem 1rem rgba(0, 0, 0, 0.17);
}
```

**Output (line 2 is still 81 chars long):**
```css
.SearchBox {
  box-shadow: 0 1rem 6rem rgba(0, 0, 0, 0.18), 0 0.3rem 1rem rgba(0, 0, 0, 0.17);
}
```

**Expected behavior:**
```css
.SearchBox {
  box-shadow: 0 1rem 6rem rgba(0, 0, 0, 0.18),
    0 0.3rem 1rem rgba(0, 0, 0, 0.17);
}
```

**Comment by evilebottnawi** [comment]
In your example you have `80` characters in line :smile:

**Comment by evilebottnawi** [comment]
@kaelig feel free to investigate and fix it, i fix critical and main issues before `1.13` released, for me right now it is lower priority

**Comment by evilebottnawi** [comment]
Same problem:
```css
.SearchBox {
  box-shadow: 0 1rem 6rem rgba(0, 0, 0, 0.18), 0 0.3rem 1rem rgba(0, 0, 0, 0.17) !important;
}
```

**Comment by BPScott** [comment]
I think the root cause of this issue is that prettier does not seem to count `;` or `!important` when counting line widths.

I've scribbled up [a set of tests in this playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6eBnGBaARhAD2wwAsBDAEwgHcACYAHSltoHoAqJlgIQhhNoU4YADZkATmRgBLaLRHSocDLQlxaADgCMtMOXEqR0AOapaAFRLqAZtIMxaCCisWraGOAFtpkI1AA0tNQk0iJwXLT86h6QUBSCEMq0UHxmAAricDAycOK01hDinlJJUfKKNnZY5UqRELS46mTuisZhmloRehJkYPB5fsY16rgArg6ZBUVSKmUx0PEKtTD1je4ADgoOEABuuZHU9UvKqBEAkkEQoyLxcATrwg74-I4EZJ6bpfWThcXw8dAVgcjhUMBF2KwIvgiKRKDQkLRFB4HAAGWgAEl6YAQOCs0mMJFRtDR6JIAGtAkisu5yFRqAAKGCSKAYdZqWAASkCsKo9I5AG4oYRiLT4YiWdSSVicdg8QSiSTyZSJQ4eTRGczWeyYFyaXCGRyWEwAL5MM1QdDKHDabDdcTYISiHoyOSMZhsTju3gvR1iSQu5jHFRqDq6fSGExmSyVeyOOIuZjNDzeXzQQLBULhd1zYQLBJJFIwdKZbLSfZTP6zKzDfJVBzHOoNJotKBtdTaLr6Xr9eQmYZmbjjWg-aYwKvRXNxGtAtasra0Xb7GCHYYYU7ui6Ha63e6PBp8AR3d6fWbfOAVkoA2D1ZcgpRr8GQqARYriYyKBHozJkEQiACe2CDNgOwSNIZC4GE2BQO86iYoWVj2t+v4AUB0GeLBZDYPwdgUIBJhQe8gruq+75QJ+SH-nhrbAaB4GQWhGHwbk2AUSh+EMRimHYeIuGoTBJrmpaWDYBoKK2voDrCH6UiyMwbosBwETegIvrOrJq6qJkmhonaEatlG1a2NUTgJm4yY+BAfjpiE7QRDmsTxFQBapLQGRZDkeQXmOkSGXW06rM2GCtO0olhhIEQNoy1aQOImR9E25A7LIoziByxbuWWnm-DMPkTg5ghSWpchkMGERBa2IU6Ha-bnJc26vA88X2XmR4fO0M7qCOfz-Au17Aqu64sBCL4SKR5FwD+lFASB4hgRBcAEehnFMYhE3IVRxiLRhWEhDxG0EURLAkR+GKsftM1zfRMHLQezFnXxS2YjtOH7WhAnPlAHAWCEwYiBg9QeF4p6qNY1h7gAygAwuD4O0BddHqKp-rqcNFqYDgGBgBgGA0bNCMqPJHoRJY0iGBUiIqNoYWSH0uR6cYgSblcNwNXu0gOB1w7ntl2RwFeQK3hFoKDbQqMsOi8xxBIAHdrJwG5DIYA-tgbIUBQABMCIoqgACsou0PSsRMpZspwPihJ8rQ2DDKb5swPS+AUH+HICu9TBfQAhNIHyFDAZCwPmKiFu4cBeI2ayQKMsB8447MIXU1ASM4uXU92+yRwHZtRHkqOoODE3iHovAEPQERHaNJ1fmtU34fD81bTd2csdXbHURxT3cbx7G0F7PviH7sCHfuMKitQWu0FomSeLQABsU-DsYuBkPSKKBKvxJr6gWgaLqaLawAzPPk9h2+S8r2vF-ElvADshq9+svv+zARGmlAID+CAEDrAGGDIKAEjiBoGkdkv8UBkB2BAaQFB34gFwDTMkWRwZsjAK0ZATJRhwA-lSfuGQyDGGKMgawP4PAfwAFYYAINweBiCYIABkKiEOIZgkAbIDC5GQCATG2MYHrFmrAAA6lA-gyBRIf14RADw-DJDrA4bw5QuQ9gwMyAAR1GHYOAuD8FkEYX9Zh5k0HiAwR-cqbYACKow+BwB0SQkAftcCCIoMIpA6sP5MjIKEVokMICeAISgFISgYGjA8OYcCoCiG6ONMaIAA) that check for edge cases around 80 characters.


For instance, both of the following margin declarations are 81 characters long. The first is not reformatted onto two lines, while the second one is correctly reformatted.

```scss
.test-81-char-declaration {
  margin: $really-long-variable-name $another-really-long-name $a-third-long-nam;
  margin: $really-long-variable-name $another-really-long-name $a-third-long-name
}
```

**Comment by BPScott** [comment]
Commas are also not counted:

```scss
.demo {
  background-position: 0 0, 0 spacing(tight), spacing(tight) -1 * spacing(tight), -1 * spacing(tight) 0;
}
```

compiles to the following - where the comma on the first line of the property is the 81st character on the line:

```scss
.demo {
  background-position: 0 0, 0 spacing(tight), spacing(tight) -1 * spacing(tight),
    -1 * spacing(tight) 0;
}
```
