### ISSUE TITLE
[scss] broken when map is argument

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#4488]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOld6ACAllGADYCuAJnOofALYC0AzgA4QymEDmAFjI1YAnCKzhCYhOM0YwhqKMzqFoAChx48WELLqk42gDQbN63JrwAjCAA8WvVJQgB3JOgAM6AMysb6AIzuvuhC3Jaoqu6GHtFRHgB0-gCsAJQpxuYW1kLUQoyQpBBCbgAklvJQlIJChPSoQgCeJngpJikA3DgAvjgghiCiktDMyKD1Is4ACvUIIyioAG4QhJR9IOWoYADWcDAAyqybxNzIcuRw-cTM4jCT8tx1yABmqKTX-QBWzDYAQvLbuz2qHocAAMsQ4M9Xu8QIchNchMhwMwRv1hMQYAB1FYwXjIAAcUVhImumPkrCRwmk4gWkP6QjgAEdyIQGXdUA9UFC3hcQNd6IRTkJzv0lFBuPoAIrkDiQpAvHn9GCoSzYyi45AAJiV8kIXHFAGEIPRHigoNA6SByNcACoquYK65dLpAA)

**Input:**
```scss
a {
  @include item-spotlight-properties-transition(
    "-title",
    (
      box-shadow: 0 3px 10px rgba(0, 0, 0, 0.15)),
      border-color: $brand-primary
    )
  );
}

```

**Output:**
```shell
Unbalanced parenthesis
```

**Expected behavior:**

```
a {
  @include item-spotlight-properties-transition(
    "-title",
    (
      box-shadow: 0 3px 10px rgba(0, 0, 0, 0.15)),
      border-color: $brand-primary
    )
  );
}
```
