### ISSUE TITLE
Does not format content inside media query for scss files

### ISSUE THREAD

**Issue by xeoneux** [prettier/prettier#4523]
**Prettier 1.12.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtnAJgSwIYAEAzmAE5wIF5RYEAU6eAHgLQDuOWMAFkgWHgA2YOgBIYeAEaC4MAvPksF8gIwAGNQAcmASh0FgAHSjL5jUgHMcUPirjoCagNzHlAX2OuM2fMTIUTaloGZnZOHj5xKRk5UwUlOPUtXQNXU3MrGwI7B2c0+TcQABoQCE0YHGgiZFA8UlIINgAFOoRqlDwANwhOYpBJUjwwAGtZAGVNIesLZBhSAFc4EusiOFIYJsGLRmQAMyFVkoArIiYAIUGR8bxMABlrOD2DpZBJ0lXSZBASImqSzVI1hgAHVwtxkAAONT-BqrYGDTRfAFwD6dR4lcgAR3mOHImzw2zwT0Eh2+9hwswWLyI0xkAEV5hB4MTSRJJKCuOCkAAmEpzPA4QTTADCEHQOxQUGg6JA81WABUpO19iS4G43EA)
```sh
--parser scss
```

**Input:**
```scss
@media screen and (max-width: calc($tablet     -     100px)) {
      margin: 1em 0;
    }

 @media screen and (max-width: $tablet         -       100px) {
      margin: 1em 0;
    }
```

**Output:**
```scss
@media screen and (max-width: calc($tablet     -     100px)) {
  margin: 1em 0;
}

@media screen and (max-width: $tablet         -       100px) {
  margin: 1em 0;
}

```

**Expected behavior:**
