### ISSUE TITLE
SCSS comments are formatted incorrectly

### ISSUE THREAD

**Issue by jgerigmeyer** [prettier/prettier#4594]
While #4311 has been marked resolved, it appears that it has only been partially fixed. Line comments are still being incorrectly converted to multi-line comments.

**Prettier 1.13.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCAaAOlAegIAIYALASwGdjIBbOhGfVAIwEMAnY4fY4oqTLsYtCAyZ8xAGwickxAOSc4AE0UBuASXZQI5ON3qNY+AL758AEjoBPALTTqMJFMWYIi7NuIAxLG4cnJo+AEJcllA2DnTsAA4KABRuHooKAIzegv4QgVxpxABMWSThnPgAlBqRANpkKugAukhkEABuhsQAZCVC1GISplB1Dc2YYACuND0+5CIDJszD9XBNSOxgMBQd3TxSqDBY0ltxe1D8-BBxGxQwthnV58QWUC-4AAIUdHFyS-yCADUuBR2KxpHAqG46BQAB4UKBULxuNrA0HgxF4J6CcJUOBuFS4mBIp6KKhgdjoTDSVTwgDmxP4ijucTgDJ8AGFxD8oExISSgmymaDERoQNgQFcttAqMhQFxOBAAO4ABS4CBlKHYbQgFFUYpArE4GwA1nAYABla5gOnIGCcCZwcXw3GcGDKo202LIdDsaS48UAKyoMNCRrApot7EYABl4XBvb7-SBrpwXcgQGSqDLxXFOPCYAB1XXkZAADgADDmFbiC0a4uncxDDB19SoAI4TCgqd3sT3sBN+x0ZuDQ232odUOnggCKE308aQPsH4pgoKLqhLSGKIDt7AoTigtM5DH7KD0PP1UzgABVhQPcWYzEA)
```sh
--parser scss
```

**Input:**
```scss
.foo,
// this comment
.bar {
  // that comment
  color: 'red'; // another comment
}

$my-list:
  'foo', // Foo
  'bar'; // Bar

$my-map: (
  'foo': 1, // Foo
  'bar': 2, // Bar
);

[href]:hover &, // this comment
[href]:focus &, // that comment
[href]:active & {
  .tooltip {
    opacity: 1;
  }
}

@import
  // Variables
  'mixins',
  'variables',
  // Base
  'reset',
  'scaffolding',
  'type',
  // Components
  'bar',
  'tabs';
```

**Output:**
```scss
.foo,
/* this comment*/
.bar {
  // that comment
  color: "red"; // another comment
}

$my-list: "foo", /* Foo*/ "bar"; // Bar

$my-map: (
  "foo": 1,
  /* Foo*/ "bar": 2,
  /* Bar*/
);

[href]:hover &, /* this comment*/
[href]:focus &, /* that comment*/
[href]:active & {
  .tooltip {
    opacity: 1;
  }
}

@import // Variables
    "mixins",
  "variables", /* Base*/ "reset", "scaffolding", "type", /* Components*/ "bar",
  "tabs";
```

**Expected behavior:**
```scss
.foo,
// this comment
.bar {
  // that comment
  color: 'red'; // another comment
}

$my-list:
  'foo', // Foo
  'bar'; // Bar

$my-map: (
  'foo': 1, // Foo
  'bar': 2, // Bar
);

[href]:hover &, // this comment
[href]:focus &, // that comment
[href]:active & {
  .tooltip {
    opacity: 1;
  }
}

@import
  // Variables
  'mixins',
  'variables',
  // Base
  'reset',
  'scaffolding',
  'type',
  // Components
  'bar',
  'tabs';
```
