### ISSUE TITLE
Negative values in long CSS properties will cause incorrect wrapping

### ISSUE THREAD

**Issue by tlaak** [prettier/prettier#4604]
Negative values in e.g. CSS backgrounds seem to cause some weird behaviour with the wrapping. Are they perhaps ignored?

**Prettier 1.13.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6GALAlgZwLQDuWANsXlBDIQE4CGADgATAA6UjjARrWANYDm1CAFcoAEySMYdKDnq1qCGI2HViACgD0xaP03zMmmBE1jhAW3MBPPFnO1+cVDgBu-AJSM8ARgAM-+gAPRjAlOGpGCjxFejhaGABuNgBfNjZ0bHwiUhoGPEhqRTAYYitmNg5uPkERcUlpWll5RVgVNS0dKD0DDCMTM0sbOwcnVw9GPwDg0NhwyIhouFj4pKhUqHTMXEISMlpiHAWCOno8TmEqLCgCopKy1nYuHgEhUQkpGTkFJTaNTTgXAhtLpwvp4r1jKYLNZbPZHM43J4fP5fEEQmEIlEYnFEik2CAADQgCD0GBYaA4ZCgBRCAgABW+smQIFoLggWDEhJAnDofDgMAAyvIwFd+MhpMI4ESrjhwjA6XR+PZkAAzfayokAKxwgQAQrzePyBbRzHAADJXOCq9VSkDNWXUZlgHCUon0ahXGAAdQ5mGQAA5fG6hLKvSdme64A7AVzFABHYRYRQKhzKpBqg622XmLDi6iSok4UXEOAARWElCt6ZtRJgtE4PrEfqQACZa3QSKKAMIQSy0ZkUKBWonCWUAFXrlOrmeSySAA)
```sh
--parser css
```

**Input:**
```css
.this-will-not-wrap {
  background: transparent url(/long/path/to/dummy-image.svg) -1000px center no-repeat;
}

.this-will-wrap-correctly {
  background: transparent url(/long/path/to/dummy-image.svg) 1000px center no-repeat;
}

.this-will-also-wrap-but-incorrectly {
  background: transparent url(/even/longer/path/to/dummy-image.svg) -1000px center no-repeat;
}

```

**Output:**
```css
.this-will-not-wrap {
  background: transparent url(/long/path/to/dummy-image.svg) -1000px center no-repeat;
}

.this-will-wrap-correctly {
  background: transparent url(/long/path/to/dummy-image.svg) 1000px center
    no-repeat;
}

.this-will-also-wrap-but-incorrectly {
  background: transparent url(/even/longer/path/to/dummy-image.svg) -1000px center
    no-repeat;
}

```

**Expected behavior:**
```css
.this-will-not-wrap {
  background: transparent url(/long/path/to/dummy-image.svg) -1000px center 
    no-repeat;
}

.this-will-wrap {
  background: transparent url(/long/path/to/dummy-image.svg) 1000px center
    no-repeat;
}

.this-will-also-wrap-but-incorrectly {
  background: transparent url(/even/longer/path/to/dummy-image.svg) -1000px 
    center no-repeat;
}
```
