### ISSUE TITLE
Parsing valid SCSS results in CssSyntaxError Unclosed block

### ISSUE THREAD

**Issue by davidgomes** [prettier/prettier#4635]
**Prettier 1.13.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgAcAbAQzDgAsJiATOAJ32AB0D8OAyJJE8qmvSbBUkWAhgBfNtPZsARhFoBPZmw6RiEAK4Mk+AO6VM8ANzr888gGsA5gx1RaAWk069+e3GXm57VHhgxNr0RGQU1HSMauwaNBAeACRuDM4AzpjEAG6MvhyykiAANCAQhDCY0GnIoKQMDgYACnUI1SikWRCYtMUg8gw2cDAAyoTkeLbIMAzacCV4aYwwjQO26KTIAGakxIslAFZp2ABCA2DWQ8Ok6HAAMnhwWzt7IGMMiwzIIGlgadUlhAYeBgAHVujBKMgABwABgBDkWIIGhC+gLgHxyvQYcAAjtpMNiVqQ1hskNtdnNvnAsFMZpSMlBbMQ4ABFbQQeBPCklGCkeRg2gQ5AAJh5A0yEwAwhB0OsvlBoI8StpFgAVPltcmLSSSIA)
```sh
--parser scss
```

**Input:**
```scss
@mixin placeholder {
    &::placeholder {@content}
}
  
body {
  color: white;
  background-colour: grey;
  
  @include placeholder {
    color: $color-silver;
  }
}
```

**Output:**
```scss
SyntaxError: (postcss) CssSyntaxError Unclosed block (1:1)
> 1 | @mixin placeholder {
    | ^
  2 |     &::placeholder {@content}
  3 | }
  4 |   
```

**Expected behavior:**
Parsing should work as this is valid SCSS. Try https://www.sassmeister.com/ or https://sneakertack.github.io/postcss-playground/ to verify that this is valid syntax. This is happening on the latest version of Prettier.
