### ISSUE TITLE
 [SCSS] Selector starting with `#{}` is lowercased

### ISSUE THREAD

**Issue by ruedap** [prettier/prettier#4666]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAZkgBAHRAOnQgjwG4coKBiYDAXwFoBGAIQEEAlLYCrLSADYQATtmFwAJuSh0QAGhAQADjACW0AM7JQAQ2HCIAdwAKehFpQ6AbhFUT5IAEbCdYANZwYAZSWvVUAHNkGGEAVzgFfw04YRhjFwCAWx1kdB0BaIUAKw0ADxYXd08vHUS4ABl-OFT0zJBfYWjhZBANMA0tBSVhfxgAdTsYAAtkAA4ABi6DaL6XJRbuuCaraoVxAEdQ1XF4nSSUpDSMiNa4RNVgsJONfwCBOABFUIh4GuOFGB1HAYlh5AAmD4uVQCW4AYQgiWSLSg0FWIFC0QAKl8LEdonQ6EA)

**Input:**
```scss
$f: ".foo";

#{$f}-1BAR {
  color: red;
}
```

**Output:**
```css
.foo-1bar {
  color: red;
}
```

**Expected behavior:**
```css
.foo-1BAR {
  color: red;
}
```

related issue: #4044
