### ISSUE TITLE
Scss variable string concatenation removing spaces

### ISSUE THREAD

**Issue by MichaelFBA** [prettier/prettier#4691]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ADgQwOZwLQBGEMMEAtnmDJgATAA6U9MBmYA1tgE4QCuUAEzwBLMjjhIavLgBsAFABJMAZ2VwYyvFhgALGgGoaAcmXUYwsAHoZmQcKjYt45ZYBmEYnC4ixuPMpwuTAFMfzJUACt0bCMASgBuRmZWDm4+QTwuOHQ4TBhJKAhM7NyYRKgAXxAAGhAIdHNoZWRQTC4eAHcABTaEZpRMADcIYQEakAIgjnUAZSwwe2xkGC5eOFr7NS4YLqDsMWRXTBk1WojlAA8AISn2WcwyOAAZezhD49OQLC4t5BBlMCqcboLj2GAAdVGumQAA4AAy1EEQNTgoLoP4guBbQZvWpZACOvGEWV2OAOSCOJ3W-zgZGEy1W1OUixkcAAirxPO8qbVqARIQJoUgAEy8oLCGSLADC5HJIEKUFxIF4agAKpgCP1KWoKhUgA)
```sh
# Options (if any):
--parser scss
```

**Input:**
```scss
.page-bottom-cta {
	background-image: url($assets-path + 'static/landing-pages/footer-image-sagrada-sm.jpg');
	background-repeat: no-repeat;
}
```

**Output:**
```scss
.page-bottom-cta {
  background-image: url($assets-path+"static/landing-pages/footer-image-sagrada-sm.jpg");
  background-repeat: no-repeat;
}
```

**Expected behavior:**
When doing string concat in scss files, the space around the ` + ` is being removed.
Is this by design or a bug?

**Comment by SemperPeritus** [comment]
All I could think of was to replace the concatenation to variable interpolation.
```css
.page-bottom-cta {
  background-image: url("#{$assets-path}static/landing-pages/footer-image-sagrada-sm.jpg");
  background-repeat: no-repeat;
}
```
But this is not the best solution.
