### ISSUE TITLE
[SCSS] Space removed after minus sign

### ISSUE THREAD

**Issue by dfdeagle47** [prettier/prettier#4698]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASADhAzgSxj6LJAAgDMcAnLGAGmKzkigBM6YALS5gbgB0oAAnACGYdsQzY8BKMRyzJufIWLB+xDcQDEwRdOgBfVes0aANnFIwSAWjks4ADwAUe5VCx03MgJTEAVMQAjAAMIeiOfLLEvDAG-PFQIDQgEOjuWMigwhQUEADuAAo5CJkowgBuEDjMySAARhSiANZwMADK6KLyAObIMBQArnAp8gwUMIVNPQC2wsikwmYMKQBWWI4AQk1grR3CM3AAMvJwC0srIF1UcBTIIFhgWJkp6BTyMADqNRzIABwhV55BifJroe5vODjCpnFIUOAAR0GlDgU2Es3mSEWyxGDzgMxw-SGuNwUB6FgAioMIPBzjiUjBhPVvsxfkgAEwMpo4My9ADCEBmc3uUGgsJAgwYABUmWVsQwDAYgA)
```sh
# Options (if any):
--parser scss
```

**Input:**
```scss
$positions: first, second, third;
@each $position in $positions {
    #{$position} {
      left: - index($positions, $position) * 100px;
  	}
}
```

**Output:**
```scss
$positions: first, second, third;
@each $position in $positions {
  #{$position} {
    left: -index($positions, $position) * 100px;
  }
}
```

**Expected behavior:**
The space after between the minus sign and `index` should never be removed. Otherwise, it breaks the scss compilation with an error `Undefined operation "-index(first, second, third, first) * 100px".`.

**Comment by evilebottnawi** [comment]
Information: `stylelint-scss` have good logic around SCSS operators (https://github.com/kristerkari/stylelint-scss/tree/master/src/rules/operator-no-unspaced), maybe we should adopt some logic here

**Comment by evilebottnawi** [comment]
Logic here https://github.com/kristerkari/stylelint-scss/blob/master/src/utils/sassValueParser/index.js
Solutions:
1. Publish https://github.com/kristerkari/stylelint-scss/blob/master/src/utils/sassValueParser/index.js as separate package and adopt this in prettier
2. Implement own logic based on code.

**Comment by evilebottnawi** [comment]
@vjeux what do you think? CSS, SCSS and Less has very difference algorithm for handle operators (special SCSS with interpolation, what also doesn't supported `postcss-values-parser`). It's harder and harder to keep them working together. I don't know how we should solve this :disappointed:

**Comment by evilebottnawi** [comment]
@vjeux sound good, i try to fix it without break for other language, if i can't we split this

**Comment by robert-j-webb** [comment]
[Here's a playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASADhAzgSxj6LJAAgDMcAnLGAGmKzkigBM6YALS5gbgB0oAAnACGYdsQzY8BKMRyzJufIWLB+xDcQDEwRdOgBfVes0aANnFIwSAWjks4ADwAUe5VCx03MgJTEAVMQAjAAMIeiOfLLEvDAG-AYgNCAQ6O5YyKDCFBQQAO4ACtkIGSjCAG4QOMxJIABGFKIA1nAwAMroovIA5sgwFACucMnsMAC2ZgDqnPBYnWBwbSXS5XgAnsjgWBnJ8gwUMAWN3WPCyKTCZgzJAFZYjgBCjWAt7cJjcAAy8nDnl9cgO6ONo9CwARQGEHgfyuwxAnSocAomywYG2tXQFHkMEm1Q4yAAHCFkpjsHBJo10JtMXB9uVfskAI6Q+BHVKlEDCLA2KBwODMfm1ChwZmUOBHYQnM5IC6w5IMMY4PqDOG4KDdcEs34y-5wmDCOq45j4pAAJmS-WEODMPQAwhAxqdNlBoAyQAMGAAVA2lWUA8pDACSDlgbTAWLSAEEWG0YGsLDCGAYDEA) for those who are curious about this issue

**Comment by roland-reed** [comment]
There is still a problem in scss code below with v2.1.1:

```scss
#root {
  height: - rem(40); // <-- "-" before "rem" will be removed
}
```
