### ISSUE TITLE
SCSS file with multi-line comments is malformed when formatting

### ISSUE THREAD

**Issue by shiftkey** [prettier/prettier#4716]
**Prettier 1.13.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngOhgCzgFs4BaDAQwCcBrAAmAB0o66B6AKg+ddY7oCCAByF0SUAK51U1OpAA2EKgGc6ACgDqASygYIAd2VsAMjokAPOtHlYAlD14c2D0qQojS4iaVQSYMaFJ8CAA3OCofCjAaAHMqCAldUgUlJDoQ6jUHVlcAiHkZCN9-QOCwoqjY+MSMZPylB1sAbgdObhZHOgAhSriE3Tl6qjoAMyVpCgwYuFUdZS0MOCsRujyC2WKAqGUcbLp+AFFzCiIheRnliamL6iWCJYpCSbZUOHwdDGkJVFRzuh1VoQ9vwhBJlPg2KD5PIviUWBQBvc6AAFABKV2m-xYSNQVARYHwdAw8SEwKJBhYm2guw6fGcHVyEHyhUi10i0T6NTqiioaQAJHEKFhSAB2AAMYpaUAAvsxmCAADQgCBCGBaaDKZCgajxfTI27bZAgCghCALRVoPHROAwADKQiiOhiyBgVAkcCVc3CMGReJiRAoyBGFHkyg9IAAVspzF0rTQbbaTnBTFA4EGQ2GlQ6VOEjcowMpNVmqDoYNoMARkAAOMXFiBhjR4oRGoRUGbhMIWtsARwkWjbvoo-sDSGDofDYaIWhdbonTvOAEUJBB4Onx0qYBRUOXK0gAEwbvFaeROgDCECIAaNUGgaaVYLgABUt5rRxnwxRlDA15mQHowD+4YJDAoIwHugHStKQA)

**I've only been able to reproduce this on Windows**, and that Playground link above shows that it doesn't munge the comments there, so I've put together a repository which should be setup to see the issue on Windows:

```
$ git clone https://github.com/shiftkey/prettier-repro-scss
$ cd prettier-repro-scss
$ npm i
$ cat file.scss
$ npm run repro
```

**Input:**
```scss
body.theme-dark {
  /**
    * App menu bar colors (Windows/Linux only)
    */
  --app-menu-button-hover-background-color: var(
    --toolbar-button-hover-background-color
  );
  /**
    * Background color for badges inside of toolbar buttons.
    * Examples of badges are the ahead/behind bubble in the
    * push/pull button and the PR badge in the branch drop
    * down button.
    */
  --toolbar-badge-background-color: $gray-700;
}
```

**Output:**
```scss
body.theme-dark {
  /**
    * App menu bar colors (Windows/Linux only)
    */
  --app-menu-button-hover-background-color: var(
    --toolbar-button-hover-background-color
  );
  /* *
    * Background color for badges inside of toolbar buttons.
    * Examples of badges are the ahead/behind bubble in the
    * push/pull button and the PR badge in the branch drop
    * down button. */
  --toolbar-badge-background-color: $gray-700;
}
```

**Expected behavior:**

Multi-line are not malformed when formatting
