### ISSUE TITLE
[CSS] Prettier splits non-standard units

### ISSUE THREAD

**Issue by seaneking** [prettier/prettier#4726]
**Prettier 1.13.5**

Following on from https://github.com/prettier/prettier/issues/4348, Prettier breaks when using various PostCSS plugins that use brackets in values, by splitting the unit away from the value. For example, with `postcss-modular-scale`. 

**Input:**
```css
.foo {
	font-size: ms(1)rem;
}
```

**Output:**
```css
.foo {
	font-size: ms(1) rem;
}
```

**Expected behavior:**

Preserve declaration value as written

```css
.foo {
	font-size: ms(1)rem;
}
```
