### ISSUE TITLE
Grid template areas with SCSS interpolation are placed into one line

### ISSUE THREAD

**Issue by msterba** [prettier/prettier#4745]
**Prettier 1.13.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAZhCBaAhgJzlyQAJMIBuAHSlQCMC9DiSH9qoaA6Ac3wEsAJtnS5+AGwDOJYDRIk+Q7PAC2AB3G54TIpKRz5JKiADEwDFh24AviTMWcBIteMH5x+2yu375b8Y4XTiheAWEAdwh8AGtpWSh5RWFVDS04Kz03IxA7cz8nG1yHfxAs4yKvAp88yyqAmiCQABoQCDUYfmhJZFACfAhwgAUnKG6UXAA3CCFmkDp8XDBouBgAZTVF-igeZBh8AFc4Fq3JOHwYQYWeFVxkUSkjkAArSQAPACEFpZXV3BU4AAyWzgd1wDxaG3wp3wyBAkjAkm6EIEsAA6kIYAALZAADgADMiIKdUQs1LC1IRoRMQS1CABHfb8QiXXDXW5Ie6nFqnFT8XYHR6SLY8cRwACK+wg8FB4JAMFwdHRgixyAATC09mJxMKAMIQFQ3WFQaA0kD7U4AFQVY05cGs1iAA)
```sh
--parser scss
```

Additional case related to closed issue https://github.com/prettier/prettier/issues/3136 in combination with SCSS interpolation: If the area definition starts with a hash `#`, it is placed into one line.

As a workaround a leading space can be added.

**Input:**
```scss
$foo-area: foo;
$bar-area: bar;

.grid-fails {
  grid-template-areas:
    "#{$foo-area} #{$foo-area}"
    "#{$bar-area} #{$foo-area}";
}

.grid-works {
  grid-template-areas:
    " #{$foo-area} #{$foo-area}"
    " #{$bar-area} #{$foo-area}";
}

```

**Output:**
```scss
$foo-area: foo;
$bar-area: bar;

.grid-fails {
  grid-template-areas: "#{$foo-area} #{$foo-area}""#{$bar-area} #{$foo-area}";
}

.grid-works {
  grid-template-areas:
    " #{$foo-area} #{$foo-area}"
    " #{$bar-area} #{$foo-area}";
}

```

**Expected behavior:**

Interpolated SCSS variables in grid template areas should not be special handled by prettier.
