### ISSUE TITLE
Yaml: Invalid behaviour for empty nodes

### ISSUE THREAD

**Issue by xorik** [prettier/prettier#4843]
**Prettier master branch**
[Playground link](https://deploy-preview-4563--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzATgQwLZwO4ToDWSAOlAARUUDOcY6cMSFA5AKQIBuAFAIIAFAQH0AygFEAwgCVxAFQCU7VuWoUAxABM4qTAFcANjGEGIYTAbgsEq6urA10qYQAd0EeGBgBLaCxjoenC2VOoAFjAwLsK4MGEQmsIQXHDo6N7a-oHBUCEaFOJQmABGljS0cDQ0vpQ0ei4uhDAAdBQAch5wFHGYMN1hXXRVNRR43gYGFADybQAyAJoUxYMwmOjwmhTeqBQAnhB6FIyYm4Sj6fAUGBDYWy156hTScNjJXWeQ2Liw-d7ldF4RjAIBQ4AAPFwGbxgbwwAy7CiaP4lSwVYbQWj1RrrZp5IbVPx5NRhTBQTSWdDCDIsAB+5AelW8WSCDwwmAA5t8YDRmTk1C4wtFUu50DyidRTOzefTKNRzGABmRZWpQhQBHo+nEunooN4AI5BChFXAUCA7fZ6dAUTANCgDRj+AYUNw6bxgipwTTi1V-Ch6OibYEUT4uDUrFFdY2VFyYMCVK4fWNOohwXY0XHKlXqF2oN3COielgWykpMmEYRRgD0NuiUZlKrsFDkTprwaTXXlA3KQa1V3GlTT8FuxQR2l0hnumbUjymWqtEBcPmg5W8UDABj0mXrDfyzyRNG9GhrLE7cGaJxt8HQzUY+8PWh0+iMwlvf1c7i4GVSLFfPMrldMcwDHiGgYG3BtHkESRDh4KAPCOegbm+bRNjGOI7TgTAuARLAy2wABaPALi6AhiFME5ykwcpcFedAETZTkEFWJdKHMVj9DoZ1Uh2P46kqBR72PNsFTPC9F1Sc8XDAPRyBAAAaEAFxYmhkFANZ3DwAQ1gQFSUCwiAMnkkBiiwMAUxgUQYxhKB2WQAIggU1c6HWAQsE5TBkF0Aw6AUgArGgwQAIVM8zRBwOBZlXOBPIsHyQBjUVUmQEBdhwAwjLcVcYAAdQyOJkAADgABgUtwIDobKsBcZKXWclIjMYA1vEYVyOWwDykC8uK6Gwbw7OyBTqhsywAEU9E6GLvLgBTVmKXLNHypAACYZqwcZV3ZSQkI6kA4KgaKFP9OA5BKXSurgABfC6gA)

**Input:** [source](https://github.com/symfony/recipes/blob/master/symfony/framework-bundle/3.3/config/packages/framework.yaml)
```yaml
framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

```

**Output:**
```yaml
framework:
  secret: "%env(APP_SECRET)%"
  #default_locale: en
  #csrf_protection: true
  #http_method_override: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: ~

  #esi: true
  #fragments: true
  php_errors:
    log: true

  ? cache
# Put the unique name of your app here: the prefix seed
# is used to compute stable namespaces for cache keys.
#prefix_seed: your_vendor_name/app_name

# The app cache caches to the filesystem by default.
# Other options include:

# Redis
#app: cache.adapter.redis
#default_redis_provider: redis://localhost

# APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
#app: cache.adapter.apcu

```

**Expected behavior:**
the `cache` section shouldn't be broken

**Comment by j-f1** [comment]
I think the issue is that the `cache:`
got changed to `? cache`.

**Comment by ikatyang** [comment]
The formatting changes it from implicit key to explicit key, which is valid, see [YAML 1.2 spec](http://yaml.org/spec/1.2/spec.html#id2798425).

**Comment by ikatyang** [comment]
@xorik Could you clarify what's your expected behavior? a sample code would be appreciated.

**Comment by ikatyang** [comment]
Moved the comment issue https://github.com/prettier/prettier/issues/4843#issuecomment-405062706 to #4853.

**Comment by ikatyang** [comment]
With the fix for #4853, it's now formatted as:

**Prettier pr-4854**
[Playground link](https://deploy-preview-4854--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzATgQwLZwO4ToDWSAOlAARUUDOcY6cMSFA5AKQIBuAFAIIAFAQH0AygFEAwgCVxAFQCU7VuWoUAxABM4qTAFcANjGEGIYTAbgsEq6urA10qYQAd0EeGBgBLaCxjoenC2VOoAFjAwLsK4MGEQmsIQXHDo6N7a-oHBUCEaFOJQmABGljS0cDQ0vpQ0ei4uhDAAdBQAch5wFHGYMN1hXXRVNRR43gYGFADybQAyAJoUxYMwmOjwmhTeqBQAnhB6FIyYm4Sj6fAUGBDYWy156hTScNjJXWeQ2Liw-d7ldF4RjAIBQ4AAPFwGbxgbwwAy7CiaP4lSwVYbQWj1RrrZp5IbVPx5NRhTBQTSWdDCDIsAB+5AelW8WSCDwwmAA5t8YDRmTk1C4wtFUu50DyidRTOzefTKNRzGABmRZWpQhQBHo+nEunooN4AI5BChFXAUCA7fZ6dAUTANCgDRj+AYUNw6bxgipwTTi1V-Ch6OibYEUT4uDUrFFdY2VFyYMCVK4fWNOohwXY0XHKlXqF2oN3COielgWykpMmEYRRgD0NuiUZlKrsFDkTprwaTXXlA3KQa1V3GlTT8FuxQR2l0hnumbUjymWqtEBcPmg5W8UDABj0mXrDfyzyRNG9GhrLE7cGaJxt8HQzUY+8PWh0+iMwlvf1c7i4GVSLFfPMrldMcwDHiGgYG3BtHkESRDh4KAPCOegbm+bRNjGOI7TgTAuARLAy2wABaPALi6AhiFME5ykwcpcFedAETZTkEFWJdKHMVj9DoZ1Uh2P46kqBR72PNsFTPC9F1Sc8XDAPRyBAAAaEAFxYmhkFANZ3DwAQ1gQFSUCwiAMnkkBiiwMAUxgUQYxhKB2WQAIggU1c6HWAQsE5TBkF0Aw6AUgArGgwQAIVM8zRBwOBZlXOBPIsHyQBjUVUmQEBdhwAwjLcVcYAAdQyOJkAADgABgUtwIDobKsBcZKXWclIjMYA1vEYVyOWwDykC8uK6Gwbw7OyBTqhsywAEU9E6GLvLgBTVmKXLNHypAACYZqwcZV3ZSQkI6kA4KgaKFP9OA5BKXSurgABfC6gA)
```sh
--parser yaml
```

**Input:**
```yaml
framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    cache:
        # Put the unique name of your app here: the prefix seed
        # is used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The app cache caches to the filesystem by default.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

```

**Output:**
```yaml
framework:
  secret: "%env(APP_SECRET)%"
  #default_locale: en
  #csrf_protection: true
  #http_method_override: true

  # Enables session support. Note that the session will ONLY be started if you read or write from it.
  # Remove or comment this section to explicitly disable session support.
  session:
    handler_id: ~

  #esi: true
  #fragments: true
  php_errors:
    log: true

  cache:
    # Put the unique name of your app here: the prefix seed
    # is used to compute stable namespaces for cache keys.
    #prefix_seed: your_vendor_name/app_name
    # The app cache caches to the filesystem by default.
    # Other options include:
    # Redis
    #app: cache.adapter.redis
    #default_redis_provider: redis://localhost
    # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
    #app: cache.adapter.apcu

```
