### ISSUE TITLE
[YAML] comments at the end of a collection

### ISSUE THREAD

**Issue by ikatyang** [prettier/prettier#4853]
**Prettier pr-4742**
[Playground link](https://deploy-preview-4742--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBbAhgB0wSygcyQB0oACc0gRgCYBmEi0gYlMlVQRhIGc4BHAK4IwcYmQoBaKnQYUWbDrBIgANCAiYYOaN2Sh0AJwMQA7gAVDCXSnQA3CDgAmqkACMD6MAGs4MAMqYnnj4yDAGQmp4vAYwZh74GMgAZugANrxqAFbcAB4AQh7evn7oHAAyeHDJaRkggQbRyCAAnqWpLpgGeDAA6k4wABbIABwADGqdELw9HphNnXDRtlVqBvwCOGtx6Ano1elwaryoOKHhhyDcwalwAIoCEPD7tTDorn2Og8jUamHoOKlggBhCDsPYoKDQFYgAS8AAqb2sKQOAF8UUA)
```sh
--parser yaml
```

**Input:**
```yaml
mapping:
    123
    # comment
sequence:
    - 123
    # comment

```

**Output:**
```yaml
mapping: 123
# comment
sequence:
  - 123
# comment

```

**Expected behavior:**
```yaml
mapping: 123
  # comment
sequence:
  - 123
  # comment

```
