### ISSUE TITLE
LESS detached rulesets as arguments break pseudo-class selectors

### ISSUE THREAD

**Issue by alexking** [prettier/prettier#4866]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AtgSwB6agCgAEAnAVwBs4BnASgAJgAdKOuki6-GgbmYF9mzDDjz4mLOhgCeAWipxKYGBGJJyAQyowZYABaZyAEwbNWrAEbqwAawDmxCKSiGdEciqR1zGm7wkCoPh4QABoQCAAHGExoKmRQdWIHAHcABUSEOJR1ADcITENQkHNiK2s4GABlCKs8W2QYMjgwvHliGFTS23R1ZAAzdXJ5MIArKmwAIVKbCsr1dDgAGTw4fsHhkBriNuQQSio4sIjiPBgAdQKYXWQADgAGI4d5M9KI3ePqOGIc1bDiOAAjqRMP9Oupur0kAMhs0QPIsA0mmEqHVKABFUgQeBrGFhGDqcwXQxXZAAJjxpQMdQAwhB0D1dlBoL8QKR5AAVAlZaHyPh8IA)
```sh
--parser less
```

**Input:**
```less
.mixin(@rules) {
  @rules();
}

.mixin({
  .my-selector:last-child {
    background-color: black;
  }
});
```

**Output:**
```less
.mixin(@rules) {
  @rules();
}

.mixin({.my-selector: last-child {background-color: black;}});

```

**Expected behavior:**
```less
.mixin(@rules) {
  @rules();
}

.mixin({
  .my-selector:last-child {
    background-color: black;
  }
});
```

which would generate this CSS code when run through a [LESS parser](https://lesstester.com/)

```css
.my-selector:last-child {
  background-color: black;
}
```

**Details**
When using a [detached ruleset as a mixin argument](http://lesscss.org/features/#detached-rulesets-feature), prettier stops formatting the LESS and starts breaking pseudo-classes by adding a space before their colon, so `.test:last-child` becomes the invalid `.test: last-child`. I'm assuming this is just a side effect of it parsing it incorrectly.
