### ISSUE TITLE
YAML: Do not put values on a separate line from the key like in JSON

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#4913]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuECBuSA6UAEODmANhAEYCGhWueOAxDgIIAyAkgMICiA+hwLIMsm2GjgC0OAM5wwAVwBOcJDgDkLAJZgAygEcAXiV4BpOHACeATnwAPNdoAiAVQfmAjGgD0AdneGArACEATQAGAEUIQhgmYIA5AA0ACQAHAFsHAHVNdPwkpgApAAVDNUJ-ADZNNjiAMX8AajISEk0IADUXAHFQgCsWbvcy2GrTABMwBkNTOFbAmHMC3QcAJg6yJlC5MoK8gCUAZjrgjoAVFwdQ1rs4zRGAeRIRliXfY4ZQ9I3PFmO7CSTTAAWAGs4nVzIE9uYSKEHO4yGgwACoGhCGoChBAgVWr4ygB3GDuVqGCQyPK3NTHEjpPYuOI7Do7CRxfzpKAcFLVKxgQxlFhwIEcIHVKJA1ruJhMXmmXSBKApMjuOqBOJyEj+HZAuzHdwAFnchAYvkCJGxHRGpggWnMOrKpm0HECS38ADMIACSL5dFZPBw0K09iNNAw6mxgnsOIQljtTHEZNUGDs8i4li4olAHDtuoY5HYrKYAFqeNQsCBWXgucy1Y7dXx1BLxHUmliBQyeHZJXgpbQJAEQHWaIFlOwQtRAqCaQwOVpqVpAiD+ApsbqhXQAkYFOodUwMfB2FIrgG3CQJfMsUJsXFMMguAAcOs58hchA6LmCBvzJAYyN8OsIaDsUDuNUDi+O4VjdFYDhkBcCSGN8miENowQ3oE3QuLwIwxA4phMC4HAMGUKS4vgdRMDeuL5mQ-hgAkuguNo2hQVYTB2Ak3RsAwAYkAUVh2HIKQAuYmiBEk6Q7CwViEC4mjmEsHCtBIVg6q0SQJBwbRMFYN6eHYMhxL4UCEIYEDHDsTBxB0TC4kCugyBwLhsL4YASGwUBsD0mjSvgeSELoSwFDAtxxECA5AnAhBJDecTZDsMSGPm2jaSM3r5gUch1C5MimBIOoFDZ3RkHY0I3tO-jHEkSSTDeVjTIQEgcOqib+MpLBHGAngkME6bSYELAdHAZQAtohBlNo7TOkCvV1HUZT4IEQIyMcZCtMEty8AsSxoB41TpGodSaOS+x7McLCELiEY3nYZB7L4LC8J4uLuPgmhQMcCQ7AwrShIQMgyDqAC8yjCDQ9DMOw3AFAwmhZLcOx2MDeDiFIsgKEoyiaDeQI6roZCaO4MAcgkvihGQ+b5rctwuAUYCITq0VjmwSQcGQi1QFschQLmnhyNh+AMM6bAdGwaQjBIZTpEs3QMFY1RoHUMS+MMSwJNIKFgDsDgSDeLA6vmSQ7Lcmh1FA5hlBwizdNUeQm+YnhXksYC8MNMBsOYMjBLoaDVBwolqAkaBlLwpjC0suieDehByECQKGEwYBAmw6THGgQIdHkcTbDedRyCMZC6DeSwsLoYB7FAMRgP4chWCMZT5pWuI3txuhAgkEC42AeR5MEZAwIYbDOiwSSaN0ai8jEHDmOYbCBBInjBIYIxzXsxbhmgchxIEcA3qYmiumghgFJ4gQ3jsVhkAktzLCMvi4h1cBxg4vChIEMTOoECHmCMxw+nEoRxCMexujrAkBJOwtwyAxB1HsJY3Y9gdBkGoNgdQYAFHcMEDgYB0i8FxGUMgZBMFJDyIYfA+Y4ByGdAxJYpgCiQx2PgJgdRTBdUPDqfigZK4GTANUSm+AAQJDUPmBgo4XCGDsNoQwQIPxwkIK0EgHQYjaE8JcFsuJdDdCgP4BIi1bimBkKEQwMhfC+DEW5FM6QM4Al4JuCQKQYj+HOkCdITAmRsAkb9NgbAXDHCgAkY4zpjiBGOGUMoTABHmC0YZAEMBnQMFfr4fA7hlRsAgFYlIOwdiEF8PmfAaAbxlBZCMCAf1zChBSI2MI3RNAcBkBIdwuhnR2LkHIDguJbhZysHsOQ1RnQkEMNUHUIw5BJHDNUbQ+BQh7DsG2CQDAUitGOJIxx6R-AdAcP4cwHQJAxGOBAUwCQOgpHzCkCQahKpoAYC4cC-h+5AluOkG8TAIBMHMBwG8ah8C+BkJ4NYLgdQpF0BlbcKQmCGEWGQBwugCiJWOHkQICT-jBDyHTBgphCCUx1KETwHReAQGMN0O5SQHAv3MAtN4MgAQAjiGgeUvBfA7DUFYOacgYD+EPB0JYmgrw7B9oEFIvhszuCJa4MAUBuhLFaLwMggR-ApDkLitQIxu5QAKHeMA5piGA2wCAAANCACASQYBqGgBIZAoAyBNIgLiAo5qEAmpQPCCACqdUgBIHIfBYUYCaCSPgtQUB8DIBgHIGQcBdW+qkMytKZB8DymQM6CgUhdXdEUpXd1cBPVkBSHAUJUA4CxvjSGkA3q5DhuQCAUwGbCDOqSHIX1MBdojBgACZAN5gi6urRAKQ6Q3VJFLdWuA4a0C5t1QobQCCFCRujWQPNdUC1SBSGoANQbZ2+qIHAUIMgIDwGnQmkAMBGj1sbcgJYurA1kBKCu5JKQY0oCgNAIdIAalwCWiQO1caZ0AF931AA)
```sh
--parser yaml
```

**Input:**
```yaml
env:
  global:
    # ALICE_EMAIL
    - secure: 'IicSqzbMKeey9gxiqDUU91v/7/K5BY0QoltL0NXHpmUWSWgpLJPKilB6SCXFB+abbSoV1GQjIj/6ntFydcAKyeVYt9PzU2GaLQr6PJR3+0GT1UQVDXSdObdI25TAQWQr7ITDspyhkX+9Y39bQU/avchnvliPoYPV56wt/VKsuJOiTbW31XRGRsXBWnEmFxcK6IekEkFtLkV/LL6IyzYnma/+YXrbBRkDT/4/lA5YbV5GdyocS946yqEY2Bfohb5zx7EvV3dSA+C03El2RyXuFARJ121tLnURjKrDxyZ7iIoxM19FBTj5+HNX4bVIYK7RpMmqHho4Sk6DY3iknSKUViVkoBPCjQzhdP+GyAgDmQzhOsHZIQCwLa184Fxur1lG10lAZbAnv54lvDn/FU5/xjxUaQVHKITSlq08Yj1MdNUyL1EA6mwg+L8wZaBcHz1qqUaxLDHjCA3dbPxDrmh9SYpWRIxl1S92EVsx4VpHEoVLx87DuX5nlKoTRLXGLwkzuE1C5csCnCQjSyzgJlz2PtOXkSkkelp8XWgRNKZq87dx7ZPr+sCuys4PkzjaDbQ8ViBTppKy8xeVlsEBRRJB4VI0Gc7b0nU1SYIGe6hql6qV1fkYI++6gYkuTaV0OMPz2vv/FWi+SOiR33TIlwEl8Da35IM7w/gSnTHRAVQluu4='
    # ALICE_PASSWORD
    - secure: 'S8k4zaS/tmFH5QaZZOO1Pclq4XWknCpEauTn6PrnDx7rUygAfCGCmUds6W2jAxFv+N5Fy2Hec8YcRUs8I4ZpROS+n96EzUjFJn997La2cMqltC9u0zvFEpWiHv6MyCm2z78lrkkKLckCWTvkGJXPJ8+rdaz82Izc3nNcBrxd6Z9Fw8bPzkHoaScJJ0atKCfIpSji6INE99CYs70KdgY3iI3EvrXYe8ySfovKP7Y8RxaHOU2d5w7beuFUMQYNfYSl9dT7EXQXd3jLQsIxDOaN432qH3GuiC+tP/0EcWMw6aacWpJKgZerfqq2yPPARgL+y0nhO4rmdSBr5ncFO1ghHiZAik1KDqKkZb/alVbGNq7VDYKwzjnBHuTOyuQKu55DqnC21WXPhM+GsmNBwEkWLsXCKkuuCC1TnHTfTYT66LiZ9HunlhtfANf5g/YXCoM+mRRl5Zgv86BWdou49Qm4b0QjSEus/zfNBrrEwO8+x3rFfbKF4drp3EFqgQ3D7RsAmVTkZkWWBGUB9GsNToyHGmZmsipKvA1xjBCfkOW8LoL9E8ig5u7aL14mz+syAmLKzUaUzPq8TJYg/py0J4XAylO14Q7GMoKejOWpUYN9kuAQuhhXvmaM5RixgYrtBhOG2SLaREpYm5Kr/UY91cnj2VMaYBmroKid0anP84cdyKg='

```

**Output:**
```yaml
env:
  global:
    # ALICE_EMAIL
    - secure:
        "IicSqzbMKeey9gxiqDUU91v/7/K5BY0QoltL0NXHpmUWSWgpLJPKilB6SCXFB+abbSoV1GQjIj/6ntFydcAKyeVYt9PzU2GaLQr6PJR3+0GT1UQVDXSdObdI25TAQWQr7ITDspyhkX+9Y39bQU/avchnvliPoYPV56wt/VKsuJOiTbW31XRGRsXBWnEmFxcK6IekEkFtLkV/LL6IyzYnma/+YXrbBRkDT/4/lA5YbV5GdyocS946yqEY2Bfohb5zx7EvV3dSA+C03El2RyXuFARJ121tLnURjKrDxyZ7iIoxM19FBTj5+HNX4bVIYK7RpMmqHho4Sk6DY3iknSKUViVkoBPCjQzhdP+GyAgDmQzhOsHZIQCwLa184Fxur1lG10lAZbAnv54lvDn/FU5/xjxUaQVHKITSlq08Yj1MdNUyL1EA6mwg+L8wZaBcHz1qqUaxLDHjCA3dbPxDrmh9SYpWRIxl1S92EVsx4VpHEoVLx87DuX5nlKoTRLXGLwkzuE1C5csCnCQjSyzgJlz2PtOXkSkkelp8XWgRNKZq87dx7ZPr+sCuys4PkzjaDbQ8ViBTppKy8xeVlsEBRRJB4VI0Gc7b0nU1SYIGe6hql6qV1fkYI++6gYkuTaV0OMPz2vv/FWi+SOiR33TIlwEl8Da35IM7w/gSnTHRAVQluu4="
    # ALICE_PASSWORD
    - secure:
        "S8k4zaS/tmFH5QaZZOO1Pclq4XWknCpEauTn6PrnDx7rUygAfCGCmUds6W2jAxFv+N5Fy2Hec8YcRUs8I4ZpROS+n96EzUjFJn997La2cMqltC9u0zvFEpWiHv6MyCm2z78lrkkKLckCWTvkGJXPJ8+rdaz82Izc3nNcBrxd6Z9Fw8bPzkHoaScJJ0atKCfIpSji6INE99CYs70KdgY3iI3EvrXYe8ySfovKP7Y8RxaHOU2d5w7beuFUMQYNfYSl9dT7EXQXd3jLQsIxDOaN432qH3GuiC+tP/0EcWMw6aacWpJKgZerfqq2yPPARgL+y0nhO4rmdSBr5ncFO1ghHiZAik1KDqKkZb/alVbGNq7VDYKwzjnBHuTOyuQKu55DqnC21WXPhM+GsmNBwEkWLsXCKkuuCC1TnHTfTYT66LiZ9HunlhtfANf5g/YXCoM+mRRl5Zgv86BWdou49Qm4b0QjSEus/zfNBrrEwO8+x3rFfbKF4drp3EFqgQ3D7RsAmVTkZkWWBGUB9GsNToyHGmZmsipKvA1xjBCfkOW8LoL9E8ig5u7aL14mz+syAmLKzUaUzPq8TJYg/py0J4XAylO14Q7GMoKejOWpUYN9kuAQuhhXvmaM5RixgYrtBhOG2SLaREpYm5Kr/UY91cnj2VMaYBmroKid0anP84cdyKg="

```

**Expected behavior:**

Leave as is

----

Reference: https://github.com/wireapp/wire-web-packages/pull/903
