### ISSUE TITLE
YAML: preserve indentation of comments

### ISSUE THREAD

**Issue by maximbaz** [prettier/prettier#4917]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHAhgJwTJAdKAAkOjiUIEYDiBiQmAdwnICYQAaECVGAS2gDOyUFkwQGABSwIhKdADcIvACYcQAI0zowAazgwAyhjC8oAc2QxMAVzidTAuJhgStZgLbpkAM3QAbR04AKwEADwAhLV19A3R3OAAZUzgff0C0LEdMZBAATzi-NVRMUxgAdRUYAAtkAA4ABk5iiEcyrVQc4rgs+RTObABHa15sV3QPLyRfALsQR3deSxtZgVMzPzgARWsIeFSZzhh0dQrlauQWQ61ePzWAYQh3TxyoUjVrRwAVY9lpxwBff5AA)
```sh
--parser yaml
```

**Input:**
```yaml
parent:
  one: 1
  # two: 2
```

**Output:**
```yaml
parent:
  one: 1
# two: 2

```

**Expected behavior:**
```yaml
parent:
  one: 1
  # two: 2
```

Commenting "two" is not idempotent, I expect to add and remove `#` and get exactly the same code.

Works correctly when I comment "one" instead of "two".

**Comment by j-f1** [comment]
Also, if you don’t put the `1` after `one:`, the comment gets duplicated:

**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAHAhgJwTJAdKAAkOjiUIOIGJCYB3CcgJhABoQJUYBLaAZ2SgsmCHQAKWBAJToAbhG4ATNiABGmdGADWcGAGUMYblADmyGJgCucdsb5xMMMRpMBbdMgBm6ADb32AFZ8AB4AQhraunrornAAMsZwXr7+aFj2mMggAJ4xPiqomMYwAOpKMAAWyAAcAAzshRD2JRqoWYVwGbJJ7NgAjpbc2M7obh5I3n42IPau3OZW03zGJj5wAIqWEPDJU+ww6KplipXITPsa3D4rAMIQru5ZUKQqlvYAKofSk-YAvr9AA)
```sh
--parser yaml
```

**Input:**
```yaml
parent:
  one: 
  # two: 2
```

**Output:**
```yaml
parent:
  ? one
# two: 2
# two: 2

```
