### ISSUE TITLE
Error thrown when multiple anchors are used in YAML objects

### ISSUE THREAD

**Issue by blicksky** [prettier/prettier#4919]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhlMALCAnAZyQB0oACMgWjIDJMd8BGUiigazgE8kyA3dADYBXOCyq16uPACYxFTBBjY4eHgAc8ENaVIAzCBBLkyAI3SrT6AF5iAPLZ4AqSUzsOyzrFNnHSIADQgWjAAltAEyKDmmgDuAArmCBEo6LwQIQAmASAmeOhgHDAAymr5IVAA5sgweCKB5QQqMHF5FQC26Mi6go2BAFYEAB4AQnkFcMXobXAAMuVwXT1wgaWEKsggnFMC2RrlMADqmUrIABwADCuajQd5ahsacI14vAuBeHAAjkIhHy3o7U6SG6Al6IEabRC1Vqy3B5QqAjgAEUhIoFsCloEYOgTEcMickNIsXkQgJ4QBhCBtDobKDQN4gISNAAqOOSIMaAF9OUA)
```sh
--parser yaml
```

**Input:**
```yaml
.anchors:
  - &anchor1
    key: value
  - &anchor2
    another: prop

foo:
  bar: baz
  <<: *anchor1
  <<: *anchor2
  

```

**Output:**
```yaml
SyntaxError: Map keys must be unique; "<<" is repeated (8:3)
   6 | 
   7 | foo:
>  8 |   bar: baz
     |   ^^^^^^^
>  9 |   <<: *anchor1
     | ^^^^^^^^^^^^^^
> 10 |   <<: *anchor2
     | ^^^^^^^^^^^^^^
> 11 |   
     | ^^^^^^^^^^^^^^
> 12 | 
     | ^
```

**Expected behavior:**

"SyntaxError: Map keys must be unique; "<<" is repeated" should not be raised when extending an object with multiple anchors.

See https://blog.daemonl.com/2016/02/yaml.html#extend-
