### ISSUE TITLE
Spaces around slash in CSS font shorthand property when using the var function

### ISSUE THREAD

**Issue by jeddy3** [prettier/prettier#4930]
**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOld6Bm0MS6AbqgE4AUAtDTAJ4AOcNAzgJYBecAlAPQBGAHQBWdGzgUO+ANw4AviAA0ICExgdobZKEoUIAdwAKlBDpSpSEDgBMVIAEYVUYANZwYAZSauOUAHNkGAoAVzhVf0kKGGMXAIBbVGR8VAAbSVUAKzYADwAhF3dPL1QEuAAZfzgU9MyQXwpo5HA2HVUmaVgAdTsYAAtkAA4ABg6DSW6XJhbOuGjSGtUKOABHUI4VuNRE5KRUjIiQSQSOYLCjzkC0uABFUIh4WsPVGFRHXtsB5AAmV5cOGl-AEAMIQBJJFpQaBLEChSQAFXeFgOkgUCiAA)
```sh
--parser css
```

**Input:**
```css
a {
  font: var(--type-size)/1.5 serif;
}
```

**Output:**
```css
a {
  font: var(--type-size) / 1.5 serif;
}

```

**Expected behavior:**

Spaces aren't added around the slash e.g.:

```css
a {
  font: var(--type-size)/1.5 serif;
}
```

This is the current behaviour for the font shorthand property when a CSS variable isn't used e.g.

Input:
```css
a {
  font: 1rem/1.5 serif;
}
```

Output:
```css
a {
  font: 1rem/1.5 serif;
}

```
