### ISSUE TITLE
Pre-commit hook always fails

### ISSUE THREAD

**Issue by dongyuzheng** [prettier/prettier#4985]
**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: [pre-commit](https://pre-commit.com/)
- Operating System: Ubuntu 18.04.1 LTS

**Steps to reproduce:**
1. `.pre-commit-config.yaml` with contents

```yaml
  -
    repo: 'git://github.com/prettier/prettier'
    rev: 1.14.2
    hooks:
      -
        id: prettier
        files: '\.(css|less|scss|ts|tsx|graphql|gql|json|js|jsx|md)$'
```

2. Run `pre-commit run --all-files`

**Expected behavior:**

* No hook failure when no files are changed

**Actual behavior:**

* Hook failure when no files are changed

Tagging @asottile
