### ISSUE TITLE
Spurious `?` added for yaml example

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#5000]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbOMCGATTWkA6UABKcVJuksQOYBOcGcdAtAM4BuYLDAjgK5w2MImwAOcMISggANCAhiYAS2htkoTHToQA7gAUtCdSkwcIy7HJAAjOpjABrDAGUxD5VBrIYdQfM82Zhh9expUTGQAM0wAGyD5ACs2AA8AIXsnV0o4ABlPOGi4hJB3OiC6ZBAAT0pY6zE6TxgAdUsYAAtkAA4ABnlGiCCW+zEqxqFmDkL5Pn5lBlDMcMikGPi4eSDUZR8-TZA2TxpYuABFfgh4Io35LBs27E7kACY7+2VY44BhCFQIqpQaAzED8IIAFUwNhM6yCAF84UA)
```sh
--parser yaml
```

**Input:**
```yaml
metadata:
    name: greeter-svc-request
spec:
```

**Output:**
```yaml
metadata:
  name: greeter-svc-request
? spec
```

This was reported by @peterj https://github.com/prettier/prettier-vscode/issues/560
