### ISSUE TITLE
yaml files are removing lines like "---"

### ISSUE THREAD

**Issue by marcofranssen** [prettier/prettier#5029]
**Prettier 1.14.2**

Imagine yaml files like this.

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-head
  namespace: kube-system
  labels:
    k8s-app: elasticsearch
    role: admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        role: admin
    spec:
      containers:
      - name: es-head
        image: mobz/elasticsearch-head:5-alpine
        imagePullPolicy: Always
        resources:
          requests:
            memory: 100Mi
          limits:
            memory: 250Mi
        livenessProbe:
          tcpSocket:
            port: 9100
          initialDelaySeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 9100
          initialDelaySeconds: 60
          timeoutSeconds: 5
        ports:
        - containerPort: 9100
          name: transport
          protocol: TCP
```

It gets reformated like

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-head
  namespace: kube-system
  labels:
    k8s-app: elasticsearch
    role: admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        role: admin
    spec:
      containers:
        - name: es-head
          image: mobz/elasticsearch-head:5-alpine
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 250Mi
          livenessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 60
            timeoutSeconds: 5
          ports:
            - containerPort: 9100
              name: transport
              protocol: TCP
```

Expected would be to leave the `---` lines as it allows to pipe multiple files in bash. E.g.

`cat deployments/*.yml | kubectl -f -`

without the `---` this will not allow you to do this kind of stuff in bash. The `---` should also be supported halfway a file as it allows you to put multiple yaml documents in one file.

See below expected result (only diff is to keep `---`).

```yaml
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-head
  namespace: kube-system
  labels:
    k8s-app: elasticsearch
    role: admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: elasticsearch
        role: admin
    spec:
      containers:
        - name: es-head
          image: mobz/elasticsearch-head:5-alpine
          imagePullPolicy: Always
          resources:
            requests:
              memory: 100Mi
            limits:
              memory: 250Mi
          livenessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 60
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            tcpSocket:
              port: 9100
            initialDelaySeconds: 60
            timeoutSeconds: 5
          ports:
            - containerPort: 9100
              name: transport
              protocol: TCP
```

Is there a config setting for this I might missed?
