### ISSUE TITLE
YAML breaks dictionary keys to fix print width

### ISSUE THREAD

**Issue by dploeger** [prettier/prettier#5044]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAngfQCYEswxIA6UABOaUSACoAWuAzqY6QIalQQBOqrANqQDWcdFWJkKkiINbokpdHAYlJVOixbsAbnF179Bw0eMnjXdKT7QA5kJFiVkitNnzOJEABoQEAA4xcaAZkUFYuLggAdwAFMIRglFYtCFxsLxAAIy5WMGEYAGVfHNwoa2QYLgBXOG8ShjguGGjs615kADN+eu8AKwYADwAhbNy4AtZUOAAZErgOrpqQIq56rmQQdAm+dN8uEpgAdVSYWmQADgAGb12IeoPs33XdpQaddK44AEdK3A-m1larHmfG6IHqqFw5SqiwYJWsfDgAEVKhB4MDQTBWBkjtgTsgACzeCqsXB8OEAYQgqDaKE4UDm3kq9WoWISnRBcAAvpygA)
```sh
--parser yaml
--tab-width 4
```

**Input:**
```yaml
my_dict:
    "This is a normal key":
        okay: yes
    "This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long key":
        okay: no

```

**Output:**
```yaml
my_dict:
    "This is a normal key":
        okay: yes
    ? "This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long key"
    : okay: no

```

**Expected behavior:**
Prettier uses the [complex key format](http://yaml.org/spec/1.2/spec.html#id2760395) (see example 2.11 of the spec) with this. There are two issues with that: 
* Prettier doesn't actually cut down the string, which would actually be possible with complex keys
* Complex keys are defined in the spec, but not supported by most parsers

The Spec doesn't allow other methods of splitting keys as I understand it.

As this will produce unparseable code in most parsers, I'd vote for ignoring too long lines in keys and just splitting values.

**Comment by ikatyang** [comment]
> Prettier doesn't actually cut down the string, which would actually be possible with complex keys

What did you mean "cut down the string"?

> Complex keys are defined in the spec, but not supported by most parsers

As far as I can tell, the complex key (explicit key) was defined since (at least) [YAML 1.0 (2004)](http://yaml.org/spec/1.0/). Could you share the reference for "not supported by most parsers"? I checked 3 YAML parsers and all of them work ([1](https://github.com/eemeli/yaml), [2](http://nodeca.github.io/js-yaml/), [3](http://yaml-online-parser.appspot.com/)).

> The Spec doesn't allow other methods of splitting keys as I understand it.

I'm not sure what did you mean but the explicit key is required for block nodes, for example:

```yaml
? - 123
  - 456
: 123
```

**Comment by dploeger** [comment]
> What did you mean "cut down the string"?

That Prettier should cut the string at a fitting place and carry on in the next line to achieve the print width limit. Like this:

**Input:**
```
my_dict:
  "This is a veeeeeeeeeeeeeeeeeeeeeery long key as it seems":
    okay: yes
```

**Output:**
```
my_dict:
  ? |
    This is a veeeeeeeeeeeeeeeeeeeeeery 
    long key as it seems
  : okay: yes
```

> As far as I can tell, the complex key (explicit key) was defined since (at least) YAML 1.0 (2004). Could you share the reference for "not supported by most parsers"? I checked 3 YAML parsers and all of them work (1, 2, 3).

I tried these:

  * https://codebeautify.org/yaml-to-json-xml-csv
  * https://www.browserling.com/tools/yaml-to-json
  * http://convertjson.com/yaml-to-json.htm
  * https://jsonformatter.org/yaml-to-json

These are under the top 5 when searching for "yaml to json". I do believe, that standard parsers (like obviously the ruby parser) may support this, but I questioned that, because so many online parsers don't seem to support it.

> I'm not sure what did you mean but the explicit key is required for block nodes, for example:

The explicit key (or complex key as I read it in the spec) can be used for keys, that aren't just strings (which isn't supported in most languages anyway). In this specific example (very long keys) it can be used together with YAML multiline strings to cut down the string (like used in the example above)

**Comment by ikatyang** [comment]
The "cut string" thing only happens with `--prose-wrap always` (`preserve` by default).

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAngfQCYEswxIA6UABOaUSACoAWuAzqY6QIalQQBOqrANqQDWcdFWJkKkiINbokpdHAYlJVOixbsAbnF179Bw0eMnjXdKT7QA5kJFiVkitNnzOJEABoQEAA4xcaAZkUFYuLggAdwAFMIRglFYtCFxsLxAAIy5WMGEYAGVfHNwoa2QYLgBXOG8ShjguGGjs615kADN+eu8AKwYADwAhbNy4AtZUOAAZErgOrpqQIq56rmQQdAm+dN8uEpgAdVSYWmQADgAGb12IeoPs33X+SNlg7y44AEdK3A-m1larHmfG6IHqqFw5SqiwYJWsfDgAEVKhB4MDQTBWBkjtgTsgACzeCqsXB8OEAYQgqDaKE4UDm3kq9WoWISnRBcAAvpygA)
```sh
--parser yaml
--prose-wrap always
--tab-width 4
```

**Input:**
```yaml
my_dict:
    "This is a normal key":
        okay: yes
    "This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long key":
        okay: no

```

**Output:**
```yaml
my_dict:
    "This is a normal key":
        okay: yes
    ? "This is a veeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeery long
      key"
    : okay: no

```

The escape rule is different in `quoteValue` and `blockValue`, we shouldn't change their node `type`. (Actually, [there is no way to escape characters inside `blockValue`.](http://yaml.org/spec/1.2/spec.html#id2796010))

---

> These are under the top 5 when searching for "yaml to json". I do believe, that standard parsers (like obviously the ruby parser) may support this, but I questioned that, because so many online parsers don't seem to support it.

🤦‍♂️ I don't know what should we do.
