### ISSUE TITLE
Incorrect formatting of map-get() negation in Sass

### ISSUE THREAD

**Issue by barrymcgee** [prettier/prettier#5221]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA+pKAzASwHMA6AZzDLIB0oASAWwEMAnIgqMpDAClowxlmAG2HcAjCzgMANPwwM4AEwIBXBhJIBWKbPnDWRONwBMu2gEoA3LVrpskBgAdoCGOUo0oJOMOluMYHkAIyYwAGsiFghVKCUAWkhhCBZueIUmJ3ijGB5GQw4yGUERYWtaAF8QGRAIJxgCaDJkUFZogHcABVYEZpQmADcIAiVqkGCWMPC4GABlJzCOImQYFlU4GsK4FhhOyaJmZDwmYTINkAArMgAPACFJiJnZpkUAGQ44I5OzmoWWM5YyBAFCoYycLA4MAA6iMYAALZAADgADL9omcoZMnEDwXAAQNPjUpABHVQEKR7JgHJhfU7nM4MAgrNb0pZ+ACKqgg8FpPxAMCYwRhSnhyBMNVWTAIwiWAGEIAxDigoK4xqozgAVQV9Y50ioVIA)
```sh
--parser scss
```

**Input:**
```scss
$margins: (
  small: 1rem,
  medium: 1.5rem,
  large: 2rem
);

.element {
  background-color: - map-get($margins, small);
}
```

**Output:**
```scss
$margins: (
  small: 1rem,
  medium: 1.5rem,
  large: 2rem
);

.element {
  margin: -map-get($margins, small);
}

```

**Expected behavior:**

The above formatting produces invalid Sass. When a minus is placed before a map-get function, a space should be enforced. 

See https://www.sassmeister.com/gist/df355857c78c0fcb7ae2e26408814128 for reference.
