### ISSUE TITLE
why transform unit to lower case forcibly?

### ISSUE THREAD

**Issue by tarol** [prettier/prettier#5239]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--parser less
```

**Input:**
```less
p {
  font-size: 30PX;
}
```

**Output:**
```less
p {
  font-size: 30px;
}
```

**Expected behavior:**
```less
p {
  font-size: 30PX;
}
```

I trace the code, and find ```maybeToLowerCase``` in ```utils.js``` will transform unit to lower case forcibly.
Now I use prettier-stylelint to format the code, and here is my ```.stylelintrc```:
```json
{
  "extends": "stylelint-config-standard",
  "rules": {
    "string-quotes": "single",
    "unit-case": null
  }
}
``` 
I think ```unit-case``` should have higher priority than prettier's default behavior.
