### ISSUE TITLE
[CSS] bug when handling var(foo)

### ISSUE THREAD

**Issue by wangxd18** [prettier/prettier#5407]
```css
.a/root {
  transition: height var(transition-time)s;
}
```
transformed to
```css
.a/root {
  transition: height var(transition-time) s;
}
```
which added an extra space after `var(transition-time)`.
