### ISSUE TITLE
unexpected SCSS formatting on string concat

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#5517]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AhgAmAHSpzAEgDNoYBaYgSwBs4lNTZyp0BbOAbjwMKrkpUAHgxwgA-AGJ+1IWO75MPTAHMIEACajFvJhWp1MAaiVo4EGGONF+goQoIAjdFqU7MAVwBONABQkyQUMTMVRzSxBrPgFZAEoHTGdXZQIxSWAA5gM4AF8wiysTaLsFHJAAGhAIAAcYKmgAZ2RQdC8vCAB3AAVWhCaUdAA3CCoNCpBHL3QwAGs4GABlaumqKBVkGC8POEqACxg2GgB1Xap4BuWwOAW+s6pBs4BPZHAGpsrVhrgvGC6plTY6GQxHQNC+lQAVg0hAAhKazeYLdhwAAyqzgwNB4JAUKEC1WKjoAEUPBYMUgQWCdiBll4vl4Xg0wG9xtUvKsYEdRjBdsgABwABkqbIgXyOU2qLzZcHpgwxlS8cAAjh4qIq-ugAUCKVjqV82FQNls9QTiaT4JiqZUYOhHFyNDzkAAma1TWgEgDCEDYgJeUGg8pAHi+ABVbf1KV8cjkgA)

**Input:**
```scss
.a {
  $font-file: font-name;
  $ie-fix: "?#iefix";
  
  good: 
    $font-file + ".eot" + $ie-fix;
  bad: 
    url($font-file + ".eot" + $ie-fix);
  bad: 
    "#{$font-file}.eot" + $ie-fix;
}
```

**Output:**
```scss
.a {
  $font-file: font-name;
  $ie-fix: "?#iefix";

  good: $font-file + ".eot" + $ie-fix;
  bad: url($font-file+".eot"+$ie-fix);
  bad: "#{$font-file}.eot"+$ie-fix;
}

```

**Expected behavior:**

```scss
.a {
  $font-file: font-name;
  $ie-fix: "?#iefix";

  good: $font-file + ".eot" + $ie-fix;
  bad: url($font-file + ".eot" + $ie-fix);
  bad: "#{$font-file}.eot" + $ie-fix;
}
```

should be space around plus sign

https://www.sassmeister.com/gist/5ea50bd3e3a5cc482a52f00a04f9a6f7
