### ISSUE TITLE
`prettier.getFileInfo` doesn’t take `overrides` into account when determining `inferredParser`

### ISSUE THREAD

**Issue by jeanfredrik** [prettier/prettier#5566]
I posted this issue in prettier-atom: https://github.com/prettier/prettier-atom/issues/460

”Format on save” isn’t working for files added via overrides in prettierrc like this:

```yml
overrides:
  - files: ['*.module', '*.theme']
    options:
      parser: php
```

According to @robwise this is an issue with Prettier itself (https://github.com/prettier/prettier-atom/issues/460#issuecomment-442170789) in that `prettier.getFileInfo` doesn’t take `overrides` into account when determining `inferredParser`.

**Environments:**
- Prettier Version: 1.15.2
- Running Prettier via: prettier-atom plugin (0.56.0) for Atom (1.32.2)
- Operating System: macOS
