### ISSUE TITLE
Refactor the testing infrastructure

### ISSUE THREAD

**Issue by j-f1** [prettier/prettier#5569]
I’m proposing a refactor of the `tests/` directory:

1. Create a module called `@prettier/run-spec` (or something, feel free to bikeshed 🚲🏠). It will spawn multiple workers to do the tests in parallel, while maintaining a cached `require()` of Prettier on each thread.
1. Move the test directory to each language directory.
1. Refactor individual test directories to this format:
   ```yml
   foo:
   - bar.js
   - baz.js
   - options.yml # see below
   - snapshot.md # see below
   ```

`options.yml` specifies the options for a directory (and its subdirectories). It takes one of two formats:
```yml
# 1. An object
parsers: [babylon, flow, typescript]
semi: false
# 2. an array
- parsers: [babylon, flow, typescript]
  semi: false
- parsers: [babylon, flow, typescript]
  semi: true
```

`snapshot.md` looks like this:

> # Options
> ```yml
> parsers:
>   - babylon
>   - flow
>   - typescript
> ```
> 
> # `bar.js`
> 
> ## Input
> 
> ```js
> bar()
> ```
> 
> ## Output
> 
> ```js
> bar();
> ```

---

What do you think about this style?
