### ISSUE TITLE
SCSS single-line comments are formatted incorrectly

### ISSUE THREAD

**Issue by d0x** [prettier/prettier#5603]
**Important Note:**
Prettier has nice support for Grid-Template-Areas . See [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6A5gJwJYBMAEwAOlPvlngLTwC2ADgDYCG8lTmcTAzkiWWURAALTrjiYyIpmIn4pMwX36CueOACN2+SLAQxt0eLEWllIAGYQI8WZeviydm4IDcJAL4gANCAh0Y2NBcyKDsmBAA7gAK7AjBKEwAbhB43iDqmExgANZwMADKdFnYUOjIMJgArnA+QjA0DADqQtjwXEVgcPlxrdiJrQCeyOBcwT4lXOIwUZnoNEzI5kwMkz4AVlwAHgBCmTl5+Uw0cAAyJXCLy6sgG5v5JegMcACKlfaXKzUgRZiTmMNcMCjNJ0HCwRp4GBCZAADgADD5QRBJo1MnRhqC4H9EhcfBwAI6VbAcGZMOYLJBLT4+SY0bDlKpfVSlJ6vd6Uq5fGBMdQQ3BQ5AAFh8FSY2AYDwAwhAaPNhlBoLiQJVJgAVHnxKnXbgwD7XXAQMB6r4QSowOhmgBMxvc7iAA )

The example shows only how to reproduce the issue with single-line comments!

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAKgCwJYDOGhGAygMKmkB0GACgE5wwx5wMYC2EAbnETBxwMAQyYiMBAA5wweAGZ4wI1tAwBXKRgBGcfFAAmGQcPQZInTghgAdKNQDmDPEeB2MHzx6cuAtPE4pABsVOF8xOBECJAx0dy8EmxAhEQN2DBS0jkz2JNjUeITPJIIXOG0xc2h4WCrYazy4qCKvJPkICHgOds70nq6kgG53AF8QABoQCClVKAJkUDEGCAB3Ogi55BARHggXCZBtBhEwAGtmUikTvCgHZBgGdThJnBhOIIB1fHhpE7hSBClVg8PAwACeWzABHmkxuBHYMEYIgcnBEyHkIiC8MmACsCAAPABCxzOFxEVgAMjc4OjMdiQHj8aQbg4gnAAIrqXq0rHPEBXBjwhhbAhQmH85ywD4uQTIAAcAAZJlJlvCPscpFsVfx2HwDkwAI7qPBMJEotFIDG8ybwzh4e6PPmlW5szncy10vkwETaaUGWVIABMkweIjwQRZ5AglgtICg0Bpk3U8KwPvmHt5IxGQA)
```sh
--parser scss
```

**Input:**
```scss
// This is SCSS. Prettier moves the area specification up behind the // comment
.grid {
        grid-template-areas: //
          "header header header" //
          "sidebar content content" //
          "footer footer footer";
 }
```

**Output:**
```scss
// This is SCSS. Prettier moves the area specification up behind the // comment
.grid {
  grid-template-areas: // "header header header"//
    "sidebar content content"//
    "footer footer footer";
}
```

**Expected behavior:**
```scss
// This is SCSS. Prettier moves the area specification up behind the // comment
.grid {
  grid-template-areas: // 
    "header header header" //
    "sidebar content content" //
    "footer footer footer";
}
```

There are related (closed) Issues for older Versions:
- https://github.com/prettier/prettier/issues/4311
- https://github.com/prettier/prettier/issues/4594
