### ISSUE TITLE
SCSS removing space when it shouldn't

### ISSUE THREAD

**Issue by jerelmiller** [prettier/prettier#5636]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ATnAzgVwDYwC0ksAhgJZRzoAEwAOlDTQAKVh44AmcNM6pKFnIxy0ABQBbSoQAWccgHNZMGuIAkAazFZNhAGakehUZLgB6AEwBKGnFJY4hGRBwxrAbkYBfEABoQCAAHUWgsZFBSdHQIAHcABSiEcJRSADcIci5-EAAjATBNOBgAZSDSMEpFZH4cOACVSTwAdVkRbHKwOBLkkXI0kQBPZHAscIDKR3QYeIFFSVJkQzxHAIArLAAPACECotLSMwAZSjgl0hX6kA3Nkqq8OABFHAh4c8uA8vQpkawwMZyQXQlBgzSyMFkyAAHAAGT4xRzNARBEZA7DUNJnAKYACOOHImFmpHmiyQy1WIEc0hq6DqAWEUEUD2erzOZIuFJgpFyYK4EOQlgC-AoeCqAGEIJIFiMoNAsSAcI4ACrclLkuDebxAA)
```sh
--parser scss
```

**Input:**
```scss
.result-container {
  @include transition(min-height ($spacer/2) ease-in-out);
}
```

**Output:**
```scss
.result-container {
  @include transition(min-height($spacer/2) ease-in-out);
}

```

**Expected behavior:**

That space between `min-height` and the math should be left alone. With the space removed, this unfortunately results in some invalid CSS as its now treated as a CSS function instead of the property name. This results in something similar to the the following CSS when compiled by Sass

```css
// Incorrect
.result-container {
  transition: min-height(50px) ease-in-out;
}
```

**Comment by pspi** [comment]
I found a similar case:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZgVymGBLaAAgBM8BnGACgEpDgAdKQw1AJzhk1aYEYAGAA4APANyMAvo0akAbnUbMAtgENWAczxQkhALQlyVamKiSoIADQgIA-NDLJQq1hADuABVUJ7KZTIh5iCxAAI1ZlMABrDgBlAXDNNWQYVkw4SwALGEUAGwB1dLx4MjiwOGivQrwZQoBPZHAye0tNMjhWGDcwtRVkdGVs1ssAKzIhACEwyJjlRTgAGU04Xv7BkBGhaITsuABFTAh4ZYG0kDjWVtZ6sjBGoIFWTRhcgJh05AAOPkt7iFbcsIE9XucAuMiWlgAjvt4J1rN4QMoyDooHA4MQ0UF2FC8OxOspusojqtWoo8EkUicyFtdtClkg+sdLDBlMFnsRXsgAExMsJ4bIJADCEEUPRQUGg4JAmFaABUWd4GasZKkAJJQdGwaJgB42ACC6uiMBq2yJcHE4iAA)
```sh
--parser scss
```

**Input:**
```scss
@function dist() {
  @return 10px;
}

div {
  margin: - dist();
}

```

**Output:**
```scss
@function dist() {
  @return 10px;
}

div {
  margin: -dist();
}

```

**Expected behavior:**
The space in `- dist()` should be preserved. Removing the space causes Sass, in turn, to generate invalid CSS. (SCSS `margin: -dist();` generates incorrect CSS: `margin: -dist();` instead of correct `margin: -10px;`.)
