### ISSUE TITLE
Prettier cannot format CSS multiple lines property with comment

### ISSUE THREAD

**Issue by CompileYouth** [prettier/prettier#5719]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6MAbAhgZxwWiiwFs4ACYAHSjLJgCcsocBLGF6JM62ymAdxYATGAAsyABlQBmHGTi44AGh60youCwDmomJJlyFOZar4B6M2QAqolnLtksZSMVKxVtAGYsM8elNkceAAHHAAKAFYleSghAEoAbmoAXxAlEAhg9mgcZFAsenoIfgAFAoRclCwANwhhNJAAI0YwAGs4GABlYKwwFigtZAYAV2UQXWIMAHVbeBwesDhOirYWarYAT2RwPAb+43oYEsYtYixkTywMY3SAKxwADwAhFvaukjgAGX64C6ubkD3B6dfpaDBwACKwwg8D+1zGPXoB224N26WC9H6MCmwjEyAAHBJ0UVjFNGMFthi4Adqr90vQ4ABHYYsBnHLCnc5IS7w9LGYgsIb0UZ80HgqEw37c-5jGBYRo4kSiZAAFnSDCwPlBAGEIK4uSAoNA6SBhsYrPLKjzjMlkkA)

**Input:**
```less
.class-name {
    transition: 
  	width 0.3s ease,
        height 0.3s ease,
  	// This is a comment
        filter0.3ssteps(5, end);
}
```

**Output:**
```less
.class-name {
    transition: width 0.3s ease, height 0.3s ease,
        // This is a comment
            filter0.3ssteps(5, end);
}
```

When I execute `prettier -l \"src/**/*.{js,jsx,ts,tsx,css,less}`，Prettier will report a format error about the formatted code above.

**Comment by lydell** [comment]
Hi! Do you mean that `prettier -l` reports a file as being unformatted even after running `prettier --write`? If so, I tried to reproduce this both in the playground and using the CLI, but couldn't.

```
$ cat test.less
.class-name {
    transition: 
  	width 0.3s ease,
        height 0.3s ease,
  	// This is a comment
        filter0.3ssteps(5, end);
}

$ prettier --version
1.15.3

$ prettier --write test.less
test.less 79ms

$ cat test.less
.class-name {
  transition: width 0.3s ease, height 0.3s ease,
    // This is a comment
      filter0.3ssteps(5, end);
}

$ prettier -l test.less

```

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6MAbAhgZxwWiiwFs4ACYAHSjLJgCcsocBLGF6JM62ymAdxYATGAAsyABlQBmHGTi44AGh60youCwDmomJJlyFOZar4B6M2QAqolnLtksZSMVKxVtAGYsM8elNkceAAHHAAKAFYleSghAEoAbmoAXxAlEAhg9mgcZFAsenoIfgAFAoRclCwANwhhNJAAI0YwAGs4GABlYKwwFigtZAYAV2UQXWIMAHVbeBwesDhOirYWarYAT2RwPAb+43oYEsYtYixkTywMY3SAKxwADwAhFvaukjgAGX64C6ubkD3B6dfpaDBwACKwwg8D+1zGPXoB224N26WC9H6MCmwjEyAAHBJ0UVjFNGMFthi4Adqr90vQ4ABHYYsBnHLCnc5IS7w9LGYgsIb0UZ80HgqEw37c-5jGBYRo4kSiZAAFnSDCwPlBAGEIK4uSAoNA6SBhsYrPLKjzjMlkkA)
```sh
--parser less
--tab-width 4
```

**Input:**
```less
.class-name {
  transition: 
  	width 0.3s ease,
    height 0.3s ease,
  	// This is a comment
    filter0.3ssteps(5, end);
}
```

**Output:**
```less
.class-name {
    transition: width 0.3s ease, height 0.3s ease,
        // This is a comment
            filter0.3ssteps(5, end);
}

```

What am I missing?
