### ISSUE TITLE
Format YAML line length

### ISSUE THREAD

**Issue by pauldraper** [prettier/prettier#5730]
Great YAML stuff.

As a feature, prettier should be able to fit YAML to a max line length, using as few lines as possible, just like it does for other languages.

For example,

```yaml
api:
  command:
    - yarn
    - run
    - serve
```

should become

```yaml
api:
  command: [yarn, run, serve]
```

or vice-versa depending on length settings.

**Comment by pauldraper** [comment]
Okay, it appears that Prettier _does_ reformat prose to match the line length, but doesn't change sequence or object styles to match.

IMO: parenthesized sequences (`[]`) and objects (`{}`) should be used wherever if is possible to fit one one line. In all other places use the multi-line non-parenthesized forms.

**Comment by fisker** [comment]
I don't think we should do this, it changes the AST, and even in the example

```yaml
api:
  command:
    - yarn
    - run
    - serve
```

Shouldn't it be

```yaml
api: {command: [yarn, run, serve]}
```

?
