### ISSUE TITLE
[SCSS] Prettier removes empty lines after multi-line function call

### ISSUE THREAD

**Issue by srmagura** [prettier/prettier#5773]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATAlgNwHQGcYBO6ADnLgATAA6U5d5ARgIZgDWA5gRAK5SpLkCcUkxjoo7ALQAbcXCYFJnJhgQwAFDXrbyAFgCsqOOwA0WnXUJMouYgrVnaFxtO5xyARgAMxAB7m6AEoAbhoAXxoaDExKAPJIaQgCASFUUKg4gDNoGElcdAAvOAEAJiEAW3S44linCwSkgQZXOCq6nWzYPMLi8i9sfQr07QioUZoGCFQAT1rtBuTyYm4CYmlWuPosnO6igQ8h8nCaEBMQCGIxaFxkUAUuAHcABXsbZBAmTAh0VFOQBgILFYcBgAGU7GBxOxkIQ3GcABYwcrSADq8PQ8FsLDgoIQ+TEmAx03eYFwNzO4lwcAIMCegPY5SYyEyTGkVLOACtcL4AEKAtgg0FMcpwAAycmZrPZIC5vlBUPWAEVuBB4JK2XAznYCFSCO9cKTySBiFwqSjAcR3iayNTMHA-kIAI7cdBCOlMBlMpAsjVnKnldDq6X5CRKlVqpCwzUgKzoWQSADCEHKjPeUGg9rO3CpABUmAwbt6pdGYPmUT8YPDkLotURYOXUJXkABOLxhMJAA)
```sh
--parser scss
--print-width 90
--no-semi
--single-quote
--tab-width 4
```

**Input:**
```scss
div.stripes {
    background: repeating-linear-gradient(
        45deg,
        transparent,
        blue 10px
    );
}

div {
    color: red;

    font-size: 2rem;

    p {
        color: blue;

        font-size: 0.5rem;
    }
}

body {
    color: purple;
       
    font-size: 1rem; 
}

```

**Output from playground (CORRECT):**
```scss
div.stripes {
    background: repeating-linear-gradient(45deg, transparent, blue 10px);
}

div {
    color: red;

    font-size: 2rem;

    p {
        color: blue;

        font-size: 0.5rem;
    }
}

body {
    color: purple;

    font-size: 1rem;
}

```

**Output when running prettier from command line on my PC:**
After the call to repeating-linear-gradient, all empty lines are removed. I expect them to be preserved.

I am using Prettier 1.15.3 on Windows 10. Prettier options are the same as above.

```css
﻿div.stripes {
    background: repeating-linear-gradient(45deg, transparent, blue 10px);
}
div {
    color: red;
    font-size: 2rem;
    p {
        color: blue;
        font-size: 0.5rem;
    }
}
body {
    color: purple;
    font-size: 1rem;
}
```

**Observations:** 
* The issue does not affect CSS. I changed my SASS file's extenstion to .css and prettier preserved the empty lines as expected.
* The call to repeating-linear-gradient seems to be the problem. If I delete it that style rule, the empty lines are preserved.
* If I put all of the arguments to repeating-linear-gradient on the same line, the empty lines are preserved.
