### ISSUE TITLE
Ansible-flavored YAML double curly brace spacing issue

### ISSUE THREAD

**Issue by jonbackhaus** [prettier/prettier#5894]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
insertPragma: false
tabWidth: 2
semi: false
singleQuote: true
bracketSpacing: true
proseWrap: 'always'

overrides:
  - files: ['*.md', '*.yml']
    options:
      insertPragma: true
  - files: '*.md'
    options:
      tabWidth: 4
```

**Input:**
```yaml
# @format
---
# As mentioned by IBM if you set password,uid,gid,group_name
# If you provide at least user,password and group_name DB2 setup will create those users
# TODO: Use the new block feature since `when` clause is equal on all tasks

- name: Creating DB2 Fenced Groups
  group:
    name: '{{item.fenced_group_name}}'
    gid: '{{ item.gid | default(omit) }}'
    state: present
  with_items: '{{ db2_instances }}'
```

**Output:**
```yaml
# @format
---
# As mentioned by IBM if you set password,uid,gid,group_name
# If you provide at least user,password and group_name DB2 setup will create those users
# TODO: Use the new block feature since `when` clause is equal on all tasks

- name: Creating DB2 Fenced Groups
  group:
    name: '{{item.fenced_group_name}}'
    gid: '{{ item.gid | default(omit) }}'
    state: present
  with_items: '{{ db2_instances }}'
```

**Expected behavior:**
`name: '{{item.fenced_group_name}}'` should reformat to include a single space between the inner curly braces: `name: '{{ item.fenced_group_name }}'`. If the single quotes are removed, Prettier adds the space between __both__ sets of braces (which isn't desired) and the single quote is required to denote a variable in Ansible. The Ansible linter flags this formatting with a "Warning." Please consider modifying the bracketSpacing behavior or otherwise making provisions for Ansible-flavored YAML formatting. Thank you!!!
