### ISSUE TITLE
Config for CSS selectors to multi-line

### ISSUE THREAD

**Issue by SYNTAG** [prettier/prettier#5937]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEALAjAGgASoEw6oDMhALIQKyEBs2wAOlNtgLYCGATgOYCWUS2AAwBuRgF9GjAHSRYbPnA6ZpAIwCuMGNGVQpqOGwAmfLjqmG4AZzAceABxg9odSTGOW7AGzYBPAQDNPOAAPYWZxEEwQCAcnKEtkUE4OCAB3AAVOBASUNgA3CB5DSJAVDjYwAGs4GABlOwqTZBgONTgo1BgWTwB1VB54Dwq4WuyBnjyBn2RwSwSovktFGHTyrnZkfzZPJaiAK0tggCFyqprathY4ABkFTe3dkAPg2pMggEU1CHh7nfaQBocJYcGbWOYlOy2WA9IowVDIAAcgiikIgSx65TsM0hVkUeTgJQ4cAAjmoeETVmx1mxfo8liweM1Wv9LG84J9vgSkFs-lEYGwVDDDHDkAQQC15J4TABhCAsDYoKDQAlRNRLAAqApyPMebEsMFp-0MEDAhqiEA0dg0eENYjEQA)

Currently, Prettier forces all CSS Selectors to be on their own line. This is a nice feature but takes too much vertical height for selectors with an initial short horizontal width. This creates unnecessarily long files for a selector that was simple to begin with.

I propose that we add a simple config that I believe will cover every CSS developer's use case, such as: `{ styleSelectorWidth : 40} ` (default: 0 = All CSS selectors on a new line). This would behave similarly to eslint's' `max-len` rule and Prettier's rationale behind `--print-width`.

Related: [#5086](https://github.com/prettier/prettier/issues/5086), [#3464](https://github.com/prettier/prettier/issues/3464)

**Input:**
```css
h1, h2, h3, h4, h5, h6 {
  margin: 0;
}

.container, .button, .heading, .description {
  display: flex;  
}
```

**Output:**
```css
h1,
h2,
h3,
h4,
h5,
h6 {
  margin: 0;
}

.container,
.button,
.heading,
.description {
  display: flex;
}
```

**Expected behavior:**
```css
h1, h2, h3, h4, h5, h6 {
  margin: 0;
}

.container,
.button,
.heading,
.description {
  display: flex; 
}
```
