### ISSUE TITLE
scss with comment result in parse errors after prettier runs several times

### ISSUE THREAD

**Issue by plehnen** [prettier/prettier#5967]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAgDNoYBaQgQzDgAoASY2cirAGwE8AafOgZwDcA5uRKlMAE24NMrOAAcKMABZSA7nEyClMJPigQATugqspvGO1m79RkwEp8wADoF8qRmUrVHL-H6KilGzsugyBLDLsANy+-h6k5pZwoYmyMa5+8eqa2qHZWjDp-vi8BmC6AK4GrDQA5ADEwNKyCsoAvgB0cBAwtXZF-qXl+FU1DU2EMvKKSp3dMAD89Zhwk9h9AbYwdXDoAEZw4uKHpBByCBbnfdwA9Df4JvAGUIqY-HD4BvKsVB-KmLx8Kw8B9VJhlLohrpWBAwCY6k4nAAmABsAGYAILXfB3TYlNhwdheD68diwCjYWJ+UZ1RrNabtDqqCCEQgbYhbOrM1nXKkjaq0iZTVqzDowGBshwc4zbWowAwVOCXOC8jL8sZ0yYtGadASCep0vUiJgSNrswwyup6voDNouNogTggM4wTDQXjIUAUAwGCCqAAK3oQHpQFH4EAkjpAewMVAA1kqAMoKMB4QTIeWKp3adCsADqSnBcF4KbgieD4Le4PYyHAvA9TrwvDgBhg-tjgmMyEorGbToAVrxsAAhWNgBMwRMsOAAGRB3ZMfZAg+wibTsgAihUenAF724E6FAZmwZa7wwPWo3IDHgYHmJMpkABGFEABkPvubedjclr1+LLbvFGXwAI4VJgXzthQnYUHuS7NlgGYKgeIC8OucBbjucEoTAFB7Pe4iPkgSJOvKFAyGmADCEDoF2KD6FAu5OhUzYACp4SGPbNm0bRAA)
```sh
--parser scss
--print-width 160
```

**Input:**
```scss
@mixin font-face($font-family, $svg-font-id, $filepath, $weight: normal, $style: normal) {
  @font-face {
    font-family: $font-family;
    font-style: $style;
    font-weight: $weight;
    src: url('#{$filepath}.eot');
    src: url('#{$filepath}.eot?#iefix') format('embedded-opentype'), // alternative replace this line with: src: local('\263A'), // for smileyface syntax
    url('#{$filepath}.woff') format('woff'),
    url('#{$filepath}.ttf') format('truetype'),
    url('#{$filepath}.svg##{$svg-font-id}') format('svg');
  }
}
```

**Output:**
```scss
@mixin font-face($font-family, $svg-font-id, $filepath, $weight: normal, $style: normal) {
  @font-face {
    font-family: $font-family;
    font-style: $style;
    font-weight: $weight;
    src: url("#{$filepath}.eot");
    src: url("#{$filepath}.eot?#iefix") format("embedded-opentype"),
      // alternative replace this line with: src: local('\263A'), // for smileyface syntaxurl("#{$filepath}.woff") format("woff"),
      url("#{$filepath}.ttf") format("truetype"), url("#{$filepath}.svg##{$svg-font-id}") format("svg");
  }
}

```

... if you copy the output to the input and repeat, it ends up **totally broken** like this:

**Final output:**
```scss
@mixin font-face($font-family, $svg-font-id, $filepath, $weight: normal, $style: normal) {
  @font-face {
    font-family: $font-family;
    font-style: $style;
    font-weight: $weight;
    src: url('#{$filepath}.eot');
    src: url('#{$filepath}.eot?#iefix') format('embedded-opentype'),
      // alternative replace this line with: src: local('\263A'), // for smileyface syntaxurl('#{$filepath}.woff') format('woff'),url('#{$filepath}.ttf') format('truetype'),url('#{$filepath}.svg##{$svg-font-id}')format(
          'svg'
        );
  }
}
```

**Expected behavior:**
It should be able to handle the above syntax without modifying the code each time prettier runs ending up with a totally broken code.

**Comment by evilebottnawi** [comment]
Workaround move comment above:
```scss
@mixin font-face($font-family, $svg-font-id, $filepath, $weight: normal, $style: normal) {
  @font-face {
    font-family: $font-family;
    font-style: $style;
    font-weight: $weight;
    src: url('#{$filepath}.eot');
    // alternative replace this line with: src: local('\263A'), // for smileyface syntax
    src: url('#{$filepath}.eot?#iefix') format('embedded-opentype'),
    url('#{$filepath}.woff') format('woff'),
    url('#{$filepath}.ttf') format('truetype'),
    url('#{$filepath}.svg##{$svg-font-id}') format('svg');
  }
}
```
