### ISSUE TITLE
When box-shadow has multiple values (separated by comma) it'd be prettier to put each value on a separate line

### ISSUE THREAD

**Issue by erusev** [prettier/prettier#6024]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCAPAtAZwBYCGAJhAO5IA6UABNQAwAOG1AjE-RwMQBmvANFVqNmAJnZ0ucKQG4qIPiAgMYAS2g5koAgCdtZAAo6EGlAQBuEFUXlptBMAGs4MAMoN7KqAHNkMbQFc4BTwYAFsAGwB1PBV4HHcwOBdjWJUzWIBPZHAcDQVPHDhtGH07L1CCZG4CcMKFACscDAAhO0dnFwJQuAAZTzgqmrqQRowXTy9wuABFfwh4QdqgkHdtQu1ssFybBm1PGEirGDxkAA46BV2IQsi7BmzduHWzAYVtOABHfxV30oJyypIapLBSFUIqXwBZY4CZTWbzAZAobLGAEVCHIjHZAiBR+AgqcITADCEFCFWyUGgrxA-kKABU0SZgYUAL4soA)
```sh
--parser css
```

**Input:**
```css
box-shadow:
  0px 1px 0 0 #fff,
  0px 2px 0 0 #eee;
```

**Output:**
```css
box-shadow: 0px 1px 0 0 #fff, 0px 2px 0 0 #eee;

```

**Expected behavior:**
```css
box-shadow:
  0px 1px 0 0 #fff,
  0px 2px 0 0 #eee;
```

When each value is on a separate line, the whole value feels significantly easier to read.

**Comment by IlanVivanco** [comment]
I would love something like this!

**Comment by ricealexander** [comment]
I agree with this. `box-shadow` with multiple values looks better with each value on a separate line.

How about other properties like `background`, `background-image`, `text-shadow`, `@font-face#src`?

**background-image** (from [Lea Verou Patterns](http://projects.verou.me/css3patterns/#checkerboard))
```
background-image:
  linear-gradient(45deg, black 25%, transparent 25%, transparent 75%, black 75%, black),
  linear-gradient(45deg, black 25%, transparent 25%, transparent 75%, black 75%, black);
```

**text-shadow** (from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow))
```
text-shadow:
  1px 1px 2px red,
  0 0 1em blue,
  0 0 0.2em blue;
```

**font-face** (from [MDN docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face))
```
@font-face {
  font-family: "Open Sans";
  src:
    url("/fonts/OpenSans-Regular-webfont.woff2") format("woff2"),
    url("/fonts/OpenSans-Regular-webfont.woff") format("woff");
}
```

I would argue that these all look prettier with separate lines when they are separated with commas, particularly when there are more than 2 values.

I think such a rule will need some consideration for which CSS properties are enhanced by splitting across lines and which ones are not. `font-family` for example, looks worse when split:

**font-family**
```
font-family:
  'Helvetica Neue',
  Helvetica,
  system-ui,
  sans-serif;
```

**Comment by y0nd0** [comment]
Could we implement this please as soon as possible. I think after so many years, it's time to improve this ugly style behavior. It's one of the worst behavior in Prettier.

**Comment by y0nd0** [comment]
Could we implement this please as soon as possible. I think it's time to improve this ugly style behavior. It's one of the worst behavior in Prettier.

I prefer always multiline when multiple values. 

**Bad**

```css
box-shadow: 0 0 10px black, 0 0 0 1px black;
```

**Good**

```css
box-shadow: 
  0 0 10px black, 
  0 0 0 1px black;
```

![just-do-it](https://user-images.githubusercontent.com/68586847/110715776-29f0e580-8206-11eb-90ab-217ea91bc795.gif)

**Comment by Airkro** [comment]
And variables:

```scss
$shadow:
  0 0 0 1px #5b9dd9,
  0 0 2px 1px rgba(30, 140, 190, 0.8);
```

From: https://github.com/stylelint-scss/stylelint-scss/blob/HEAD/src/rules/dollar-variable-colon-newline-after/README.md

**Comment by sciyoshi** [comment]
I have a proof-of-concept PR that implements this here: https://github.com/prettier/prettier/pull/13260. It hard-codes specific properties to always wrap if they have more than one value. (Notably, I skipped font-family since as another commenter pointed out it doesn't look great wrapped.)

**Comment by sciyoshi** [comment]
Note that since it looks at the property, it won't apply to SASS variables.

**Comment by sciyoshi** [comment]
It seems like this might need some more discussion as to the preferred behavior - I've narrowed down the two primary decisions that would need to be made.

### Always wrap lists

We can choose to always use the new wrapping behavior for lists with two or more elements, or only do it if the line would wrap anyways.

**Always wrapping lists:**

```css
.selector {
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.2);
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.2),
    0 1px 2px 0 rgba(0, 0, 0, 0.2);
}
```

**Only use new wrapping if line needs to wrap:**

```css
.selector {
  box-shadow: 0 0 0 1px rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.2);
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.2),
    0 1px 2px 0 rgba(0, 0, 0, 0.2);
}
```

### Only wrap certain properties

Orthogonal from the above, we can choose to apply this new wrapping behavior only for certain properties (like `box-shadow`, `background-image`, etc) while keeping the existing behavior for others (notably, `font-family`, but also `transition-property`). This makes sense if those properties often have many short elements, but makes the behavior inconsistent and possibly unexpected.

**Only apply new wrapping to certain properties:**

```css
.selector {
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.2),
    0 1px 2px 0 rgba(0, 0, 0, 0.2);
  font-family: -apple-system, BlinkMacSystemFont,
    avenir next, avenir, segoe ui, helvetica neue, helvetica,
    Cantarell, Ubuntu, roboto, noto, arial, sans-serif;
  transition-property: opacity, color, transform, box-shadow,
    margin, padding;
}
```

**Apply new wrapping behavior to every property:**

```css
.selector {
  box-shadow:
    0 0 0 1px rgba(0, 0, 0, 0.1),
    0 1px 2px 0 rgba(0, 0, 0, 0.2),
    0 1px 2px 0 rgba(0, 0, 0, 0.2);
  font-family:
    -apple-system,
    BlinkMacSystemFont,
    avenir next,
    avenir,
    segoe ui,
    helvetica neue,
    helvetica,
    Cantarell,
    Ubuntu,
    roboto,
    noto,
    arial,
    sans-serif;
  transition-property:
    opacity,
    color,
    transform,
    box-shadow,
    margin,
    padding;
}
```
