### ISSUE TITLE
Markdown: `--prose-wrap never` is giving extra line-break when using >- for multiline frontmatter 

### ISSUE THREAD

**Issue by sanscheese** [prettier/prettier#6031]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdWBLGAbOJAAgHIAVOAZxmygHMiBGAJgGYSsBDAVxgAsIAJ2IArbAFsARhCwxOdSkixEiqIpQji4y1UTl1ZcTpTiDGxAD6odAZTmCa9IpyKS8EBtkpE6gozENjU2ZiAD5rKBU7TgdaBhc3DyIvHz9OANgqeDMlSN14aksIlRKiABkhbAAvKoJkgAdKatq4IgATCDxmuvqIGGdxbtaiHTUCmCKdUorBIYammrqOrsXW3v7OQdXRvSzJvOnK1fm55bn1gaGdHfH90pUZuexG087zvsvtzOpg3JUxvZEcJTEqPY7PBYtdpvY4XTZzEZ5AGFIHFe5gqEQ14rKFwrYtG6A4EHUFHTEvY5nWEfeFfQko4n3cpkupYykw3E0-EELDoCJYACqTSc4WSkQAZoJoDBxOlsslvGAeMKGHAAB4wQQuSj1ThgOAgAA0IAg9Ro0EoyFAMSlAHcAAoxBCWlCcABuEGwbSNIEkWrAAGs4DAbLqwHFkJruHBjXwZXgAOp8XBUMNwGzO3DYN24ACeyBA2DoUCEBuNtBMDntWrosuQ4s4eBMxpElDVACF-UGQ5s4GVaAakA2mzGQK21TY4gQAIrcPqD4fNkC6wSVguywQBjq2qA++qzWAJr38ZAADgADMb9xATAmtfUC1A4G7TD6-ABHbjYPzV+R1oeNkuJiDJGgjRsaKoznO8D1oBo5yJIR5tCeSDMMamqcNgXT0AAwpo-4gCWT4+twJhkJwkguoucAAL40UAA)
```sh
--parser markdown
--prose-wrap never
```

**Input:**
```markdown
---
title: 'Testing 123'
author: jimbo
tags:
  - some
  - tag
teaser1: |-
  Starting a blog is great
teaser2: >-
  Starting a blog is great
tester1:
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle  
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
tester2:
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle  
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
---

Using >- in frontmatter is causing extra space
```

**Output:**
```markdown
---
title: "Testing 123"
author: jimbo
tags:
  - some
  - tag
teaser1: |-
  Starting a blog is great
teaser2: >-
  Starting a blog is great

tester1:
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
tester2:
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle  

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
      

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
---

Using >- in frontmatter is causing extra space

```

**Expected behavior:**
```markdown
---
title: "Testing 123"
author: jimbo
tags:
  - some
  - tag
teaser1: |-
  Starting a blog is great
teaser2: >-
  Starting a blog is great
tester1:
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
tester2:
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle  
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
      
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
---

Using >- in frontmatter is causing extra space

```

**Comment by j-f1** [comment]
Also reproduces with the plain YAML parser:

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCWMA2ckAIDkAKnAM7pQDmuAjAEwDM+AOlAIYCuMAFhAE54ArNAFsARhBYxWFEkha5cAWlwkIwuPKW4pFSXFYk4vangA+izQGUpvclVa5RmCFTQlcFXvph6DR2ngAfBZQCtastmiUuA5OLrhuHl6sPrCk8MZyoVrwZGYhCoW4ADJ8aABe5dgJAA4kFVVwuAAmEJgN1TUQMDHCHU24msq5MPmaRaW8-bX1ldWt7XNNXT2sfUtD2ulj2RNlSzPTC9Mrvf2amyM7RQqT02h1R20n3WcbaWT+WQrD27jB40KdwOD1mjRazwOpzW00G2V+eX+BRuwPBoKei3B0PWjUufwBuyB+zRjwOxyhrxh7zxiIJNxKxOq6LJkKxlJx2BAABoQBAauhoCRkKAIrwIAB3AAKEQQQpQrAAbhA0M1uSBRLxWGAANZwGCWGpaqIUZAwXjsOA8rgwYSYADqXAwpENYDglllGDQCowAE9kCA0BQoHw4GqooZbJLNRRhKxkAAzViYQw8gQkAAeACFNTq9ZY1nBilFQ0hE8nLSA0+nLMbsABFdjdEtllMgQ28CP+n1rTBqmpTWB2lXcZAADgADDz+xBDHbNTV-VA4AqjGqvABHdhoLxR6SxhNJ1uGPqm80V+qUeuN+AH8s8qSiIfNEdIWj3zVodqUADCan3KGDJc1XYQxCFYUQ5RbOAAF9oKAA)
```sh
--html-whitespace-sensitivity ignore
--parser yaml
--prose-wrap never
```

**Input:**
```yaml
title: 'Testing 123'
author: jimbo
tags:
  - some
  - tag
teaser1: |-
  Starting a blog is great
teaser2: >-
  Starting a blog is great
tester1:
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle  
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
tester2:
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle  
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
```

**Output:**
```yaml
title: "Testing 123"
author: jimbo
tags:
  - some
  - tag
teaser1: |-
  Starting a blog is great
teaser2: >-
  Starting a blog is great

tester1:
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: |-
      Lorizzle ipsizzle dolizzle pot amizzle
tester2:
  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle  

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle
      

  - test: >-
      Lorizzle ipsizzle dolizzle pot amizzle

```
