### ISSUE TITLE
Yaml indentation duplicated at nested sequences

### ISSUE THREAD

**Issue by mc-zone** [prettier/prettier#6043]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBadAdKBDAjErAAkNUICMlCAmI4wsS2uwgE0pqmeLndtIDMCnOgPyEALExKF+VSpOFYQAGhAQADjACW0AM7JQ2AE5GIAdwAKxhPpTYAbhC0sVIMkexgA1nBgBldU8tKABzZBgjAFc4VQALGABbABsAdViteF1AsDg-GwytewyAT2RwXX1VYN04IxgLDxCE7GR+bCSa1QArXQAPACEPb18-bAS4ABlguFb2zpAe3r9gkKS4AEVIiHhZjpiQQKMaozLisaTXdSNgmBTnGFjkAA4ABlUriBqUj3Uyq7hjvYZqojHAAI6RLSghrYJotJBtPaqGoJLThKL7XQrNabbYzBFzfYwbBkO4sB7IKiqCLYLRJFYAYQgCWaZSg0GBIEiNQAKiTbIiagBfIVAA)
```sh
--parser yaml
```

**Input:**
```yaml
---
a1:
  - b: 2
    c: 
      d: 2
      e: 2
  - f:
    - f1: 4
    - f2: 4
  

```

**Output:**
```yaml
---
a1:
  - b: 2
    c:
      d: 2
      e: 2
  - f:
      - f1: 4
      - f2: 4

```

**Expected behavior:**
Indentation of `f1`, `f2` should be the same as the input.

**Comment by evilebottnawi** [comment]
Thanks for the issue, PR welcome

**Comment by Rikilele** [comment]
Hi, thanks @mc-zone and @evilebottnawi for looking into the issue.
I encountered the same problem, but actually thought of a counter argument for the expected style.

Take the following example:
```yaml
- a:
  - b
  c:
    - d
```

When given the example yaml,`b` and `c` give an impression as though if they are on the same nested level, when in fact `b` is on a nest level one below `c` The JSON translation shows this more clearly:

```json
[
  {
    "a": [
      "b"
    ],
    "c": [
      "d"
    ]
  }
]
```

In order to show the nest levels crystal clear in yaml notation, the example should be "prettiered" to:

```yaml
- a:
    - b
  c:
    - d
```

And for consistency, all nested sequences should have duplicate indentations.

What do we think?
