### ISSUE TITLE
Prettier is incorrectly formatting PostCSS file with variable substitution syntax

### ISSUE THREAD

**Issue by rdsedmundo** [prettier/prettier#6051]
Prettier is adding spaces between the number value and the unit, and it's making its way like that through the final code, breaking the CSS.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtnAJgSwIYAEAFOngB4C0A7jljABZIEAsAHAAwAOZAlAcAB0oBAHQAjLBThk86TgBs4AZwB8AbTDy8SpQD0AvAPAR5FIwF0C-IVati8YANYBzAE4QArlElKcALzgmABIiGjp6Hm4CEPo4HGd6GEiyAG4bWzCGJjA8eTAiIMz6AgB6AgAmZLThW1j4xOCiOoSk7mqrAF8hDpAAGhAIThgcaCVkUDxXdyoABUmEMZQ8ADcIWj6QMVcHRzgYAGVOBxwoZ2QYVw84fsT0eQB1ehx4JSOwOH2F55xl54BPZDgHQbE5KOCuGAzbbOUjIABmuTB-QAVkoyAAhbZOPb7WRwAAyJzg8MR1xAqLI+xOzkUAEUPBB4CT5EiQEdXGDXICwMD+pxXCcYPdaAxkBw+e4wfdtpxAfzlODlsT+q44ABHDw4VVQvAwvDM1lg9A4c6XMm+U50hlMpAIllkmB4MTC8LIcr9C54HDyakAYQg6FhKCg0GVIA8YIAKk7FnawR0OkA)
```sh
--parser css
```

**Input:**
```css
@media (max-width: 480px) {
 .bd-examples>[class^="col-"]  {
    background-size: $(width)px $(height)px;
    width: calc($width / 2)px;
    height: $(height)px;
  }
}
```

**Output:**
```css
@media (max-width: 480px) {
  .bd-examples > [class^="col-"] {
    background-size: $(width) px $(height) px;
    width: calc($width / 2) px;
    height: $(height) px;
  }
}

```
