### ISSUE TITLE
Less: unary negation is incorrectly changed to binary subtraction

### ISSUE THREAD

**Issue by folz** [prettier/prettier#6082]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAhgJwOYEspIAEADIQAIDOADumPtgLSpwAmuArqiYQwBSU06URgA8RAGyzY4hANTlqtek1YdUASgDcIADQgIVGLmgVkoLJggB3AApYEplOgBuEXC10gARploBrOBgAZUF6ZBhMdjg9AAsYVHEAdRjceEUwOCCHVNxnVIBPZHAKUz18CjhMGBtfbAxkADN0cQq9ACsKEQAhXzAA4PRmABl8OEbm1pAOkSD6cTgARXYIeHGW6JAaTArMIvmSzypMfBhE9xgY5AAOYj0jiArE3yoio7gd5zG9AEdl+BqDI4QOgKAwoHBWKxPJg4L9cDCaug6ug1pMKqhcOFIhsKHNFn8xkgmus9DB0F4ziwLsgAEyk3y4cT0ADCEFQ9RQUGgXxA7AqABVyY5iRUAL6ioA)
```sh
--parser less
```

**Input:**
```less
margin: 0 @spacing-medium 0 -(@spacing-xxlarge + @spacing-medium);
```

**Output:**
```less
margin: 0 @spacing-medium 0 - (@spacing-xxlarge + @spacing-medium);

```

**Expected behavior:**

Prettier should not add a space after the `-` sign, as it changes the compiled meaning from

```css
margin: 0 8px 0 -28px;
```

to the shorthand declaration

```css
margin: 0 8px -28px;
```

**Comment by evilebottnawi** [comment]
Thanks for issue

**Comment by remisture** [comment]
Do you guys have a fix or workaround for this?

**Comment by lydell** [comment]
@remisture You can use `// prettier-ignore` comments as a workaround.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgJzjGASzhwFpCBzKCPAHSgFsBDHCwqJDABgwAEBnLEzDsKpBnAAmhAK4NuGUgAoBQkVDEAPTQBsWFOBgDUfQcNHipshgEoA3CAA0ICFiLR+yUCxwQA7gAKLAieKEwAbhCEkk4gAEY4wgDW+ADKaqLIMDgycM4AFjAMOgDq+YTwZmBwqSEVhOEVAJ7I4Pyezuz8JDABiRTMyABmTDrdzgBW-JoAQolgKTCpTBIAMuxww6PjIFOaqaI6cACKMhDwW2N5IEI43TitR+2xuOwwJdEw+cgAHFzOuAg3RKiSwrVwcHu4U2zgAjmd4H1XKEQEx+KQoHApFJYnh4YQ8H0mAMmJcdt0GIQsjlrvxDicEZskCMrs4YEw4h9JF9kAAmNmJQg6UQAYQgDEGKGomNiMm6ABUOaEWd0AL6qoA)
```sh
--parser less
```

**Input:**
```less
// prettier-ignore
margin: 0 @spacing-medium 0 -(@spacing-xxlarge + @spacing-medium);
```

**Output:**
```less
// prettier-ignore
margin: 0 @spacing-medium 0 -(@spacing-xxlarge + @spacing-medium);

```

**Comment by remisture** [comment]
Thank you, that worked :) Any idea if anyone is working on a fix?

**Comment by lydell** [comment]
Nobody seems to be working on a fix.

**Comment by Hotell** [comment]
having same issue here. just to add more example (issue is present on non calculated values as well)

**Input:**
```less
@sidebarMainPaneTopOffset: 2px;
@sidebarMainPaneHorizontalOffset: 10px;

.container {
  margin: -(@sidebarMainPaneTopOffset) -(@sidebarMainPaneHorizontalOffset) 32px;
}
```

**Output:**
```less
.container {
  margin: -(@sidebarMainPaneTopOffset) - (@sidebarMainPaneHorizontalOffset) 32px;
}
```

**HOT FIX**
remove those parens, if you can

```less
.container {
  // input
  margin: -@sidebarMainPaneTopOffset -@sidebarMainPaneHorizontalOffset 32px;
 // output
  margin: -@sidebarMainPaneTopOffset -@sidebarMainPaneHorizontalOffset 32px;
}
```
