### ISSUE TITLE
case of URI in background-image should be respected.

### ISSUE THREAD

**Issue by ulivz** [prettier/prettier#6281]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAIwEMwBrAcwCcIBXKAEwFoBLAW1KriW3poAbABQALGDAAOAZyQB6OVQDuqUoLaTSATwjEAVnDAxpqSBzkcmUOTQ7SA+gHY4jgAxNic0umNzOVOQBBACoAZgBJAA4IAGUATQA2QIBpACUAWUCs7JzAgCEKQNSARShA4oBKAG4CAF8QABoQCEkYNmhpZFBSGjolAAUehE6UUgA3CDYmRpBiGnIKOBgYzTA2KCpkGBp6OCbxDkEAdVE2eGlVuBjhs7Yxs61kcGlOpvXpOBoYfvmqLmR0GoPk09NIAB55eaUJYxUgcOAAGXWcABQL2IFBYJi6yogjgxXoEHgqMEwJAmhoHxoT0kEGkMDALxmkho6xgRymMFEyEiriaLLpcCO80kNJocCpYxRTQAjoT4D8WiMQKRpCwoHA4EwtTNxXK2OKftx-khAaT0R8OGwtjsLTi8QSiSjTWimjBSMQOUwucgAExu+ZsdQbADCEA4JpAUGg0pA9A+ABUPSMzWTVTASWSmBAwJn0QwpPQYL687VakA)
```sh
# Options (if any):
None
```

**Input:**
```css
.foo {
  background-image: url(https://foo/A*3I8oSY6AKRMAAAAAAAAAAABkARQnAQ);
}
```

**Output:**
```css
.foo {
  background-image: url(https://foo/A*3i8osy6akrmaaaaaaaaaaabkarqnaq);
}
```

**Expected behavior:**

Prettier shouldn't change the case of url.

**Other informations**

I found https://github.com/prettier/prettier/issues/2835 and https://github.com/prettier/prettier/issues/4644, but they didn't involve this case.
