### ISSUE TITLE
Specify "the default value" under overrides

### ISSUE THREAD

**Issue by jablko** [prettier/prettier#6357]
I wish it were possible to specify "the default value" (whatever that may be) under `overrides`. For example, the following complains:
```YAML
singleQuote: true
overrides:
  - files: "*.sol"
    options:
      singleQuote:
```
```
[error] Invalid singleQuote value. Expected true or false, but received null.
```
Could we permit the value `null` for any configuration option, or offer some other way to specify "the default value"?

**Comment by lydell** [comment]
Could you elaborate on how this is useful, please?

**Comment by jablko** [comment]
Well, currently I can specify configuration options for specific files only:
```YAML
overrides:
  - files: "*.sol"
    options:
      singleQuote: true
```
What I want is the opposite: To specify configuration options for all files except specific ones.

Maybe it's not an important enough feature, or `null` overrides isn't the right way to go about it ...

**Comment by lydell** [comment]
What's wrong with this?

```yaml
singleQuote: true
overrides:
  - files: "*.sol"
    options:
      singleQuote: false
```
