### ISSUE TITLE
CSS internet explorer repeat syntax: Invalid whitespace added between brackets

### ISSUE THREAD

**Issue by questionmarcus** [prettier/prettier#6375]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6SsCGBLKcBOABMADpSGEAm2AzgA4A2mAnkoQOb7aUDcZF1ek1aEAtAFsaoztz7kOXSqPjjGmeKMgMAruKg02+OHTjqAFAFYANIQCMAM3wBKORQlSZSrbv1szD5wBtCwBdOQBfECsQCDoYbGgaZFBMfHwIAHcABVSEJJRMADcIbiiQACN8TDAAazgYAGU6atx2ZBh8bThogAsYcQYAdR7seHpquAa80exC0eZkcBok6NwaAhgsqvZxTGR7TAZ16IArGgAPACEq2vqGzHE4ABlcOH3D45Az84bWhjgAIraCDwd5HbogZr4db4RZgZZlOhcWCDbgwHrIAAcAAZokiIOtBlU6IskXAYYU3tEAI7A+BbWL5ECYKR4OCUdllIy07BGLaYHZ7JAHcHRdbibDtToQmh-QF0t7Cj4QmCYcqoyjo5AAJmiHRwDFaAGEIOJdosoNAqSBtOsACpq-Ii9bhcJAA)
```sh
--parser css
```

**Input:**
```css
.container {
  display: grid;
  display: -ms-grid;
  grid-template-columns: repeat(5, 1fr);
  -ms-grid-columns: (1fr)[5];
}
```

**Output:**
```css
.container {
  display: grid;
  display: -ms-grid;
  grid-template-columns: repeat(5, 1fr);
  -ms-grid-columns: (1fr) [5];
}

```

**Expected behavior:**
```css
.container {
  display: grid;
  display: -ms-grid;
  grid-template-columns: repeat(5, 1fr);
  -ms-grid-columns: (1fr)[5];
}
```
