### ISSUE TITLE
Prettier can't parse css transition property when it's too long

### ISSUE THREAD

**Issue by chris-fran** [prettier/prettier#6437]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAMgH1SAjAQwCdcCiiYaqoBnASxg+iW3QA2cAB7YADKgDMbbHCps4AWg5RFEAK4xxqAIxsANNgC2tAOYrFQ9FonTZ8pRY03dB7BAAOVMFwCe2vXsFZVVnALYAbgZsAF8CGJB9EE9uaDZkUFoaCAB3AAVaBHSUKgA3CA4AE0SQChYwAGs4GABlLx8oU2RmdTgkgAsYIwEAdX6uODZ2uBairg5Sv2RwNnSklQUaGDyWUxNkdCoBBSSAKzZhACF6ptaqIzgAGRU4A6OTkHPhFpVTIQBFdQQeBvY59EBeGibZZsMCrGoebIKEYsDzLRGTOA0UqvJIARyB8B2nmKIHkiigcDglWpNRocAJHHpOyoeyooI+CiMHG6NF6SU4nQBhNeSB64JgVAoIyqMH6yAATElmFQOAJfgBhCBGfYoKDQXEgdQKAAqUuKhzBSURKhgMsqcuQOjEYhiMSAA)
```sh
--parser scss
--print-width 100
--single-quote
```

**Input:**
```scss
.foo {
  &__bar {
    transition: flex 0.3s ease-in-out 0.1s, margin-left 0.3s ease-in-out 0.1s, opacity 0.1s ease-in-out 0.1s;
  }
}
```

**Output:**
```scss
.foo {
  &__bar {
    transition: flex 0.3s ease-in-out 0.1s, margin-left 0.3s ease-in-out 0.1s,
      opacity 0.1s ease-in-out 0.1s;
  }
}
```

**Expected behavior:**

Maybe something like this?

```scss
.foo {
  &__bar {
    transition: flex 0.3s ease-in-out 0.1s, 
      margin-left 0.3s ease-in-out 0.1s,
      opacity 0.1s ease-in-out 0.1s;
  }
}
```
