### ISSUE TITLE
[YAML]: unexpected indent in nested list

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#6457]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbAhlA5gV3VuJAAiggBM4B9AKwGcAdKR0im24gWg9RgaajDowAC0KMiRDkQCe6AE78JUsgEs5cMDAhyVcduImSiAOhGYCqCFkYgANCAgAHGCui1koeXIgB3AAryCO4o6ABuECpkdiAARnJCANZwMADKjkIq2Mgwcjhw9sIwALaoAOrCKvC06WBwKUGVKqGV0sjgtO72mbRwcjB+8VhF6MgAZuioPfZ0AB4AQvFgSanoRXAAMplwYxNTILMpmViocACKOBDwO5P5IOlyPXJtsiXRjjqwpZEwwsgAHAAGezvCA9UrxRxtd56Xqhbb2ACOF3gAycwRA6FoHCgcDgFCi9nUSLUcAG+GG1z2PSKKmyuVutCOJ3Ol22SHGN3sMHQMS+ZB+yAATFz4ipUEcAMIQIoUlCkHHRHA9AAqPOCHJ6AF9NUA)

**Input:**
```yml
language: node_js

node_js: --lts

cache:
  - yarn
  - directories:
    - .changelog
```

**Output:**
```yml
language: node_js

node_js: --lts

cache:
  - yarn
  - directories:
      - .changelog
```

**Expected behavior:**
```yml
language: node_js

node_js: --lts

cache:
  - yarn
  - directories:
    - .changelog
```
