### ISSUE TITLE
CSS grid columns not aligned

### ISSUE THREAD

**Issue by dtinth** [prettier/prettier#6477]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgEIEMDOcAJptJgBYwwAO+SqqA7swHSMDMLEATgOaoAVAEqow+fAFpe3AJZEJARlQBiOAA9cAW2oAbOBPYB2duwBsAJnYAzTOlQAdKC3VbdcTMEeZM0uRPjaOrjwSJgA2uRwuERw3P4Q1AC6mPYguN6Y6d64qRneEVExcQBGEFQQmoleeTW1GWGauDJQ8UkpIMUZnd7FuQpW3OGNzRKl5ZXVdVPT3qiZAK4wEJj9g7iLEADcjgC+IAA0IAkwMtD4yKC43NwQjAAKVwjnKLgAbhByBx3cuGAA1nAYABlai-Zq8ZAwbjzOCHSiaHQAdXIMng+FBYDgQKeqJkr1RAE9kOBxF9moRuDA7j9eI1kFZcDpCIcAFb4NTYH7-QFArRwAAyzTg9MZzJAbLUQPBegAivMysKkAymbCQKDuBTiWJzodqLJYIi5DByMgABwABl1N0IiJ+1GJergFNewsOAEd5fBqQlnmlJFA4MRiF9uHAPTJQ9TcLTcCKVYdCJoZJDoar8NK4HKFXGxTBcMVDURjchzIcoU0dOCAMIVOkoKDQV0geaEAT557Kwg7HZAA)
```sh
--parser css
```

**Input:**
```css
/* Based on https://www.w3.org/TR/css-grid-1/#example-3733623f */
.example {
  grid-template: [header-top] "a   a   a"     [header-bottom]
                   [main-top] "b   b   b" 1fr [main-bottom]
                            / auto 1fr auto;
}
```

**Output:**
```css
/* Based on https://www.w3.org/TR/css-grid-1/#example-3733623f */
.example {
  grid-template:
    [header-top] "a   a   a" [header-bottom]
    [main-top] "b   b   b" 1fr [main-bottom]
    / auto 1fr auto;
}
```

Columns are no longer aligned, and Prettier collapses the whitespaces making it impossible for me to align the grids without CSS comment hacks.

**Workaround:** 
```css
.example {
  grid-template:
    [header-top] /**/ "a   a   a" [header-bottom]
    [main-top] /****/ "b   b   b" 1fr [main-bottom]
    / /*************/ auto 1fr auto;
}
```

**Expected behavior:**
When [`grid`](https://www.w3.org/TR/css-grid-1/#grid-shorthand) or [`grid-template`](https://www.w3.org/TR/css-grid-1/#explicit-grid-shorthand) is in this form

> [ [&lt;line-names&gt;](https://www.w3.org/TR/css-grid-1/#typedef-line-names)[?](https://www.w3.org/TR/css3-values/#mult-opt) [&lt;string&gt;](https://www.w3.org/TR/css3-values/#string-value) [&lt;track-size&gt;](https://www.w3.org/TR/css-grid-1/#typedef-track-size)[?](https://www.w3.org/TR/css3-values/#mult-opt) [&lt;line-names&gt;](https://www.w3.org/TR/css-grid-1/#typedef-line-names)[?](https://www.w3.org/TR/css3-values/#mult-opt) ][+](https://www.w3.org/TR/css3-values/#mult-one-plus) [ / [&lt;explicit-track-list&gt;](https://www.w3.org/TR/css-grid-1/#typedef-explicit-track-list) ][?](https://www.w3.org/TR/css3-values/#mult-opt)

Prettier should align the grid columns on each row, similar to how Markdown tables are handled. One possible expected formatting:

```css
/* Based on https://www.w3.org/TR/css-grid-1/#example-3733623f */
.example {
  grid-template:
    [header-top] "a    a   a"     [header-bottom]
    [main-top]   "b    b   b" 1fr [main-bottom]
    /             auto 1fr auto;
}
```

The same principle should apply to [`grid-template-areas`](https://www.w3.org/TR/css-grid-1/#grid-template-areas-property) alignment:

**Input:**
```css
.example {
  grid-template-areas: "head head" "nav main" "foot .."
}
```

**Expected output:**
```css
.example {
  grid-template-areas:
    "head head"
    "nav  main"
    "foot ...."
}
```
