### ISSUE TITLE
line breaking or space after commas in css url()

### ISSUE THREAD

**Issue by judbd** [prettier/prettier#6482]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHShx1QEMwBrAcwCcIBXKDAWgEsBbUquJQ44+jQA2ACgAWMGAAcAzkgD08uAA9S7KULgA6SO3kyI7OPICO9VvAA0Q6FUuChlgO4Wxl3ZxlaAVlKoBKAG4ceQAqIVYKOBwwG3oMVihSGlwOLjgZUPlCAF9CQnRsHC0XGDEASU5uPD4Scmo6RhY07l4ifgcRfBAJaTlFFTUNbV19Q2MzCzhrW3thZ1d3Q08fP26gkNCy1hkcaGinCBoKTOyoHJBLEAgpGFZoGWRQZLonAAVkhEeUUgA3CFYGEuaBo9TgMAAylJyIkqMgYDR6NMejB2EIAOpiKYyaFgOAQr4WVi-CxYZDgGSPK6JGRwGgwN6gqicZAAM1IQlpV28MmUACFQZRwRC1HAADKJOBsjlckA85QQ2GaACK9Ag8GlnOR0JotJo5LAlOBUhoiRg6MBZWQAA4AAxXE0QWno0FSckmjJ035Sq5mdVwRk3b4gUgyZhQOBwDBR4E0OCTOOMrgspDsrVXWnsVjwxHImRKuCq-2a2UwUioC0YK1IABMVwRpFYESgVAAwstSOSoPtgfRaQAVcvfNO0nI5IA)
```sh
--parser css
```

**Input:**
```css
body {
  background-image:
    url(https://example.com/some/quite,long,url,with,commas.jpg); /*like cloudinary images*/
}

body .withImage {
  background-image:
    url("https://example.com/some/quite,long,url,with,commas.jpg"); /*this one works*/
}
```

**Output:**
```css
body {
  background-image: url(
    https://example.com/some/quite,
    long,
    url,
    with,
    commas.jpg
  ); /*like cloudinary images*/
}

body .withImage {
  background-image: url("https://example.com/some/quite,long,url,with,commas.jpg"); /*this one works*/
}

```

**Expected behavior:**
Don't format, break lines or add space inside of `url()`. Formatting `url()` break the link. Work if url string is inside double quotes.
