### ISSUE TITLE
Ugly/wrong formatting for comments in CSS multiline properties

### ISSUE THREAD

**Issue by wedi** [prettier/prettier#6511]
1. Did search. Found related issues but no duplicate: #5719 #5603
2. No new option. Ugly formatting result / bug.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgE4QEYQwQC02cA5gK4A2AhtpsZnTAJZSbqoA6UAAgDNoMYgNpg4mYL0yYhsUbQC2ragE8kmAOQAlfIQhaA3DLnDiAZxhrqcTVAjYltaiY5mFAdzityACxhNABYABhC3WQtsME1qCDAXAApdfSItAEoAGmZ4pJSCImIdChp6DMzTWSrKbGpkgDp61HkYC1RcApIANwAmEOIWdlISumx6zwgBAR6MsydaGGSJqZmszAxMAGE-XCVJHoA2AGpsgHkABzhsWkwegGYTzAAxVjIhAA9MO4BOI84edxVWQ1OpaRrNYRtDoGYi9fqDKDDKijcaTASzITzRZaZbo9JGdZYba7STHbIvN4QT53epkzAASQAophftkAMq0MTYViYACs9QAjH8uLwAL68ECZEAQc5saAWZCgei4TwABXoCAVKFoXQgrAAJpKQHhrmAANZwGBs87idjkZAwbCUOBSgJKagAdT8rHgFhtEjZmp9rC6PrUyHAFgVUvYFiuMFV13IzmQYmocalACsLO8AEKmi1W5RwAAy7DgqZcGZA2febLttgAipRCBWkGnqzbsHHsBGwFGjedubAPQaYH5kAKwlKhxA4x7rucI0O4D2uhWpQBHFvwRMyrUgWgWYhQOBwfXno1kbevOCJ2jJ2iV9MukBxlQOp2viwNuDN1vPtWMC0Hgo76uOyA9FKjq0KodqbBASgpigDinkalBxgAKiBWodnAoqikAA)
```sh
--parser css
--print-width 100
```

**Input:**
```css
/* roboto-regular - latin */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src: local('Roboto'), local('Roboto-Regular'),
       url('../fonts/roboto-v20-latin-regular.woff2') format('woff2'), /* Chrome 26+, Opera 23+, Firefox 39+ */
       url('../fonts/roboto-v20-latin-regular.woff') format('woff'); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

```

**Output:**
```css
/* roboto-regular - latin */
@font-face {
  font-family: "Roboto";
  font-style: normal;
  font-weight: 400;
  src: local("Roboto"), local("Roboto-Regular"),
    url("../fonts/roboto-v20-latin-regular.woff2") format("woff2"),
    /* Chrome 26+, Opera 23+, Firefox 39+ */ url("../fonts/roboto-v20-latin-regular.woff")
      format("woff"); /* Chrome 6+, Firefox 3.6+, IE 9+, Safari 5.1+ */
}

```

**Expected behavior:**
Expected to keep the relationship of code and comments, either end of line or above. This example is (a little bit) less ugly with `--print-width 80` ([Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgE4QEYQwQC02cA5gK4A2AhtpsZnTAJZSbqoA6UAAgDNoMYgNpg4mYL0yYhsUbQC2ragE8kmAOQAlfIQhaA3DLnDiAZxhrqcTVAjYltaiY5mFAdzityACxhNABYABhC3WQtsME1qCDAXAApdfSItAEoAGmZ4pJSCImIdChp6DMzTWSrKbGpkgDp61HkYC1RcApIANwAmEOIWdlISumx6zwgBAR6MsydaGGSJqZmszAxMAGE-XCVJHoA2AGpsgHkABzhsWkwegGYTzAAxVjIhAA9MO4BOI84edxVWQ1OpaRrNYRtDoGYi9fqDKDDKijcaTASzITzRZaZbo9JGdZYba7STHbIvN4QT53epkzAASQAophftkAMq0MTYViYACs9QAjH8uLwAL68ECZEAQc5saAWZCgei4TwABXoCAVKFoXQgrAAJpKQHhrmAANZwGBs87idjkZAwbCUOBSgJKagAdT8rHgFhtEjZmp9rC6PrUyHAFgVUvYFiuMFV13IzmQYmocalACsLO8AEKmi1W5RwAAy7DgqZcGZA2febLttgAipRCBWkGnqzbsHHsBGwFGjedubAPQaYH5kAAOEJSocQOMe67nCNDuA9roVqUARxb8ETMq1IFoFmIUDgcH1F6NZB3rzgidoydolfTLpAcZUDqdb4sDbgzdbF9qxgWg8FHfVx2QHopUdWhVDtTYICUFMUAcM8jUoOMABVQK1Ds4FFUUgA)) but still the relation code <=> comment is lost which is not good.

**Related:**
#5719 #5603
