### ISSUE TITLE
Pre-commit hook always fails

### ISSUE THREAD

**Issue by dpinol** [prettier/prettier#6612]
**Environments:**

- Prettier Version: 1.18.2
- Running Prettier via: pre-commit
- Operating System: MacOs 10.14.5

**Steps to reproduce:**
```
.pre-commit-config.yaml with contents
  - repo: 'git://github.com/prettier/prettier'
    rev: 1.18.2
    hooks:
      - id: prettier
```
        
Run pre-commit run

**Expected behavior:**
No hook failure when no files are changed by prettier

**Actual behavior:**

Hook failure when no files are changed

I guess the issue is that prettier logs out the name of the processes file even if it didn't change it:

```
prettier --write src/app/app.component.ts        
src/app/app.component.ts 525ms
```
