### ISSUE TITLE
less background url formated lowercase

### ISSUE THREAD

**Issue by zealot09** [prettier/prettier#6697]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6eBnGACYAdKbbAIwEMwBrAcwCcIBXKAEwFoBLAW1KriW3poAbABQALGDAAOGJAHpZVAO6pSgtpNIBPCMQBWcMDAypIHWRyZRZNDhgD6ANgBmcBwA4ArLNJOjszlSyAIIAVADsAKIACgCqAEoA0gCcEACaAOoRQdk5uUEAQhRBcQCKUEElAJQA3AQAviAANCAQkjBs0BjIoKQ0dIpRvQhdKKQAbhBsTE0gxDTkFHAwAMoaYGxQVMgwNPRwzeIcgumibJhrcMvDZ2xjZ5rI4BhdzRsYcDQwUfNUXMhOqnezV0GAAHvl5pQlstSBw4AAZDZwf6A-YgEGg5YbKiCOAlegQeAowRAkAaGjvGiPXHPGaSGgbGDpKYwUTINwABma9Ig73S80kj3pcEpY2RzQAjgT4N9WiMQKQMCwoHA4Ew1TMaHApWwtd9uH8kACSWj3hw2Ntdqbsbj8YTkUbUc0YKRiMymKzkAAmZ3zNhqTYAYQgHENICg0HFIHo7wAKq6Rsb3nU6kA)
```sh
--parser less
```

**Input:**
```less
.test {
  background-image: url(https://gw.alipayobjects.com/mdn/rms_6fe685/afts/img/A*7EPURK9oYWEAAAAAAAAAAABkARQnAQ);
}
```

**Output:**
```less
.test {
  background-image: url(https://gw.alipayobjects.com/mdn/rms_6fe685/afts/img/A*7epurk9oyweaaaaaaaaaaabkarqnaq);
}

```

**Expected behavior:**
expect the url not processed
```
.test {
  background-image: url(https://gw.alipayobjects.com/mdn/rms_6fe685/afts/img/A*7EPURK9oYWEAAAAAAAAAAABkARQnAQ);
}
```
