### ISSUE TITLE
Inconsistent breaking of template literals

### ISSUE THREAD

**Issue by algomaster99** [prettier/prettier#6729]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAggHSgAhwQwF5gADbTGAEmACMBfHASwGcCdIpmZ9YA6HavSat87aFx4xeghizYcJfGcPnjuS2rJFjO6qdjx5lc0Qr38DOEnWwA+bKgD06e1GxmcAcQBO+AA4AFoxgOIQ4XACeADZwACa8zHBgMIzQZLg4AAIAtnGMotBREeFg3nAIBFCxlgAU2YxQALSxcABuwXCNAO6MsTABSDgA7ABsABx+AB4AlJXVGXX4k81tHd29-YMAjAAMAEwALFOzwJZ4EK1w3gBmURBdjZODzKUQUVEA3Gc4F1e3940IoMgrEWlAvhkbFASCAADQgCB+FLiZCgfDebz3AAK6IQzGQIHwrQgvThIBovjAAGs4DAAMp+fBgBoAc2QMG8AFc4PCAjBslEAOpBeDMRlgOB0vGMFLtGARAlgZj4+ENRLeGBY3ws7L4ZDXfBRRLwgBWzEmACFKTT6fhcgAZBpwfWG40gM2TOmsmIARU5EHgLqNPJAjO86oJNHwNDgUTJfm8DRggo2AWQYx28ITEESgt8fgJCbg6suZIAjv74FrEfiUPhmI0oOUWrEyWUK4wylr8Dq9UgDcH4Yl6kG3cxvXA-QHnf3XSHuDQU3000g9vCOfhGFFWQBhCDZXUEqDQZ3wzmJAAq0drA8SdDoQA)

### Scenario 1
**Input:**
```jsx
<A
  a={`
	${b} is a constant. ${b} is a constant.${b} is a constant.${b} is a constant.${b} is a constant.
    ${b} is a constant. 
  `}
>
</A>
```

**Output:**
```jsx
<A
  a={`
	${b} is a constant. ${b} is a constant.${b} is a constant.${b} is a constant.${b} is a constant.
    ${b} is a constant. 
  `}
></A>
```

**Expected behavior:**
As expected.

### Scenario 2

**Input:**
```jsx
const Graphic = styled.section`
  @media only screen and
  (min-device-width: 768px) and
  (max-device-width: 1024px) {
    overflow-x: scroll;
    overflow-y: hidden;
  }
`
```

**Output:**
```jsx
const Graphic = styled.section`
  @media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
    overflow-x: scroll;
    overflow-y: hidden;
  }
`
```

**Expected behavior:**
Should have left it multi-line

Why is there an inconsistent breaking of template literals? When does it break and when not? Referring to this PR - https://github.com/prettier/prettier/pull/5979, what is meant by "simple template literals"?

**Comment by thorn0** [comment]
Scenario 2 has nothing to do with the simple/not simple distinction. The thing is Prettier special-cases some hard-coded template literal tags, including `styled.*`, and applies special rules to literals that have this tags. In this case, it parses and reformats the string as CSS, using the CSS parser and printer. Other examples are (but not limited to) `` html`...` `` and `` graphql`...` ``. This feature is a bit controversial and might change (become configurable) in the next major release (see https://github.com/prettier/prettier/issues/5588 and https://github.com/prettier/prettier/pull/6626). 

Did I answer your question?

**Comment by algomaster99** [comment]
@thorn0 Thanks for the quick response!
My current workaround is to use `"max-len": ["error", { "ignoreTemplateLiterals": true }],` in `eslint` config to make the tests pass. Is this okay?

**Comment by lydell** [comment]
@algomaster99 We recommend turning off all rules that conflict with Prettier. See: https://prettier.io/docs/en/integrating-with-linters.html

`max-len` _can_ be used with Prettier, but I wouldn't personally recommend it. You’ll always be fighting with it. See: https://github.com/prettier/eslint-config-prettier#max-len

**Comment by algomaster99** [comment]
Thanks @lydell !
But apparently, we *have* to use `max-len`. We think it will make our code look neater. Anyway, thanks for the help.

**Comment by thorn0** [comment]
It's actually a bug. Media queries ignore `--print-width`. Can't find another issue about this, so let's reopen this one.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtnAJgSwIYAE0ANgJ4EDOYATnAgQXlFgDpQAU6OUAtFnADccYODwDuOLDAAWSAgHYAbAA4ADgA8AlI2ZtOedX0HDREqbIIBGAAwAmACwbtwNgwYQBcagDNiEMTzqclTUEMTEANyubh5evv48pHLSkvxQUVAAvmwgADQgEKowONAUyKB41KFiAAqVCGUoeAIQknkgAEbUeGAA1nAwAMqqPdwA5sgw1ACucPnSMOjEAOop8BQjIoMNOMVCMKTI4BRl+dwUXjA13WPoeMjeeMQX+QBWFOoAQt19A4N4mAAMtw4A8ni8QO91INxsQ4ABFaYQeBg55zEAjagXahHMAndqqajcGDLSQyZD2az5QkQC7LbqqI6EuDYzztACOSPg10KjRAeAoPCgdH4WHatE5OFo1zwt3uSEeaPyFy4kxm6IosIRXNBCvB6JgeA6pPMyFs+SmeBwxHGAGEIOg7kcoNBQflphcACpGxqKi6ZTJAA)
```sh
--parser css
--print-width 40
```

**Input:**
```css
@media only screen  and
(min-device-width: 768px) and
(max-device-width: 1024px) {
    overflow-x: scroll;
    overflow-y: hidden;
}

```

**Output:**
```css
@media only screen and (min-device-width: 768px) and (max-device-width: 1024px) {
  overflow-x: scroll;
  overflow-y: hidden;
}

```

**Comment by evilebottnawi** [comment]
@thorn0 it is expected, we try to avoid break `@media` for better readability, i can't find discussion, but it was in some of PRs

**Comment by thorn0** [comment]
I can't find any such discussion either. Looks like a bug to me.

**Comment by evilebottnawi** [comment]
@thorn0 hm, what is expected:
```css
@media only screen  and
  (min-device-width: 768px) and
  (max-device-width: 1024px) {
    overflow-x: scroll;
    overflow-y: hidden;
}
```

```css
@media only screen  
  and (min-device-width: 768px)
  and (max-device-width: 1024px) {
    overflow-x: scroll;
    overflow-y: hidden;
}
```
