### ISSUE TITLE
YAML: comment in list not format correctly

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6952]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCECMSA6UAE+AtPuhEvgJbwC2mehhARgIYBOF1cdevUD+AMTFSGTrQBMA4c3bjuU-kukiy8mgGYVsjlVoAWPoRJq93AKwCd6ywUZ4yE3HZNizPO9ff1ld4a-J3RUIZfFZdLhpFPhUA9S0-RnD1Q18QABoQCAAHGEpoAGdkUHY2CAB3AAV2BCKUFgA3CEoAEwyQJjYWMABrOBgAZWzuyigAc2QYNgBXOEyACxgaABsAdXmuAuGwOAHa6koG6gBPZHACoszRgrg2GEqusZoWZFQWZZvMgCsCgA8AIS6vX6AxYNDgABlRnBXu9PiAfr8BqMxss4ABFaYQeCwj5zEDDNg3NhnY5g5btbJsUYwVatGDzZAADgADJkqRAbqsutkzlS4MSGjDMgBHLHwB45OogFgFIhQOBwFpK9psOBiyhqh4sJ4vJBvPGZG40SiTGb4gootGY7Ew-Vw-EwFhMOktBnICSZKYsSjLFEAYQgNGeZyg0GFIGmNwAKs66gb4Q1ZgBJKDK2ADMDU3IAQTTAxgxzRuJuAF9S0A)
```sh
--parser yaml
```

**Input:**
```yaml
foo1:
  - foo: item1
    bar: item1



  # - foo: item2
  #   bar: item2



  # - foo: item3
  #   bar: item4

  - foo: item5
    bar: item5
    
foo2:
  - foo: item1
    bar: item1


  # - foo: item2
  #   bar: item2



  # - foo: item3
  #   bar: item4



```

**Output:**
```yaml
foo1:
  - foo: item1
    bar: item1

  # - foo: item2
  #   bar: item2

  # - foo: item3
  #   bar: item4

  - foo: item5
    bar: item5

foo2:
  - foo: item1
    bar: item1
  # - foo: item2
  #   bar: item2
  # - foo: item3
  #   bar: item4

```

**Expected behavior:**

foo2 should format comments like foo1

**Comment by cinderblock** [comment]
Another manifestation of what I presume is the same bug. You can't even fix it with `prettier-ignore`.

### Input
```yaml
    needs:
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]

    steps:
```

### Output
```yaml
    needs: [check-format, check-lint, check-spelling]

    # coverage,
    # install-and-run-from-git,
    steps:
```
I expected no change. There seem to be two things happening here:
1. Comments are being removed from the list. I don't think this is generally desirable. A common thing in JS for instance is to comment a single line from a list of things and that comment isn't taken out of the list.
2. Comments are not allowed to be "after" a section and are forced to be used as comments that seem to describe the next section. Empty lines around comments should be preserved, imho.

However, if I try to "fix" this with `# prettier-ignore`, it breaks even worse:

### Input
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]
    steps:
```

### Output
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]
    # coverage,
    # install-and-run-from-git,
    steps:
```

This is also "unstable" as every time I autofix, Prettier replicates the comments. After "formatting" 5 times:

### Output
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    steps:
```
