### ISSUE TITLE
Should Prettier enforce a double-colon for CSS pseudo-elements?

### ISSUE THREAD

**Issue by paulozoom** [prettier/prettier#6956]
CSS supports both `:before` and `::before` for pseudo-element syntax. However, the double-colon `::before` is the recommended option, to differentiate pseudo-elements from pseudo-classes. 

**Prettier has no preferences on single vs. double-colon for pseudo-elements. Should it, or is it beyond its scope and a responsibility of linters?**

The only argument for still _allowing_ the single-colon syntax is that IE8 doesn’t support the double colon syntax. This CSS-Tricks article elaborates on it: https://css-tricks.com/to-double-colon-or-not-do-double-colon/ However, IE8 only has a 0.12% global market share, and surely declining.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6eBnGSBGcBmEATnAATAA6UppkANsUqSQCYDcVAvlVenFklwFiZStVoQGRJqw5ROIADQgIABxgBLaBmSgAhkSIQA7gAUDCHSj0A3CBpZKQOInrABrODADKqtxqgAc2QYIgBXOGUACxgAWzoAdSiNTD8wOG9LFI0bFIBPZHAMHWUAjDgiGFNXQNi9ZHw9OnLlACsMAA8AIVcPL289WLgAGQC4BqaWkHaO7wDAujgARTCIeAnmyJA-InKiQrBip1UiAJgEhxgo5AAOAAZlE4hyhNdVQpP+Cptx5QBHVbwapqKwgPQYAC0UDgcBYsKcJABGhI1T0tXqSEam2U5ViGhC4S2GHmixWa3GmMmWxgehwFxYV2QACZlKE9Bo6PMAMIQWJ1QpQaC-EBhcoAFVpVix5U4nCAA)
```sh
--parser css
```

**Input:**
```css
.test:before {
  color: red;
}

.test::before {
  color: red;
}
```

**Output:**
```css
.test:before {
  color: red;
}

.test::before {
  color: red;
}
```

**Expected behavior:**
```css
.test::before {
  color: red;
}

.test::before {
  color: red;
}
```
