### ISSUE TITLE
CSS Multiline declaration should not be on the same line as the property

### ISSUE THREAD

**Issue by GrimLink** [prettier/prettier#6986]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0oijU4CALIgEkwCcBbPGIgSwqYjY4BnEuUpiqXdIxbtOAXjlEANhDB4lIiuO18BOFWqVJlq9QApJZhoICu6dFwAeRBUVIgASnADmNpXmZ3ABo3EABiYAYoPFY4AF9g0IiomOJrOwdHBJAAShyQg3N3ZPQ-JWxo2OycgG5RbTiqOCVBYjItbTFdWWwbZiMiPqUzYsiABw5aOIB6Eq4lOArUuIA6Ev5ZaqIZDhHwyJ2YarqOzukNjmxBZjBjPDGxhAATK0Orm5Duy6GQyFZ2Wr1cQJLQgkHkFZgfyCYTtSgAIwIAGtvMwIDYoE9jGE4LjlDwaMxsKi8E8uAgYGYAIwABhpTx8n0gKiJMFocFiRAALDSAKQhUkAKxsghwzP4VnFrPZsU+Si43loMCgcBhxmwXN5OSIAHY+QKnsLRdgpZKICzsGyOXA5QqlSq1URsABOLXawiwODMaaQABuXqIUAg2GYcEeHBOcRAQRAEDGMC40EEyFAATRAHcAAoBBDJlB4X0QLhPaMgeHMZFwGAAZQmYB43mQMGYNhtICVrCUAHVaFx4II63Bq7m+1xfX2AJ7IcAw0s8VrMGCZivedjIfAtNuCwSOABCFbASKr1dSABkCev1K0Y9vHNWGwsAIo2CDwS+bmMTZgL6eCMCzz9mB4GAu2LNlkAADhpQCIFaLsKzGacxlDBd-VLABHF94GXOM8xAPBBAqXEGRLGNQ0wrhQ2XPBVzwd9rxAVpWC4JsWzbQQHzgZ9Xzgei2xgPB4VAp5wKQAAmGNmzweYGwAYQgf46JQIMVVLEU4AAFUEvMNwY31WwASUxClqzAID4wAQUxasYAnBY+LiOIgA)
```sh
--parser scss
```

**Input:**
```scss
@font-face {
  @each $format in $formats {
    @if $format == local {
      $format-local: local(if($suffix == "Regular", "#{$name}", "#{$name $suffix}")), local("#{$full-name}");
    } @else {
      $format-url: url("#{$path}/#{$file-name}.#{$format}") format("#{$format}");
      $format-src: append($format-src, $format-url, comma);
    }
  }
}

.class {
  background: #eee linear-gradient(100deg, $color-theme 40%, adjust-color($color-theme, $lightness: -4%) 70%, adjust-color($color-theme, $lightness: -9%)) center/cover no-repeat;
}
```

**Output:**
```scss
@font-face {
  @each $format in $formats {
    @if $format == local {
      $format-local: local(
          if($suffix == "Regular", "#{$name}", "#{$name $suffix}")
        ),
        local("#{$full-name}");
    } @else {
      $format-url: url("#{$path}/#{$file-name}.#{$format}")
        format("#{$format}");
      $format-src: append($format-src, $format-url, comma);
    }
  }
}

.class {
  background: #eee
    linear-gradient(
      100deg,
      $color-theme 40%,
      adjust-color($color-theme, $lightness: -4%) 70%,
      adjust-color($color-theme, $lightness: -9%)
    )
    center/cover no-repeat;
}
```

**Expected behavior:**

The first value should not be on the same line as the property.
This is also the default behavior with [stylelint-config-recommended](https://github.com/stylelint/stylelint-config-recommended).
Which follows the common stylistic conventions found within a handful of CSS styleguides, including: The Idiomatic CSS Principles, Google's CSS Style Guide, Airbnb's Styleguide, and @mdo's Code Guide.

[The stylelint rule affected by this](https://stylelint.io/user-guide/rules/declaration-colon-newline-after).

```scss
@font-face {
  @each $format in $formats {
    @if $format == local {
      $format-local:
        local(if($suffix == "Regular", "#{$name}", "#{$name $suffix}")),
        local("#{$full-name}");
    } @else {
      $format-url:
        url("#{$path}/#{$file-name}.#{$format}")
        format("#{$format}");
      $format-src: append($format-src, $format-url, comma);
    }
  }
}

.class {
  background:
    #eee
    linear-gradient(
      100deg,
      $color-theme 40%,
      adjust-color($color-theme, $lightness: -4%) 70%,
      adjust-color($color-theme, $lightness: -9%)
    )
    center/cover
    no-repeat;
}
```

**Comment by evilebottnawi** [comment]
Please provide provide full **Expected behavior**, i can't understand what is  `first value` in your example

**Comment by GrimLink** [comment]
@evilebottnawi sorry, the expected output was also the input 😅
I changed the input to a unformated version and added Expected behavior code sample.

**Comment by evilebottnawi** [comment]
Unfortunately this is not heuristic and can lead to a very ugly code

**Comment by GrimLink** [comment]
@evilebottnawi please explain why?
The only difference is the break at the property.

**Output**
```scss
.class {
  background: #eee
    linear-gradient()
```

**Expected**
```scss
.class {
  background:
    #eee
    linear-gradient()
```

**Comment by evilebottnawi** [comment]
```css
.class {
  background: #eee
    linear-gradient(#e66465, #9198e5);
}
```

should be
```css
.class {
  background: #eee linear-gradient(#e66465, #9198e5);
}
```

because it is heuristic

**Comment by GrimLink** [comment]
@evilebottnawi I get the feeling you are not understanding me.
You comment is correct for 80 characters or less.
But my issue lies when it is more.
Then the values should nest under the property.
Just as with stylelint and many css styleguides.

**Comment by evilebottnawi** [comment]
@GrimLink i.e. break only when it is more than 80 characters?

**Comment by GrimLink** [comment]
@evilebottnawi yes!

Please checkout the https://stylelint.io/user-guide/rules/declaration-colon-newline-after rule to see the correct wrapping.

**Comment by evilebottnawi** [comment]
@GrimLink 
Note:
```css
a {
  color:
    pink;
}
```

is ugly and should be avoided, let's wait other answers

**Comment by GrimLink** [comment]
@evilebottnawi again it's for multiline properties
So the second rule (always-multi-line) not the first rule!

First of the first example is also not used by styleguides.

```css
a {
  box-shadow:
    0 0 0 1px #5b9dd9,
    0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

**Comment by JounQin** [comment]
@GrimLink You should always enable `stylelint-config-prettier` and `stylelint-prettier` if you want to use `stylelint` with `prettier` together IMO.

`prettier` should take care of all formats or styles.

**Comment by GrimLink** [comment]
@JounQin that is not the issue.
The way prettier formats multiline properties is.
Please read issue text -> https://github.com/prettier/prettier/issues/6986#issue-524003880

**Comment by JounQin** [comment]
@GrimLink Sorry, my English is not so good, I still can't get the point, didn't you complain about prettier not formatting your scss expected same as other formatters? Please point out if I'm wrong.

**Comment by thorn0** [comment]
The issue is not about tools and style guides. What `@GrimLink` wants sounds reasonable to me:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6MAbAhgZxwAmAB0p98AjLMAawHMAnCAVygBMkSyyBiOPzrhgCWUOFnoBaBllZCEMABQBGAAwrWcWgBoK2GvgAsKgKQ6AnnAwYIAd3wB2EzpsALIfACUAsmHlx6APSQAG7+3vhQEBL0cAAOYjAA3CQAviBaIBCxMELQOMig4ow2AAriCPkoWMEQQqzpIOT0VNRwMADKsVQitMgw9ExwGS4wALYYAOpu8Dhdvu0V7kLB7mbI4HgNIjj+MCXNtKNYyABmWBg7GQBWOAAeAELNNG3tWKNwADIicKfnlyA3W7tHoYOAARSYEHgvwuQxAXXoO3o6zAmwysXoIhgEzqMBcyAAbCp0YwdhNmrF1hi4EjQg0AI6Q+D7LKVEC4CSiOAaeoZGKMoQxfZYQ7HJBnWEZHajIR9AZwnAg8FMn7iv5wmBYcg41h45AAJgy-SwQmEUFoAGEIKMjutIqIGkwdgAVLWVCX-YKDACSbHk7TAmOyAEE2O0YGZQTCdikUkA)
```sh
--parser css
--print-width 60
```

**Input:**
```css
.class {
  background:
    #eee
    linear-gradient(100deg, black 40%, yellow 70%, white)
    center/cover
    no-repeat;
}
```

**Output:**
```css
.class {
  background: #eee
    linear-gradient(100deg, black 40%, yellow 70%, white)
    center/cover no-repeat;
}
````

**Requested:**
```css
.class {
  background: 
    #eee
    linear-gradient(100deg, black 40%, yellow 70%, white)
    center/cover no-repeat;
}
```

**Comment by GrimLink** [comment]
@JounQin no problem 😉
Your not wrong.
The formatting used by Prettier is different from styleguides and the default from Stylelint, for multiline properties.

When Prettier formats css that is longer than the max line length the first value is placed before the property.
Instead being wrapped below, with the rest of the values.

**Wrong:**
```css
a {
  box-shadow: 0 0 0 1px #5b9dd9,
    0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

**Expected:**
```css
a {
  box-shadow:
    0 0 0 1px #5b9dd9,
    0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```
