### ISSUE TITLE
sass formating fault

### ISSUE THREAD

**Issue by mskim8522** [prettier/prettier#7006]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```scss
  @media only screen and (min-resolution: 192dpi), // IE9-11 don't support dppx
    only screen and (min-resolution: 2dppx) { // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
```

**Output:**
```scss
  @media only screen and (min-resolution: 192dpi), 
    // IE9-11 don't support dppx only screen and (min-resolution: 2dppx) { 
    // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
```

**Expected behavior:**
