### ISSUE TITLE
SCSS Formatting: mixin/function close parens

### ISSUE THREAD

**Issue by nex3** [prettier/prettier#7033]
For background: I'm the lead designer of Sass, and also the tech lead of the CSS/Sass infrastructure team at Google. I'm considering adopting Prettier as the official recommended formatter for Sass, and as the internal formatter we use for all of Google's CSS and Sass. If we decide to move forward with Prettier, we'd be happy to contribute some improvements and bug fixes upstream. However, we'd like its formatting to match the formatting we've historically recommended for Sass as well as the formatting in use within Google (and the formatting of similar constructs in other languages).

The biggest blocker for this is the way long mixin and function argument lists are formatted, with the closing `)` on its own line rather than on the same line as the final argument. If this could be fixed, we'd be mostly fine with the rest of the formatting.

---

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAtgSwB6agAigEN04AKAEhgAsiYBaGIgazgGd6j6A3OAJwCe9ADbQA5knxE+YgK6lY+YZjYwANPgpsII8fUwMA7pmHD6UOHAAmjCJMN8iAB3wwIUwnENK8cAJT4wAA6BPgA9GH4AHLukLAIMCEAviEhqHhgwrJWcIQk5MY0+LyCSuJSMvIJPqoaAGaypvgQdWUwbM2tNHhibBo0dPhiEOz4TkSqrtS5yhZKCGI0fgDcIGogEE4wmNBsyKDSfBCGAArSCHsoRNwQmFZrIABGjmCsMADK42A9yDB8snB1tQYOhhAB1agGdhfODvC4GTDcAwCZDgNh7dZ4Nj8GAnRxidBEZB1IjCbHrABWbGwACEXm93vkADK+Ymk8kgKnYd49YRwACKsgg8DZZMBIHGfGxfFRbDA6IeTj4eBgYLuNGQAA4AAzrJUQbFgxxOVFK9j8XgPACOQvgeM2lxAE3Mlhy93WfDgNswnrxRAJRKQJLF62xWF+-3FbF5AttcFFHKYjzVVg1SAATOs-kQTD0AMIQdCE1FQaDx9aybEAFSIj0uwY53ABAEkoDlYO8wMqtgBBNvvGACPkJuBJJJAA)
```sh
--parser scss
```

**Input:**
```scss
@mixin name($that-takes-a-very-long: argument list, $so-long-it-will-need-to: wrap to a new line) {
  // No content
}

@include name(with very long argument list, full of lots of things, that goes past the line length);
```

**Output:**
```scss
@mixin name(
  $that-takes-a-very-long: argument list,
  $so-long-it-will-need-to: wrap to a new line
) {
  // No content
}

@include name(
  with very long argument list,
  full of lots of things,
  that goes past the line length
);

```

I'd expect:

```scss
@mixin name(
  $that-takes-a-very-long: argument list,
  $so-long-it-will-need-to: wrap to a new line) {
  // No content
}

@include name(
  with very long argument list,
  full of lots of things,
  that goes past the line length);
```
