### ISSUE TITLE
CSS Multiline declaration should not be on the same line as the property

### ISSUE THREAD

**Issue by GrimLink** [prettier/prettier#7039]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAOlLMBGEAHgLQDOAFqgCYQDuS6ADM6wIwAOR6ATgOb5UACgDMTADTo2AFglSAnHKYA6ABwBKSSxYAmLlP39BouTNOKta9QG4cAXxDiQEDjACW0MslCoePegAKvgheKKgAbhBu1I4g+DyoYADWcDAAyhyJblB8yDA8AK5wThQwALYANgDqFG7wZJlgcGkhdW7hdQCeyOBkXk7ZZHA8MAEJfGWoyABmqBVDTgBWZEQAQgnJqWmoZXAAMtlwM3MLIMtEadl8FXAAigUQ8MfzxSCZPEM8PWB9sRw82RgVWiMAoyFUEje-iGVQSHB6-zgn3CRycAEcHvAxi5QmgyCQoHA4NRibEeHAMW5yWNUBMpkhZi8nEMym48oVXmQrjd7o8jgyTq8YKh8MDqKDkDonPlUG4KlcAMIQMqTHpQaCokAFIYAFRFoUZp3CRQAklASbA0mAAa4AILmtIwTo3Z5DOx2IA)
```sh
--parser css
```

**Input:**
```scss
a {
  box-shadow: 0 0 0 1px rgba(30, 140, 190, 0.8), 0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

**Output:**
```css
a {
  box-shadow: 0 0 0 1px rgba(30, 140, 190, 0.8),
    0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

**Expected behavior:**
```css
a {
  box-shadow:
    0 0 0 1px rgba(30, 140, 190, 0.8),
    0 0 2px 1px rgba(30, 140, 190, 0.8);
}
```

The first value should not be on the same line as the property when wrapped to multiline  declaration.

_Old previous issue #6986_

**Comment by whatisaphone** [comment]
Search keywords: newline comma multiple split lines

I often notice this with `transition` too.

Current formatting:

```css
.box {
  transition: color 0.15s ease-in-out, background-color 0.15s ease-in-out,
    border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
```

Ideal formatting:

```css
.box {
  transition:
    color 0.15s ease-in-out,
    background-color 0.15s ease-in-out,
    border-color 0.15s ease-in-out,
    box-shadow 0.15s ease-in-out;
}
```

---

To avoid some of the confusion from the last issue, this should of course continue to respect `printWidth` like usual.

80 characters wide:

```css
.box {
  background: aaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccc;
}
```

81 characters wide:

```css
.box {
  background:
    aaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbb,
    ccccccccccccccccccccccc;
}
```

**Comment by domske** [comment]
Yes, please implement this behavior. Either break when overflow the line width or always. I would prefer always, because it's very clean (prettier) when all values are below each other. You can change it without any confusion.

**Current behavior (BAD):**

```css
.text {
  text-shadow: 1px 0px 0px black, 0px 1px 0px black, -1px 0px 0px black,
    0px -1px 0px black;
}
```

**Wrong implementation (BAD):**

```css
.text {
  text-shadow: 1px 0px 0px black, 
    0px 1px 0px black, 
    -1px 0px 0px black,
    0px -1px 0px black;
}
```

**Correct implementation (GOOD):**

```css
.text {
  text-shadow: 
    1px 0px 0px black, 
    0px 1px 0px black, 
    -1px 0px 0px black,
    0px -1px 0px black;
}
```

**Always - If more whan one value. (BEST):**

```css
.text {
  text-shadow: 
    1px 1px 0px black, 
    -1px -1px 0px black;
}
```

Prettier could either accept an option if "always" or on line overflow. OR detect it automatically if a line break is inserted before the first value.

**Comment by evilebottnawi** [comment]
Here good example how it should work https://github.com/prettier/prettier/issues/7039#issuecomment-622459161

**Comment by ext** [comment]
I've recently hit this issue as well and I'm a bit surprised by the current behavior. I believe the best implementation would be to always add line-breaks when using multiple declarations since it adds clarity and makes it obvious multiple statements are present:

```css
.my-class {
  transition: 
    background-color 250ms ease-in-out,
    color 250ms ease-in-out,
    opacity 250ms ease-in-out;
}
```

**Comment by y0nd0** [comment]
Sereosly, why is this not already implemented in Prettier? Beacuase this is prettier.

Another demo:

**Current Prettier output**

```scss 
.something {
  transition: color 150ms cubic-bezier(0.4, 0, 0.2, 1) transform 150ms
    cubic-bezier(0.4, 0, 0.2, 1);
}
```

**Expected "prettier" output**

```scss
.something {
  transition:
    color 150ms cubic-bezier(0.4, 0, 0.2, 1)
    transform 150ms cubic-bezier(0.4, 0, 0.2, 1);
}
```

Only break when multiple values are assigned. Single values can be formatted like the current behavior in one line.

I just wonder why the tag `status:needs discussion`? What's not clear?
It's Prettier and not Uglier. That is a very clear case. But please explain to me.
What's the problem here?
