### ISSUE TITLE
Broken SCSS Comment Fixing

### ISSUE THREAD

**Issue by GrahamCampbell** [prettier/prettier#7109]
**Prettier 1.19.1**

```sh
# Options (if any):
--parser postcss --print-width 120 --single-quote
```

**Input:**
```scss
.test {
    background:
        /////// foo
        // bar

        radial-gradient(circle farthest-corner at 5% 10%, #000000, transparent 50%);
}

```

**Output:**
```scss
.test {
    background:
        /////// foo
        // bar radial-gradient(
        circle farthest-corner at 5% 10%,
        #000000,
        transparent 50%
    );
}

```

**Expected behavior:**
```scss
.test {
    background:
        /////// foo
        // bar

        radial-gradient(
            circle farthest-corner at 5% 10%,
            #000000,
            transparent 50%
        );
}

```

**Comment by jnns** [comment]
Another issue with SCSS comments:

**Input** 
```scss
.real-world-example {
  background: radial-gradient(
      circle at left 0% bottom $position,
      transparent,
      transparent $diameter,
      #fbfbfb calc(#{$diameter} + 1px) // Add 1px for edge-smoothing.
    );
}

.simplification { 
  foo: (
    calc() // not a comment anymore
  );
}
```
**Output** ([Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6ATnAhgGwLQDuE6OAJnnAB5YC2ADjnAATAA6UTTARlmANYBzdBACuUUkibospAJa48QmbIQwAFO05amYWejCMmWGE0YAzEwAYApNwgwYEGkwAkdCAGdZMWdAA0mtpMMNJQHnRYmLABHEEhWGERUSYucrRw8OgxQUwAxGZcBQU6uGBqucCp8jQZcOgAvkwA1EwAjHSUAJRMAPQ9TACCpKRtHUxmxExwpAJweB40EPYAFrJQAqiBnJ0A3Oz17OyoXvQ4smayYMa+HMBMgRMQkhqxnFc4Zd19TFD2RjpOGqwIxQACei0whxgu327BAfhAEDoPmgHmQoEiwgIAAVIgg0SgsAA3CCyUjwkBcaT8DIAZQiunWyBCIjgCOWMBoOAA6qt4OFeHBafjvLIid5QchwB40Qi1h46jBsdIBDQsMgzLgFQiAFYeSgAIWpfDp6QAMms4BqtWyQHrKLS1gJGABFET2K1ITU4bUgJIK9BSjxgGUUujoNYwblkmDLZAADksCPDnjg3OkdCl4bgAaJVoRAEd3fBlUiCSAsB48FA4NNphTMEW9HBlVhVeqvTaEQqaLJmehWd2na7i57vb6YFguNHSLHkAAmBHxWRndYAYUBHZAvxrFJECoAKlOCePbUTWQBJcSqWlgCPIgbiWkwUGMa0+uD1epAA))

```scss
.real-world-example {
  background: radial-gradient(
    circle at left 0% bottom $position,
    transparent,
    transparent $diameter,
    #fbfbfb calc(#{$diameter} + 1px) / / Add 1px for edge-smoothing.
  );
}

.simplification {
  foo: (calc() / / not a comment anymore);
}
```
**Expected output** 

```scss
.real-world-example {
  background: radial-gradient(
    circle at left 0% bottom $position,
    transparent,
    transparent $diameter,
    #fbfbfb calc(#{$diameter} + 1px) // Add 1px for edge-smoothing.
  );
}

.simplification {
  foo: (calc() // not a comment anymore);
}
```
