### ISSUE TITLE
Keep adding semicolons when meet SCSS @include directive with an empty comment

### ISSUE THREAD

**Issue by ntnyq** [prettier/prettier#7110]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#.....)

**Input:**
```scss
@mixin foo {
  width: 100px;
}

.bar {
  @include foo //
}
```

**Output:**
```scss
// Run Prettier once
@mixin foo {
  width: 100px;
}

.bar {
  @include foo //;
}

// Run Prettier many times (When formatOnSave)
@mixin foo {
  width: 100px;
}

.bar {
  @include foo //;;;;;;;;;;;;
}
```

**Expected behavior:**
```scss
// 1. Remove the empty comment and add a semicolon
@mixin foo {
  width: 100px;
}

.bar {
  @include foo;
}

// 2. Add just one semicolon where it should be
@mixin foo {
  width: 100px;
}

.bar {
  @include foo; //
}
```
