### ISSUE TITLE
[scss] @at-root not intended properly

### ISSUE THREAD

**Issue by zebapy** [prettier/prettier#7243]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqACBDGBaAJwghlQDoAHbA7AcxooAs894APUganKpvuyYt2pAHypGAJgA0AHSgZyAGzjYAJqm4AyVGMmpgchZgCWUMIoCuquOIkBuQxgC21WqdYQKSVABIAzlRgprR4AOwO8s6u7gBGJDAQTt7+gcF4ACwRjugmZpbWqE5wqsbYABSKtACU+tlRBG5QHl6+AdhBUCEAHBEK6C4NsfGJyW0dIQCsvRgAvo5zUCBSIJ4wxtB+yKDURADuAArUCJso2ABuEMaqSyAxNGAA1nAwAMqpncgwBBZwy4wwTkUAHVGMZ4GM4C9jmDjGcwQBPZDgPybZamPxwAgwfZ8FzIABm2EUGOWACs-GwAEL3J6vbBFAAypjgBKJJJA5LYL2CygAihYSCykITib8QLwMQQkX4wCibhQCKYYECrjBGMgugAGZYKiAYoEMJEKuCSs4s5YARwF8BxnhOIGwfjwUDgxWKNwIcCtxk9OLoeOFbLFGKcxk+32DPLg-MFrNFyxg2BiKtUauQ0hAX2wxkUwQAwokAyAoNBzSALBiACpJk4i9lnH4ASSg1lgLzAiooMAAgi2XjB4co4xiZjMgA)
```sh
--parser scss
```

**Input:**
```scss
    @at-root .paragraph--text + .paragraph--text > h2,
    .lead + & > h2 {
    @include h2;
    margin-top: $spacing-7;
    margin-bottom: $spacing-4;

    @include media(lg) {
      margin-top: $spacing-8;
      margin-bottom: $spacing-5;
    }
  }

```

**Output:**
```scss
@at-root .paragraph--text + .paragraph--text > h2,
  .lead + & > h2 {
  @include h2;
  margin-top: $spacing-7;
  margin-bottom: $spacing-4;

  @include media(lg) {
    margin-top: $spacing-8;
    margin-bottom: $spacing-5;
  }
}

```

**Expected behavior:**
I would expect the `.lead` to have 0 spaces before it like below. Is this a bug? 
```scss
@at-root .paragraph--text + .paragraph--text > h2,
.lead + & > h2 {
  @include h2;
  margin-top: $spacing-7;
  margin-bottom: $spacing-4;

  @include media(lg) {
    margin-top: $spacing-8;
    margin-bottom: $spacing-5;
  }
}

```

**Comment by evilebottnawi** [comment]
For me zero spaces is very ugly

**Comment by zebapy** [comment]
It at least matches up with the top 'selector' and the bottom bracket though. Perhaps it's due to it not being unique to the one selector and instead the whole list of selectors?

**Comment by thorn0** [comment]
It's Prettier's standard way to format CSS. Why would `@at-root` be formatted differently?

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCAaABKgIwEMAnXYAHSl1wBMBLAZwAcAbIgTyVymjgG4qAXxDYQEZjHrRGyUKRIQA7gAVSCWSiIA3CPVqiQBEkTABrODADKzU-SgBzZDBIBXOGIAWMALasA6p708CymcFYawfTawRzI4IyyYvaMcCQwKiYOPkTI6ESsqWIAVowAHgBCJuaWVkQ+cAAy9nB5BUUgpWVW9g6scACKrhDwbYUeILYkqSTxYImGzCT2MP76MJ7IABwADGJLEKn+JszxS3Az2q1iAI7D8JkSmiBEjAC0UHBwtN+GJHB3ej-TJEbK5JD5cZiVI+ejONwTRi9fpDEatCHtCYwIgENa0DbIABMYhcRHorF6AGEID4cvFeJ9DK5UgAVHGaSEdbTuACSUB+sCsYGWkgAgvyrDAOP0xqkhEIgA)
```sh
--parser css
```

**Input:**
```css
.foo, .bar {
  display: none;
}
```

**Output:**
```css
.foo,
.bar {
  display: none;
}

```

**Comment by thorn0** [comment]
The proposed formatting makes it look like the syntax is `(@at-root <selector>), <selector> { ... }` whereas in fact it's `@at-root (<selector>, <selector>) { ... }`.

Am I correct that the code example can be rewritten this way?
```scss
@at-root {
  .paragraph--text + .paragraph--text > h2,
  .lead + & > h2 {
    @include h2;
    margin-top: $spacing-7;
    margin-bottom: $spacing-4;

    @include media(lg) {
      margin-top: $spacing-8;
      margin-bottom: $spacing-5;
    }
  }
}
```
Prettier won't do such a rewrite, but if this syntax is indeed equivalent, I see no point in fixing something in this issue.
