### ISSUE TITLE
Formatting YAML file inserts ternary operators after line length exceeded

### ISSUE THREAD

**Issue by thejcannon** [prettier/prettier#7625]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA5A8gFQAQBl2oDi2AohgKqEASAdHfQ408y6260gDpTbYDWcAJ5JsANwCGAGwCucbviKkK1dqrXqNDLj35CREmXBAAaEBAAOMAJbQAzslDiATk4gB3AArOE9lONEQVgAmJiAARk7iYAIwAMrmUVZQAObIME6ypgAWMAC2kgDqWVbwtglgcLE+JVaiJYLI4Lb2pkm2cE4wHpHJueLIAGZS7aYAVrYAHgBCkdFwceK5cLhJRkhDkiMg4xOxScmScACK0hDwg8NwpglO7U6NgouSoeZOSTAFwTBZyAAcAAzXVztAqRcyNV5wO6iIymACOp3g3QsvhA4lsAFooHA4EFcaEnHAEVZCd1xL1+utLqZ2rkrGkMlcQLZ9ocTmc1hstjBxGFPkFvsgAEymdLiKySfYAYQguT6jSg0FhIGk7UwvN8XKZolkAEkoHjYLEwG9LABBA2xGCCQ4XTZwAC+DqAA)
```sh
--parser yaml
```

**Input:**
```yaml
NOT LONG ENOUGH................................................................:
  key: value
LONG ENOUGH.....................................................................:
  key: value
```

**Output:**
```yaml
NOT LONG ENOUGH................................................................:
  key: value
? LONG ENOUGH.....................................................................
: key: value

```

**Expected behavior:**
Don't put ternary operators in a file format that doesn't have ternary operator support 😛.
