### ISSUE TITLE
Yaml parser convert long line into something like ternar operator

### ISSUE THREAD

**Issue by yujj** [prettier/prettier#7667]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEEA2ATA+gZwgVymwCcBDAI3IEsYsBbARyQB0pWACdyKHfOuYjhZROnOADcEMAHQwq-GBTRxpOMAAs4GfMumTiATyxoIps+YuWr1q1ADm0qKX7DRo7lDhg50JO3Hy5BAAHlhklDSMrCAANKgADj48yKCkxMQQAO4ACmkIOMggpOIQVBixIORkYADWcDAAyvGkYFT2yDDE+HBx6jB0aADq6jRwOM1gcA35NFQBMAaFYDgFcW04AjDZZHZ0pMgAZqRoG3EAVjjBAELVdY3OcAAybXCHx6cgF8ENbXbKAIr4CDwN4nHogZqCASFAzONAVeIZDaDMjxQqIsYCSQVBhA+DbCDxAooUg4AC0ni0WgqxDguKotO2pF2+yQRzBcQ2dCoHS64JwvwBeNebPe4MU5EGZRg6mQACY4p1SFQ0L8AMIQOh7QpQaCvOL4DYAFQoxPZH3E3QAkkQpA0wMQqIkAIJEBoLZSgj6ItowKUYGXIAAcAAYAL5hoA)
```sh
--parser yaml
```

**Input:**
```yaml
old_sound_rabbit_mq:

  consumers:
    event.timetable.schedule.very_looooooooooooooooooooooooooooooooooooooooooong.name:
      connection: vimbox_rabbitmq

```

**Output:**
```yaml
old_sound_rabbit_mq:
  consumers:
    ? event.timetable.schedule.very_looooooooooooooooooooooooooooooooooooooooooong.name
    : connection: vimbox_rabbitmq

```

**Expected behavior:**
```yaml
old_sound_rabbit_mq:

  consumers:
    event.timetable.schedule.very_looooooooooooooooooooooooooooooooooooooooooong.name:
      connection: vimbox_rabbitmq
```

Add info:
Increasing --print-width=100 helps.
