### ISSUE TITLE
Incorrect removal of parenthesis in generic parameters

### ISSUE THREAD

**Issue by GrayStrider** [prettier/prettier#7705]
Input:
```TS
type num = ReturnType<(() => number)>;
```

Output:
```TS
// Broken
type num = ReturnType<() => number>
```

Expected:
```TS
type num = ReturnType<(() => number)>
```

Config:
```yaml
printWidth: 80
tabWidth: 2
useTabs: true
semi: false
singleQuote: true
quoteProps: as-needed
jsxSingleQuote: true
trailingComma: es5
bracketSpacing: true
jsxBracketSameLine: true
arrowParens: avoid
```

TS: 3.8.3
Prettier: 1.19.1
