### ISSUE TITLE
Less: single quotes in comments lead to broken output

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7780]
**Prettier next**
[Playground link](https://deploy-preview-6773--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6VACAKgeQCI5IYDkAOlOieQHQCOArgB4CMGw5GnGAhmx1wMgAbCACciAYgCsMgNz8BnAEZiAJnFEBaUQEsA5gAsYRZgAdGGAM4QhO1RhijuUS6e6iEMWagBUXH6gKigBk1GAilnB8UIqxGAC27no6UEQADPIxcQC+QblQ+TQMjABM0ZwA7nYwBiZpaQCkmZwGcPpGJgAcaeaZhVB0TADM0aQwiaLJUNrtxhjMPYyyGOT5K1AgADQgEKYwOtCWyKDuohAVAAruCEco3EIV3ACeR9tKTmAA1nAwAMpuYBSemQjnocG2RniQgA6gYdPBXNwwHBfjd4ToAG7wp7IcCWV4gFKRUQwC5OPSJZAAM3ukW2ACtLIwAEIfb5-bjxOAAGRScGptPBIEZjF+QKEcAAivQIPABUI6SA3KJibiJfitkrdLBodUDMhuttTGdItCnKZcca4MSMfztgxZXAybtbiBuJZNFA4HB1KpNR4GDoPGTuBTuPLFZF4joQaIwdtLOKpTK5UgaQqhTBuEpdaoasgSttHNwdLYoHoAMIQeKUlDWqSa+iRLDZ27pxUYsEASSg6lgvzAuj2AEFe78YE8JRG4NlskA)
```sh
--parser less
```

**Input:**
```less
// TODO: '
// '
.qux1 {
    a {
        color: #555;
        border-right: 1px solid transparent;/*   */
        &.close {
            margin: 0;
        }
    }
}

.qux2 {
  width: 100%;
  height: 180px;
}

.qux3 {
	margin-right: 10px; 
}
 

```

**Output:**
```less
// TODO: '
 // '

.qux1 {
  a {
    color: #555;
    border-right: 1px solid transparent; id tran
    &.close {
      margin: 0;
    }
  }
}
.qux2 {
  width: 100%;
  height: 180px;
}
.qux3 {
  margin-right: 10px;
}
```
