### ISSUE TITLE
Prettier ignore comment is ignored on yaml files

### ISSUE THREAD

**Issue by soullivaneuh** [prettier/prettier#7805]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: NodeJS
- Runtime: Node.js v12
- Operating System: Linux

**Steps to reproduce:**

See [this playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABABwE5xjASzmwFoCBzKCXAHSgwAEBnOOdAC30yaQHpfyBGOwCuAIwB0kALa8ceQsTm58RbLwJMmIuE14BWfQE4jdAIKZMAIRFQAJgBs4NGgFFYQgJ4uAykwcAwsSEAGYEYACG8Eh06OhaDmDBBGGR8AD6TjAsUGDYnpgw6VQwAG7EKUR2JDIxUHFx6ekhEWAw1J51DQ0WmC4AKrrZLgBiBAAeMCK4TC7uhDDeNCOt7fkuALIQYADW814rbR1ISHlwUXAAMnhM7nkFMH6ByakXXd0NJOgw2DqxDeV7NQkOgAOTMfxJbALcIXQF2aiZG4Ie6FUH-OIiFjYEHgrHEdJ2OAtEQOGDo+oNBHSCIEKAgkrlbCVOB2KQQaQY9BMll2EEtBwsLlMGBRLEggCEmHYmF4kCgIvQvRs9iccygIk5NCeQWhlTScB8oqmPCQADlXK4ACLpABqrgASgBJEZOgJmfpOgDyZv+CShoVhGWwEUwBDsCRqHPecXhwPQNBAEMSyUIBrj2HSIbDEf8ia5+JxCaThcJxIipJg+cpcWptPp6Gz4YS7M5Nfi4jrdJ4XLiXwA7oOuTywqz+RFBc52yKxTx0FKZXLoIrlbZHM43BqtTqXkHDcbxUgAKpmq2Ou1mS5Oq0e72+qAgAA0IAghQIy+QoAi2GwEH7AAVvwQJhkBACJSggcMnxAMQQ12PAfEwVo6XIZAfh0Z9OGkBwAHV2CEXQkKSHxgKEAhSi8UCwC0aDu2Cf8Q3IGlkAFFhnwAKyYcYrDgnYEIiaQrjpOAWInNiQE48YfBQpwAEURAgeBRMnZ8kOwbFQM8ASHGgnAIBYHDs1A+RsXKaCAEcFPgBjXxAlAIiYEgoFYIk7Gg3BLIIXAGIiJiImU8SWGkAg0N+OBnyYGS4HkxSRKQVjwpAUUxBw8NhGQAAmZ8flpBwUICDlmJQKhnOg-F+giMQ7IS59Sh0J17AQR48gIQozHsI1PCcALEpwOkYFSux0qQAAOAAGABfCagA). 

**Expected behavior:**

No change on the file.

**Actual behavior:**

File is fixed, regardless the ignore comment.

Also the doc seems incomplete. Even I can find tests about it on the codebase, there is no mention about yaml files: https://prettier.io/docs/en/ignore.html

**Comment by thorn0** [comment]
`# prettier-ignore` should be the last comment before the ignored node. The docs indeed need an update.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAAQM5zugCxhgAdskB6CgcwEsYCBXAIwDpIBbCkgJzmNpwe3PgKEVa2bIzjYKAVnkBOJQB0oGXvxiCeAWlrUoEPuoCCJEgCFGUACYAbOKtUBRWPQCeLgMrYHAMJCOgBmtGAAhvBI6ujoUg5gwbRhkfAA+k4wuFBgPJ4kMOnGMABuQimCdnqcMVBxcenpIRFgMCaedQ0NFiQuACqy2S4AYrQAHjCMfNgu7jow3qojre35LgCyEGAA1vNeK20dSEh5cFFwADL82O55BTB+gcmpF13dDXroMDwysQ3lewmJDoADkOH8SR4C3CF0BdhMmRuCHuhVB-zijFwPBB4KxQnSdjgLUYDhg6PqDQRHAitCgIJK5R4lTgdnYEA4GPQTJZdhBLQcuC52BgUSxIIAhCQCCQKJAoCL0L0bPYnHMoIxOaonkFoZU0nAfKKpuQkAA5VyuAAi6QAaq4AEoASRGToCZn6ToA8mb-gkoaFYRkeBESLQ7Akahz3nF4cD0KoQBDEskdAa4zx0iGwxH-ImuficQmk4XCcSIqSYPnKXFqbT6ehs+GEuzOTX4iw63TyFy4l8AO6Drk8sKs-kRQXOdsisXkdBSmVy6CK5W2RzONwarU6l5Bw3G8VIACqZqtjrtZkuTqtHu9vqgIAANCAIIVaMvkKAIjweBB+wAFb8EGwZAQAiUoIHDJ8QGYENdn4HwSFaOlqGQH4ZGfIgOAcAB1Ah6FkJCkh8YD6FoUovFAsApGg7tgn-ENqBpZABVwZ8ACtsHGKw4J2BCIg4K46TgFiJzYkBOPGHwUKcABFRgIHgUTJ2fJCeGxUDPAEhxoN4OkYBw8MGGQAAOAAGVTf1wHDs1ArRsXKaCAEcFPgBjXxAlAImwPQoDwIk7GgvgXNoPgGIiJiImU8TcA4Wg0N+OBn2wGS4HkxSRKQVikpAUVmEMuxjKQAAmZ8flpBwUICDlmJQYw-Og-F+giZhPOy59ShkJ17AQR48loQozHsI1PCcaK4AAXwmoA)
```sh
--parser yaml
```

**Input:**
```yaml
# @see https://github.com/prettier/prettier/issues/5599
# prettier-ignore
AppBundle\Entity\SslCertificate:
  sslcertificate_letsencrypt_notverified-com:
    __factory:
      App\Tests\Fixtures\Entity\Factory\MockEntityFactory::createLetsEncryptSslCertificate:
        - true
    vendor: '@sslcertiticatevendor_letsencrypt'
    user: '@user_default'
    domain: notverified.com
    verified: false
    status: !php/const AppBundle\Enum\SslCertificateStatus::NEED_VERIFICATION
  sslcertificate_rapidssl-com:
    vendor: "@sslcertiticatevendor_rapidssl"
    user: "@user_default"
    domain: rapidssl.com
    subdomains:
      - www
    verified: false
    status: !php/const AppBundle\Enum\SslCertificateStatus::UNDER_VALIDATION

```

**Output:**
```yaml
# @see https://github.com/prettier/prettier/issues/5599
# prettier-ignore
AppBundle\Entity\SslCertificate:
  sslcertificate_letsencrypt_notverified-com:
    __factory:
      App\Tests\Fixtures\Entity\Factory\MockEntityFactory::createLetsEncryptSslCertificate:
        - true
    vendor: '@sslcertiticatevendor_letsencrypt'
    user: '@user_default'
    domain: notverified.com
    verified: false
    status: !php/const AppBundle\Enum\SslCertificateStatus::NEED_VERIFICATION
  sslcertificate_rapidssl-com:
    vendor: "@sslcertiticatevendor_rapidssl"
    user: "@user_default"
    domain: rapidssl.com
    subdomains:
      - www
    verified: false
    status: !php/const AppBundle\Enum\SslCertificateStatus::UNDER_VALIDATION

```
