### ISSUE TITLE
Incorrect format in css when selector attribute value is a URL

### ISSUE THREAD

**Issue by jcestibariz** [prettier/prettier#7850]
**Prettier 2.0.1**

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA2gCwE5wGYC8AOiJjDAA5ID01cAHqgLYUA2cAdJEyQLoAEwfgBMAlgGc2qAJ5J+UaHH4BfEABoQECjFHRxyUKmzYIAdwAKRhPpSpWpmfo0AjbKjABrODADKFd6JQAObIMNgArnAaZEysAOqYovCS7nA+1kmiAG5J0sjg4k4ggeJw2DDmbkFMqMh4dqUaAFbi9ABCbp7ePsxwADKBcHUNUSAt9D6BQewAiuEQ8MOsjSD+2KXY+WCF6qvYgTBxosIwmMgAHAAMGhQmpXFuFPm3cBtZQxoAjvPwlVo2aHEAFooHA4MJwbtcN9RLhKqhqrUkPVlqNSkxRKEImiprMfkNkSMNDBUM4jiczkgAEzEtyiVhTADCECYNXyrwArLtwqUACqkmwolZZSIASSgENgPjA+20AEEJT4YNJ2EtSsplEA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```css
a[href="http://example.com"] { display: none }
```

**Output (v2.0.1):**

```css
a[href="http://example.com"]
{
  display: none;
}
```

**Output (v1.19.1):**

```css
a[href="http://example.com"] {
  display: none;
}
```
**Expected behavior:**

The double quotes should have been changed to single quotes and the opening brace should have been left in the same line as the selector.

In v1.19.1 the bug with the quotes was present but the bug with the opening brace is new in v2.0.1.

**Expected output:**
```css
a[href='http://example.com'] {
  display: none;
}
```
