### ISSUE TITLE
[CSS] Invalid @page rule formatting

### ISSUE THREAD

**Issue by vlad-zhukov** [prettier/prettier#7859]
**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABADgQwOZyQMwEsAnAZxgAJgAdKCiyAV1jmIFpi5S4YkKtcFAIwBuWgF8QAGhAR0MQtFLJQmYsQgB3AApqEylJgA2mzAE9lMgEbFMYANY8AyljCEo2ZDGKM4MgBYwALZGAOr+hPCkrnBO+pGEAG6RZsjgpJYg7tzEMNq22EGYyPjG3DIAVqQAHgBCtg7OmEFwADLucCVlfiBV1U7u2EZwAIqMEPBdRuUgWGSsaWAZ0rPE7jChhAAmMP7IABwADDLoGtyhtuhpp1ysiZ0yAI7j8PlyBiCYpGxQcHBb-xWnGeJDg+RwRSmM24QUIXh8PVIg2GYwmnQI3RkMEwVk2Oz2SAATFjbIQjIMAMIQIKQlBcACsK0Y3AAKjiDKVpj1Er4AJJQAGwJxgNbyACCAqcMDMwyhcHE4iAA)

**Input:**

```css
@page:first 
{
  counter-reset: page 1;
}
```

**Output: (v2.0.2)**

```css
@page: first{
  counter-reset: page 1;
};
```

**Output: (v1.19)**

```css
@page:first {
  counter-reset: page 1;
}
```

**Expected behavior:**
```css
@page:first {
  counter-reset: page 1;
}
```
