### ISSUE TITLE
Modern CSS color function syntax

### ISSUE THREAD

**Issue by mathiasbynens** [prettier/prettier#8154]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAEwA6VOaQA2EATkpqQOYBGAFAAwA0mAjAEwAcL7ArLwEoA3HgLEyFajQCGjFh26Y+vFgwB0gkfkIQS5TAAsAzkTqsAnIq4BSFrwbXhonXorGisi1c63M93+qazuL6HvS8AGxq7ObWmAwWauYAzGxRvJyYAPR+Dk7aIRREYAZ0kdGxbOZqnBFKyVER7Nm5jloEWQBULmR0RgBKAOIAQvHxGgxsLf7CmJ1ZeAC+IEwgEAAOMACW0EbIoNKkpBAA7gAKhwh7KNJEJ9IAnnurNKTSYADWcDAAyuvvWygVGQMFIAFc4KsDDAALZEADqBi28CM-zAcB+V2RWwAbsiHshwEZniBAUY4KQYGc3lQYdJkKhbuTVgArIwAD2Gb0+3x+0hhcAAMoC4AymZCQGz2T9AVQiHAAIpgiDwMVEZkgf6kcmkQlgYkrTWkQEweFbAAmMAMyE4zCNEHJ8Le60J61IcB1ONFqwAjsr4NSNtcQNIjABaKBwODm6OG91+rbu6nSWn0pCM9US8kwrYg8FZ2XypUq0Xp8WrGDSGhmy3WpDsCtvLZEWUAYQgMLphI9vENYPJABUq9cMxqcRCAJJQGOwH5gY2bACC05+MAe8rV5MWiyAA)
```sh
--parser css
```

**Input:**
```css
foo {
  color: rgb(0, 128, 255);
  color: rgba(0, 128, 255, 0.5);
  color: hsl(198, 28%, 50%);
  color: hsla(198, 28%, 50%, 0.5);
  color: lab(56.29% 019.93 16.58 / 50%);
  color: lch(56.29% 19.86 236.62 / 50%);
  /* color(sRGB 0 0.50 1 / 50%); */
}
```

**Output:**
```css
foo {
  color: rgb(0, 128, 255);
  color: rgba(0, 128, 255, 0.5);
  color: hsl(198, 28%, 50%);
  color: hsla(198, 28%, 50%, 0.5);
  color: lab(56.29% 019.93 16.58 / 50%);
  color: lch(56.29% 19.86 236.62 / 50%);
  /* color(sRGB 0 0.50 1 / 50%); */
}
```

**Expected behavior:**
```css
foo {
  color: rgb(0 128 255);
  color: rgb(0 128 255 / 50%);
  color: hsl(198deg 28% 50%);
  color: hsl(198deg 28% 50% / 50%);
  color: lab(56.29% 019.93 16.58 / 50%);
  color: lch(56.29% 19.86 236.62deg / 50%);
  /* color(sRGB 0 0.50 1 / 50%); */
}
```

Notes:

- in general, [use the modern comma-free syntax instead of the legacy comma-based syntax](https://twitter.com/mathias/status/1253242715304857601) ("legacy" is how the CSS Color spec refers to it)
- use `rgb()` with the new syntax instead of `rgba()` (which is a legacy function)
- use `hsl()` with the new syntax instead of `hsla()` (which is a legacy function)
- consider being opinionated w.r.t. how to represent alpha values. IMHO using percentage notation is most readable, as it clarifies the range: e.g. `70%` vs `0.7`
- consider being opinionated about using the `deg` suffix where applicable, e.g. in the first parameter for `hsl()` and the last non-alpha parameter for `lch()`. Again, because this clarifies that the range lies between `0-360`.
- the `color()` syntax is not yet supported by the parser, but that's a separate issue.
- optionally, consider being opinionated about preferring `#rrggbba`/`#rgba` hex notation over `rgb()` notation, or the other way around
