### ISSUE TITLE
CSS pseudo-class are not pretty

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8180]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZUIwBQB0oAJcB0AzhALZwC0YANgIZFE77FmXoAWcATlXQ04RLkKAN24BPCtQgzZcuVADmveozyDWoiVPm7ZSlfygBKXMAC+OHEjSYBLYTVX2hbGJx5OjzV1q6TpPV0DLzUfTTF-HSD5EL41UwBqfBt0bHUHSlCXTQ5uQzCNYUiAmNjlbIzfEuiymTjnEzNLKGtbdPDHeJzhPM9uqojtQLroCoHOyhqRuoajUwA-FPZ6DtwAI1S7dUmCgV2+vZ3cRP2iqeHR+vHG-F3pq7Gj-GMcYxt3KXoYKnYAS2oABMMAAmPDJACM7yQ6zgADMIFw4M0QAAaEAQAAOMD+0CIyFAtC4XAgAHcAApEhD4lC0aik2jifHo9ZcWhgADWcBgAGVMey-kpkDAuABXODo9gwUjUADq-3gRH5YDgPOpfxxIg14mQ4AYaJAgqI3Bg5LZilItGQcLpxvRACsiAAPABCbM53J5tHIABlBXBrbaJSBHU6eYLFNQ4ABFUXoANIG3UO0gflcY1cXVgfXozFcQUwWV-QHuZAADgADLmScbZWzMbq83AM2IDQBHOPwM1YmkgegUKBwOCA4cGpEdv5Is20C1WxNB9HG0h-YVi4NECNR2PxwPJ4MwWjrIsl9jIEHokW0AERgDCZEtuubAFYDaLjQAVQ80pMpkTigCSUAjrAPJgPm2IAIJATyMDiFGu7GuY5hAA)
```sh
--parser css
```

**Input:**
```css
:not(
  .some-class
  .some-other-class
  .some-very-loooooooooooooong-class
  .some-very-loooooooooooooong-class
) {}

:not(
  .some-class
  .some-other-class
  .some-very-loooooooooooooong-class
  .some-very-loooooooooooooong-class
) +  :not(
  .some-class
  .some-other-class
  .some-very-loooooooooooooong-class
  .some-very-loooooooooooooong-class
) {}

:not(
  .some-class
  .some-other-class
  .some-very-loooooooooooooong-class
  .some-very-loooooooooooooong-class
) ~  :has(
  b:not(
    .some-class
    .some-other-class
    +
    .some-very-loooooooooooooong-class
    .some-very-loooooooooooooong-class
  )
):nth-last-child(2n + 1)::before {}
```

**Output:**
```css
:not(.some-class
    .some-other-class
    .some-very-loooooooooooooong-class
    .some-very-loooooooooooooong-class) {
}

:not(.some-class
    .some-other-class
    .some-very-loooooooooooooong-class
    .some-very-loooooooooooooong-class)
  + :not(.some-class
    .some-other-class
    .some-very-loooooooooooooong-class
    .some-very-loooooooooooooong-class) {
}

:not(.some-class
    .some-other-class
    .some-very-loooooooooooooong-class
    .some-very-loooooooooooooong-class)
  ~ :has(b:not(.some-class
      .some-other-class
      + .some-very-loooooooooooooong-class
      .some-very-loooooooooooooong-class)):nth-last-child(2n + 1)::before {
}

```

**Expected behavior:**

Don't know, some better way.
