### ISSUE TITLE
YAML: Unstable array formatting

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8377]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqpzgEwM5IA6UGGA2saaWABZxgDWAtAGYQBOAtgIYwA0lKulr1mAGwCWsASSGoRjJngAOcMZKgBzGXNQBieRABucdt01wdcg1Lwxu6ptyg4m7AK5RW7CJyaaJfkFSAF1iYNQ7OGUCED4QCGUYCWg8ZFBudh8AdwAFTIQ0lAds7gBPNPiAIzNGOBgAZWVuMClNZBgPSxAaGE4xAHUaQLgVFrgGwsCJI0Cy5HA8SpBbUxhcs00eZBYHPG6AKzwADwAhWoZ6hu5OOAAZKTgdvcOThraxOABFdwh4Z7E+3izXY+3YCzKNzEcRAynYUhgAwkOBgNGQAA4AAzAnz7AZmZQLOGjUwmGEAR1+8A2iSKIG4eCYWFwuBh7DglIk7I25m2SF2gO6+04Eg6XXieA+3ypT35L3i9iqSJRaKQACYFWYJBpNABhXx8kCjACsMPc+wAKtwqkUBUCQEZ3HAAJIuBCNMDwpIAQRcDRgZU+AP2AF8Q0A)
```sh
--parser yaml
```

**Input:**
```yaml
    needs:
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]

    steps:
```

**Output:**
```yaml
needs: [check-format, check-lint, check-spelling]

# coverage,
# install-and-run-from-git,
steps:

```

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdqpzgEwM5IA6UGGAxKgA4BOcMMAlnNQLQMDmUEtxp6A2rz7owACzhgA1iwBm3ALYBDGABohwsROkAbBrDUlhqTVJZ5KcbbqjsDR1BUgA3ZovZw7RinrwxFVlkUoHBZqAFcoWWoIeRZ2BlV1DABdYiTfOEoCEBUQCEpGaDxkUEVqaIB3AAUyhGKUfwrFAE9i3IAjakUpOgBlSm69dmQYcI8QURh5bQB1UQS4c264XrqEhicE5uRwPDaQH2YYKq72JWQZfzxxgCs8AA8AIS6emF7FeTgAGT04C6vbg9ekNtHAAIphCDwf7aa65AbUa7UHbND7aHIgGh6GAzBg4GCiZAADgADPDotcZl1KDsaItmC4MQBHSHwE75eogRR4FhYXC4DG0FkMWgnNznJCXWHja7yBgjMa5PAg8Gsv6SgG5PztXH4wlIABMWq6DGs7AAwjEJSBFgBWDFha4AFUU7XqUrhICcYTgAElggg3mBqAwCgBBYK9GDNUEw64AX3jQA)
```sh
--parser yaml
```

**Input:**
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]

    steps:
```

**Output:**
```yaml
needs:
  # prettier-ignore
  [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]

# coverage,
# install-and-run-from-git,
steps:

```

**Second Output:**
```yaml
needs:
  # prettier-ignore
  [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]

# coverage,
# install-and-run-from-git,
# coverage,
# install-and-run-from-git,
steps:

```

---

original post by @cinderblock  https://github.com/prettier/prettier/issues/6952#issuecomment-584883813

Another manifestation of what I presume is the same bug. You can't even fix it with `prettier-ignore`.

### Input
```yaml
    needs:
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]

    steps:
```

### Output
```yaml
    needs: [check-format, check-lint, check-spelling]

    # coverage,
    # install-and-run-from-git,
    steps:
```
I expected no change. There seem to be two things happening here:
1. Comments are being removed from the list. I don't think this is generally desirable. A common thing in JS for instance is to comment a single line from a list of things and that comment isn't taken out of the list.
2. Comments are not allowed to be "after" a section and are forced to be used as comments that seem to describe the next section. Empty lines around comments should be preserved, imho.

----

If I try to "fix" this with `# prettier-ignore`, it breaks even worse:

### Input
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]
    steps:
```

### Output
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]
    # coverage,
    # install-and-run-from-git,
    steps:
```

This is also "unstable" as every time I autofix, Prettier replicates the comments. After "formatting" 5 times:

### Output
```yaml
    needs:
      # prettier-ignore
      [
        check-format,
        check-lint,
        check-spelling,
        # coverage,
        # install-and-run-from-git,
      ]
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    # coverage,
    # install-and-run-from-git,
    steps:
```
