### ISSUE TITLE
CSS @supports selector adds unwanted space inside pseudo-selectors

### ISSUE THREAD

**Issue by runarberg** [prettier/prettier#8409]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAzgVwA7YgJxnQAJ04AbOMGAgCiQDMIxN0BaANwEt0uAjSgEpiwADpRixPphg0ojZqxHjJkiDPJcocJMSjQ4AbhXEAviZPTZ0BS3bdeAuMomr1MTdt0AmbAA9SCE0AE2ICAEMoAHMjE3MoUxAAGhAIbBguaHRkUHD8fAgAdwAFPIRslHDyQvCAT2yUvnxwsABrOBgAZWwWrSjkGHxMOBSACxgAW3IAdVGueHQesDhO8vmubhha5HB0BpAtMkJi5qiJ8OQGKrIUgCt0PwAhZraOzvCJuAAZLThL65GIHufk6fUoAEVMBB4P9yDcQD18EcdmA9skEfgtDBplxgjBRsgABwABhS2AKZGmzWwO3JcCOHD+KQAjlD4Cc0hUQOF2No4MF+ej8HBWVxhSdwmcLowASkyBMuAMhoDeNEIWy-jK4YCYOE+Di8QSkN4UoNwlxPFEAMIQCbnHb0gCs6NYcAAKnqKldtaZTEA)
```sh
--parser css
```

**Input:**
```css
@supports selector(:focus-visible) {
  button:focus {
    outline: none;
  }
  
  button:focus-visible {
    outline: 2px solid orange;
  }
}
```

**Output:**
Notice the space between the colon (`:`) and the `focus-visible`, making the pseudo-selector invalid.
```css
@supports selector(: focus-visible) {
  button:focus {
    outline: none;
  }

  button:focus-visible {
    outline: 2px solid orange;
  }
}
```

**Expected behavior:**
No space between the colon and the pseudo selector name.
```css
@supports selector(:focus-visible) {
  button:focus {
    outline: none;
  }

  button:focus-visible {
    outline: 2px solid orange;
  }
}
```
