### ISSUE TITLE
less: the words start with /\*\d/ in background url will converted to lower case

### ISSUE THREAD

**Issue by manglobe** [prettier/prettier#8492]
**Prettier-vscode 5.0.0**
[Playground link](https://prettier.io/playground/#.....)

```sh

```

**Input:**

```less
.foo{
  background: url(https://foo/a*3ABCD)
}
```

**Output:**

```less
.foo{
  background: url(https://foo/a*3abcd)
}
```

**Expected behavior:**

```less
.foo{
  background: url(https://foo/a*3ABCD)
}
```

**Comment by fisker** [comment]
This is fixed by #7592, you need wait for next release, you can use quoted url for now

```less
.foo{
  background: url("https://foo/a*3ABCD")
}
```

**Prettier pr-7592**
[Playground link](https://deploy-preview-7592--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEA6AZhCwA6UAE+ARgIZgDWA5gE4QCuUAJkvndQDYAUAFjDAA4BnJAHoRmCCJIAqAMwBBAEIBhACIBKPAF8QAGhAR+MAJbRByUCWq0A7gAUrCcyhLsbJAJ7n9RamXJwMADK-GTGUJTIMNR0cPpwALZEcIyMKQAyJBF0JJRwAGIQ1AkkfOGRLnQwEHogvAnsAOrcxvCCoWBwQU6txgBurR7I4ILeIOGCcNQwdn6UJcjorpP6AFaCAB6KfhSBQSQJcOnhcIvLcSDrG0Hl7HAAinQQ8GfsKyCh1JPUw3ejtfxqOEYI1jIwYNxkAAOAAM+kBEEmjT8-GGgLg3z6p30AEcnvBZoZnCASIIALRQOApFK1ahwPHGOmzXILJBLN4XSYJYxRGKc24PfGnNnnfQwEhEUHgyFIABMYr8xnY5WUEASrJAGIArLU6JMACoS5zs959WIASSYCGCYCBRnkTCCMA8d1eky0WiAA)
```sh
--parser less
```

**Input:**
```less
.foo{
  background: url(https://foo/a*3ABCD)
}
```

**Output:**
```less
.foo {
  background: url(https://foo/a*3ABCD);
}

```
