### ISSUE TITLE
Incorrect whitespace added after escaped colon in css grid line name

### ISSUE THREAD

**Issue by Bassetts** [prettier/prettier#8512]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6A5gJwJYBMAEwAOlPvlngLTwC2ADgDYCG8lmEA7gM5IllkBtdh0oBGSgAYJRIkikBdfEwCuMCAG4SAXxIkQAGhAQ6MbNC7JQTTMIAK1hBZRMGHJgE8LhgEaYmYAGs4GABlOn9sKHRkGExlOEMACxgaBgB1ROx4LnCwOBDHLOwANyz3ZHAuLxBIrjhMGFs-dBomZAAzFzrDACsuAA8AIT9A4JCmGjgAGUi4Dq6EkD7+kMj0BjgARWUIeHmGbpBwzDrMCrAqgyOcWDS8GETkAA4JQzp2OrS-Ogr3uFPinNDABHHbwJrGJwgJhcShQOBwXCIq6YOCg7CoppMFptJCdA6LOo0bAxOKEtYbba7OZ4haGGBMbx3XAPZAAJnpfmwDDWAGEIDRWhV-gBWK7KOoAFUZTnxh2K8QAklAkbAQmAcCYAIIqkIwdwbfZ1LRaIA)
```sh
--parser css
```

**Input:**
```css
.grid {
  grid-template-rows:
    [row-1-00\:00] auto;
}


```

**Output:**
```css
.grid {
  grid-template-rows: [row-1-00\: 00] auto;
}

```

**Expected behavior:**
There should be no whitespace after the escaped colon in the grid linename.

```css
.grid {
  grid-template-rows: [row-1-00\:00] auto;
}

```
