### ISSUE TITLE
SCSS formatting of single line comments on variables

### ISSUE THREAD

**Issue by Alphy11** [prettier/prettier#8542]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAzhAtnAtANwEMAnAS0ICMAbOJAHSgAJnGB6VxgZThLAAtGFCAA8A5OkZ84pAOZ8YAOkYMWjDNjwQYU4gRLlqcRgGoVLdowAixCAAcAJhADuUcZOlzFZ5gCZGAKjV0UgAvPGFhCWMg0PD0AG4GBgVMHABhKkJ0CWAzBgBfJKgikAAaEDsYUmh0ZFASGycABRIEWpRCKidCAE9a8opiQjAAazgYTlth0igZZBhiAFc4cvksKgB1PlJ4dCmwOG4oYKr8HZ7kcGyykBn0OGIYJqGZLEJkADNO+-KAK3RhAAhIajcacQg4AAyMzgn2+KxA-2EnBmMhoAEVFlpYUgvlQfiApsR7sRLmBruVbGRYBtSPZtMgABwABkpNnuGyGtkuVLgJPwsPKAEcsfBnnZ2iAsrgoHA4PZ5TdiHARaRlc9CK93rj4eV7lhSPMlgjgrMMaKcXiCTBKLT6XxkD5ygtCKQqKi0tg3pc+QBWG6Le4AFUo7StCPwywAklAFbBOGAyLYYABBWOcGA9Ghw-FwfL5IA)
```sh
--parser css
```

**Input:**
```css
$some-variable:
    // Search box's height. 
    $some-other-variable +
    // Dropdown's height.
    2 * $size-xxs + $size-xs;

.someClass {
  
}




```

**Output:**
```css
$some-variable:
    // Search box's height. $some-other-variable +
  // Dropdown's height.
  2 * $size-xxs + $size-xs;

.someClass {
}

```

**Expected behavior:**
The ` $some-other-variable +` line gets added to the previous comment line which breaks the code itself. it should stay on it's own line.

**Comment by fisker** [comment]
@evilebottnawi Yes, fixed by #8366.

**Prettier pr-8366**
[Playground link](https://deploy-preview-8366--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEASAzhAtnAtANwEMAnAS0ICMAbOJAHSgAJnGB6VxgZThLAAtGFCAA8A5OkZ84pAOZ8YAOkYMWjDNjwQYU4gRLlqcRgGoVLdowAixCAAcAJhADuUcZOlzFZ5gCZGAKjV0UgAvPGFhCWMg0PD0AG4GBgVMHABhKkJ0CWAzBgBfBhAAGhA7GFJodGRQEhsnAAUSBGqUQionQgBPatKKYkIwAGs4GE5bQdIoGWQYYgBXOFK4LAo4e3t1gBlCafnCGTgAMQhiLEIYCunkEEJ5mAgSkHksKgB1PlJ4dAmwOG4oMEKvgvl0bmBsk8pug4MQYA0BjJzsgAGbtGGlABW6GEACEBsNRpxCDgtlM4Kj0UsQNjhJwpjIaABFeZaClINFUDEgCbEGHEG7oCG9HlkWBvUj2bTIAAcAAZSrYbDC3gNbDclXB+fgKaUAI6s+AIuytW7oXBQODrdZPYhwA2kO0Ig7IjlU0owrCkWYLanBabMw3szncmCUCVSvjIHylOaEUhUBlpbCukBagCsT3mMIAKpRWiHqfhFgBJKCbWCcMBkWwwACC5c4MC6NEpXLg+XyQA)
```sh
--parser scss
```

**Input:**
```scss
$some-variable:
    // Search box's height. 
    $some-other-variable +
    // Dropdown's height.
    2 * $size-xxs + $size-xs;

.someClass {
  
}

```

**Output:**
```scss
$some-variable:
    // Search box's height.
  $some-other-variable + // Dropdown's height.
  2 * $size-xxs + $size-xs;

.someClass {
}

```
