### ISSUE TITLE
Prettier breaks code when inline lists are used as arbitrary arguments [SCSS]

### ISSUE THREAD

**Issue by boyenn** [prettier/prettier#8565]
I don't know why anyone would ever use a list this way, but it is valid code and prettier breaks it. 

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHShx1QEMwBrAcwCcIBXKDAWkgBsIakcaqyAKAKwAGHCLGiRAOhkBKANyEAviAA0ICAAcYAS2gBnZKFI06AdwAKJhIZSk2Z0lkPrUNchTgwAypvI6oKmQYGno4dQALGABbNgB1CJ14fT8wOG8bJJ0ANySsZHB9FxAA-TgaGAt3KmjSZAAzezL1ACt9AA8AIXdKL29SaLgAGQC4BqbwkDb27wCqNjgARXoIeHG2ZpA-GjKaAv0wIrUtmgCYOJ0MGAjkAA5hdU06Mrj3TQKnuF3ssfUARxW8CqWlsIFI+mYUDgcAwMOONDgAJ0CKqpBqdSQjQ2kzK0R0wVCOLmC2WqzGmIm6hgpFQFyuNyQACYqe4dGw5gBhCDRWoFL6CY70MoAFRptixm2yYQAkkwED4wKdtABBJjeGBYBbrMpKJRAA)
```sh
--parser scss
```

**Input:**
```scss
body {
  background-color: rgba(50 50 50 50...);
}
```

**Output:**
```scss
body {
  background-color: rgba(50 50 50 50..);
}

```

**Expected behaviour:**
Same as input.
