### ISSUE TITLE
Mangling of Sass Custom Properties or CSS variables

### ISSUE THREAD

**Issue by robert-j-webb** [prettier/prettier#8604]
As a refresher, [here's what custom properties are](https://sass-lang.com/documentation/style-rules/declarations#custom-properties)

Their syntax is very permissive:

> CSS custom properties, also known as CSS variables, have an unusual declaration syntax: they allow almost any text at all in their declaration values. What’s more, those values are accessible to JavaScript, so any value might potentially be relevant to the user. 

Which means it's really easy to mangle them. I found 2 ways.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEYAJgB0pZYC0RAhkQG5yoCeRANtAOZFgDOblpqAlqQEb04RKKQC2wmAAtSMImNJ0A7j3r15pANbDy9HlGH9UcLUiwBiYABIK3PoLjEst3gKFEATADobdt8IBmLAAqLA8AXwBufEIY4jJWDi5XByJpWSI2KQgAV3oAEyJtOAAHIh4YTjY4MR5IRigzPAJCLHqIVDNjfLio-HCQABoQCBKYHmg2ZFBudCUABW4EKZRSeiVFKeGjUjBtGABlEt39JmQYVBy4YakYMXoAdSkKuDZjsDgD5YqeCgqaZDgDhDED6aqoGDzVCkJgKZAAMzW1WGACs2AAPABC0L2cEO4jgABl9HAEUjriA0eiDqchABFHKYUlIRH0ZEgY6ocGAtjsLYc3iwB48fLSZAADgADMMSuhqg9oSVAbLXtQqCCAI6M+BQ0YrECkTgGOD5E0g4xanjGKEwuEs8nDaq1c6XClsWlwBlMslsikwATC0VSZAeYYXUiqU4AYQgYjtIFeAFYQTlqgAVAQrVnsihXACSUFNsAOYF4YwAgoWDjAaEIfdVwuEgA)

**Input:**

```scss
:root {
  --a-very-long-css-variable-name-that-may-will-make-a-line-break: #{$variable - variable-2.$variable-3 * 2};
  
  --a-css-variable-that-should-keep-its-semicolon: {
    color: red
  };
}
```

**Output:**

```scss
:root {
  --a-very-long-css-variable-name-that-may-will-make-a-line-break: #{$variable -
    variable-2.$variable-3 * 2};

  --a-css-variable-that-should-keep-its-semicolon: {
    color: red;
  }
}
```

**Expected behavior:**

The semicolon should be kept and whitespace should not be added or removed.

We can not modify anything inside of the variable declaration, or we may mangle it. These values must be past directly to the user.
