### ISSUE TITLE
Wrong less formatting

### ISSUE THREAD

**Issue by Morgy93** [prettier/prettier#8755]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AtnAJgSwIYC0A7jljABYAUAAnAB4wBOc6ArugDQAE1ARs3gDWASi5FyCLjXpMW7LgF4uAcnQ4oy0XihYpfAYMU8AzmGYIA+hfSjgAHShcnXVAAc8AczgFXjCFlYwGGMucgBGAGJ3LwIYHBgAG28JPFwoD3tHZ2z0PEYPdQJeCBgYCHQkLgAmAAZXOgBuB2yAXwcWkA4QCFc46GNkUDy-IgAFPIQBlDwEojwATwGu-jwwQTgYAGV3MHUPZCZWOC7yGHQEgHVyeLhjHbhNyficADd4+eRwYyWQdWM4RgwUaMTy5ZAAMxm-y6ACtjHQAEIgtYbTZ4TAAGXUcAhUOOIDhdE2eySAEVWCUcUhIQloSB3Ix-oxPklvp16Yx1DALqQKMgABw1Lq+CD-C4g1yfXy3AEvHFdACOFPgwJ6UxAeGMBCgcGw2HZzCVOGYwNBeFxtPx-zUB0YRy6xhJcHJlItdJgeF4PLI5GQVS6TDwOASewAwuUwShbgBWdmsf4AFU9UxpdJeRwAkjoEFszDhegBBHSbGDzJJuuAtFpAA)
```sh
--parser less
```

**Input:**
```less
.media-width(@extremum, @break) when (@extremum = 'min') and (@break = @screen__m) {
    .page-products h1#page-title-heading{
        margin-bottom: 20px;
    }
}
```

**Output:**
```less
.media-width(@extremum, @break)
  when
  (@extremum = "min")
  and
  (@break = @screen__m) {
  .page-products h1#page-title-heading {
    margin-bottom: 20px;
  }
}

```

**Expected behavior:**
```less
.media-width(@extremum, @break) when (@extremum ='min') and (@break =@screen__m) {
  .page-products h1#page-title-heading {
    margin-bottom: 20px;
  }
}
```
