### ISSUE TITLE
Less: Spaces incorrectly added in property/value and property/variable accessors

### ISSUE THREAD

**Issue by charsboo** [prettier/prettier#8767]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATAlgNwATADpTbYAOAhqhlAOZLYB0pmcATqVXABQCMAbMQB4AabAFYADAICUAbQACzOAGcArgBsYAXQDcBAL4ECdAEYR+uAkUiqIzWrMhQAZuipyrNxRunFm6ALakzACe2noggiAQxDDo0IrIoIHMEADuAAqBCPEopKoppEHxEUasYADWcDAAymRg6NTIMMzKcBEAFjB+qgDqbejwirVwVVn9WP1ByOCKRSD1iiwwaaxUAciOuQsRAFaK-ABCpRXVpH5wADL1cOubrSC7-FX1VKpwAIrKEPA3qlsgZMwFswpq8ZuF-r5YN10KgYG1kAAOMQRHwQBbdVjEKY+JQsJjggCOn3gyyi2RApEUAFooHA4Kh6eCFET0Aplmw1kgNr87gs-OhGs1ec9Xh8vtcubcIjBSEZobD4UgAEzS1joVTPADCED8nJAShE4OUCwAKrLsty-pgWgBJKAM2BVMC+aIAQXtVRgQVePwWul0QA)

```sh
--parser less
```

**Input:**

```less
div {
  padding: .average(16px, 50px)[@result];
}

.box {
  color: @config[@colors][primary];
}
```

**Output:**

```less
div {
  padding: .average(16px, 50px) [ @result];
}

.box {
  color: @config[ @colors][primary];
}
```

**Expected behavior:**
Spaces should **not** be added before the square brackets (`[`) or the at symbols (`@`).
