### ISSUE TITLE
[CSS] Prettier converts "invalid" no-space value to a "valid" space value (changes the meaning/behavior of CSS code)

### ISSUE THREAD

**Issue by trusktr** [prettier/prettier#8792]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCACYAdKbbAWmMwiQG5sB6AKmwBUALASwGdt3mIBXAGwAm2KBBjYwzAIZQA5nFTYAkuI7YAblP6theEKyibtgvRIiC4AGmwAHOACdsAYQDKLrnbCK6NAkQBGUmAA1rL2fFCCxJD8EPZIGlL2ABSk5Nb2cIIAlJQEAL4gliAQNjCs0OzIoEnhAO4ACkkIVShadVIAnlXF-vZBwXAwLjZBBrLIMPa8ViDMMAC2-ADqbPDso2BwLi2s5ep7ncjg7D36UOwOMA39sgtSyOhal8UAVuwAHgBC-SFDLlIFnAADIGOCPZ6zd4fFzjfhwACKvDE4KQT34LxAo3sl3sxzApyKWPsBhgyx0MGYyAAHAAGYo2cKXZb9GzHRlwXHqcHFACOyPgN1KrRAUnYxCgcCyWSJmX5rEyNykdweaMhxUuC1Yk2ms3YcMRAtR6MxMCk-nJgkpyAATMUplJWNo5E4IAt7sdOQBWIm8S6Mc2tE2zdQzJSRBDDMAksoAQUiLhgnXhEIxcHy+SAA)
```sh
--parser css
```

**Input:**
```css
.foo {
  --foo:; /* This should not change. It is valid "invalid" code, per CSS spec. */
  background-color: var(--foo, red);
}
```

**Output:**
```css
.foo {
  --foo: ; /* This should not change. It is valid "invalid" code, per CSS spec. */
  background-color: var(--foo, red);
}

```

**Expected behavior:**

An valid "invalid" CSS property is converted into a "valid" CSS property containing a value of a single space.

**Before:**

https://codepen.io/trusktr/pen/2507ea1e5ecb8b8a41800335fc327349

![red-background](https://user-images.githubusercontent.com/297678/87881051-7f446200-c9ab-11ea-94df-a6832de07647.png)

**After:**

https://codepen.io/trusktr/pen/5518a13792dda7288323eee272b0b9a3

![white-background](https://user-images.githubusercontent.com/297678/87881058-8a978d80-c9ab-11ea-8872-c267f8942315.png)

A value like `--foo:;` is invalid CSS, but converting it to a "valid" value like `--foo: ;` introduces a new value that changes code behavior and thus changes visual output.

It is important not to change the code behavior.

---

<details><summary><b>More info: I stumbled on this info while playing with the Space Toggle technique</b></summary>

I found this while playing with the awesome "Space Toggle" technique.

The space toggle technique is used in @James0x57's [`css-media-vars`](https://github.com/propjockey/css-media-vars/) lib, to provide variables that make it easier to write media queries within existing CSS code structure without new `@media` blocks, thus without having to break code structure apart and keeping it DRY.

For example (from the README), code like

```css
  .breakpoints-demo > * {
    width: 100%;
    background: red;
  }
  @media (min-width: 37.5em) and (max-width: 56.249em) {
    .breakpoints-demo > * {
      width: 49%;
    }
  }
  @media (min-width: 56.25em) and (max-width: 74.99em) {
    .breakpoints-demo > * {
      width: 32%;
    }
  }
  @media (min-width: 56.25em) {
    .breakpoints-demo > * {
      background: green;
    }
  }
  @media (min-width: 75em) {
    .breakpoints-demo > * {
      width: 24%;
    }
  }
```

can be written as

```js
  @import 'https://unpkg.com/css-media-vars@1.0.1/css-media-vars.css'; /* <-- Amazing, check this out. */

  .breakpoints-demo > * {
    --xs-width: var(--media-xs) 100%;
    --sm-width: var(--media-sm) 49%;
    --md-width: var(--media-md) 32%;
    --lg-width: var(--media-gte-lg) 24%;
    width: var(--xs-width, var(--sm-width, var(--md-width, var(--lg-width))));

    --sm-and-down-bg: var(--media-lte-sm) red;
    --md-and-up-bg: var(--media-gte-md) green;
    background: var(--sm-and-down-bg, var(--md-and-up-bg));
  }
```

This allows the media queries to be co-located in the CSS structure, similar to what we can do with Sass, Less, and Stylus, but this relies on standard CSS spec.

As another example, I had some desktop-only code,

```css
#faces {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	touch-action: none;
	display: flex;
}
```

and I added mobile support like this:

```css
#faces {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	touch-action: none;
	display: flex;
	--layout-mobile: var(--media-xs) column;
	--layout-desktop: var(--media-gte-sm) row;
	flex-direction: var(--layout-mobile, var(--layout-desktop));
}
```

The above `css-media-var` examples don't have to do with the issue directly, but I had noticed that an invalid value could be converted to a valid value that _could_ override a previously valid value (like [an `initial` value](https://github.com/propjockey/css-media-vars/blob/master/css-media-vars.css#L8)).

More info on Space Toggles:

- https://twitter.com/James0x57/status/1282303255826046977 - @James0x57's introductory tweet (actually quite complicated for casual CSS users)
- https://twitter.com/James0x57/status/1283596399196680192 - Tweet with a simpler example. Relating to the main issue, try changing `--toggler: ;` to `--toggler:;` in the CSS code and the visual outcome will change.
- https://propjockey.github.io/bcd7sdd/ - Uses space toggles to create a circuit board. The binary inputs (check boxes in this case, but vars could also be set from JS) lead to rendering a number like an old digital clock.
- https://twitter.com/James0x57/status/1283906181031960576 - Tweet introducing css-media-vars, with discussion on how the "Space Toggle" technique per spec, not relying on bugs or hacks.

Very neat outcomes, especially the `css-media-vars`!

Anywho, Space Toggle is only slightly related to the `--foo:;` issue, but it's how I stumbled on it.

</details>
