### ISSUE TITLE
SCSS: Valid rules are being commented out, after a comment

### ISSUE THREAD

**Issue by amittal-quot** [prettier/prettier#8915]
On 6th line from bottom 

``` 
@media only screen and (min-resolution: 192dpi), // IE9-11 don't support dppx
   only screen and (min-resolution: 2dppx) { // Standardized
```

becomes
```
  @media only screen and (min-resolution: 192dpi),
    // IE9-11 don't support dppx only screen and (min-resolution: 2dppx) {
```

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAkgWwIYDmcGAsgJYAeZUAzgDpToYC0GASnDQA7Q1kBuxMviIMmrDjGp4MwwnAaLGmDt14ChIhcrGYA0nDhdZWmhgBmAJwg4MNMHgA21AhgBGcAJ7QAJhhgAFsQA7mQ+gRgQ5v5BZJYYXHiWCDA0AHRKAAI4lNQmBMzmjgCuYQAUAJQYwAwYGEwACkkwGACMSBgAynAtMvhUOMW2yY54UoL+EDHEicmwtRj9zKHhAR2tAAwbAKQA3AuNzRgATB0A8oKWlmHEgcSxBAEtMFN4xS8ANJF3lqE0mvIzKFHI53MQaDBkjAwEEfAdMMEglA7D0pFBXDIVhE8FA-A8nhgxpCyG53sRoNN8hg4I44DgUhlkRh8TAOm8XvsoABfJS6dg9aQmeS6PmdAIQSwtKGCnJUZHmCUomBo1xuPBgADWBGsxVxzDkREJuJYfAAXnBGQxsrlkcICtKoHgygAScxkWnMVoUL6u91wZjHb0YZ1YgKeoPOlnhqo1JlqzXaiC6nz6rQdYqWRwut0er0VTnwjAAQXeEC4yTdFDg8RgeA1nAwDmSkWieB8PhcLGCcDcGrIMGYOSgzB8cH4ZDA-q4lBpzEsYzIr2NzAgg+oI7HE6nM8cc4XEA+hdJLR8EE4UAA5C1IFBLieuFwKABeAB8PmnjLqTAAKkFkhezCgKYaGKGEYk7PAzF1cs4ErOA-CHDdx0nZhpyrXd5ykYDqEnWQYAAjAgNoWtcSSHxP3qTAAGEbESKQ3HdftPFkKAFQ6J4YC4GgkHQBwoDIYp-jSSAcFQABicw4DGJ8wBoGhB3gsg8DnTgIBKLCoAWbJFJkaBHGY+xkgQI0-DKRDkhoNT3kXKB1gATmOd8yAqL4mCwABROzPVaDBT0vFoQIfCV70fBY6j0gywCM5EcVM8zVPUmyOkch8KBjSiuhInwyLIc04SZOp4y1HU9QNOB00zbM-QDNLOTqQr1WKpM9TNcrg1DcNgyjL06owHkmUyHCSlHXyjGSBx4DKOgQAAAztFS0SdCoZumr5pv4AAWNIAGY0g2VaMHWgBWab8wYfqQA+EAyw0mhkFAJJrGCJo5julAnGCPBPDuq63HnTUek6RIwBcZBIWKOArqeHBHAAdQCftOGBuBulofsBCY5BwDky6QGof5JQaecCHwZBzCcf4roAKxoCgACF-vrGBOjwekABlqDgMmKchkAaYoToXFpABFYoIHgbnHEpkBZgJrH7Bxq7y2oGBYbCQJkAADg2JXrH+WH5y4LGYIJwRcYARzF+AibLN6QEg5goEMUcfFx5JLbiOAicIUmkHJqXef+HIwcsCGrr4dERatrm-Z5q7azcNXVmQY54-nRj0RonBfZATgjtxwS4G-PA3De-3pf4CGsFxFJOiisguBgItcU6GBPFpSX-i5LkgA)
```sh
--parser scss
```

**Input:**
```scss
// Image Mixins
// - Responsive image
// - Retina image


// Responsive image
//
// Keep images from scaling beyond the width of their parents.

@mixin img-fluid() {
  // Part 1: Set a maximum relative to the parent
  max-width: 100%;
  // Part 2: Override the height to auto, otherwise images will be stretched
  // when setting a width and height attribute on the img element.
  height: auto;
}


// Retina image
//
// Short retina mixin for setting background-image and -size.

@mixin img-retina($file-1x, $file-2x, $width-1x, $height-1x) {
  background-image: url($file-1x);

  // Autoprefixer takes care of adding -webkit-min-device-pixel-ratio and -o-min-device-pixel-ratio,
  // but doesn't convert dppx=>dpi.
  // There's no such thing as unprefixed min-device-pixel-ratio since it's nonstandard.
  // Compatibility info: https://caniuse.com/#feat=css-media-resolution
  @media only screen and (min-resolution: 192dpi), // IE9-11 don't support dppx
   only screen and (min-resolution: 2dppx) { // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
  @include deprecate("`img-retina()`", "v4.3.0", "v5");
}

```

**Output:**
```scss
// Image Mixins
// - Responsive image
// - Retina image

// Responsive image
//
// Keep images from scaling beyond the width of their parents.

@mixin img-fluid() {
  // Part 1: Set a maximum relative to the parent
  max-width: 100%;
  // Part 2: Override the height to auto, otherwise images will be stretched
  // when setting a width and height attribute on the img element.
  height: auto;
}

// Retina image
//
// Short retina mixin for setting background-image and -size.

@mixin img-retina($file-1x, $file-2x, $width-1x, $height-1x) {
  background-image: url($file-1x);

  // Autoprefixer takes care of adding -webkit-min-device-pixel-ratio and -o-min-device-pixel-ratio,
  // but doesn't convert dppx=>dpi.
  // There's no such thing as unprefixed min-device-pixel-ratio since it's nonstandard.
  // Compatibility info: https://caniuse.com/#feat=css-media-resolution
  @media only screen and (min-resolution: 192dpi),
    // IE9-11 don't support dppx only screen and (min-resolution: 2dppx) {
    // Standardized
    background-image: url($file-2x);
    background-size: $width-1x $height-1x;
  }
  @include deprecate("`img-retina()`", "v4.3.0", "v5");
}

```

**Expected behavior:**
