### ISSUE TITLE
format scss @font-face wrong

### ISSUE THREAD

**Issue by LuoXiaoZheng** [prettier/prettier#8959]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZtGBadBDMOAAmAB0oijNZc8BbASwBsBPJIgckjrumwchRqMDgG5ylAM4AnMOwCu0pgAoOAejV4YAOjxMBAEyjbuamGuEB9AJwAWAAwOAHJYCM0gOyuYtgExgYDwZtOAgRAEpxCiIZOSJFFXVNHT1DY1NzKztHexd3Lx9-QODQmAB+AGIGOHQGAA8OcKoIaTotVTg6ACM4AwNe7AgABwQYFhHGgBoJSnilVQ0tXX0wIxMIOjMLLBsHZzdPbz8AoO0Adwh0dF9G5tb2jgurm-Dp6MoEheTltPXNzJ22X2+SORVOT3Qt0w9xgqghUxmH3mSSWqVW6Q2Wyye1yBwKx2K2hgMEhTWhbVhHBg0nkcDGE1eiLmiUWKRWawy21guxyeUOhROwUkADcAOZVQTCKEtCmqEWixpRAC+IEmIGGMAY0EkyFAeGk0ggZwACvqEDqUHozngWDq1V1pAQANZ0gDKQwIDCgouQ1NpaoAFjA6EwAOoBhjwSQewiu82RhjCyMsZDgSR2kBeyRwaQwY2O0VtZD4JjZtUAK0kdQAQo6wC6YK76HAADJeuDFvRlkCVuqur2iphwACK8jCHaQJe7Huk2ekqckYHTqpAQ2kXpgoYYBhgAeQTnsarXEGzocdQ1Ta7gc+FHbVAEcx-B88MLSA8JJsFA4L1eivpHAj4MAB+Z4IWeCdqWcBqtmjC+jS0EgJIA5DqO46Qd2MB4F0W47nuSC+Gq1J4MwA4AMIbEWKDXgArCu8jZgAKthFpTohwq0gAklA-SwK6YDrkMMAAII8a6YxDhhcBKkqQA)

```sh
# Options (if any):
--single-quote
--trailing-comma all
```

**Input:**

```scss
@font-face {
  font-family: 'common-iconfont';
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot');
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot?#iefix') format('embedded-opentype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff2') format('woff2'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff') format('woff'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.ttf') format('truetype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.svg#iconfont') format('svg');
}
```

**Output:**

```scss
@font-face {
  font-family: "common-iconfont";
  src: url("//at.alicdn.com/t/font_940408_1r71t42ct7i.eot");
  src: url("//at.alicdn.com/t/font_940408_1r71t42ct7i.eot?#iefix")
      format("embedded-opentype"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.woff2") format("woff2"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.woff") format("woff"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.ttf") format("truetype"),
    url("//at.alicdn.com/t/font_940408_1r71t42ct7i.svg#iconfont") format("svg");
}

```

**Expected behavior:**
```scss
@font-face {
  font-family: 'common-iconfont';
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot');
  src: url('//at.alicdn.com/t/font_940408_1r71t42ct7i.eot?#iefix') format('embedded-opentype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff2') format('woff2'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.woff') format('woff'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.ttf') format('truetype'),
    url('//at.alicdn.com/t/font_940408_1r71t42ct7i.svg#iconfont') format('svg');
}
```
