### ISSUE TITLE
SCSS: keep empty line around nested selctors without declaration

### ISSUE THREAD

**Issue by scheinercc** [prettier/prettier#9076]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6GEAOBaANnANzl22LgFsEYACYAHSmuslwgCclq24ATAbgZNB1AGRIAFhCJtawoYybVUUOAGd4PUvkqxZCxcwisOXXgP3UAvtWGXhw5Wo1aKVPQblKV63i5016CyYWdk5ufk87BSj5JkcfTTJ-d0UQk3DzDwt45yS3QINgo1DTCIsYqwZLEAAaECwYAEtoVWRQAEM2NggAdwAFToRWlHbcHvaAT1a6gCM2drAAazgYAGVMBcaoAHNkGDYAVzg6ihneHl4AGXadg-btuAAxdnJ2mCad5BB2g4xakHEMHIuAA6uJGvBVBswHBVkMIY0CBCJl8wKppiAtqo4GwYH15ttXsgAGajbF1ABWqgAHgAheZLFardqUS5bOAksnHEBU6mrLbbfAARQOEHgnNw5JAGzY2LYX1UaIxmDYWxgIMaPBg4mQAA4AAx1FUQbEg+aYL4qtQ4oj-ACOovg+Kww2+qmwKl4vH+3AdjW4+PuRKQpMl3Ox5Eae0O4YFwsdHJDXLqMHaMw1Wp1SAATCn5o1cAKAMIQcjBkBqACs-wO2IAKmnhqGpQQjgBJKAXWCrMCqzAwACCndWMAm+Al2MsliAA)
```sh
--parser scss
```

**Input:**
```scss
.top-level-element {
  foo: bar;
  
  &:hover {
    
    .nested-element {
      foo: bar;
    } 
  }
  
  .nested-element {
    
    .nested-element {
      foo: bar;
    }
  }
  
  .nested-element {
    foo: bar;
    
    .nested-element {
      foo: bar;
    }
  }
}
```

**Output:**
```scss
.top-level-element {
  foo: bar;

  &:hover {
    .nested-element {
      foo: bar;
    }
  }

  .nested-element {
    .nested-element {
      foo: bar;
    }
  }

  .nested-element {
    foo: bar;

    .nested-element {
      foo: bar;
    }
  }
}

```

**Expected behavior:**
The Output should not change from the input. Nested selectors should preserve the empty line to their parent even if that parent has no declaration.
