### ISSUE TITLE
SCSS: function arguments on different lines in maps

### ISSUE THREAD

**Issue by TheComputerM** [prettier/prettier#9128]
**Prettier 2.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAJgSwM4AcA2AhgJ4C0ARgE5yEDWuEms2SABALaG6npxzfs4lAOZwAFAB0orVpOkzWEkLkpMYpaPmJK2SzcVYq1SgDRSFikNjDUEGqFp2X9ra7ainzCpQA9s9x2RnBwM3PmlCKHRZTh9SAHdMdBgACzYAYmBOblEYMVRhVXQKajoGNWwTS2x2JQBKUgBGAF86z3kZJRqA7SC9ENcbcNZI6LF2JgSk1IysrlJc-MKkkpp6RmYqrtqQOtaRqJjCOMTktNZM7IW4PIKi1bKNmErLdnR6ptb2i23SUZ4IPEPH0QC4wggDmNYlMzrMros7isqGtyptXu9dp82iAzB1quw-lFSABXXBOfpaQbuSExSanGYXOY5G5Le7Ix4VLZWHZ7bG4n4gN49cmggbgiKHcZ06bnS7zBHLYrs9ac9H1fajI4nGVw+UsxFK0oqtFKfDCD4tPleTqC4r-dCA4G6UWU8U08bHGEMuXM26Kh7G55cs0Wr4463ownFUkisFDCGaqVQL2ypnXP1so2ooNq3Zh-neEBm4UguPUxMTZP01Pw-X+5XZl6m815uru6HV3W+1lIrNPJsgHz4UNWvHNqMAoGxsXxiVQz2dxm1jO9lH9syD4eYy3fQvF-4x0sz8uSysprvpnuGtec5vq0cCocl51l4YV6Wwpd6lfXjmbXxbryu51AWGA4AQJABo2Uh1AA3DioK4DAmDQNgyCgIQlCUICAAKmEIGhKCEPg8QkGhJggFQhBgLQNwAMq4NRTDCMgMCUMScAUXA7DkHA6C8OgAAykTCMShCiAAYhAlCcDAyFQCxRHEjAEAISkMDsPgADqKSYPAeDUXAdEEXpmAAG56cQyDgNg5EgEw2BCDAOGUOJnDIAAZsRjkUQAVtgPgAEKuTR9GEIIglMHAnneZxID+T4dHMfgcAAIrEhA8AxfgPnKJhjmUNZ1i2QhRiwFpMrIAAHAADBRKgQI5Wmubg1kqHABVmdFFEAI4ZfALkQLghEgIQ-hQHwAkIdQfWYNQLluYQ2W5Y5EysexcXYMlaX9dFSBeTlcUwIQ5AVWcyAAEwUWxhCYPgzEAMIQOw7koB1ACsCHEo5AAqJ2EQduVmRxACSUQIDAdE2JgSEAIJRHRMDECly1wM0zRAA)
```sh
--parser scss
```

**Input:**
```scss
$display-breakpoints: map-deep-merge(
  (
    "print-only": "only print",
    "screen-only": "only screen",
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, "sm")-1})",
    "sm-only": "only screen and (min-width: #{map-get($grid-breakpoints, "sm")}) and (max-width: #{map-get($grid-breakpoints, "md")-1})",
    "sm-and-down": "only screen and (max-width: #{map-get($grid-breakpoints, "md")-1})",
    "sm-and-up": "only screen and (min-width: #{map-get($grid-breakpoints, "sm")})",
    "md-only": "only screen and (min-width: #{map-get($grid-breakpoints, "md")}) and (max-width: #{map-get($grid-breakpoints, "lg")-1})",
    "md-and-down": "only screen and (max-width: #{map-get($grid-breakpoints, "lg")-1})",
    "md-and-up": "only screen and (min-width: #{map-get($grid-breakpoints, "md")})",
    "lg-only": "only screen and (min-width: #{map-get($grid-breakpoints, "lg")}) and (max-width: #{map-get($grid-breakpoints, "xl")-1})",
    "lg-and-down": "only screen and (max-width: #{map-get($grid-breakpoints,"xl")-1})",
    "lg-and-up": "only screen and (min-width: #{map-get($grid-breakpoints,"lg")})",
    "xl-only": "only screen and (min-width: #{map-get($grid-breakpoints,"xl")})",
  ),
  $display-breakpoints
);
```

**Output:**
```scss
$display-breakpoints: map-deep-merge(
  (
    "print-only": "only print",
    "screen-only": "only screen",
    "xs-only": "only screen and (max-width: #{map-get($grid-breakpoints, " sm
      ")-1})",
    "sm-only": "only screen and (min-width: #{map-get($grid-breakpoints, " sm
      ")}) and (max-width: #{map-get($grid-breakpoints, " md ")-1})",
    "sm-and-down": "only screen and (max-width: #{map-get($grid-breakpoints, "
      md ")-1})",
    "sm-and-up": "only screen and (min-width: #{map-get($grid-breakpoints, " sm
      ")})",
    "md-only": "only screen and (min-width: #{map-get($grid-breakpoints, " md
      ")}) and (max-width: #{map-get($grid-breakpoints, " lg ")-1})",
    "md-and-down": "only screen and (max-width: #{map-get($grid-breakpoints, "
      lg ")-1})",
    "md-and-up": "only screen and (min-width: #{map-get($grid-breakpoints, " md
      ")})",
    "lg-only": "only screen and (min-width: #{map-get($grid-breakpoints, " lg
      ")}) and (max-width: #{map-get($grid-breakpoints, " xl ")-1})",
    "lg-and-down": "only screen and (max-width: #{map-get($grid-breakpoints," xl
      ")-1})",
    "lg-and-up": "only screen and (min-width: #{map-get($grid-breakpoints," lg
      ")})",
    "xl-only": "only screen and (min-width: #{map-get($grid-breakpoints," xl
      ")})",
  ),
  $display-breakpoints
);

```

**Expected behavior:**
