### ISSUE TITLE
@keyframes rule with global scope in CSS modules produces invalid CSS

### ISSUE THREAD

**Issue by tmazeika** [prettier/prettier#9339]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABA1nAngMwE4CGAtnAM4AESA5gDYQBGBNAFKQA4CWUAlOcADpRy5fBCJ9Bw4TEJRSOCHiJJyeCDALxmABgAmcKtwDck8gF9TMCBKFSZBOQqUq1GrQGYAbHoPHTFqDMQABoQCDYYDmhSZFACPDUAdwAFeIQYlCZEgiwY0PpCMEwYAGU2AjAuKmQZAFc4ULgiejhdfV0AGQcqWoIqOAAxRSJNSKhqzNqrEJAACxgiGgB1WY54dgq4EvS1jgA3NaxkcFI8kC5SODwYZMIqEeQcJkvQgCtSAA8AIULikuI4B0uHBHs8GiB3h8SlUaHAAIq1dQgpBPGgvEDlPCXPDHMCnGZsPBcGBLDi6GCzZAADm0oUJEEuS0IbGOhLIVz2INCAEdEfBbuEMiACKQALRQOCtVozPBwXkcWW3PoPFFg0KXIgcGp4erqmHwvnI1HojT0UnkylIABMoXsHBoVQAwmIVSAyABWGa1S4AFQI9AyxvBe3qAEkoPpYCUwESIgBBCMlGBYWGgtFwMxmIA)
```sh
--parser css
```

**Input:**
```css
@keyframes :global(spin) {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

**Output:**
```css
@keyframes: global(spin){
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
};

```

**Expected behavior:**
```css
@keyframes :global(spin) {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
