### ISSUE TITLE
css custom property value formatted with space before rgba function bracket

### ISSUE THREAD

**Issue by hawckins** [prettier/prettier#9573]
There should not be any space between rgba and open bracket ( stylelint is catching as an error. 

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuZAnCEYAJgB0pZYC0REAVkQM4DuAljGABZEyMCuAtgEZFcQAeVRgEMAJhGpJC0mbLlYADAAd+AAoUA6AIwAmAKyo4HdRv2HjytagDmXYQAoAbsNT2S5IpEO8BQsRKIbLgBKABpNLWCAbnwAXxBQkAglGFpoSmRQF3RqAAUXBAyUYQAbamEATwzErlRhMABrOBgAZSV62ihrZBhUNjhEoy44UVERgBlhLrZhazgAMQhUDmEYVK7kEGE2GAgEkEYYDhKAdUZ6OEp2sDgWwvpaR3oKzbBKapBOyjhUGFy66wrZAAM1K30SZEo-AAQnVGs0WsIOHBxp04CCwQMQJD+C1OtYSnAAIpsTDopCgkrgkDtVDfVCvd77JSoTowE60USsZC6BSJFkQb4nOpKTYsy4-RzoxIAR1J8H+ySKW0oRCgcBGI32hjltEM-1mQIpmMS3w4tB6fSxlHxhJJZIxVKxMGEXA5XMYyB0iV6wloJXxAGEIBwjSBLnp9mxvgAVV1FSnUxz9ACSUDGsBaYFZKQAgumWjAKoTHd9YrEgA)
```sh
--parser css
--print-width 120
```

**Input:**
```css
:root {
  --oj-switch-thumb-box-shadow:                     0px 0.125rem 0.25rem 0px rgba(var(--oj-core-box-shadow-rgb),0.1);
}
```

**Output:**
```css
:root {
  --oj-switch-thumb-box-shadow: 0px 0.125rem 0.25rem 0px rgba (var(--oj-core-box-shadow-rgb), 0.1);
}

```

**Expected behavior:**
```css
:root {
  --oj-switch-thumb-box-shadow: 0px 0.125rem 0.25rem 0px rgba(var(--oj-core-box-shadow-rgb), 0.1);
}
