### ISSUE TITLE
Trailing-comma config ignored in YAML

### ISSUE THREAD

**Issue by grafluxe** [prettier/prettier#9582]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAhgSwDaagcyQAIAdKIo4MiikkCAIwCs4wYBaAEwjgGd2oEDqkwcA7qIAWedgAcATnnGZOMSXWJ122nXQA01GnQAqAUQDKxjaXAQAtnfREAkuaLpOnOJyKS48uDpDAF8yMjgAD1lWeE4kQypyI3pmGPYRGH4JNRkFJXYJVXVkG31DWhAzS2s6SAcnADkAeWNff0CQELCoXSSybj4iQRgiXgBXVBEwOGIAPgTym0YWNi4efmH00QKpXMVYHaKakB1dEAMkiqqrEtr7RyJm1r8AokAUAiIGMZHlmIByXhDCBidyjGD7fBEThjOBEGAQIh-WZ-IJJYLneiyGCYaC8ZCgdDyeTAgAKhIQeJQ6GwYnQAE88XoQAx5OgwABrOAwcyyNl4fDIcEwplwOwMbxeTgAGXQBDG6HwcAAYhB5I4YNiCMgQOhvhAMZIYHZsAB1aTwXi86bmCmiTAAN1EdO1vHBmDYGLwvH8MBJrPwjmQGGw3qZTF4EQAQqyOVzzOg7HApXg4EHqaGQOGIuZ+dg4ABFMZCVNIYMZ3nyb3ybV0hPYDF5WAmlRqZAADgADEyFBBvSbWbJtQo+P57ammQBHIvwP0QWSUnUbODebwYgJTzABP0KwOl9NwJneuyYQXyYUgXi5gvTktlg8gGDoBjNorIABMTPBWFwBAAwvd0G1QQoHHEAxm9Ywn0pO8mXtGFnCgLxYHMMBFCxABBRDzBgOk8zTEM4GCYIgA)
```sh
--html-whitespace-sensitivity strict
--parser yaml
--trailing-comma none
```

**Input:**
```yaml
failing: 
  {
    "object-does-not-fit-within-print-width": "------",
    "TEST": "comma IS added here"
  }

expected:
  {
    "object-fits-within-print-width": "",
    "TEST": "comma NOT here"
  }

---
  
does not suffice: >
  {
    "object-does-not-fit-within-print-width": "------",
    "TEST": "comma NOT here — but object's now a string due to '>'"
  }
```

**Output:**
```yaml
failing:
  {
    "object-does-not-fit-within-print-width": "------",
    "TEST": "comma IS added here",
  }

expected: { "object-fits-within-print-width": "", "TEST": "comma NOT here" }

---
does not suffice: >
  {
    "object-does-not-fit-within-print-width": "------",
    "TEST": "comma NOT here — but object's not a string due to '>'"
  }

```

**Expected behavior:**

I expect that the nested JSON object in the YAML output will **not** have a trailing comma since I have the `trailing-comma` config disabled. Side note, the trailing comma makes the nested JSON invalid, so it's more than a visual aesthetic.

Thanks in advance.
