### ISSUE TITLE
Add line below above CSS selector

### ISSUE THREAD

**Issue by owen-bick** [prettier/prettier#9771]
**Prettier 2.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHShxwDNoYBaEgQwFsBLAGyyRwBJbr6oBuQ41NTABrAOYAnCAFcoGVmwDuAC3rw+RHJEYRx8gA7j6ncVnXEysCgGd6ALzisAjADY9AD3UBfQtTz9NENq6ONxKcIYwZjjwbpQYcJDi1DD00KxQ0HBRAGQAdHCx4VDUjBSM3MJI1CTw4n4a5uTWdg44AAy5AOzicLRRjZYKcPSiSjCsAKxtbf045VBwFGEjY06zxqLcZXA1rB2OPX3+xJCwCOM4+CA4gOmEV7MAbuEpYCUUJSNQrDGUMBB6s3+QlULHauQmsz0EBsKTSOGoqCsgSkan83ignhAABoQP9YVArMhQNRxJIFAAFEkIQkoEoKahYQk41BJERwGAAZT0wKgomQMHEUjgON6qDgGHiGAAMtReVJqKI4AAxHScGApXnIEDUFEQbEgMa0RgAdRU8Cs3LAcA51NU9AeIK1YCsTJA3Csz3JSVEnGQNEYHpxACsrG4AEKs4Tsjl0OBS7hwP0lQMgENuDncUSMOAARSkEHgSYDwpA3PEHvEWqsztdBm4MGN9AwMCUyAAHG0cQZoXBjUk9FqDHAK099QBHfPwL3-GnaqwUBbi8X6noT+g9L0K31If0pj0MfmCks2XnZvMFxM75MlmAIxvN1tIABMOIFXHmogAwhBaNuQMOJn1KQPQAFQRGkBSFHEHiFABJWRzg5MBDD0GAAEFZA5GAsGzIsPU8TwgA)
```sh
--parser scss
--use-tabs
```

**Input:**
```scss
body {
  font-family: $main;
  background: $white;
  color: $primary;
  font-size: 16px;
}
a {
  color: inherit;
  text-decoration: none;
  &.external-link:after {
    font-size: 0.7rem;
    font-weight: 500;
    line-height: 1;
    margin-left: 0.1rem;
    content: " ↗";
    vertical-align: text-top;
    opacity: 0.5;
    position: absolute;
  }
}
```

**Output:**
```scss
body {
	font-family: $main;
	background: $white;
	color: $primary;
	font-size: 16px;
}
a {
	color: inherit;
	text-decoration: none;
	&.external-link:after {
		font-size: 0.7rem;
		font-weight: 500;
		line-height: 1;
		margin-left: 0.1rem;
		content: " ↗";
		vertical-align: text-top;
		opacity: 0.5;
		position: absolute;
	}
}

```

**Expected behavior:**
I would like to add an space above CSS selectors. Example of this: 

```scss
body {
	font-family: $main;
	background: $white;
	color: $primary;
	font-size: 16px;
}

a {
	color: inherit;
	text-decoration: none;

	&.external-link:after {
		font-size: 0.7rem;
		font-weight: 500;
		line-height: 1;
		margin-left: 0.1rem;
		content: " ↗";
		vertical-align: text-top;
		opacity: 0.5;
		position: absolute;
	}
}

```

I'm hoping someone can provide insight into this. I feel as if it's easier to read SCSS code when there's a space, but I don't see a way to customize this.
