### ISSUE TITLE
LESS: Commented lines without semi-colons

### ISSUE THREAD

**Issue by ericjeney** [prettier/prettier#9800]
In LESS, for statements that are missing a semi-colon but include a comment, Prettier inserts the semi-colon in the wrong place. If the comment ends in a semi-colon, it adds a second semi-colon to the end. If it does not, it adds the semi-colon on the following line. In both cases, I would expect the statement itself to end in the semi-colon, and for the comment to follow it.

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6eBnGACYAdKbI7AIwgCcATOcpbABmwHonsoJSLryBuA47AFsAhuQDmASyh1GLNhxHipBAL4gANCAgAHGBOgZkoUeQgB3AAqiEhlMIA2Z4QE9DmkuWFgA1nBgBlbS8pMWQYcgBXOE04QRI4SmpKABlhKDEI4TE4ADEKERg9dOQQYQiYCA0QAAsYQXsAdWqJTCCwOH8bFokANxbnErAMNxApDBoYC08xEWQAMwdxzQArDAAPACFPHz9-YUE4ZKk4ecXokFW1-xD7OABFCIh4U-slkCDycfIS2+Gq7XIUhgDQklBg1WQAA56JoARBxg1PNoSgC4F8eidNABHR7wKY6WylDAAWigcASCSq5DgOIk1KmWVmSAWr3O40EEjCkTZN3uuJOzLOmhgwhIILBEKQACZhZ4JPYQgBhCCCJkgNEAViqEXGABVRbYWW8elEAJJQaiwfxgQG6ACCFv8MGctxe4xUKiAA)
```sh
--parser less
```

**Input:**
```less
.test {
    border: 0 // no border;
    margin: 0 // no margin
}
```

**Output:**
```less
.test {
  border: 0 // no border;;
  margin: 0 // no margin
;
}

```

**Expected behavior:**

Either:
```less
.test {
  border: 0; // no border;
  margin: 0; // no margin
}

```
Or:
```less
.test {
  border: 0; // no border
  margin: 0; // no margin
}

```
